### ISSUE TITLE
Unable to download pdb_mmcif database due to some recurring error.

### ISSUE THREAD

**Issue by skhatri007** [deepmind/alphafold#100]
**bash download_pdb_mmcif.sh /home/igib/try/try2**

Running rsync to fetch all mmCIF files (note that the rsync progress estimate might be inaccurate)...
rsync: failed to connect to rsync.rcsb.org (132.249.210.197): Connection timed out (110)
rsync error: error in socket IO (code 10) at clientserver.c(125) [Receiver=3.1.2]

Please provide help with this error . I contacted rsync and they explained the issue is not at their end.

**Comment by miesav** [comment]
You might want to check #40

**Comment by skhatri007** [comment]
Thanks allowing the port in the firewall worked.
