### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement numpy==1.19.5 (from versions: none)

### ISSUE THREAD

**Issue by Rusfell** [deepmind/alphafold#101]
Hi, alphafold team.

When i tried to build the Docker image with:
`docker build -f docker/Dockerfile -t alphafold .`

I got the error:
> Step 12/17 : RUN pip3 install --upgrade pip     && pip3 install -r /app/alphafold/requirements.txt     && pip3 install --upgrade jax jaxlib==0.1.69+cuda${CUDA/./} -f       https://storage.googleapis.com/jax-releases/jax_releases.html
 ---> Running in e6d50b2f28c2
Requirement already satisfied: pip in /opt/conda/lib/python3.7/site-packages (21.2.2)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Collecting absl-py==0.13.0
  Downloading absl_py-0.13.0-py3-none-any.whl (132 kB)
Collecting biopython==1.79
  Downloading biopython-1.79-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (2.3 MB)
Collecting chex==0.0.7
  Downloading chex-0.0.7-py3-none-any.whl (52 kB)
Collecting dm-haiku==0.0.4
  Downloading dm_haiku-0.0.4-py3-none-any.whl (284 kB)
Collecting dm-tree==0.1.6
  Downloading dm_tree-0.1.6-cp37-cp37m-manylinux_2_24_x86_64.whl (93 kB)
Collecting docker==5.0.0
  Downloading docker-5.0.0-py2.py3-none-any.whl (146 kB)
Collecting immutabledict==2.0.0
  Downloading immutabledict-2.0.0-py3-none-any.whl (4.0 kB)
Collecting jax==0.2.14
  Downloading jax-0.2.14.tar.gz (669 kB)
Collecting ml-collections==0.1.0
  Downloading ml_collections-0.1.0-py3-none-any.whl (88 kB)
ERROR: Could not find a version that satisfies the requirement numpy==1.19.5 (from versions: none)
ERROR: No matching distribution found for numpy==1.19.5
The command '/bin/bash -c pip3 install --upgrade pip     && pip3 install -r /app/alphafold/requirements.txt     && pip3 install --upgrade jax jaxlib==0.1.69+cuda${CUDA/./} -f       https://storage.googleapis.com/jax-releases/jax_releases.html' returned a non-zero code: 1

What should i do?

thaks~

Rusfell

**Comment by abridgland** [comment]
Hi, can you confirm whether you're still getting this error? It's not something I've seen before but there have been some changes to the Docker setup since the initial release so perhaps the issue has been resolved.

**Comment by IcarusL** [comment]
> Hi, can you confirm whether you're still getting this error? It's not something I've seen before but there have been some changes to the Docker setup since the initial release so perhaps the issue has been resolved.

The error is still here. I met the same problem today with the newest release.

**Comment by Augustin-Zidek** [comment]
This should be fixed by https://github.com/deepmind/alphafold/commit/57a2455e5fab752d8df430ae1d0334e1a21b548c, feel free to reopen if the issue still appears.
