### ISSUE TITLE
How to use？

### ISSUE THREAD

**Issue by genomicsgroup** [deepmind/alphafold#102]

**Comment by genomicsgroup** [comment]
I have 96 process to run AlphaFold，but i noticed that the Jackhammer progress only use 8 of them，how to setting the program use more CPU to RUN the Jackhammer？

**Comment by miesav** [comment]
Change the number of cpus here:

https://github.com/deepmind/alphafold/blob/b88f8dacef5d94e4d3d49613d08523feb20caec1/alphafold/data/tools/jackhmmer.py#L33-L48

**Comment by genomicsgroup** [comment]
Thanks for your reply, but i already changed the CPU number of jackhmmer.py, when I running the run_docker.py again, the shell 
 command line still shows that only 8 threads were used for jackhammer. I was confused because i check the scripts many times, but i could't find the solution.

**Comment by yamule** [comment]
What's happen if you set n_cpu=1 ?
If it uses only 1 thread, the problem would be caused by the setting of docker or it's jackhmmer's behavior. If it still uses 8 threads, the problem would be caused by the AlphaFold script (possibly the script in the docker is not updated).

**Comment by genomicsgroup** [comment]
@yamule Thanks for your kindly reply, I try to set n_cpu=1, it still uses 8 threads, i agree that the script in docker will not bee automatically follows the script to update, i will try to rebulid the docker environment, hope the program will working properly.

**Comment by genomicsgroup** [comment]
@miesav @yamule i rebuild the docker environment, and solved the problem, i think the problem was caused by the container were isolated from the local system, and would't reflash the docker script when host script has been changed.
