### ISSUE TITLE
Alphafold raises an error when it is predicting protein structure

### ISSUE THREAD

**Issue by psp3dcg** [deepmind/alphafold#103]
When I test some proteins like 1EC5 and 3PBJ downloaded from RCSB PDB, the program reported a wrong message like this:

Traceback (most recent call last):
  File "run_alphafold.py", line 302, in <module>
    app.run(main)
  File "/opt/conda/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "run_alphafold.py", line 276, in main
    predict_structure(
  File "run_alphafold.py", line 177, in predict_structure
    relaxed_pdb_str, _, _ = amber_relaxer.process(prot=unrelaxed_protein)
  File "/home/workspace/alphafold/alphafold/relax/relax.py", line 58, in process
    out = amber_minimize.run_pipeline(
  File "/home/workspace/alphafold/alphafold/relax/amber_minimize.py", line 460, in run_pipeline
    _check_residues_are_well_defined(prot)
  File "/home/workspace/alphafold/alphafold/relax/amber_minimize.py", line 140, in _check_residues_are_well_defined
    raise ValueError("Amber minimization can only be performed on proteins with"
ValueError: Amber minimization can only be performed on proteins with well-defined residues. This protein contains at least one residue with no atoms.
-------------------------------------------------
Could anyone give me some help? Thanks a lot~

**Comment by abridgland** [comment]
These proteins contain "X" residues in their FASTA sequences which are not supported in the relax stage. You should be able to find unrelaxed predictions for these proteins in your output directory. If you want predictions for all residues then you have to modify the fasta sequence by replacing X with one of the standard amino acids. You can find the list here: https://github.com/deepmind/alphafold/blob/b88f8dacef5d94e4d3d49613d08523feb20caec1/alphafold/common/residue_constants.py#L532-L535

**Comment by psp3dcg** [comment]
> These proteins contain "X" residues in their FASTA sequences which are not supported in the relax stage. You should be able to find unrelaxed predictions for these proteins in your output directory. If you want predictions for all residues then you have to modify the fasta sequence by replacing X with one of the standard amino acids. You can find the list here:
> 
> https://github.com/deepmind/alphafold/blob/b88f8dacef5d94e4d3d49613d08523feb20caec1/alphafold/common/residue_constants.py#L532-L535

Thank u for your reply~
