### ISSUE TITLE
The number of atoms of predicted protein

### ISSUE THREAD

**Issue by wuwo007** [deepmind/alphafold#105]
When I used the trained model shared within AlphaFold2 to predict the structure of the protein T1024 in CASP14, I get the predicted structure file "ranked_0.pdb". 
But the number of atoms in the "ranked_0.pdb" is **6490**, while the number of atoms in the  target structure file shared by CASP is **2977**. I have checked the input for  protein T1024, the number of AAs is 408. I don't know why this happen. Has anyone else encountered this problem?

**Comment by yamule** [comment]
I think the final prediction result file has H atoms which are not included in the file shared by CASP.

**Comment by wuwo007** [comment]
@yamule  Thanks very much.  Yes, you are right.  And there is another reason: The length of protein sequence of T1024 shared by CASP is 408, and this protein sequence is also the input of AlphaFold2. But the target structure file shared by CASP is the strcuture of part of sequence (T1024-D1: 2-194, T1024-D2: 203-406).  Does anyone know how to calculate tm-score between the predicted structure pdb file and the target structure pdb file in CASP14? Is it needed to preprocess the predicted structure pdb file?

**Comment by yamule** [comment]
Yes, you must delete residues outside of those domains before processing it with TMscore https://zhanglab.ccmb.med.umich.edu/TM-score/ .
However, I think T1024-D1.pdb and T1024-D2.pdb are provided by the CASP organizer.
as
https://predictioncenter.org/download_area/CASP14/targets/casp14.targets.T-dom.public_11.29.2020.tar.gz
Thus Just put them as follows
`TMscore yourpredictedstructure.pdb T1024-D1.pdb`
`TMscore yourpredictedstructure.pdb T1024-D2.pdb`
will work (the scores are normalized with the second input files), I think (but please check carefully).
If an answer structure is not provided by the organizer, preprocessing step is really tiresome.
You must re-assign residue sequence number at first.

**Comment by wuwo007** [comment]
@yamule  Thanks!  I have another problem when calculationing the tm-score of predicted protein structures of CASP14:  The target protein structures shared by ( https://predictioncenter.org/download_area/CASP14/targets/) are incomplete. The number of proteins of CASP14 used in AlphaFold2 is 61, while the number of shared target protein structures is 34. Do you know where to download the target protein structures of CASP14?

**Comment by yamule** [comment]
> Do you know where to download the target protein structures of CASP14?

No.
(I assume AlphaFold team contacted CASP organizer and get permissions and files from the owner of the structures when writing the paper.)

**Comment by Augustin-Zidek** [comment]
Closing this issue now, thank you @yamule for answering @wowo007's questions!
