### ISSUE TITLE
Minor supplement/source discrepancy in structure module

### ISSUE THREAD

**Issue by gahdritz** [deepmind/alphafold#108]
I think that I've found a minor discrepancy between the source code and the official supplement (but I've been wrong before...). I thought I'd flag it here for the record.

On line 11 of algorithm 20 (StructureModule), the angle resnet inputs are fed into linear layers without preliminary ReLU's. [In the source code](https://github.com/deepmind/alphafold/blob/b88f8dacef5d94e4d3d49613d08523feb20caec1/alphafold/model/folding.py#L951), they're ReLU'd first.

**Comment by a-pritzel** [comment]
Hi gahdritz,

This is indeed an error in the supplementary material, the models have been trained with a relu in the position where it is in the code.
However I don't expect this to make a big difference if we were to train the model without it.

Regards,
Alex
