### ISSUE TITLE
preparation of custom sequence DB

### ISSUE THREAD

**Issue by daron-m-standley** [deepmind/alphafold#113]
Hi, I am trying to prepare an AF2 genetic (sequence) DB from an in-house set of 30,000,000 sequences.

I have two questions:

1. Are the HMM files required or can simple FASTA-formatted data be used?

2. Assuming HMMs are required for good performance, I tried following the instructions on the BFD website:
 

> We clustered sequences that could be aligned to a longer sequence with 90% of their residues and a sequence identity of 30% using Linclust/MMseqs2 --cov-mode 1 --min-seq-id 0.3.
> 
> We removed all clusters with less than three sequences and turned the database into an HH-suite3 database using the Uniclust pipeline.

The mmseqs step went fine. However, the last step "turned the database into an HH-suite3 database using the Uniclust pipeline." is still a bit cryptic for me. Is there a script that converts the mmseqs cluster file into a format that `make_a3m.sh` can read? 

Is any documentation on this procedure available?

My interpretation so far is:

1. split the mmseqs cluster file into individual FASTA files (one per cluster)

2. apply the following two transformations to each fasta file (with > 2 seq):

```
make_a3m.sh "${TMPDB}_fasta" "${TMPDB}_a3m" "${TMPPATH}"
make_hhmake.sh "${CLUSTDB}_a3m" "${CLUSTDB}_hhm" "${TMPPATH}"
```

Thanks in advance for more advice on this.

Daron

**Comment by Augustin-Zidek** [comment]
Hi Daron,

1. This depends on the MSA search tool – with HHBlits you need to have the database in their custom format that includes precomputed HMMs. However, with Jackhmmer it is enough to provide a fasta file, see e.g. how we do this with UniRef/MGnify (https://github.com/deepmind/alphafold/blob/main/alphafold/data/pipeline.py#L133). I recommend using Jackhmmer (at least for initial experiments), as preparing the custom genetics database will be simpler.

2. I recommend reading https://github.com/soedinglab/hh-suite/wiki#building-customized-databases.

**Comment by daron-m-standley** [comment]
Thanks for the advice! Will do
