### ISSUE TITLE
run_docker.py:193] RuntimeError: Internal: Could not find the corresponding function

### ISSUE THREAD

**Issue by liuboeo** [deepmind/alphafold#117]
I tried to run it several times, and every time it showed this error. There are only **msas** and **feature.pkl** files in the output folder, and no PDB file output. Has anyone encountered the same problem?

I0810 23:05:10.010185 139642644297536 run_docker.py:193] I0810 15:05:09.950007 139795630245696 run_alphafold.py:141] Running model model_1
I0810 23:05:22.235947 139642644297536 run_docker.py:193] 2021-08-10 15:05:22.082009: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 2036118240 exceeds 10% of free system memory.
I0810 23:05:24.040426 139642644297536 run_docker.py:193] 2021-08-10 15:05:23.973254: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 2036118240 exceeds 10% of free system memory.
I0810 23:05:25.443530 139642644297536 run_docker.py:193] 2021-08-10 15:05:25.409538: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 2036118240 exceeds 10% of free system memory.
I0810 23:05:27.048878 139642644297536 run_docker.py:193] 2021-08-10 15:05:26.849014: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 2036118240 exceeds 10% of free system memory.
I0810 23:05:28.450367 139642644297536 run_docker.py:193] I0810 15:05:28.371603 139795630245696 model.py:132] Running predict with shape(feat) = {'aatype': (4, 468), 'residue_index': (4, 468), 'seq_length': (4,), 'template_aatype': (4, 4, 468), 'template_all_atom_masks': (4, 4, 468, 37), 'template_all_atom_positions': (4, 4, 468, 37, 3), 'template_sum_probs': (4, 4, 1), 'is_distillation': (4,), 'seq_mask': (4, 468), 'msa_mask': (4, 508, 468), 'msa_row_mask': (4, 508), 'random_crop_to_size_seed': (4, 2), 'template_mask': (4, 4), 'template_pseudo_beta': (4, 4, 468, 3), 'template_pseudo_beta_mask': (4, 4, 468), 'atom14_atom_exists': (4, 468, 14), 'residx_atom14_to_atom37': (4, 468, 14), 'residx_atom37_to_atom14': (4, 468, 37), 'atom37_atom_exists': (4, 468, 37), 'extra_msa': (4, 5120, 468), 'extra_msa_mask': (4, 5120, 468), 'extra_msa_row_mask': (4, 5120), 'bert_mask': (4, 508, 468), 'true_msa': (4, 508, 468), 'extra_has_deletion': (4, 5120, 468), 'extra_deletion_value': (4, 5120, 468), 'msa_feat': (4, 508, 468, 49), 'target_feat': (4, 468, 22)}
I0810 23:05:28.450789 139642644297536 run_docker.py:193] 2021-08-10 15:05:28.405281: W external/org_tensorflow/tensorflow/stream_executor/gpu/asm_compiler.cc:235] Falling back to the CUDA driver for PTX compilation; ptxas does not support CC 8.6
I0810 23:05:28.450997 139642644297536 run_docker.py:193] 2021-08-10 15:05:28.405345: W external/org_tensorflow/tensorflow/stream_executor/gpu/asm_compiler.cc:238] Used ptxas at ptxas
I0810 23:05:28.451255 139642644297536 run_docker.py:193] 2021-08-10 15:05:28.407106: E **external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:625] failed to get PTX kernel "shift_right_logical_3" from module: CUDA_ERROR_NOT_FOUND: named symbol not found**
I0810 23:05:28.451434 139642644297536 run_docker.py:193] 2021-08-10 15:05:28.407227: E **external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:2040] Execution of replica 0 failed: Internal: Could not find the corresponding function**
I0810 23:05:28.451600 139642644297536 run_docker.py:193] Traceback (most recent call last):
I0810 23:05:28.451762 139642644297536 run_docker.py:193] File "/app/alphafold/run_alphafold.py", line 302, in <module>
I0810 23:05:28.451921 139642644297536 run_docker.py:193] app.run(main)
I0810 23:05:28.452078 139642644297536 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 312, in run
I0810 23:05:28.452234 139642644297536 run_docker.py:193] _run_main(main, args)
I0810 23:05:28.452390 139642644297536 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
I0810 23:05:28.452547 139642644297536 run_docker.py:193] sys.exit(main(argv))
I0810 23:05:28.452703 139642644297536 run_docker.py:193] File "/app/alphafold/run_alphafold.py", line 284, in main
I0810 23:05:28.452857 139642644297536 run_docker.py:193] random_seed=random_seed)
I0810 23:05:28.453011 139642644297536 run_docker.py:193] File "/app/alphafold/run_alphafold.py", line 148, in predict_structure
I0810 23:05:28.453166 139642644297536 run_docker.py:193] prediction_result = model_runner.predict(processed_feature_dict)
I0810 23:05:28.453362 139642644297536 run_docker.py:193] File "/app/alphafold/alphafold/model/model.py", line 133, in predict
I0810 23:05:28.453516 139642644297536 run_docker.py:193] result = self.apply(self.params, jax.random.PRNGKey(0), feat)
I0810 23:05:28.453672 139642644297536 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/jax/_src/random.py", line 75, in PRNGKey
I0810 23:05:28.453829 139642644297536 run_docker.py:193] k1 = convert(lax.shift_right_logical(seed_arr, lax._const(seed_arr, 32)))
I0810 23:05:28.453986 139642644297536 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/jax/_src/lax/lax.py", line 382, in shift_right_logical
I0810 23:05:28.454143 139642644297536 run_docker.py:193] return shift_right_logical_p.bind(x, y)
I0810 23:05:28.454297 139642644297536 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/jax/core.py", line 264, in bind
I0810 23:05:28.454450 139642644297536 run_docker.py:193] out = top_trace.process_primitive(self, tracers, params)
I0810 23:05:28.454605 139642644297536 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/jax/core.py", line 604, in process_primitive
I0810 23:05:28.454759 139642644297536 run_docker.py:193] return primitive.impl(*tracers, **params)
I0810 23:05:28.454913 139642644297536 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/jax/interpreters/xla.py", line 262, in apply_primitive
I0810 23:05:28.455068 139642644297536 run_docker.py:193] return compiled_fun(*args)
I0810 23:05:28.455224 139642644297536 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/jax/interpreters/xla.py", line 378, in _execute_compiled_primitive
I0810 23:05:28.455382 139642644297536 run_docker.py:193] out_bufs = compiled.execute(input_bufs)
**I0810 23:05:28.455539 139642644297536 run_docker.py:193] RuntimeError: Internal: Could not find the corresponding function**
root@bo-7920:/media/bo/DATA1/alphafold#

**Comment by liuboeo** [comment]
I guess it may be related to the configuration of the graphics card, is there anyone who can help

**Comment by jomimc** [comment]
I have the same problem, running on a single GPU:
python3 docker/run_docker.py --fasta_paths="test file" --max_template_date=2020-05-14 --preset=reduced_dbs --gpu_devices "GPU_uuid"

**Comment by linchundan88** [comment]
I have the same problem. I have two RTX3090 GPUS with cuda11.1.

**Comment by linchundan88** [comment]
I saw "https://github.com/deepmind/alphafold/issues/83", ans I will try it.

**Comment by linchundan88** [comment]
set ARG CUDA=11.1 and then rebuild the docker image.

**Comment by liuboeo** [comment]
> set ARG CUDA=11.1 and then rebuild the docker image.

Thank you very much, let me try

**Comment by Augustin-Zidek** [comment]
This should be fixed by https://github.com/deepmind/alphafold/commit/57a2455e5fab752d8df430ae1d0334e1a21b548c, feel free to reopen if the issue still appears.
