### ISSUE TITLE
 when runing the script "download_pdb_mmcif.sh" , I got an error " max connections (25) reached ".

### ISSUE THREAD

**Issue by linchundan88** [deepmind/alphafold#118]
@ERROR: max connections (25) reached -- try again later
 rsync error: error starting client-server protocol (code 5) ...

**Comment by Augustin-Zidek** [comment]
You could try using a different mirror, see https://www.wwpdb.org/ftp/pdb-ftp-sites for a list of mirrors available.

Change the mirror in `scripts/download_pdb_mmcif.sh`. Here is an example that uses EBI's mirror:

```
rsync --recursive --links --perms --times --compress --info=progress2 --delete --port=33444 \
  rsync.ebi.ac.uk::pub/databases/pdb/data/structures/divided/mmCIF/ \
  "${RAW_DIR}"
```

Try to use a mirror that is close to your geographic location (PDBj for Asia, EBI for Europe, RCSB for America).

**Comment by linchundan88** [comment]
Thank you.
