### ISSUE TITLE
Error aria2c downloading files

### ISSUE THREAD

**Issue by avilella** [deepmind/alphafold#119]
I found that on an NFS filesystem, downloading the reference files with aria2c leads to an error. I googled and found a solution here:

```
find ~/alphafold/scripts/ -name "download*sh" | while read i; do perl -p -i -e 's/aria2c\ \"/aria2c\ \-\-file\-allocation\=trunc \"/' $i; done
```

Then following the instructions from then onwards works.

**Comment by Augustin-Zidek** [comment]
Neat. The other option might be to use `wget` or `curl`, the only potential disadvantage being slower download speed.
