### ISSUE TITLE
GPU required?

### ISSUE THREAD

**Issue by ekiefl** [deepmind/alphafold#12]
The README implies that AlphaFold would at least prefer to use GPUs. However, it doesn't mention whether or not GPUs are required.

**Comment by ryao-mdanderson** [comment]
Thanks Alphafold team! 
I have a similar question: does AlphaFold require GPUs?
Another question: if our HPC cluster does not run docker, any other way to run the software?

**Comment by huhlim** [comment]
Based on my experience, it is working fine only with CPUs. Also, you may enforce the script to run without GPUs using 
`run_docker.py --use_gpu=False` + additional arguments

**Comment by andreasntr** [comment]
> 
> 
> Based on my experience, it is working fine only with CPUs. Also, you may enforce the script to run without GPUs using
> `run_docker.py --use_gpu=False` + additional arguments

That's very good to know.
How long does it take to make a single prediction using CPU? And how much RAM does it use on average?

**Comment by huhlim** [comment]
I have not checked about the RAM usage for the inference, but the input feature generation step requires significantly because of sequence searching against the BFD.
For the timing using CPU, it took more than predictions using GPUs. For a ~140 residue protein, it took ~25 minutes x 5 models for model buildings + ~25 minutes for the input feature generation.

**Comment by andreasntr** [comment]
> For the timing using CPU, it took more than predictions using GPUs

Which CPU are you referring to? It would be of great help if I had a benchmark for my cpu

**Comment by huhlim** [comment]
I have two Intel Xeon Silver 4214 @ 2.2GHz (24 threads for each) on a node. I have no idea how many threads were used for the inference.

**Comment by andreasntr** [comment]
> 
> 
> I have two Intel Xeon Silver 4214 @ 2.2GHz (24 threads for each) on a node. I have no idea how many threads were used for the inference.

That's good enough, thank you so much for sharing this detail

**Comment by Ejhfast** [comment]
> I have not checked about the RAM usage for the inference, but the input feature generation step requires significantly because of sequence searching against the BFD.
> For the timing using CPU, it took more than predictions using GPUs. For a ~140 residue protein, it took ~25 minutes x 5 models for model buildings + ~25 minutes for the input feature generation.

Thanks, this is super helpful. 

I'd also love to know more about how much memory is required to run on GPUs and time required for GPU-based inference if anyone has specific numbers from their setups.

**Comment by sanjaysrikakulam** [comment]
> Thanks Alphafold team!
> I have a similar question: does AlphaFold require GPUs?
> Another question: if our HPC cluster does not run docker, any other way to run the software?

Hi,

We have created a How-To for non-docker AlphaFold setup and it can be found here https://github.com/kalininalab/alphafold_non_docker

Kind regards,
Sanjay

**Comment by ryao-mdanderson** [comment]
Thank you for sharing the information,  @huhlim @andreasntr ; @sanjaysrikakulam good to know there is a non-docker version!

**Comment by tfgg** [comment]
Yes, you can run without a GPU (with the `--use_gpu=False` flag) but it'll be much slower. Thanks to other people for answering and providing timings.

**Comment by aghozlane** [comment]
Hi
We don't have docker and we don't use conda too (I built my own singularity recipe).  I want to run cpu version. The flag --use_gpu is marked in the script run_docker.py, and is missing in run_alphafold.py. I tried to use the option --flagfile=flags.txt but it says: Unknown command line flag 'use_gpu'. Is possible to indicate that I don't want to use a gpu to to run_alphafold.py script ?

**Comment by jaacoppi** [comment]
I suggest that the information about running without GPU be added to README.md.

Should I make a PR or do you (the developers) prefer to add this info based on the comments in this issue?

**Comment by htsurui** [comment]
I am tryin to install alphafold2. I want to know what GPGPUs are compatible with alphafold2?

**Comment by paulmenzel** [comment]
> Should I make a PR or do you (the developers) prefer to add this info based on the comments in this issue?

@jaacoppi, I am no developer, but it’d be great, if you made a merge/pull request.

**Comment by anpanche** [comment]
Hi, I can understand from above conversation that I can run alphafold multimer without GPU. But I want to know is there any minimum configuration of the system or number of cpu, RAM requirement ? 
If I want to run it on cloud which VM shall I select ? I am looking for the cheaper option.
 Many thanks in advance.
