### ISSUE TITLE
Colab simplified version seems to have a more precise prediction?

### ISSUE THREAD

**Issue by huanxian1995** [deepmind/alphafold#126]
I‘ve predict structure via Colab version as well as full version. But compared with the full version, the simplified version is closer to the actual experimental results.  Especially the stability and the expression of the protein. Is there any reason?

**Comment by ValZapod** [comment]
It depends on your setting. For example of last things https://mobile.twitter.com/sokrypton/status/1426235782747021313

**Comment by huanxian1995** [comment]
> It depends on your setting. For example of last things https://mobile.twitter.com/sokrypton/status/1426235782747021313

But it seems that there are limited parameters in the full version of alphafold2? What can I change so that I can get results similar to the  Colab simplified version?

**Comment by Augustin-Zidek** [comment]
You are probably lucky with this structure, but when we compared over a large dataset the full model came out as better.

To run the standalone AlphaFold in a mode similar to the Colab, you need to:
1. Run with reduced databases (`--db_preset=reduced_dbs`) and disable HHBlits on UniClust (comment it out in the data pipeline).
2. Disable templates (e.g. by setting `max_template_date=1000-01-01`).
