### ISSUE TITLE
No structural visualization observed in Colab output

### ISSUE THREAD

**Issue by diyang1354** [deepmind/alphafold#129]
Hi, I can't see the structural visualization in the Run AlphaFold and download prediction cell, what could be the problem? I can download the pdb output.
![image](https://user-images.githubusercontent.com/51859749/129355766-013cdff8-2893-430e-a8eb-1e411c606ec1.png)

**Comment by Augustin-Zidek** [comment]
Hi, I can't reproduce this unfortunately – the structure shows fine for me when I run the Colab. 

Could you try zooming in (using a two finger gesture) in the 3d viewer area? It is possible to accidentally zoom out so much that the structure becomes invisible...

**Comment by diyang1354** [comment]
Hi, it works now. Thank you!
