### ISSUE TITLE
BFD download bottleneck

### ISSUE THREAD

**Issue by georgkempf** [deepmind/alphafold#13]
Hi,
this is not really an issue with the code but it seems that downloading the BFD database is a real bottleneck (at least for me). I tried aria2c and wget and with both I only get around 200 kb/s download rate. It is certainly not a limit of bandwidth on my side. Estimated time of completion is 9d! Does anyone maybe have the file mirrored?

**Comment by ioioba** [comment]
Same for me. I get around 6000 kb/s in the first minute and then it continuously goes down to 80 - 200 kb/s ... estimated time of completion is 25d! :D

**Comment by tjonesster** [comment]
Encountering the same issue. The dataset is licensed under the CC BY 4.0 license so redistribution is allowed. Can someone with a complete copy set up a torrent so that we can seed for one another?

**Comment by tfgg** [comment]
Hi there, we've set up a mirror on cloud storage here:

https://storage.googleapis.com/alphafold-databases/casp14_versions/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt.tar.gz

Please try using it in your download script.

This link makes available:
BFD (unmodified), by Steinegger M. and Söding J., available under a Creative Commons Attribution-ShareAlike 4.0 International License.

**Comment by MSaeed2025** [comment]
Hi,
I tried several times to download and extract bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt.tar.gz file, but I failed to extract it successfully, each time after the extracting the first 1.5 T file I got the unexpected end of the archive error, while the hash and the size seems correct, what should I do to fix this? any solution? I spent more than a month to fix this but I couldn't!
