### ISSUE TITLE
Did not get all the output expected

### ISSUE THREAD

**Issue by luckydogomg** [deepmind/alphafold#130]
Hello,

I tried to run the prediction, the job is completed, but I only got 4 output files, no final predicted structures. I don't see any error output. Someone else used the same code but a different sequence gets all the outputs, is the sequence length causing the problem? How can I fix it?

Thank you very much!

I only have the listed files or directory in the output directory.
features.pkl  
msas  
ranking_debug.json  
timings.json

**Comment by obonyojimmy** [comment]
same here too

**Comment by Pi3k-Akt** [comment]
same here too

**Comment by liuqs1990** [comment]
same here too

**Comment by liuqs1990** [comment]
> same here too

Hi did you solve the problem?

**Comment by liuqs1990** [comment]
my last line for the error says:
```
/app/run_alphafold.sh` line 3: 8 killed python /app/alphafold/run_alphafold.py "$@"
```
What about yours?

**Comment by abridgland** [comment]
Hi, does this happen on all input sequences? Could you also share the last part of the logs before the process quits?

**Comment by Augustin-Zidek** [comment]
Closing this issue for now, feel free to reopen if this is still a problem.
