### ISSUE TITLE
About RuntimeError of hhsearch 

### ISSUE THREAD

**Issue by 7itrees** [deepmind/alphafold#132]
I use 
`python3 docker/run_docker.py --fasta_paths=T1050.fasta --max_template_date=2020-05-14 --preset=casp14` 

to test 
But in the process of Inference, there was a problem with hhsearch：

I0816 15:02:07.595606 139742538180416 run_docker.py:193] I0816 07:02:07.594562 140008981772096 utils.py:40] Finished **Jackhmmer (mgy_clusters_2018_12.fa) query in 792.715 seconds**

I0816 15:02:07.706304 139742538180416 run_docker.py:193] I0816 07:02:07.704662 140008981772096 hhsearch.py:76] Launching subprocess "/usr/bin/hhsearch -i /tmp/tmpsjega8h6/query.a3m -o /tmp/tmpsjega8h6/output.hhr -maxseq 1000000 -d /mnt/pdb70_database_path/pdb70"

I0816 15:02:08.787286 139742538180416 run_docker.py:193] I0816 07:02:08.786523 140008981772096 utils.py:36] Started HHsearch query
I0816 15:02:09.019671 139742538180416 run_docker.py:193] I0816 07:02:09.018909 140008981772096 utils.py:40] **Finished HHsearch query in 0.232 seconds**

I0816 15:02:09.021292 139742538180416 run_docker.py:193] Traceback (most recent call last):
I0816 15:02:09.021610 139742538180416 run_docker.py:193] File "/app/alphafold/run_alphafold.py", line 302, in <module>
I0816 15:02:09.021679 139742538180416 run_docker.py:193] app.run(main)
I0816 15:02:09.021736 139742538180416 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 312, in run
I0816 15:02:09.021789 139742538180416 run_docker.py:193] _run_main(main, args)
I0816 15:02:09.021839 139742538180416 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
I0816 15:02:09.021890 139742538180416 run_docker.py:193] sys.exit(main(argv))
I0816 15:02:09.021941 139742538180416 run_docker.py:193] File "/app/alphafold/run_alphafold.py", line 284, in main
I0816 15:02:09.021996 139742538180416 run_docker.py:193] random_seed=random_seed)
I0816 15:02:09.022310 139742538180416 run_docker.py:193] File "/app/alphafold/run_alphafold.py", line 128, in predict_structure
I0816 15:02:09.022600 139742538180416 run_docker.py:193] msa_output_dir=msa_output_dir)
I0816 15:02:09.022685 139742538180416 run_docker.py:193] File "/app/alphafold/alphafold/data/pipeline.py", line 140, in process
I0816 15:02:09.022789 139742538180416 run_docker.py:193] hhsearch_result = self.hhsearch_pdb70_runner.query(uniref90_msa_as_a3m)
I0816 15:02:09.022850 139742538180416 run_docker.py:193] File "/app/alphafold/alphafold/data/tools/hhsearch.py", line 87, in query
I0816 15:02:09.022930 139742538180416 run_docker.py:193] stdout.decode('utf-8'), stderr[:100_000].decode('utf-8')))

I0816 15:02:09.023019 139742538180416 run_docker.py:193] **RuntimeError: HHSearch failed:**

I0816 15:02:09.023086 139742538180416 run_docker.py:193] stdout:
I0816 15:02:09.023138 139742538180416 run_docker.py:193] 
I0816 15:02:09.023187 139742538180416 run_docker.py:193] 
I0816 15:02:09.023236 139742538180416 run_docker.py:193] stderr:

Can someone give me some suggestions or solutions? thanks

**Comment by Ricco-L** [comment]
+1 
I have a similar problem

**Comment by 7itrees** [comment]
> +1
> I have a similar problem
this may solve your problem
https://github.com/soedinglab/hh-suite/issues/282

**Comment by 7itrees** [comment]
https://github.com/soedinglab/hh-suite/issues/282

**Comment by MurphyDavid** [comment]
I'm hitting this exact problem.

I gather than it's from a bug in a third party tool,  soedinglab/hh-suite but I'm unclear from that thread how to go about getting the alphafold  docker to to work on a given CPU. 

Do I need to re-create the  alphafold docker image with different settings? recompile the tool in question on the docker?
