### ISSUE TITLE
Colab Notebook undefined symbol error

### ISSUE THREAD

**Issue by jiwonslee** [deepmind/alphafold#133]
When running the 'Search against genetic databases' cell I get this error:

NotFoundError: /opt/conda/lib/python3.7/site-packages/tensorflow/core/kernels/libtfkernel_sobol_op.so: undefined symbol: _ZN10tensorflow6StatusC1ENS_5error4CodeEN4absl14lts_2020_09_2311string_viewEOSt6vectorINS_10StackFrameESaIS7_EE
![image](https://user-images.githubusercontent.com/11918639/129787625-c58822c6-3814-46c4-b761-65c32cc14b48.png)

**Comment by berkedilekoglu** [comment]
Hi!
I had the same issue. I guess it is related to TensorFlow version. After 'Download AlphaFold' part, restart runtime from runtime option and then install tensorflow v 2.2.0  by `pip install -U tensorflow==2.2.0`. My problem was solved after these steps.

<img width="991" alt="Screen Shot 2021-08-17 at 23 22 33" src="https://user-images.githubusercontent.com/19657350/129795229-c363ab26-9bc3-420f-8dce-5a1725675da9.png">

**Comment by berkedilekoglu** [comment]
Hi!
I had the same problem and I guess this issue is related to tensorflow version because I found similar ones on the internet. I installed tensorflow version 2.2.0 by `!pip install -U tensorflow==2.2.0` before the 'Install third-party software' part and problem was solved. Before doing that make sure to do Factory reset runtime from the runtime menu. 

<img width="962" alt="Screen Shot 2021-08-17 at 23 57 54" src="https://user-images.githubusercontent.com/19657350/129800016-c5f91691-c404-4a24-9cb8-7c03cbe4c1b5.png">

**Comment by tfgg** [comment]
Hi, are you using the latest version of the notebook, and have you run all the cells in order? We [recently](https://github.com/deepmind/alphafold/commit/f65e94fc71093caf4243643022eac30a449c6f7c) made sure that it's using Tensorflow 2.5.0 in the Colab, as Colab recently changed the default to 2.6.0.

**Comment by berkedilekoglu** [comment]
Hi, I used the last version of Alphafold [notebook](https://colab.research.google.com/github/deepmind/alphafold/blob/main/notebooks/AlphaFold.ipynb?pli=1#scrollTo=D-UYO_Xb3hcO) however I got the same error. Also, I'm sure that I run all cells in order. I tried to install Tensorflow 2.2.0 but I got another error in the Alphafold Prediction step. When I install Tensorflow 2.5.0 by `!pip install -U tensorflow==2.5.0 ` at the begging of the notebook all problems were solved and notebook run properly.

**Comment by zsz1987** [comment]
I have a similar error：
NotFoundError                             Traceback (most recent call last)
<ipython-input-37-1640ae7ce3a3> in <module>()
     24 import py3Dmol
     25 
---> 26 from alphafold.model import model
     27 from alphafold.model import config
     28 from alphafold.model import data

6 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/load_library.py in load_library(library_location)
    152 
    153     for lib in kernel_libraries:
--> 154       py_tf.TF_LoadLibrary(lib)
    155 
    156   else:

NotFoundError: /opt/conda/lib/python3.7/site-packages/tensorflow/core/kernels/libtfkernel_sobol_op.so: undefined symbol: _ZN10tensorflow6StatusC1ENS_5error4CodeEN4absl14lts_2020_09_2311string_viewEOSt6vectorINS_10StackFrameESaIS7_EE

**Comment by zihengxuwu** [comment]
> Hi, I used the last version of Alphafold [notebook](https://colab.research.google.com/github/deepmind/alphafold/blob/main/notebooks/AlphaFold.ipynb?pli=1#scrollTo=D-UYO_Xb3hcO) however I got the same error. Also, I'm sure that I run all cells in order. I tried to install Tensorflow 2.2.0 but I got another error in the Alphafold Prediction step. When I install Tensorflow 2.5.0 by `!pip install -U tensorflow==2.5.0 ` at the begging of the notebook all problems were solved and notebook run properly.

Seconded

**Comment by jiwonslee** [comment]
> Hi, I used the last version of Alphafold [notebook](https://colab.research.google.com/github/deepmind/alphafold/blob/main/notebooks/AlphaFold.ipynb?pli=1#scrollTo=D-UYO_Xb3hcO) however I got the same error. Also, I'm sure that I run all cells in order. I tried to install Tensorflow 2.2.0 but I got another error in the Alphafold Prediction step. When I install Tensorflow 2.5.0 by `!pip install -U tensorflow==2.5.0 ` at the begging of the notebook all problems were solved and notebook run properly.

This solved my problem!
