### ISSUE TITLE
how to change number of cycles?

### ISSUE THREAD

**Issue by DLMURPHY150** [deepmind/alphafold#136]
This isn't per se' an issue but, I've noticed on the colab alphafold2_advanced notebook page that under the section sampling options the number of cycles (max_recycles) can be changed, i.e for NN refinement in modelling.

However, I can't see in the AlphaFold2 code repository (here on GitHub) which python script/module this should actually edited in and how to specifically do this? (On the aforementioned notebook the default is something like 1 or 3).

Many thanks for any help or clarifications. Apologies for the trivialness of this but I would like to increase number of cycles to better fold some of my trickier target proteins.

David

**Comment by tfgg** [comment]
Hi David,

You can change the number of recycling iterations in AlphaFold by changing these two configuration options (to the same new number):

```
config.data.common.num_recycle
config.model.num_recycle
```

this could be done, for example, in [this function](https://github.com/deepmind/alphafold/blob/main/alphafold/model/features.py#L27).

However, I would caution that increasing the number of recycling iterations to beyond the number used at training time ("hypercycling" as I like to call it) isn't officially tested or validated to actually provide higher levels of accuracy on an appropriate test set. Anecdotally there appears to be some successes and that unofficial Colab notebook you mention does provide the ability to do so.

It might be the case that pLDDT is no longer an accurate estimate of model confidence when the model is hypercycled, but you can use your own judgement and knowledge of the target to decide when to trust the prediction. Good luck!

**Comment by MFSeidl** [comment]
Thanks @DLMURPHY150. I think If found the lines in config.py!

Cheers
Michael
