### ISSUE TITLE
Benchmarking alphafold

### ISSUE THREAD

**Issue by mcianfrocco** [deepmind/alphafold#137]
Hello - 

Thank you for such a wonderful algorithm for the community! We have installed the software onto a community server and we want to ensure that we are getting appropriate performance. 

Are there benchmark jobs for speed available that could serve as a comparison? 

Thank you,
Mike

**Comment by biohegedus** [comment]
Hi, I think that it depends on many factor, on various properties of the protein itself. We mention a setup and very basic timings in our preprint: AlphaFold2 transmembrane protein structure prediction shines
https://www.biorxiv.org/content/10.1101/2021.08.21.457196v1
Tamas

**Comment by boegel** [comment]
Are there any reference timings for `T1050.fasta` (which can be obtained from https://www.predictioncenter.org/casp14/target.cgi?target=T1050&view=sequence), which is used in the README (https://github.com/deepmind/alphafold#running-alphafold) as an example?

**Comment by Augustin-Zidek** [comment]
Sorry for the late answer. I strongly recommend the following talk on benchmarking and optimising AlphaFold speed from HPC-UGent: https://www.youtube.com/watch?v=jP9Qg1yBGcs

**Comment by boegel** [comment]
@Augustin-Zidek I'm the one who gave that talk, in case that wasn't clear ;)
