### ISSUE TITLE
Better TMPDIR handling

### ISSUE THREAD

**Issue by meson800** [deepmind/alphafold#138]
## Background

Currently, the data processing tool run scripts [hard-code \tmp](https://github.com/deepmind/alphafold/blob/main/alphafold/data/tools/hhblits.py#L99) as the temporary directory that is passed to the utility function. Looking at the utility function, it simply [uses mkdtemp](https://github.com/deepmind/alphafold/blob/main/alphafold/data/tools/utils.py#L24-L31):
```
@contextlib.contextmanager
def tmpdir_manager(base_dir: Optional[str] = None):
  """Context manager that deletes a temporary directory on exit."""
  tmpdir = tempfile.mkdtemp(dir=base_dir)
  try:
    yield tmpdir
  finally:
    shutil.rmtree(tmpdir, ignore_errors=True)
```
which as the [Python documentation]() states:

> If dir is not None, the file will be created in that directory; otherwise, a default directory is used. The default directory is chosen from a platform-dependent list, but the user of the application can control the directory location by setting the TMPDIR, TEMP or TMP environment variables. There is thus no guarantee that the generated filename will have any nice properties, such as not requiring quoting when passed to external commands via os.popen().

In particular, `tempfile` uses the following as a base to create new temp file/directories:

> 1. The directory named by the TMPDIR environment variable.
> 2. The directory named by the TEMP environment variable.
> 3. The directory named by the TMP environment variable.
> 4. A platform-specific location:
>    On Windows, the directories C:\TEMP, C:\TMP, \TEMP, and \TMP, in that order.
>    On all other platforms, the directories /tmp, /var/tmp, and /usr/tmp, in that order.
> 5. As a last resort, the current working directory.

## Problem
When running Alphafold outside of Docker, such as on a cluster, `/tmp` may be a size-limited mount. Each compute node could often also set `TMPFILE` or the other environment variables to relevant, locally-backed mounts that are faster to access than `/tmp`. By having hard-coded temporary directory base locations, it means that `/tmp` may fill when run outside of Docker on a cluster.

## Solution
See the soon-linked pull request :)

**Comment by Augustin-Zidek** [comment]
Hi, thanks for reporting this. We fixed it in https://github.com/deepmind/alphafold/commit/0be2b30b98f0da7aecb973bde04758fae67eb913, so I recommend upgrading to AlphaFold 2.1.0 to get the bug fix in.
