### ISSUE TITLE
Commercial license: how to obtain one.

### ISSUE THREAD

**Issue by javierbq** [deepmind/alphafold#14]
Hi,

I would like to use alphafold for commercial purposes, is it possible to license the model?

**Comment by effectsToCause** [comment]
Related, if running alphafold using the full_dbs setting does that mean only the apache license applies?  Is it only the casp14 parameters that are covered under the creative commons license?

**Comment by Augustin-Zidek** [comment]
Hi, we have recently changed the license terms for the AlphaFold weights to CC BY 4.0, which permits commercial use.

**Comment by poinco-gogo** [comment]
Just to confirm, are the model parameters available **free of charge** for industrial purposes?

**Comment by RickyAndreFlores** [comment]
> Hi, we have recently changed the license terms for the AlphaFold weights to CC BY 4.0, which permits commercial use.

Will this guarantee that work arising from alphafold will not be patented commercially? If not, it might be a good idea to prioritize making all finding somehow public domain, or other measures to prevent one company from trying to lock away all the findings behind patents/other legal means and maybe even make them disclose it publicly to avoid trade secrets.
