### ISSUE TITLE
Provide AlphaFold2 as a wheel instead of Docker only and remove the hardcode cpus

### ISSUE THREAD

**Issue by jshleap** [deepmind/alphafold#141]
Hi I would like to know if there is a possibility that you could provide a python wheel for alphafold. 

A bit of context: We work in a distributed HPC environment where we cannot allow Docker to be used (security). We do have singularity and have run properly, but we would like to use the software we have compiled in our stack as it is more tailored to our systems. 

By providing a wheel with all the necessary components (including the stereo_chemical_props.txt file in the appropriate place) sites like ours could use the most of our resources with your algorithm.

Also, since we are HPC, it would be most beneficial if the harcoded cpus will be gathered either by argument or by environmental variables.

Best

**Comment by Augustin-Zidek** [comment]
Unfortunately we don't have the capacity to maintain and support Singularity/Wheel. We added a link in the README to the two AlphaFold issues that have links to third party repositories with Singularity definition files (https://github.com/deepmind/alphafold/issues/10 and https://github.com/deepmind/alphafold/issues/24).
