### ISSUE TITLE
could not open file '/data/bfd/...sorted_opt_cs219.ffdata'

### ISSUE THREAD

**Issue by paulgarias** [deepmind/alphafold#142]
I compiled alphafold using a docker image and was able to run alphafold up to a point. It seems to be asking for a file:

```
- 21:02:35.351 ERROR: 	could not open file '/data/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt_cs219.ffdata'
```

but in the bdf folder, I only find these (I retained the original tar.gz file):
```
-rw------- 1 pgarias pgarias 1.5T Mar  3  2019 bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt_a3m.ffdata
-rw-r--r-- 1 pgarias pgarias 272G Jul 28 13:58 bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt.tar.gz
-rw------- 1 pgarias pgarias 9.6M Jul 29 13:28 bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt_a3m.ffindex
```

The full Dockerfile is from here:
https://github.com/uvarc/rivanna-docker/tree/master/alphafold/2.0.0

The command I used to run was this (a singularity image pull from the built docker):

```
singularity run -B $ALPHAFOLD_DATA_PATH:/data -B .:/etc --pwd /app/alphafold --nv $CONTAINERDIR/alphafoldnew_latest.sif \
    --fasta_paths=/scratch/pgarias/fastafiles/sarscovid2.fasta \
    --output_dir=/scratch/pgarias/outputdir \
    --model_names=model_1,model_2,model_3,model_4,model_5 \
    --preset=full_dbs \
    --max_template_date=2020-05-14 \
    --data_dir=/data \
    --uniref90_database_path=/data/uniref90/uniref90.fasta \
    --uniclust30_database_path=/data/uniclust30/uniclust30_2018_08/uniclust30_2018_08 \
    --mgnify_database_path=/data/mgnify/mgy_clusters_2018_12.fa \
    --bfd_database_path=/data/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt  \
    --pdb70_database_path=/data/pdb70/pdb70 \
    --template_mmcif_dir=/data/pdb_mmcif/mmcif_files/ \
    --obsolete_pdbs_path=/data/pdb_mmcif/obsolete.dat
```
The `ALPHAFOLD_DATA_PATH` and `CONTAINERDIR` were defined correctly. 

Was there some step in the download process that was not completed? Is there something else that I should look for? 

Thank you for your time on this issue!

**Comment by paulgarias** [comment]
I reviewed the bfd documenation and found that my uncompression was incomplete.

**Comment by stianale** [comment]
> I reviewed the bfd documenation and found that my uncompression was incomplete.

Hi, what do you mean by "bfd documentation"? I find no such thing. 

The tar.gz seems to consist only of the *a3m.ffdata file when I use tar -xvzf.
