### ISSUE TITLE
Singularity Definition

### ISSUE THREAD

**Issue by jdhayes** [deepmind/alphafold#143]
Here is a singularity definition dirived from your Dockerfile:
    https://github.com/jdhayes/alphafold/blob/main/docker/Singularity.def
Do you think you could integrate this with your codebase, should I make a pull request?

**Comment by jdhayes** [comment]
Moved to:
https://github.com/jdhayes/alphafold/blob/main/singularity/Singularity.def

**Comment by EricDeveaud** [comment]
Hello in order to tun the downlaod scripts from the container
aria2 and rsync should be installed
esay fix, see above diff. not sure it worth providing a patch ;-)
 
 ```
packbuilder:alphafold/alphafold-v2.0.0 > diff -u Singularity.def alphafold-v2.0.0.recipe
--- Singularity.def     2021-09-23 17:13:49.019136000 +0200
+++ alphafold-v2.0.0.recipe     2021-09-23 17:13:29.162525000 +0200
@@ -41,6 +41,8 @@
 kalign \
 tzdata \
 wget \
+aria2 \
+rsync \
 && rm -rf /var/lib/apt/lists/*
 
 # Get code base
```

regards 

Eric

**Comment by tomgreen66** [comment]
Did a `run_docker.py`-like script get written?  I converted Python to bash since we didn't need any Python API - see: [/ARCCA/alphafold/tree/singularity/docker/run_singularity.sh](/ARCCA/alphafold/tree/singularity/docker/run_singularity.sh)

**Comment by EricDeveaud** [comment]
see bottom of the singularity defintion file. 
a shell script is generated. 
```
echo '#!/bin/bash
#ldconfig
source /opt/conda/etc/profile.d/conda.sh
conda activate base
python /app/alphafold/run_alphafold.py "$@"' > /app/run_alphafold.sh
```

this is the launcher you should use

`singularity run <singulariy arguments> <alphafold arguments>`

**Comment by Augustin-Zidek** [comment]
Unfortunately we don't have the capacity to maintain and support Singularity. We added a link in the README to the two AlphaFold issues that have links to third party repositories with Singularity definition files (https://github.com/deepmind/alphafold/issues/10 and https://github.com/deepmind/alphafold/issues/24).

**Comment by RobbieTheK** [comment]
Looks like the link to the cuda download is broken:

`FATAL:   While performing build: conveyor failed to get: Error reading manifest 11.1-cudnn8-runtime-ubuntu18.04 in docker.io/nvidia/cuda: manifest unknown: manifest unknown`
