### ISSUE TITLE
NotFoundError in tensorflow

### ISSUE THREAD

**Issue by jimkwon** [deepmind/alphafold#144]
==========================
NotFoundError                             Traceback (most recent call last)
<ipython-input-4-1640ae7ce3a3> in <module>()
     24 import py3Dmol
     25 
---> 26 from alphafold.model import model
     27 from alphafold.model import config
     28 from alphafold.model import data

6 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/load_library.py in load_library(library_location)
    152 
    153     for lib in kernel_libraries:
--> 154       py_tf.TF_LoadLibrary(lib)
    155 
    156   else:

NotFoundError: /opt/conda/lib/python3.7/site-packages/tensorflow/core/kernels/libtfkernel_sobol_op.so: undefined symbol: _ZN10tensorflow6StatusC1ENS_5error4CodeEN4absl14lts_2020_09_2311string_viewEOSt6vectorINS_10StackFrameESaIS7_EE
==========================

In Stackoverflow, some people suggested a tensorflow version problem. I tried to install different versions of tensorflow using pip, but all attempts generated other errors.

**Comment by delta4desaturase** [comment]
I had the same problem. It worked after I tried this: 

pip install -U tensorflow==2.3.0

and then "restart and run all". 

I got the information from this website: https://github.com/tensorflow/text/issues/385

Hope this would be helpful!

**Comment by delta4desaturase** [comment]
Colab has two versions of tensorflow pre-installed: a 2.x version and a 1.x version. Colab uses TensorFlow 2.x by default, you can switch to 1.x by this:

%tensorflow_version 1.x

import tensorflow
print(tensorflow.__version__)

If you want to switch TensorFlow versions after import, you will need to restart your runtime with 'Runtime' -> 'Restart runtime...' and then specify the version before you import it again.

Check this out: https://colab.research.google.com/notebooks/tensorflow_version.ipynb#scrollTo=uBIKyjpEVxlU

**Comment by alibekk93** [comment]
https://github.com/deepmind/alphafold/issues/124

**Comment by jimkwon** [comment]
It works! Thanks so much!

**Comment by AnyaP** [comment]
Glad you found a workaround! This was indeed a TensorFlow version issue and it should now be fixed (see #124 for details).
