### ISSUE TITLE
How to skip Amber relaxation/refinement step in casp14 method?

### ISSUE THREAD

**Issue by DLMURPHY150** [deepmind/alphafold#147]
Hi, sorry this isn't really an issue again but more of another code query-

On the university HPC cluster I am trying to run AlphaFold2 on I am having considerable computational resource issues (not really surmountable) at specifically the Amber phase of relaxation/refinement. I don't really need to do relaxation/refinement as I'm really only interested in the overall fold, topology and general structural features of my target proteins and thus do not need luxurious high resolution/quality structure models etc. However, as you can see from one of my other issues that I've raised on the alphafold GitHub, I would like to still keep the casp14 method in order to increase the number of modelling cycles (recycles) as we still think we can attain better accuracy models this way (see issue #136 ).

So, what is the simplest and cleanest (in terms of python code editing) way to skip the Amber step in the casp14 method?

Many thanks for any help,
David

**Comment by tfgg** [comment]
Hi David,

The easiest thing to do right now would be to copy out these lines:

https://github.com/deepmind/alphafold/blob/main/run_alphafold.py#L183-L193

and replace it with

```relaxed_pdbs[model_name] = protein.to_pdb(unrelaxed_protein)```

I haven't tested this but this should write out the unrelaxed proteins at the end, and skip the relax step.

**Comment by DLMURPHY150** [comment]
Hi Tim, this code modification works fine on my setup, though it appears Amber issues related to comp resources only occurs for large proteins approx >600 res on our Liverpool HPC cluster (gpu nodes), so thanks again!

**Comment by CryoSky** [comment]
Hello,
I tried to skip the Amber relaxation step and followed @tfgg 's suggestions. But I got an error like this:
Traceback (most recent call last):
  File "run_alphafold_noamber.py", line 364, in <module>
    app.run(main)
  File "/home/alphafold/af2/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/alphafold/af2/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "run_alphafold_noamber.py", line 338, in main
    predict_structure(
  File "run_alphafold_noamber.py", line 256, in predict_structure
    f.write(relaxed_pdbs[model_name])
KeyError: 'model_1'

Could anyone give some suggestions about how should I make modifications?
