### ISSUE TITLE
Convert AlphaFold2 model to TensorFlow format

### ISSUE THREAD

**Issue by achetver** [deepmind/alphafold#152]
Hello!

Is it possible to convert AlphaFold2 model to TensorFlow format?

I tried to do this after reading [instruction](https://github.com/deepmind/dm-haiku/blob/main/docs/notebooks/jax2tf.ipynb), but it is unclear how to find and extract the model definition which can be transferred to TF.

I was able to load the pretrained model(s) using next code:
> model_name = 'model_1'  # model_2, ...
> num_ensemble = 1
> 
> model_config = config.model_config(model_name)
> model_config.data.eval.num_ensemble = num_ensemble
> 
> model_params = data.get_model_haiku_params(
>     model_name=model_name, data_dir='/home/user/repositories/models/')
> 
> model_runner = model.RunModel(model_config, model_params)

but I don't find a way to use it for conversion.

Also I tried to initialize model using next code:
> def model(model_config):
>     model = modules.AlphaFold(model_config.model)
>     return model(1,
>           is_training=False,
>           compute_loss=False,
>           ensemble_representations=True)

and got next error:
ValueError: All `hk.Module`s must be initialized inside an `hk.transform`.

@Augustin-Zidek @tomwardio @saran-t 
Can you give me some advices?

**Comment by jimmy9389** [comment]
hello!
I am trying to covert alphafold 2 tensorflow format now.

I followed instuctions from haiku Documents(https://dm-haiku.readthedocs.io/en/latest/notebooks/jax2tf.html) and wrap the jax evaluation function with JaxModule,where I used apply function from RunModel  as the apply_fn.

Here is the codes I tried to convert an alphafold model to tensorflow and execute it:

```
from alphafold.model import model,data,config
import os
import pickle
import tensorflow as tf
from jax.experimental import jax2tf
import sonnet as snt
import tensorflow as tf
import tree
import jax

os.environ['XLA_PYTHON_CLIENT_PREALLOCATE'] = "false"
gpus = tf.config.list_physical_devices('GPU')
if gpus:
    try:
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
    except RuntimeError as e:
        # Memory growth must be set before GPUs have been initialized.
        print(e)


def main():
    model_name = 'model_1'
    data_dir = '/home/jimmy.zhang/40_nfs/repos/BioCal_zhejiang/alphafold/run_alphafold/alphafold_params'
    output_dir='/home/jimmy.zhang/40_nfs/repos/BioCal_zhejiang/alphafold/run_alphafold/0'


    model_config = config.model_config(model_name)
    model_config.data.eval.num_ensemble = 1
    model_params = data.get_model_haiku_params(
        model_name=model_name, data_dir=data_dir)
    model_runner = model.RunModel(model_config, model_params)

    features_output_path = os.path.join(output_dir, 'features.pkl')
    feature_dict = pickle.load(open(features_output_path, 'rb'))

    model_random_seed=1234
    processed_feature_dict = model_runner.process_features(
        feature_dict, random_seed=model_random_seed)
    apply_fn = model_runner.apply
    net = JaxModule(model_params, apply_fn,model_random_seed)
    prediction_result = net(processed_feature_dict)
    print(prediction_result)

def create_variable(path, value):
  name = '/'.join(map(str, path)).replace('~', '_')
  return tf.Variable(value, name=name)

class JaxModule(snt.Module):
  def __init__(self, params, apply_fn, random_seed,name=None):
    super().__init__(name=name)
    self._params = tree.map_structure_with_path(create_variable, params)
    self._apply = jax2tf.convert(lambda p, x: apply_fn(p, jax.random.PRNGKey(random_seed), x))
    self._apply = tf.autograph.experimental.do_not_convert(self._apply)

  def __call__(self, inputs):
    return self._apply(self._params, inputs)



if __name__ == '__main__':
    main()
```
But I got memory allocation failure Error. I am using V100-32GB gpu, it could run with alphafold with jax well. So I believe there must be something wrong.
I notice that there is some while loop in alphafold module. So I am wondering that whether  jax2tf will flat the while loops in memory and How could I avoid it?
