### ISSUE TITLE
Error on tensor proto size 

### ISSUE THREAD

**Issue by rkflygaard** [deepmind/alphafold#154]
Hi,
I'm getting an error when trying to run alphafold on a particular sequence, that tensor proto cannot exceed 2GB (see attached file with the error log). I have successfully run alphafold on many other sequences without any problem, but for this particular sequence I am getting this tensor proto error no matter what I try (e.g. running with full database vs reduced one, different gpu nodes to not hit out of memory). 

Any help on what I can try would be much appreciated!
Thanks a lot!

[AF2_slurm_56393_snoke5_alphafold_56393_4294967294.txt](https://github.com/deepmind/alphafold/files/7065565/AF2_slurm_56393_snoke5_alphafold_56393_4294967294.txt)

**Comment by yzyw0702** [comment]
Same issue took place in my case, when the input sequence is very long (>1500).

**Comment by rkflygaard** [comment]
> Same issue took place in my case, when the input sequence is very long (>1500).

The strange thing for me though is that I have successfully run sequences of >2000 residues without getting any errors or problems, but this single input sequence always gives an error on tensor proto size.

**Comment by Augustin-Zidek** [comment]
Hi, this is most likely because the MSA is too big. There is a suggested workaround (reducing the size of the MSA) in: https://github.com/deepmind/alphafold/issues/71

**Comment by Augustin-Zidek** [comment]
Addressed in https://github.com/deepmind/alphafold/commit/0be2b30b98f0da7aecb973bde04758fae67eb913.
