### ISSUE TITLE
MGnify download unreachable

### ISSUE THREAD

**Issue by prolatium** [deepmind/alphafold#16]
Hi,
I have been trying to download the MGnify dataset, but the host is unreachable.
"Connecting to ftp.ebi.ac.uk (ftp.ebi.ac.uk)|193.62.197.74|:21... failed: Connection timed out."
Is it possible to put this dataset on google cloud as well?

**Comment by prolatium** [comment]
Sorry, manual download from the browser solved the issue. (ftp://ftp.ebi.ac.uk/pub/databases/metagenomics/peptide_database/)

**Comment by tfgg** [comment]
Hi, if this is still a problem - we have made it available on a mirror here:

https://storage.googleapis.com/alphafold-databases/casp14_versions/mgy_clusters_2018_12.fa.gz

This makes available:
“[MGnify: v2018_12](http://ftp.ebi.ac.uk/pub/databases/metagenomics/peptide_database/current_release/README.txt)” (unmodified), by Mitchell AL et al., available free of all copyright restrictions and made fully and freely available for both non-commercial and commercial use under [CC0 1.0 Universal (CC0 1.0) Public Domain Dedication](https://creativecommons.org/publicdomain/zero/1.0/)
