### ISSUE TITLE
 Could not find CIFs in /mmcif_files

### ISSUE THREAD

**Issue by jcs0902** [deepmind/alphafold#160]
I have been working to get alphafold running with a singularity image on my schools cluster. There was an issue using Rsync to get the whole PDB downloaded in cif format so we used FTP and manually put them in the right folder. All of the files exist in .cif format in the proper directory and the directory is specified correctly in my run script, but every time it fails with this error:

 Could not find CIFs in *Directory that has all the cif files*

Any clue what may be wrong or how I could go about fixing it?

**Comment by Augustin-Zidek** [comment]
Is it possible the cif files in the directory are still gzipped?

**Comment by jcs0902** [comment]
They are fully unzipped and are in the XXXX.cif format.

**Comment by Augustin-Zidek** [comment]
Could you try running the following code snippet that does the check on the directory?

```python
import glob
import os

mmcif_dir = "<path to the directory with the mmCIF files>"

if not glob.glob(os.path.join(mmcif_dir, '*.cif')):
  print('Could not find CIFs in %s', mmcif_dir)
```

If it reports the same problem, then it could be also a permission problem – are the files world readable?

**Comment by jcs0902** [comment]
I ran that and got no errors and all of the files are world readable. 

Here is the full error when I try to run alphafold:
`
WARNING: Skipping mount /etc/localtime [binds]: /etc/localtime doesn't exist in container
/opt/alphafoldenv/lib/python3.8/site-packages/absl/flags/_validators.py:203: UserWarning: Flag --preset has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  warnings.warn(
E0902 16:20:15.371900 140697111770944 templates.py:860] Could not find CIFs in /gpfs/share/apps/alphafold/2.0.0/pdb_mmcif/mmcif_files
Traceback (most recent call last):
  File "/app/alphafold/run_alphafold.py", line 283, in <module>
    app.run(main)
  File "/opt/alphafoldenv/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/opt/alphafoldenv/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/app/alphafold/run_alphafold.py", line 210, in main
    template_featurizer = templates.TemplateHitFeaturizer(
  File "/app/alphafold/alphafold/data/templates.py", line 861, in __init__
    raise ValueError(f'Could not find CIFs in {self._mmcif_dir}')
ValueError: Could not find CIFs in /gpfs/share/apps/alphafold/2.0.0/pdb_mmcif/mmcif_files
`

**Comment by rohandavidg** [comment]
I seem to be having the same issue

File "/app/alphafold/alphafold/data/templates.py", line 861, in __init__
    raise ValueError(f'Could not find CIFs in {self._mmcif_dir}')
ValueError: Could not find CIFs

**Comment by Augustin-Zidek** [comment]
Are you running AlphaFold using Docker? 

If so, do you see 

```
Mounting <path to your mmcif dir> -> <...>
```

in the logs? I also see you are mounting a gpfs filesystem. Do you know whether it is supported by Docker?

**Comment by jcs0902** [comment]
We are not running AlphaFold with Docker. We have been trying to use a Singularity Image so that it will run on our HPC.

**Comment by Geraldene** [comment]
I am experiencing the same problem, @Augustin-Zidek do you have a time estimate as to when this issue may be resolved. Thanks in advance.

**Comment by arkanilroy** [comment]
I have been facing the same issue!
I am trying to run a local installation without docker and it gives me the same error about not finding the cif files in the directory that they are. I downloaded the reduced_dbs version and also used the preset and it still did not work. 
Please help!

**Comment by tomgreen66** [comment]
I seem to have got it working locally with Singularity and have written a basic shell script to setup the database locations at [/ARCCA/alphafold/tree/singularity/docker/run_singularity.sh](/ARCCA/alphafold/tree/singularity/docker/run_singularity.sh) but I have so far had to fix permissions on files and seems its very sensitive and when having issues example command being run would help.

**Comment by tomgreen66** [comment]
It's just the bindings for Singularity to point to the databases. I could refactor a bit to remove the need for a file but helped me debug. Realised the whole script is a bit overkill but was copying the docker way of running it. Ideally I can see that to run on clusters it needs converting to nextflow or similar to deal with different resource requirements for each step but that's a future project.

**Comment by tomgreen66** [comment]
Its created in the script - basically just the SINGULARITY_BIND environment variable where bindings can be sourced to set it before running Singularity e.g.

```
export SINGULARITY_BIND="${SINGULARITY_BIND},$source_path:$target_path"
echo "export SINGULARITY_BIND=\"$SINGULARITY_BIND\"" > bindings.txt
```

Bit blunt but assumed container needed databases in certain locations but didn't register the arguments are basically setting locations and can be anywhere.

**Comment by josomir** [comment]
why is this issue closed when there is no clear answer? I am facing same problem.

**Comment by josomir** [comment]
> Hello, I have finally figured out a solution for the issue. In my bash script that calls singularity, there were issues binding all the database directories. I was able to solve the issue by putting soft links to each database directory inside of one folder. I then directed the singularity script to bind to that directory such that all of them would be visible and everything is running now. Hope this helps!

could you please elaborate on that solution? are you still binding each database separately? can you maybe provide your binding commands? thanks!
