### ISSUE TITLE
Running on Colab pro: error at 'prot=unrelaxed_proteins[best_model_name]'

### ISSUE THREAD

**Issue by songshuang1996** [deepmind/alphafold#161]
Dear Experts,
Thank you for providing such good software. I have predicted many proteins structures successfully, however sometimes I meet error at 'prot=unrelaxed_proteins[best_model_name]' ,when whole process is almost done. This is quite frustrating, since it is quite time consuming.  What should I do to solve this problem?  Thank you for advice.
![image](https://user-images.githubusercontent.com/81628468/131940294-6ebfe34b-e9c4-45b7-aefd-46bc8011bb4f.png)

**Comment by radhikasethi2011** [comment]
+1 
facing the same problem - illegal memory access was encountered @tfgg

**Comment by Augustin-Zidek** [comment]
Could you try what has been suggested in https://github.com/deepmind/alphafold/issues/170?
