### ISSUE TITLE
What GPGPUs are compatible with alphafold2

### ISSUE THREAD

**Issue by htsurui** [deepmind/alphafold#165]
I am trying to set up alphafold2 in my workstation. I would like to use GPGPU. What GPGPUs are compatible with alphafold2? In other words, what compute capability is necessary for the calculation. Pascal or better is required?

**Comment by tavolivos** [comment]
To give a contribution, I can run alphfold2 (non docker installation) locally on a desktop PC with the following set up: AMD ryzen 3900x, rtx 3070, 32 GB RAM, NVMe PCIe SSD 1TB, and HHD 4TB.

**Comment by htsurui** [comment]
Thank you tavolivos. Rtx 3070 is Ampere structure and is the newest. At present, I can not afford it. I have several boards with Kepler structure and one with Pascal structure. I would like to know whether those are compatible with or not.

**Comment by andycowie** [comment]
Hi, htsurui - we have tested AlphaFold with A100 and V100 and CUDA 11, it also works on K80 GPUs on Colab. Note that larger proteins will require more VMEM. It might also be worth testing it with the `reduced_dbs` mode - which is faster, uses less RAM and uses less bandwidth to download.

**Comment by htsurui** [comment]
Thank you andycowie. Its a valuable information. I will try K80 on my
workstation.

2021年9月14日(火) 19:15 andycowie ***@***.***>:
