### ISSUE TITLE
How to predict the structure of cyclic peptides?

### ISSUE THREAD

**Issue by JustinDoIt** [deepmind/alphafold#167]
I have a cyclic peptide sequence. I put it into Alphafold2 Colab, but I didn't get a cyclic peptide structure. What should I do to connect the C-terminal and N-terminal for the next dynamic simulation (GROMACS)?

Should I do some processing on the structure obtained by Alphafold2 Colab for Gromacs dynamics? Or input sequence to Alphafold2 Colab need for some pre-processing? Or can Alphafold2 not predict the sequence of cyclic peptides?

It's really important for my research, thanks for any help.

**Comment by andycowie** [comment]
AlphaFold doesn't explicitly support cyclic peptides as it assumes the protein is linear and non-cyclic. Fixing this at the model level would be a substantial change.

However, if AlphaFold does produce a ring-like structure with the termini close to one another, you could try taking the unrelaxed structure (`unrelaxed_model_N.pdb` in the outputs), modifying the topology, and relaxing it with your forcefield of choice.
