### ISSUE TITLE
run_alphafold_test

### ISSUE THREAD

**Issue by player1321** [deepmind/alphafold#168]
Hi, 

I tried to run run_alphafold_test.py, and I think the line79-82, i.e., 
self.assertSequenceEqual(
        ['features.pkl', 'msas', 'ranked_0.pdb', 'ranking_debug.json',
         'relaxed_model1.pdb', 'result_model1.pkl', 'timings.json',
         'unrelaxed_model1.pdb'], target_output_files)

should be
self.assertSequenceEqual(
        sorted(['features.pkl', 'msas', 'ranked_0.pdb', 'ranking_debug.json',
         'relaxed_model1.pdb', 'result_model1.pkl', 'timings.json',
         'unrelaxed_model1.pdb']), sorted(target_output_files))

**Comment by Augustin-Zidek** [comment]
Thanks for reporting this. I will push a fix shortly (the easiest fix is to change `AssertSequenceEqual` to `AssertCountEqual`).

**Comment by Augustin-Zidek** [comment]
Fixed in https://github.com/deepmind/alphafold/commit/1d43aaff941c84dc56311076b58795797e49107b.

**Comment by rigan0707** [comment]
> Hi,
> 
> I tried to run run_alphafold_test.py, and I think the line79-82, i.e., self.assertSequenceEqual( ['features.pkl', 'msas', 'ranked_0.pdb', 'ranking_debug.json', 'relaxed_model1.pdb', 'result_model1.pkl', 'timings.json', 'unrelaxed_model1.pdb'], target_output_files)
> 
> should be self.assertSequenceEqual( sorted(['features.pkl', 'msas', 'ranked_0.pdb', 'ranking_debug.json', 'relaxed_model1.pdb', 'result_model1.pkl', 'timings.json', 'unrelaxed_model1.pdb']), sorted(target_output_files))
