### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by Soramuse** [deepmind/alphafold#169]
I0911 11:00:08.990978 140064779871040 run_docker.py:193] I0911 03:00:08.990507 140644718901056 run_alphafold.py:142] Running model model_1
I0911 11:00:13.139355 140064779871040 run_docker.py:193] I0911 03:00:13.138924 140644718901056 model.py:132] Running predict with shape(feat) = {'aatype': (4, 396), 'residue_index': (4, 396), 'seq_length': (4,), 'template_aatype': (4, 4, 396), 'template_all_atom_masks': (4, 4, 396, 37), 'template_all_atom_positions': (4, 4, 396, 37, 3), 'template_sum_probs': (4, 4, 1), 'is_distillation': (4,), 'seq_mask': (4, 396), 'msa_mask': (4, 508, 396), 'msa_row_mask': (4, 508), 'random_crop_to_size_seed': (4, 2), 'template_mask': (4, 4), 'template_pseudo_beta': (4, 4, 396, 3), 'template_pseudo_beta_mask': (4, 4, 396), 'atom14_atom_exists': (4, 396, 14), 'residx_atom14_to_atom37': (4, 396, 14), 'residx_atom37_to_atom14': (4, 396, 37), 'atom37_atom_exists': (4, 396, 37), 'extra_msa': (4, 5120, 396), 'extra_msa_mask': (4, 5120, 396), 'extra_msa_row_mask': (4, 5120), 'bert_mask': (4, 508, 396), 'true_msa': (4, 508, 396), 'extra_has_deletion': (4, 5120, 396), 'extra_deletion_value': (4, 5120, 396), 'msa_feat': (4, 508, 396, 49), 'target_feat': (4, 396, 22)}
I0911 11:00:13.288195 140064779871040 run_docker.py:193] 2021-09-11 03:00:13.287858: W external/org_tensorflow/tensorflow/stream_executor/gpu/asm_compiler.cc:235] Falling back to the CUDA driver for PTX compilation; ptxas does not support CC 8.6
I0911 11:00:13.288301 140064779871040 run_docker.py:193] 2021-09-11 03:00:13.287893: W external/org_tensorflow/tensorflow/stream_executor/gpu/asm_compiler.cc:238] Used ptxas at ptxas
I0911 11:00:13.291284 140064779871040 run_docker.py:193] 2021-09-11 03:00:13.290937: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:625] failed to get PTX kernel "shift_right_logical_3" from module: CUDA_ERROR_NOT_FOUND: named symbol not found
I0911 11:00:13.291444 140064779871040 run_docker.py:193] 2021-09-11 03:00:13.290991: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:2040] Execution of replica 0 failed: Internal: Could not find the corresponding function
I0911 11:00:13.304502 140064779871040 run_docker.py:193] Traceback (most recent call last):
I0911 11:00:13.304669 140064779871040 run_docker.py:193] File "/app/alphafold/run_alphafold.py", line 310, in <module>
I0911 11:00:13.304764 140064779871040 run_docker.py:193] app.run(main)
I0911 11:00:13.304851 140064779871040 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 312, in run
I0911 11:00:13.304934 140064779871040 run_docker.py:193] _run_main(main, args)
I0911 11:00:13.305018 140064779871040 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
I0911 11:00:13.305102 140064779871040 run_docker.py:193] sys.exit(main(argv))
I0911 11:00:13.305185 140064779871040 run_docker.py:193] File "/app/alphafold/run_alphafold.py", line 292, in main
I0911 11:00:13.305269 140064779871040 run_docker.py:193] random_seed=random_seed)
I0911 11:00:13.305352 140064779871040 run_docker.py:193] File "/app/alphafold/run_alphafold.py", line 149, in predict_structure
I0911 11:00:13.305434 140064779871040 run_docker.py:193] prediction_result = model_runner.predict(processed_feature_dict)
I0911 11:00:13.305516 140064779871040 run_docker.py:193] File "/app/alphafold/alphafold/model/model.py", line 133, in predict
I0911 11:00:13.305598 140064779871040 run_docker.py:193] result = self.apply(self.params, jax.random.PRNGKey(0), feat)
I0911 11:00:13.305680 140064779871040 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/jax/_src/random.py", line 105, in PRNGKey
I0911 11:00:13.305762 140064779871040 run_docker.py:193] True, prng.seed_with_impl(prng.threefry_prng_impl, seed))
I0911 11:00:13.305846 140064779871040 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/jax/_src/prng.py", line 190, in seed_with_impl
I0911 11:00:13.305929 140064779871040 run_docker.py:193] return PRNGKeyArray(impl, impl.seed(seed))
I0911 11:00:13.306011 140064779871040 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/jax/_src/prng.py", line 228, in threefry_seed
I0911 11:00:13.306093 140064779871040 run_docker.py:193] k1 = convert(lax.shift_right_logical(seed_arr, lax._const(seed_arr, 32)))
I0911 11:00:13.306175 140064779871040 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/jax/_src/lax/lax.py", line 386, in shift_right_logical
I0911 11:00:13.306257 140064779871040 run_docker.py:193] return shift_right_logical_p.bind(x, y)
I0911 11:00:13.306338 140064779871040 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/jax/core.py", line 267, in bind
I0911 11:00:13.306419 140064779871040 run_docker.py:193] out = top_trace.process_primitive(self, tracers, params)
I0911 11:00:13.306500 140064779871040 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/jax/core.py", line 612, in process_primitive
I0911 11:00:13.306582 140064779871040 run_docker.py:193] return primitive.impl(*tracers, **params)
I0911 11:00:13.306664 140064779871040 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/jax/interpreters/xla.py", line 275, in apply_primitive
I0911 11:00:13.306748 140064779871040 run_docker.py:193] return compiled_fun(*args)
I0911 11:00:13.306830 140064779871040 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/jax/interpreters/xla.py", line 391, in _execute_compiled_primitive
I0911 11:00:13.306914 140064779871040 run_docker.py:193] out_bufs = compiled.execute(input_bufs)
I0911 11:00:13.306996 140064779871040 run_docker.py:193] RuntimeError: Internal: Could not find the corresponding function

I want to ask for help, how can I fix this problem?

**Comment by Soramuse** [comment]
I'm using Ubuntu20.04, RTX3080,  Driver version: 465.31, CUDA Version: 11.3

**Comment by Augustin-Zidek** [comment]
Could you try changing CUDA version as suggested in https://github.com/deepmind/alphafold/issues/55#issuecomment-889914885? 

See also https://github.com/deepmind/alphafold/issues/83 or https://github.com/deepmind/alphafold/issues/117.
