### ISSUE TITLE
RuntimeError: Unknown: an illegal memory access was encountered in external...

### ISSUE THREAD

**Issue by mario0397** [deepmind/alphafold#170]
Hi, 

I have an error each time that I try to run a calculation. 

In the step "Run AlphaFold and download prediction", I get the error:

RuntimeError: Unknown: an illegal memory access was encountered
in external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_asm_compiler.cc(57): 'cuLinkCreate(0, nullptr, nullptr, &link_state)'

Please, it will be great if you can solve it or tell me how to solve it. 

Best regards, Mario.

![image](https://user-images.githubusercontent.com/90528920/132959796-d123fe1b-a0a2-4122-9310-638c8a58e949.png)

**Comment by Augustin-Zidek** [comment]
The error is happening during the relaxation stage – so I suspect you are giving OpenMM a prediction that causes it to crash. Could you try disabling it and checking whether the unrelaxed AlphaFold structure is sensible?

You can disable the relaxation stage by changing the following line in the "Run AlphaFold and download prediction" cell:

```py
relaxed_pdb, _, _ = amber_relaxer.process(
    prot=unrelaxed_proteins[best_model_name])
```
to
```py
relaxed_pdb = unrelaxed_proteins[best_model_name]
```

**Comment by andycowie** [comment]
Closing this as it seems to be dormant. Feel free to reopen if you have new results.
