### ISSUE TITLE
how to set pdb in JAX ?

### ISSUE THREAD

**Issue by wtzhao1631** [deepmind/alphafold#171]
When setting pdb in the modules.AlphaFold( ) function, I get the following error, how do I fix it? or how do I set pdb in the JAX environment?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run_alphafold.py", line 306, in <module>
    app.run(main)
  File "/opt/conda/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "run_alphafold.py", line 280, in main
    predict_structure(
  File "run_alphafold.py", line 148, in predict_structure
    timings[f'process_features_{model_name}'] = time.time() - t_0
  File "/home/workspace/alphafold/alphafold/model/model.py", line 133, in predict
    result = self.apply(self.params, jax.random.PRNGKey(0), feat)
  File "/opt/conda/lib/python3.8/site-packages/jax/_src/api.py", line 2485, in _check_arg
    raise TypeError(f"Argument '{arg}' of type {type(arg)} is not a valid JAX type.")
TypeError: Argument '[[12  7  3 11 14  9 17  6  5  9  7 15 15 13  9  5  8 18 18  5 10 13  3  2
   3  1 16  5 10  7  0  9 18  9  3  0 15  4 10 16 17  6  7  5  5 13  5  7
  11  0  0  9 19  6 11 10 15 15 10 14 13  5 11  9  5  8 15  9 16  0  5  3
   8  5 14 16 14  3 15  4  9  9 15 12 19 19  7  5 10 11  0  3  6  3 14  9
  12  7 13  8  5 12 13 10 10 11  2  9  2  3  0 17 19  4 16  2  3 12 13  1
  10  0 10  8  2 13  7]
 [12  7  3 11 14  9 17  6  5  9  7 15 15 13  9  5  8 18 18  5 10 13  3  2
   3  1 16  5 10  7  0  9 18  9  3  0 15  4 10 16 17  6  7  5  5 13  5  7
  11  0  0  9 19  6 11 10 15 15 10 14 13  5 11  9  5  8 15  9 16  0  5  3
   8  5 14 16 14  3 15  4  9  9 15 12 19 19  7  5 10 11  0  3  6  3 14  9
  12  7 13  8  5 12 13 10 10 11  2  9  2  3  0 17 19  4 16  2  3 12 13  1
  10  0 10  8  2 13  7]
 [12  7  3 11 14  9 17  6  5  9  7 15 15 13  9  5  8 18 18  5 10 13  3  2
   3  1 16  5 10  7  0  9 18  9  3  0 15  4 10 16 17  6  7  5  5 13  5  7
  11  0  0  9 19  6 11 10 15 15 10 14 13  5 11  9  5  8 15  9 16  0  5  3
   8  5 14 16 14  3 15  4  9  9 15 12 19 19  7  5 10 11  0  3  6  3 14  9
  12  7 13  8  5 12 13 10 10 11  2  9  2  3  0 17 19  4 16  2  3 12 13  1
  10  0 10  8  2 13  7]
 [12  7  3 11 14  9 17  6  5  9  7 15 15 13  9  5  8 18 18  5 10 13  3  2
   3  1 16  5 10  7  0  9 18  9  3  0 15  4 10 16 17  6  7  5  5 13  5  7
  11  0  0  9 19  6 11 10 15 15 10 14 13  5 11  9  5  8 15  9 16  0  5  3
   8  5 14 16 14  3 15  4  9  9 15 12 19 19  7  5 10 11  0  3  6  3 14  9
  12  7 13  8  5 12 13 10 10 11  2  9  2  3  0 17 19  4 16  2  3 12 13  1
  10  0 10  8  2 13  7]]' of type <class 'tensorflow.python.framework.ops.EagerTensor'> is not a valid JAX type.

**Comment by Augustin-Zidek** [comment]
It seems that you are providing a dictionary of TF tensors instead of dictionary of Numpy arrays. I recommend taking a look at the source code of the [AlphaFold Colab](https://colab.research.google.com/github/deepmind/alphafold/blob/main/notebooks/AlphaFold.ipynb) to see how the features are passed to the model.
