### ISSUE TITLE
max_template_date for running Alphafold

### ISSUE THREAD

**Issue by diwu524** [deepmind/alphafold#173]
Hi,

I am new to this, and trying to set up Alphafold on my server. I tried to run the following command and got an error message

python3 docker/run_docker.py --fasta_paths=../protein_seq/sam_orig.fasta  --preset=reduced_dbs

FATAL Flags parsing error: flag --max_template_date=None: Flag --max_template_date must have a value other than None.
Pass --helpshort or --helpfull to see help on flags.

So, I added the flag but still not able to run: python3 docker/run_docker.py --fasta_paths=../protein_seq/sam_orig.fasta --max_template_date=2021-05-14 --preset=reduced_dbs

I0915 18:02:01.947087 140080838014784 run_docker.py:119] Mounting /home/dw524/Documents/protein_seq -> /mnt/fasta_path_0
I0915 18:02:01.947247 140080838014784 run_docker.py:119] Mounting /home/dw524/Documents/alphafold/~/dw524/Documents/alphafold/reduced_db/uniref90 -> /mnt/uniref90_database_path
I0915 18:02:01.947338 140080838014784 run_docker.py:119] Mounting /home/dw524/Documents/alphafold/~/dw524/Documents/alphafold/reduced_db/mgnify -> /mnt/mgnify_database_path
I0915 18:02:01.947427 140080838014784 run_docker.py:119] Mounting /home/dw524/Documents/alphafold/~/dw524/Documents/alphafold/reduced_db/pdb70 -> /mnt/pdb70_database_path
I0915 18:02:01.947496 140080838014784 run_docker.py:119] Mounting /home/dw524/Documents/alphafold -> /mnt/data_dir
I0915 18:02:01.947571 140080838014784 run_docker.py:119] Mounting /home/dw524/Documents/alphafold/~/dw524/Documents/alphafold/reduced_db/pdb_mmcif -> /mnt/template_mmcif_dir
I0915 18:02:01.947643 140080838014784 run_docker.py:119] Mounting /home/dw524/Documents/alphafold/~/dw524/Documents/alphafold/reduced_db/pdb_mmcif -> /mnt/obsolete_pdbs_path
I0915 18:02:01.947713 140080838014784 run_docker.py:119] Mounting /home/dw524/Documents/alphafold/~/dw524/Documents/alphafold/reduced_db/small_bfd -> /mnt/small_bfd_database_path
Traceback (most recent call last):
  File "/home/dw524/.local/lib/python3.8/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.41/containers/create

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/run_docker.py", line 201, in <module>
    app.run(main)
  File "/home/dw524/.local/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/dw524/.local/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "docker/run_docker.py", line 173, in main
    container = client.containers.run(
  File "/home/dw524/.local/lib/python3.8/site-packages/docker/models/containers.py", line 811, in run
    container = self.create(image=image, command=command,
  File "/home/dw524/.local/lib/python3.8/site-packages/docker/models/containers.py", line 870, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/home/dw524/.local/lib/python3.8/site-packages/docker/api/container.py", line 430, in create_container
    return self.create_container_from_config(config, name)
  File "/home/dw524/.local/lib/python3.8/site-packages/docker/api/container.py", line 441, in create_container_from_config
    return self._result(res, True)
  File "/home/dw524/.local/lib/python3.8/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/home/dw524/.local/lib/python3.8/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/home/dw524/.local/lib/python3.8/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.41/containers/create: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /home/dw524/Documents/alphafold/~/dw524/Documents/alphafold/reduced_db/uniref90")

Could anyone help me with this please? I am just using the reduced database, and not sure how I should set the max_template_date. Thanks!

**Comment by Augustin-Zidek** [comment]
Hi, you are setting the `max_template_data` correctly and the error is unrelated to that. I believe the problem is with the `uniref90` path since the error says:

```
Bad Request ("invalid mount config for type "bind": bind source path does not exist: /home/dw524/Documents/alphafold/~/dw524/Documents/alphafold/reduced_db/uniref90")
```

Could you check that directory exists and Docker is able to access it?

**Comment by diwu524** [comment]
> Hi, you are setting the `max_template_data` correctly and the error is unrelated to that. I believe the problem is with the `uniref90` path since the error says:
> 
> ```
> Bad Request ("invalid mount config for type "bind": bind source path does not exist: /home/dw524/Documents/alphafold/~/dw524/Documents/alphafold/reduced_db/uniref90")
> ```
> 
> Could you check that directory exists and Docker is able to access it?

Ah, ok. I checked the path and uniref90 folder does not exist. I was following the instructions on Github and installed only the reduced dataset. How should I install uniref90? I just tried 'scripts/download_all_data.sh reduced_db/ uniref90', and it does not work. Thank you!

**Comment by Augustin-Zidek** [comment]
You will have run the following:

```
scripts/download_uniref90.sh <full path to the directory where you have other databases>
```

i.e.
 
```
scripts/download_uniref90.sh /home/dw524/Documents/alphafold/~/dw524/Documents/alphafold/reduced_db/
```

Make also sure you have enough space on your disk to download UniRef90 (58 GB unpacked, 29.7 GB when downloaded as tar.gz) – that might have been the reason it failed to download before.
