### ISSUE TITLE
ModuleNotFoundError: No module named 'simtk.openmm.app.internal'

### ISSUE THREAD

**Issue by archana433** [deepmind/alphafold#175]
> python3 run_alphafold.py 
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
Traceback (most recent call last):
  File "/media/temp/archana/alphafold-main/run_alphafold.py", line 35, in <module>
    from alphafold.relax import relax
  File "/media/temp/archana/alphafold-main/alphafold/relax/relax.py", line 18, in <module>
    from alphafold.relax import amber_minimize
  File "/media/temp/archana/alphafold-main/alphafold/relax/amber_minimize.py", line 26, in <module>
    from alphafold.relax import utils
  File "/media/temp/archana/alphafold-main/alphafold/relax/utils.py", line 21, in <module>
    from simtk.openmm.app.internal.pdbstructure import PdbStructure
ModuleNotFoundError: No module named 'simtk.openmm.app.internal'

I have already installed the openmm  with conda install -c conda-forge openmm command. Also tried with pip also.
Please suggest some solution.

**Comment by Augustin-Zidek** [comment]
I think this is because you installed OpenMM 7.6.0 while AlphaFold works with 7.5.1.

Could you try installing OpenMM using this command: `conda install -c conda-forge openmm=7.5.1`?

**Comment by archana433** [comment]
Thanks, it resolved.

**Comment by yangqiong888** [comment]
if this question happend at goole colab,how can i do?what command i should run?

**Comment by yangqiong888** [comment]
> I think this is because you installed OpenMM 7.6.0 while AlphaFold works with 7.5.1.
> 
> Could you try installing OpenMM using this command: `conda install -c conda-forge openmm=7.5.1`?
what command should i run i use goole colab

**Comment by biotech70** [comment]
I removed openmm v7.7 and installed v7.5.1 using conda install -c conda-forge openmm=7.5.1, but the error still persists.

**Comment by mainguyenanhvu** [comment]
@biotech70 How did you deal with the problem? I reinstall it by using `conda install -c conda-forge openmm=7.5.1`, but it threw a new error:
```
/python3.9/site-packages/openmmtools/utils/equilibration.py", line 6, in <module>
    from openmm import unit, OpenMMException
ModuleNotFoundError: No module named 'openmm'
```

Please help me to solve it.

**Comment by LWjustdo** [comment]
I reinstall it by using conda install -c conda-forge openmm=7.5.1, but it threw a new error:ModuleNotFoundError: No module named 'openmm'
