### ISSUE TITLE
Calculation error

### ISSUE THREAD

**Issue by LuXuhui666** [deepmind/alphafold#177]
When I calculated the fusion protein with only 491 amino acid residues, and there was a Linker in the middle (I think linker is not the main reason),  the program reported two errors during the calculation, the errors are as follows:
**-23:08:31.477 INFO：Realigning 41595 HMM-HMM alignments using Maximum Accuracy algorithm
-23:29:54.044 ERROR: Error in /home /software/hh-suite-master/src/hhalignment.cpp:3456:MergeMasterSlave:
-23:29:54.044 ERROR:     did not find 549 match states in sequence 1 of  Srr557859_7281350. Seuquence:(Sequence omitted)**
(This sequence doesn't come from my protein sequence, I don't know where. And my protein sequence is only 491 amino acids, no 549.)

**Comment by Augustin-Zidek** [comment]
There are multiple options and workarounds:
1. Update UniClust to a newer version. See https://github.com/soedinglab/hh-suite/issues/277.
2. Run HHBlits only against BFD, but not against UniClust (note the result quality might be slightly lower). 
3. Use the [AlphaFold Colab](https://colab.research.google.com/github/deepmind/alphafold/blob/main/notebooks/AlphaFold.ipynb) that doesn't use HHBlits (note the result quality might be slightly lower).
