### ISSUE TITLE
PDB_mmcif database download issue

### ISSUE THREAD

**Issue by AnjaliSetiya** [deepmind/alphafold#179]
I have been trying to download PDB_mmcif database with aria2c as well as rsync but i am getting the same issue
**rsync: failed to connect to rsync.wwpdb.org (132.249.210.197): Connection timed out (110)
rsync error: error in socket IO (code 10) at clientserver.c(125) [Receiver=3.1.2]**

Please let me know is there is any other way that i can download the databases
Thank you

**Comment by Augustin-Zidek** [comment]
You could try using a different mirror, see https://www.wwpdb.org/ftp/pdb-ftp-sites for a list of mirrors available.

Change the mirror in `scripts/download_pdb_mmcif.sh`. Here is an example that uses EBI's mirror:

```
rsync --recursive --links --perms --times --compress --info=progress2 --delete --port=33444 \
  rsync.ebi.ac.uk::pub/databases/pdb/data/structures/divided/mmCIF/ \
  "${RAW_DIR}"
```

Try to use a mirror that is close to your geographic location (PDBj for Asia, EBI for Europe, RCSB for America).

**Comment by archana433** [comment]
I used a different mirror but getting the same error. 
Running rsync to fetch all mmCIF files (note that the rsync progress estimate might be inaccurate)...
rsync: failed to connect to rsync.ebi.ac.uk (193.62.193.138): Connection refused (111)
rsync error: error in socket IO (code 10) at clientserver.c(127) [Receiver=3.1.3]

Please let me know is there is any other way that i can download the databases
Thank you

**Comment by shanizev** [comment]
Hi, 
same problem here (Asian region)
I did try a different mirror and it is still not working. 

rsync: failed to connect to data.pdbj.org (133.1.158.160): Connection timed out (110)
rsync error: error in socket IO (code 10) at clientserver.c(125) [Receiver=3.1.2]

thanks

**Comment by DininduSenanayake** [comment]
@shanizev : Were you using `--port=33444` for Asia mirror ?. If yes, try changing it to `873` .i.e.

```
rsync --recursive --links --perms --times --compress --info=progress2 --delete --port=873 \
  ftp.pdbj.org::ftp_data/structures/divided/mmCIF/  \
  "${RAW_DIR}"
```

**Comment by benjaminlozanow** [comment]
It is probably a problem with the firewall and rsync. It happened the same when I was running it at my University.
You can talk to your IT support or use a script I developed to download the database without using rsync https://github.com/benjaminlozanow/pdb_data_download

**Comment by sunqiangzai** [comment]
> @shanizev : Were you using `--port=33444` for Asia mirror ?. If yes, try changing it to `873` .i.e.
> 
> ```
> rsync --recursive --links --perms --times --compress --info=progress2 --delete --port=873 \
>   ftp.pdbj.org::ftp_data/structures/divided/mmCIF/  \
>   "${RAW_DIR}"
> ```

solved, thanks
