### ISSUE TITLE
Issue regarding downloading the PDB_mmcif database 

### ISSUE THREAD

**Issue by AnjaliSetiya** [deepmind/alphafold#180]
I have followed your tutorial have been trying to download PDB_mmcif database with aria2c as well as rsync but i am getting the same issue
rsync: failed to connect to rsync.wwpdb.org (132.249.210.197): Connection timed out (110)
rsync error: error in socket IO (code 10) at clientserver.c(125) [Receiver=3.1.2]

Please let me know is there is any other way that i can download the databases
Thank you

**Comment by Augustin-Zidek** [comment]
You could try using a different mirror, see https://www.wwpdb.org/ftp/pdb-ftp-sites for a list of mirrors available.

Change the mirror in `scripts/download_pdb_mmcif.sh`. Here is an example that uses EBI's mirror:

```
rsync --recursive --links --perms --times --compress --info=progress2 --delete --port=33444 \
  rsync.ebi.ac.uk::pub/databases/pdb/data/structures/divided/mmCIF/ \
  "${RAW_DIR}"
```

Try to use a mirror that is close to your geographic location (PDBj for Asia, EBI for Europe, RCSB for America).

**Comment by martin-jeremy** [comment]
I try all the mirrors and I still have the same issue. I'm from Europe region. Any advice ?
