### ISSUE TITLE
Use contact/distance restraints

### ISSUE THREAD

**Issue by nzhang89** [deepmind/alphafold#181]
Is it possible to use additional restraints (e.g. from cross-link experiments we know two residues are in contact) as input, which is implemented in for example I-TASSER ([https://zhanggroup.org/I-TASSER/option1.html](https://zhanggroup.org/I-TASSER/option1.html))? Thank you.

**Comment by Augustin-Zidek** [comment]
Sorry, this feature is not supported in AlphaFold.

**Comment by fabiotrovato** [comment]
Hi, 
I am following this issue as it is an interesting use case, especially for multi-domain protein with high flexibility. For example, in the EMBL-EBI database there are many predicted proteins that are long (2000 res) and mostly unstructured with few folded domains. In a cell, it is possible that such proteins have very different conformations compared to the one predicted by Alphafold and crosslinks in vivo can provide such structural information. 

Let's suppose I have a set of distance restraints. Is it possible to modify the Alphafold code so to pass the crosslinks (list of atom pair indices)?. I am happy to code this functionality, if I can have some guidance from the Alphafold developers and if the license allows this.

Thank you,
Fabio
