### ISSUE TITLE
Allocator (GPU_0_bfc) ran out of memory trying to allocate 45.45GiB (rounded to 48803099904)requested by op

### ISSUE THREAD

**Issue by stefanoliver** [deepmind/alphafold#184]
Not sure if this is a new topic but running AlphaFold2 on my workstation produced the following error...

Allocator (GPU_0_bfc) ran out of memory trying to allocate 45.45GiB (rounded to 48803099904)requested by op

My workstation has the following hardware...
Intel Xeon W-2195 CPU @2.3GHz
256 Gb system memory
Four GeForce RTX 2080Ti GPUs

The protein length I was modelling was 2757aa

The output after the error was...
I0922 09:49:00.854184 140053800166976 run_docker.py:193] 2021-09-22 16:49:00.853879: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:2040] Execution of replica 0 failed: Resource exhausted: Out of memory while trying to allocate 48803099744 bytes.
I0922 09:49:00.869728 140053800166976 run_docker.py:193] Traceback (most recent call last):
I0922 09:49:00.869844 140053800166976 run_docker.py:193] File "/app/alphafold/run_alphafold.py", line 302, in <module>
I0922 09:49:00.869922 140053800166976 run_docker.py:193] app.run(main)
I0922 09:49:00.869991 140053800166976 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 312, in run
I0922 09:49:00.870054 140053800166976 run_docker.py:193] _run_main(main, args)
I0922 09:49:00.870125 140053800166976 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
I0922 09:49:00.870186 140053800166976 run_docker.py:193] sys.exit(main(argv))
I0922 09:49:00.870245 140053800166976 run_docker.py:193] File "/app/alphafold/run_alphafold.py", line 284, in main
I0922 09:49:00.870305 140053800166976 run_docker.py:193] random_seed=random_seed)
I0922 09:49:00.870364 140053800166976 run_docker.py:193] File "/app/alphafold/run_alphafold.py", line 148, in predict_structure
I0922 09:49:00.870422 140053800166976 run_docker.py:193] prediction_result = model_runner.predict(processed_feature_dict)
I0922 09:49:00.870481 140053800166976 run_docker.py:193] File "/app/alphafold/alphafold/model/model.py", line 133, in predict
I0922 09:49:00.870540 140053800166976 run_docker.py:193] result = self.apply(self.params, jax.random.PRNGKey(0), feat)
I0922 09:49:00.870598 140053800166976 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/jax/_src/traceback_util.py", line 183, in reraise_with_filtered_traceback
I0922 09:49:00.870657 140053800166976 run_docker.py:193] return fun(*args, **kwargs)
I0922 09:49:00.870749 140053800166976 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/jax/_src/api.py", line 402, in cache_miss
I0922 09:49:00.870804 140053800166976 run_docker.py:193] donated_invars=donated_invars, inline=inline)
I0922 09:49:00.870858 140053800166976 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/jax/core.py", line 1561, in bind
I0922 09:49:00.870912 140053800166976 run_docker.py:193] return call_bind(self, fun, *args, **params)
I0922 09:49:00.870966 140053800166976 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/jax/core.py", line 1552, in call_bind
I0922 09:49:00.871020 140053800166976 run_docker.py:193] outs = primitive.process(top_trace, fun, tracers, params)
I0922 09:49:00.871077 140053800166976 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/jax/core.py", line 1564, in process
I0922 09:49:00.871133 140053800166976 run_docker.py:193] return trace.process_call(self, fun, tracers, params)
I0922 09:49:00.871187 140053800166976 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/jax/core.py", line 607, in process_call
I0922 09:49:00.871240 140053800166976 run_docker.py:193] return primitive.impl(f, *tracers, **params)
I0922 09:49:00.871294 140053800166976 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/jax/interpreters/xla.py", line 610, in _xla_call_impl
I0922 09:49:00.871347 140053800166976 run_docker.py:193] return compiled_fun(*args)
I0922 09:49:00.871402 140053800166976 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/jax/interpreters/xla.py", line 898, in _execute_compiled
I0922 09:49:00.871455 140053800166976 run_docker.py:193] out_bufs = compiled.execute(input_bufs)
I0922 09:49:00.871510 140053800166976 run_docker.py:193] jax._src.traceback_util.UnfilteredStackTrace: RuntimeError: Resource exhausted: Out of memory while trying to allocate 48803099744 bytes.
I0922 09:49:00.871565 140053800166976 run_docker.py:193] 
I0922 09:49:00.871618 140053800166976 run_docker.py:193] The stack trace below excludes JAX-internal frames.
I0922 09:49:00.871672 140053800166976 run_docker.py:193] The preceding is the original exception that occurred, unmodified.
I0922 09:49:00.871725 140053800166976 run_docker.py:193] 
I0922 09:49:00.871779 140053800166976 run_docker.py:193] --------------------
I0922 09:49:00.871833 140053800166976 run_docker.py:193] 
I0922 09:49:00.871887 140053800166976 run_docker.py:193] The above exception was the direct cause of the following exception:
I0922 09:49:00.871941 140053800166976 run_docker.py:193] 
I0922 09:49:00.871994 140053800166976 run_docker.py:193] Traceback (most recent call last):
I0922 09:49:00.872048 140053800166976 run_docker.py:193] File "/app/alphafold/run_alphafold.py", line 302, in <module>
I0922 09:49:00.872107 140053800166976 run_docker.py:193] app.run(main)
I0922 09:49:00.872160 140053800166976 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 312, in run
I0922 09:49:00.872215 140053800166976 run_docker.py:193] _run_main(main, args)
I0922 09:49:00.872268 140053800166976 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
I0922 09:49:00.872322 140053800166976 run_docker.py:193] sys.exit(main(argv))
I0922 09:49:00.872375 140053800166976 run_docker.py:193] File "/app/alphafold/run_alphafold.py", line 284, in main
I0922 09:49:00.872429 140053800166976 run_docker.py:193] random_seed=random_seed)
I0922 09:49:00.872484 140053800166976 run_docker.py:193] File "/app/alphafold/run_alphafold.py", line 148, in predict_structure
I0922 09:49:00.872538 140053800166976 run_docker.py:193] prediction_result = model_runner.predict(processed_feature_dict)
I0922 09:49:00.872591 140053800166976 run_docker.py:193] File "/app/alphafold/alphafold/model/model.py", line 133, in predict
I0922 09:49:00.872645 140053800166976 run_docker.py:193] result = self.apply(self.params, jax.random.PRNGKey(0), feat)
I0922 09:49:00.872698 140053800166976 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/jax/interpreters/xla.py", line 898, in _execute_compiled
I0922 09:49:00.872752 140053800166976 run_docker.py:193] out_bufs = compiled.execute(input_bufs)
I0922 09:49:00.872805 140053800166976 run_docker.py:193] RuntimeError: Resource exhausted: Out of memory while trying to allocate 48803099744 bytes.

I'm a complete novice when it comes to interpreting and solving issues on Linux-based systems so please provide clear feedback on how to solve the problem, if possible.

Thanks in advance!

**Comment by Augustin-Zidek** [comment]
A quick workaround would be to split the protein in two overlapping parts (e.g. 1–1500 and 1257–2757) and merge these afterwards. By doing this, you would be running AlphaFold in a regime which we verified to work well.

Is this a feasible solution for you?

**Comment by stefanoliver** [comment]
> Is this a feasible solution for you?

Thanks for the reply.  I'll give it a go.  Was the error caused by a lack of resources or is there something else going on?

**Comment by Augustin-Zidek** [comment]
> Was the error caused by a lack of resources or is there something else going on?

Most likely the former, given how long your sequence is.

**Comment by ValZapod** [comment]
> Was the error caused by a lack of resources

I also have ome 2080 Ti. I had an impression that you can only use 1 GPU memory, unless NVlink is really that good?

**Comment by stefanoliver** [comment]
> > Was the error caused by a lack of resources or is there something else going on?
> 
> Most likely the former, given how long your sequence is.
AlphaFold2 only seems to be able to use 1 GPU.  There are 4 in the workstation but only one is being used.  Can AlphaFold2 use more than one GPU?

**Comment by nnnwyn** [comment]
> 
Hi, is there any idea in how to merge two proteins?
