### ISSUE TITLE
RuntimeError: Resource exhausted

### ISSUE THREAD

**Issue by JW-2021** [deepmind/alphafold#185]
Hi,

I was trying to fold a large complex with over 7,000aa in total. I ran the job on our cluster with the following settings:  460G RAM, 48 CPUs, but the job failed in the end because of the following error: **RuntimeError: Resource exhausted: Out of memory while trying to allocate 294970604000 bytes.** 

I don't know if it's a Jax/tensorflow error, but I tried lowering "XLA_PYTHON_CLIENT_MEM_FRACTION" to "0.1" and setting "XLA_PYTHON_CLIENT_PREALLOCATE=false". However, these didn't solve the problem. 

Could this be caused by some internal memory exhaustions in the program, with software buffers being overflowed? 
Any suggestions on how to solve it would be highly appreciated!
Thank you in advance!

The following is the tail information of the log file.

$ tail AF2_slurm_57293_snoke5_alphafold_57293_4294967294.l 
sys.exit(main(argv))
File "/opt/bioxray/programs/anaconda3/envs/alphafold/alphafold/run_alphafold.py", line 284, in main
predict_structure(
File "/opt/bioxray/programs/anaconda3/envs/alphafold/alphafold/run_alphafold.py", line 149, in predict_structure
prediction_result = model_runner.predict(processed_feature_dict)
File "/opt/bioxray/programs/anaconda3/envs/alphafold/alphafold/alphafold/model/model.py", line 133, in predict
result = self.apply(self.params, jax.random.PRNGKey(0), feat)
File "/opt/bioxray/programs/anaconda3/envs/alphafold/lib/python3.8/site-packages/jax/interpreters/xla.py", line 912, in _execute_compiled
out_bufs = compiled.execute(input_bufs)
RuntimeError: Resource exhausted: Out of memory while trying to allocate 294970604000 bytes.

**Comment by Augustin-Zidek** [comment]
A quick workaround would be to run on 2,500 amino acid chunks (with overlaps) and merge them afterwards. By doing this, you would be running AlphaFold in a regime which we verified to work well. 

Is this a feasible solution for you?

**Comment by JW-2021** [comment]
Hi, 
Thanks a lot for your kind reply. I have tried this strategy and performed several runs of different chunk assemblies. Unfortunately, I couldn't get any promising model using chunks for folding. The subunit pieces couldn't fold into any complex. That's strange because they can form stable complexes in vitro. 
Anyway, thank you all the same.

**Comment by subedibp** [comment]
I do get similar error message for my approx 1.2K long residue. My intent is to see how they fold as a trimer but I have not been able to execute the code and run it for just a monomer. I managed to do it as a monomer of two domains but again cannot get the trimer of either domains as even small domain of 400AA would result in "resource exhausted". Any suggestion to make it run? I am a beginner with very basic coding skills and rely entirely on colab for model prediction. Thank you in advance for your help and support.

**Comment by JW-2021** [comment]
Hi,
I think you have a different error from mine.
If you are using the ColabFold, normally it's no problem to fold a model with 1,2k aa. It's a little strange if you got a "resource exhausted" error for 400aa. There's something that might be worth trying. You could generate fewer models, like 3 instead of 5, and use fewer sequences for alignment. If it couldn't solve the problem, you may try to run Alphafold2 job in Colab PRO+, and I could fold models of 1500aa in the PRO+ version using the full database without any problems. 
Hope it can help you.

**Comment by subedibp** [comment]
Thanks for the response and I shall try what you suggested. More, resource exhausted error message for 400aa is mostly because I am trying trimer prediction which exceeds 1K aa. I noticed the optimal residues that could be used for folding within colab is 1.1K (atleast in my case). I was wondering if there is way I could increase that without having to pay for Colab pro. Thank you once again and any further suggestion are welcome if I can get to fold more aa residues (even upto 1.3K)

**Comment by andycowie** [comment]
Closing this as it seems to no longer be an issue. Feel free to reopen if there is still a problem.

**Comment by ChrisJWest** [comment]
> Hi, I think you have a different error from mine. If you are using the ColabFold, normally it's no problem to fold a model with 1,2k aa. It's a little strange if you got a "resource exhausted" error for 400aa. There's something that might be worth trying. You could generate fewer models, like 3 instead of 5, and use fewer sequences for alignment. If it couldn't solve the problem, you may try to run Alphafold2 job in Colab PRO+, and I could fold models of 1500aa in the PRO+ version using the full database without any problems. Hope it can help you.

I'm running ColabPro via the Alpha Colab notebook with ~1000AA and was getting the issues above. I was wondering, how do we modify the number of models in the notebook? I may have missed it but I didn't see where I could change the parameter. Thanks!

**Comment by aissak21** [comment]
I've got similar concerns on ColabFold. I'm running a sequence of similar length as the test sequence (59 characters) and get "REsource exhausted: Out of memory while trying to allocate 1048576 bytes." Tryna figure out how to solve this without going pro.

**Comment by Augustin-Zidek** [comment]
The problem with Colab is that you can land on a machine with a low-spec GPU which then can't handle even shorter proteins. But the issue with a 59-residue sequence looks suspicious, I recommend restarting the Colab runtime and trying again.

Modifying the number of models will not help, since the models run one after another and have very similar memory usage.

I recommend one of the following options: 
* restarting the Colab - you might get a GPU with more memory, 
* looking up the sequence in [AlphaFold Protein Structure Database](www.alphafold.com), 
* running AlphaFold locally, 
* running with Colab Pro.

**Comment by aissak21** [comment]
Thank you. I actually did run it into the database. I think restarting Colab would be the best option.
