### ISSUE TITLE
release new version (v2.1.0)?

### ISSUE THREAD

**Issue by boegel** [deepmind/alphafold#186]
Considerable changes have been made in the `main` branch since `v2.0.0` was tagged (see https://github.com/deepmind/alphafold/compare/v2.0.0..main), one of which is support for running with a reduced database via `--preset=reduced_dbs` which is very useful.

Are there any plans to tag newer versions of AlphaFold, like `v2.1.0`?

That would be really helpful, to ensure that AlphaFold installations are not just random commits, but specific "releases".

**Comment by sassy-crick** [comment]
I second that. The software is getting quite some traction and thus it is important to have a reproducible installation, which can be achieved by proper releases. It is frustrating for users if they want to use the software on a different facility and then they have to fiddle around, simply their installation procedure is `git clone` in the lack of proper releases.

**Comment by ashrafgt** [comment]
Strongly agreed. I've been waiting on a new official release since this:
https://github.com/deepmind/alphafold/issues/29#issuecomment-882605365

**Comment by Augustin-Zidek** [comment]
Sorry for the delay. We just released v2.0.1: https://github.com/deepmind/alphafold/releases/tag/v2.0.1.
