### ISSUE TITLE
uniclust30 bottleneck

### ISSUE THREAD

**Issue by chrisroat** [deepmind/alphafold#19]
Thank you for your work fixing #13 -- that really helped!  

I am now seeing a similar download bottleneck with uniclust30 (it has effectively stalled).

**Comment by chrisroat** [comment]
FYI, this will eventually succeed.  It took 6+ hours to download 25GB.

**Comment by tfgg** [comment]
Hi, if this is still a problem we have made a mirror available:

https://storage.googleapis.com/alphafold-databases/casp14_versions/uniclust30_2018_08_hhsuite.tar.gz

This makes available:
“[Uniclust30: v2018_08](http://wwwuser.gwdg.de/~compbiol/uniclust/2018_08/)” (unmodified), by Mirdita M. et al., available under a [Creative Commons Attribution-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-sa/4.0/).
