### ISSUE TITLE
amber_minimize.py is not using GPU? source code line 93

### ISSUE THREAD

**Issue by baoxingsong** [deepmind/alphafold#193]
The relax step using openmm is computational cost.
When running AlphaFold, I noticed AlphaFold is using CPU for the relax step. The openmm document indicates it could use GPU.
Is there any reason why line 93 of amber_minimize.py is configured as using CPU, please?

**Comment by georgkempf** [comment]
I was also wondering about this. I changed it to CUDA which seems to work fine. There's a significant speed increase for large models when using GPU.

**Comment by YaoYinYing** [comment]
yes it works fine to me. 
[see the instructions](http://docs.openmm.org/latest/userguide/library/04_platform_specifics.html#cuda-platform)

**Comment by FilomenoSanchez** [comment]
@georgkempf  I'm trying to make this step run on GPU instead of CPU as well but I'm not very experienced with this part of the code. Could you describe what you changed in the code? (code diff would be fine). Thanks!

**Comment by JiaqingFu** [comment]
@georgkempf @baoxingsong  I change the code of amber_minimize.py from 'CPU' to 'CUDA',and it did make the code run on gpu(view from nvidia-smi,occupy gpu util),but I find the running time just the same ,do you know why?

**Comment by georgkempf** [comment]
@FilomenoSanchez 
You need to replace "CPU" by "CUDA" in the following file and line:
https://github.com/deepmind/alphafold/blob/be37a41d6f83e4145bd4912cbe8bf6a24af80c29/alphafold/relax/amber_minimize.py#L93

The line should then look like this:
`platform = openmm.Platform.getPlatformByName("CUDA") `

@JiaqingFu 
How long are your sequences? I didn't benchmark it systematically but I had the impression that for long sequences, e.g. 2-5k it made a big difference.

**Comment by ojcharles** [comment]
Good discussion so far,
just wanted to contribute a small test I did, setting lines 93 and 533 as "CPU" then rerunning set as "CUDA".
Amber minimise iteration time cost summary over 5 models
    CPU:      mean-5.5m   stdev-3.9m
    CUDA:   mean-19.6s   stdev   4.7s
    Setup:   AMD Ryzen Threadripper 3970X     RTX TITAN
    Query:   Aspergillus nidulans VosA-VelB hetero-complex    759 AA length
no comparison, and as mentioned above this time cost divergence should only increase for larger proteins.
imho "CUDA" should be the default.

**Comment by Augustin-Zidek** [comment]
Hi, this was fixed in https://github.com/deepmind/alphafold/commit/57a2455e5fab752d8df430ae1d0334e1a21b548c - AlphaFold now uses GPU for relaxation by default. You can turn that off using `use_gpu_relax=false` or turn off relax completely using `run_relax=false`.
