### ISSUE TITLE
Issue regarding downloading the PDB_mmcif database 

### ISSUE THREAD

**Issue by archana433** [deepmind/alphafold#196]
I used a different mirror but getting the same error.
Running rsync to fetch all mmCIF files (note that the rsync progress estimate might be inaccurate)...
rsync: failed to connect to rsync.ebi.ac.uk (193.62.193.138): Connection refused (111)
rsync error: error in socket IO (code 10) at clientserver.c(127) [Receiver=3.1.3]

rsync --recursive --links --perms --times --compress --info=progress2 --delete --port=33444
rsync.data.pdbj.org::ftp_data/structures/divided/mmCIF/
"${RAW_DIR}"

Running rsync to fetch all mmCIF files (note that the rsync progress estimate might be inaccurate)...
rsync: getaddrinfo: rsync.data.pdbj.org 33444: Name or service not known
rsync error: error in socket IO (code 10) at clientserver.c(137) [Receiver=3.2.3]

$ rsync -avz --delete data.pdbj.org::ftp_data/structures/divided/mmCIF/ ./download
rsync: [Receiver] failed to connect to data.pdbj.org (133.1.158.160): Connection refused (111)
rsync error: error in socket IO (code 10) at clientserver.c(137) [Receiver=3.2.3]

Please let me know if there is any other way for the Asian region that I can download the databases
Thank you

**Comment by sjdv1982** [comment]
I believe that only the RCSB uses port 33444, the EBI uses the default rsync port. 
The following works for me:

```
rsync --recursive --links --perms --times --compress --info=progress2 --delete \
  rsync.ebi.ac.uk::pub/databases/pdb/data/structures/divided/mmCIF/ \
  "${RAW_DIR}"
```

**Comment by Augustin-Zidek** [comment]
I would also recommend trying other PDB mirrors as @sjdv1982 suggested and see if any of them works for you. It is also possible this was just a temporary issue so it might work now. Closing this issue for now, feel free to reopen it if this problem persists.
