### ISSUE TITLE
link to paper in readme is down

### ISSUE THREAD

**Issue by ryan-wolbeck** [deepmind/alphafold#2]
When clicking the link to the paper I get the following

![1DCA136E-9B13-4AD4-B4F1-8E466BD2470D](https://user-images.githubusercontent.com/41489316/125843789-0ecc67a2-1ce2-47c0-8aad-a733dcdb4f65.png)

If you could share the proper link I'd be happy to submit a PR :)

**Comment by Augustin-Zidek** [comment]
The link should work now. Could you check again?

**Comment by ryan-wolbeck** [comment]
yep it's working thanks @Augustin-Zidek
