### ISSUE TITLE
Singularity - HHblits: Could find neither hhm_db nor a3m_db

### ISSUE THREAD

**Issue by gmfricke** [deepmind/alphafold#202]
Hello,
 Running alphafold using a singularity image built from the alphafold docker image I get:

```
1007 18:24:10.061186 139722171791168 utils.py:40] Finished Jackhmmer (mgy_clusters_2018_12.fa) query in 1309.504 seconds
I1007 18:24:10.062455 139722171791168 hhsearch.py:76] Launching subprocess "/usr/bin/hhsearch -i /tmp/tmpju8xhewb/query.a3m -o /tmp/tmpju8xhewb/output.hhr -maxseq 1000000 -d /data/pdb70/pdb70"
I1007 18:24:10.082331 139722171791168 utils.py:36] Started HHsearch query
I1007 18:24:56.723806 139722171791168 utils.py:40] Finished HHsearch query in 46.641 seconds
I1007 18:24:56.840150 139722171791168 hhblits.py:128] Launching subprocess "/usr/bin/hhblits -i /input.fasta -cpu 4 -oa3m /tmp/tmpvyfkzgfa/output.a3m -o /dev/null -n 3 -e 0.001 -maxseq 1000000 -realign_max 100000 -maxfilt 100000 -min_prefilter_hits 1000 -d /data/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt -d /data/uniclust30/uniclust30_2018_08/uniclust30_2018_08"
I1007 18:24:56.860358 139722171791168 utils.py:36] Started HHblits query
I1007 18:27:01.512093 139722171791168 utils.py:40] Finished HHblits query in 124.650 seconds
E1007 18:27:01.512362 139722171791168 hhblits.py:138] HHblits failed. HHblits stderr begin:
E1007 18:27:01.512461 139722171791168 hhblits.py:141] - 18:27:01.456 ERROR: Could find neither hhm_db nor a3m_db!
E1007 18:27:01.512520 139722171791168 hhblits.py:142] HHblits stderr end
Traceback (most recent call last):
  File "./run_alphafold.py", line 283, in <module>
    app.run(main)
  File "/opt/alphafoldenv/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/opt/alphafoldenv/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "./run_alphafold.py", line 255, in main
    predict_structure(
  File "./run_alphafold.py", line 115, in predict_structure
    feature_dict = data_pipeline.process(
  File "/app/alphafold/alphafold/data/pipeline.py", line 151, in process
    hhblits_bfd_uniclust_result = self.hhblits_bfd_uniclust_runner.query(
  File "/app/alphafold/alphafold/data/tools/hhblits.py", line 143, in query
    raise RuntimeError('HHblits failed\nstdout:\n%s\n\nstderr:\n%s\n' % (
RuntimeError: HHblits failed
stdout:


stderr:
- 18:27:01.456 ERROR: Could find neither hhm_db nor a3m_db!

```
All required data appears to be in the correct places and are reachable from within the image.

```
Singularity alphafold.sif:/app/alphafold> ls /data/
bfd  mgnify  params  pdb70  pdb_mmcif  small_bfd  uniclust30  uniref90
```

Singularity alphafold.sif:/app/alphafold> ls -l /data/bfd/
total 1858454314
-rw------- 1 1001 1001 1555724298013 Mar  3  2019 bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt_a3m.ffdata
-rw------- 1 1001 1001    1817298807 Mar  2  2019 bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt_a3m.ffindex
-rwxr-xr-x 1 1001 1001   16814534465 Mar  4  2019 bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt_cs219.ffdata
-rwxr-xr-x 1 1001 1001    1688518403 Mar  4  2019 bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt_cs219.ffindex
-rw------- 1 1001 1001  326882934659 Mar  3  2019 bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt_hhm.ffdata
-rw------- 1 1001 1001     129631317 Mar  2  2019 bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt_hhm.ffindex

Singularity alphafold.sif:/app/alphafold> ls -l /data/pdb70/*
-rw----r-x 1 0 0         410 Oct  4 17:28 /data/pdb70/md5sum
-rw----r-x 1 0 0 56554823611 Oct  4 17:43 /data/pdb70/pdb70_a3m.ffdata
-rw----r-x 1 0 0     2049264 Oct  4 17:43 /data/pdb70/pdb70_a3m.ffindex
-rw----r-x 1 0 0     6967926 Oct  4 17:43 /data/pdb70/pdb70_clu.tsv
-rw----r-x 1 0 0    22338334 Oct  4 17:43 /data/pdb70/pdb70_cs219.ffdata
-rw----r-x 1 0 0     1562700 Oct  4 17:43 /data/pdb70/pdb70_cs219.ffindex
-rw----r-x 1 0 0  3485614545 Oct  4 17:44 /data/pdb70/pdb70_hhm.ffdata
-rw----r-x 1 0 0     1884124 Oct  4 17:44 /data/pdb70/pdb70_hhm.ffindex
-rw----r-x 1 0 0    20263781 Oct  4 17:44 /data/pdb70/pdb_filter.dat

Any suggestions would be appreciated.

All the best,

Matthew

**Comment by liziyang99** [comment]
Hello, I also encountered this problem. Just like your description, my data is complete. I don't know why
Have you solved this problem?
Any suggestions would be appreciated.thanks

**Comment by gmfricke** [comment]
> @gmfricke 755 is just my personal preferences.
> I checked 444 & it worked.

Thanks for testing that. Changing the permissions on the database seems to have helped. At least the runtime on Alphafold has now exceeded where the previous crash occurred. I will keep you up to date - thank you so much for the help!
