### ISSUE TITLE
ModuleNotFoundError: No module named 'alphafold.model.tf'

### ISSUE THREAD

**Issue by sdtruong** [deepmind/alphafold#208]
I'm receiving the following issue in the Colab notebook:
```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-31-1640ae7ce3a3> in <module>()
     24 import py3Dmol
     25 
---> 26 from alphafold.model import model
     27 from alphafold.model import config
     28 from alphafold.model import data

1 frames
/usr/local/lib/python3.7/dist-packages/alphafold/model/features.py in <module>()
     21 import tensorflow.compat.v1 as tf
     22 
---> 23 from alphafold.model.tf import input_pipeline
     24 from alphafold.model.tf import proteins_dataset
     25 

ModuleNotFoundError: No module named 'alphafold.model.tf'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
```

I installed all the installation/download cells, but this issue keeps following up. Whenever I check `alphafold.model`, it says there is no `tf` attribute. How would I fix this issue? Is something from TensorFlow not downloading?

I also noticed that whenever I run `from alphafold.model import model`, I get `ModuleNotFoundError: No module named 'alphafold.model.tf'`. I hope that provides some insight on where the issue is.

**Comment by srkndgn** [comment]
Hi, How did you add _init.py? Can you please explain details where to add and how to add

**Comment by Augustin-Zidek** [comment]
Hi, sorry about this! Could you try adding `sys.path.append('/content/alphafold')` in the "Search against genetic databases" cell as shown below:

```python
# --- Python imports ---
import sys
sys.path.append('/opt/conda/lib/python3.7/site-packages')
sys.path.append('/content/alphafold')  # <- Add this line
```

I think this should resolve the issue.

**Comment by liziyang99** [comment]
You can see if there is this file(_init.py) under your directory structure(alphafold/model/tf),I'm not sure if your question is for this reason.
