### ISSUE TITLE
ModuleNotFoundError  

### ISSUE THREAD

**Issue by srkndgn** [deepmind/alphafold#209]
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-17-1640ae7ce3a3> in <module>()
     24 import py3Dmol
     25 
---> 26 from alphafold.model import model
     27 from alphafold.model import config
     28 from alphafold.model import data

ModuleNotFoundError: No module named 'alphafold.model'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.

**Comment by Augustin-Zidek** [comment]
Hi, sorry about this! Could you try adding `sys.path.append('/content/alphafold')` in the "Search against genetic databases" cell as shown below:

```python
# --- Python imports ---
import sys
sys.path.append('/opt/conda/lib/python3.7/site-packages')
sys.path.append('/content/alphafold')  # <- Add this line
```

I think this should resolve the issue.

**Comment by srkndgn** [comment]
Thanks for prompt reply.
I did it but now I have this error;
NameError                                 Traceback (most recent call last)
<ipython-input-1-ae0b49d61c11> in <module>()
     18 
     19 output_dir = 'prediction'
---> 20 os.makedirs(output_dir, exist_ok=True)
     21 
     22 plddts = {}

NameError: name 'os' is not defined

**Comment by Augustin-Zidek** [comment]
We addressed this in https://github.com/deepmind/alphafold/commit/0be2b30b98f0da7aecb973bde04758fae67eb913.
