### ISSUE TITLE
Error searching against genetic database

### ISSUE THREAD

**Issue by DMCaefer** [deepmind/alphafold#212]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-11-1640ae7ce3a3> in <module>()
     24 import py3Dmol
     25 
---> 26 from alphafold.model import model
     27 from alphafold.model import config
     28 from alphafold.model import data

ModuleNotFoundError: No module named 'alphafold.model'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

**Comment by Augustin-Zidek** [comment]
Hi, sorry about this! Could you try adding `sys.path.append('/content/alphafold')` in the "Search against genetic databases" cell as shown below:

```python
# --- Python imports ---
import sys
sys.path.append('/opt/conda/lib/python3.7/site-packages')
sys.path.append('/content/alphafold')  # <- Add this line
```

I think this should resolve the issue.

**Comment by sdtruong** [comment]
> Hi, sorry about this! Could you try adding `sys.path.append('/content/alphafold')` in the "Search against genetic databases" cell as shown below:
> 
> ```python
> # --- Python imports ---
> import sys
> sys.path.append('/opt/conda/lib/python3.7/site-packages')
> sys.path.append('/content/alphafold')  # <- Add this line
> ```
> 
> I think this should resolve the issue.

This worked for me before, but I am getting an error with this method once again. I don't know why. The only thing I've done different is that I've upgraded to Colab Pro (and using High-RAM GPU). Do you know what may be causing the issue now?
