### ISSUE TITLE
UnfilteredStackTrace                      Traceback (most recent call last)

### ISSUE THREAD

**Issue by srkndgn** [deepmind/alphafold#214]
---------------------------------------------------------------------------
UnfilteredStackTrace                      Traceback (most recent call last)
<ipython-input-10-ae0b49d61c11> in <module>()
     41                                                            random_seed=0)
---> 42     prediction_result = model_runner.predict(processed_feature_dict)
     43 

16 frames
/opt/conda/lib/python3.7/site-packages/alphafold/model/model.py in predict(self, feat)
    132                  tree.map_structure(lambda x: x.shape, feat))
--> 133     result = self.apply(self.params, jax.random.PRNGKey(0), feat)
    134     # This block is to ensure benchmark timings are accurate. Some blocking is

/usr/local/lib/python3.7/dist-packages/jax/_src/traceback_util.py in reraise_with_filtered_traceback(*args, **kwargs)
    161     try:
--> 162       return fun(*args, **kwargs)
    163     except Exception as e:

/usr/local/lib/python3.7/dist-packages/jax/_src/api.py in cache_miss(*args, **kwargs)
    413         device=device, backend=backend, name=flat_fun.__name__,
--> 414         donated_invars=donated_invars, inline=inline)
    415     out_pytree_def = out_tree()

/usr/local/lib/python3.7/dist-packages/jax/core.py in bind(self, fun, *args, **params)
   1617   def bind(self, fun, *args, **params):
-> 1618     return call_bind(self, fun, *args, **params)
   1619 

/usr/local/lib/python3.7/dist-packages/jax/core.py in call_bind(primitive, fun, *args, **params)
   1608   tracers = map(top_trace.full_raise, args)
-> 1609   outs = primitive.process(top_trace, fun, tracers, params)
   1610   return map(full_lower, apply_todos(env_trace_todo(), outs))

/usr/local/lib/python3.7/dist-packages/jax/core.py in process(self, trace, fun, tracers, params)
   1620   def process(self, trace, fun, tracers, params):
-> 1621     return trace.process_call(self, fun, tracers, params)
   1622 

/usr/local/lib/python3.7/dist-packages/jax/core.py in process_call(self, primitive, f, tracers, params)
    614   def process_call(self, primitive, f, tracers, params):
--> 615     return primitive.impl(f, *tracers, **params)
    616   process_map = process_call

/usr/local/lib/python3.7/dist-packages/jax/interpreters/xla.py in _xla_call_impl(***failed resolving arguments***)
    622   compiled_fun = _xla_callable(fun, device, backend, name, donated_invars,
--> 623                                *unsafe_map(arg_spec, args))
    624   try:

/usr/local/lib/python3.7/dist-packages/jax/linear_util.py in memoized_fun(fun, *args)
    261     else:
--> 262       ans = call(fun, *args)
    263       cache[key] = (ans, fun.stores)

/usr/local/lib/python3.7/dist-packages/jax/interpreters/xla.py in _xla_callable(fun, device, backend, name, donated_invars, *arg_specs)
    693 def _xla_callable(fun: lu.WrappedFun, device, backend, name, donated_invars, *arg_specs):
--> 694   return lower_xla_callable(fun, device, backend, name, donated_invars, *arg_specs).compile().unsafe_call
    695 

/usr/local/lib/python3.7/dist-packages/jax/interpreters/xla.py in compile(self)
    785       else:
--> 786         self._executable = XlaCompiledComputation.from_xla_computation(self.hlo, *self.compile_args)
    787     return self._executable

/usr/local/lib/python3.7/dist-packages/jax/interpreters/xla.py in from_xla_computation(xla_computation, nreps, device, backend, tuple_args, out_avals, kept_var_idx)
    808     options.parameter_is_tupled_arguments = tuple_args
--> 809     compiled = compile_or_get_cached(backend, xla_computation, options)
    810     if nreps == 1:

/usr/local/lib/python3.7/dist-packages/jax/interpreters/xla.py in compile_or_get_cached(backend, computation, compile_options)
     82             return compiled
---> 83     return backend_compile(backend, computation, compile_options)
     84 

/usr/local/lib/python3.7/dist-packages/jax/interpreters/xla.py in backend_compile(backend, built_c, options)
    386   # separately in Python profiling results
--> 387   return backend.compile(built_c, compile_options=options)
    388 

UnfilteredStackTrace: RuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 3738206208 bytes.

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
<ipython-input-10-ae0b49d61c11> in <module>()
     40     processed_feature_dict = model_runner.process_features(feature_dict,
     41                                                            random_seed=0)
---> 42     prediction_result = model_runner.predict(processed_feature_dict)
     43 
     44     mean_plddt = prediction_result['plddt'].mean()

/opt/conda/lib/python3.7/site-packages/alphafold/model/model.py in predict(self, feat)
    131     logging.info('Running predict with shape(feat) = %s',
    132                  tree.map_structure(lambda x: x.shape, feat))
--> 133     result = self.apply(self.params, jax.random.PRNGKey(0), feat)
    134     # This block is to ensure benchmark timings are accurate. Some blocking is
    135     # already happening when computing get_confidence_metrics, and this ensures

/usr/local/lib/python3.7/dist-packages/jax/interpreters/xla.py in backend_compile(backend, built_c, options)
    385   # we use a separate function call to ensure that XLA compilation appears
    386   # separately in Python profiling results
--> 387   return backend.compile(built_c, compile_options=options)
    388 
    389 def _execute_compiled_primitive(prim, compiled, result_handler, *args):

RuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 3738206208 bytes.

**Comment by abridgland** [comment]
Hi, this error has been caused by running out of memory. This is usually caused by running long sequences or sometimes from the MSA tools returning very large MSAs. How long is your sequence?
