### ISSUE TITLE
Explanation of parameters and tutorials

### ISSUE THREAD

**Issue by hperez-ucam** [deepmind/alphafold#217]
I wonder where we could find information about all input parameters and arguments, and also some command line tutorials beyond what one can find in the google collar notebook. 
If this is not the place for such questions, please tell me where we could ask this.
Thanks
Horacio

**Comment by abridgland** [comment]
Hi, if you have any questions that aren't covered in the [README](https://github.com/deepmind/alphafold/blob/main/README.md) or the descriptions of the flags in [run_alphafold.py](https://github.com/deepmind/alphafold/blob/0007c352272415f70c921d8533a1b9e2d824f21f/run_alphafold.py#L46-L130) then feel free to ask below and I'd be happy to help.
