### ISSUE TITLE
Filesize limitations

### ISSUE THREAD

**Issue by fabiotrovato** [deepmind/alphafold#219]
Hello,

I am trying to use alphafold for my predictions and I would like to understand the difference between the full-size and reduced databases "reduced_dbs" and if the accuracy of the structural prediction is influenced by this choice? This is relevant for the next questions.

If using the reduced database leads to potentially less accurate predictions for some proteins, it would make sense to use the full database. However, in such case I cannot copy files larger than 1TB to my scratch partition, which means I cannot use bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt_a3m.ffdata. Is there a way to split this file (and associated bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt_a3m.ffindex) in two parts? If yes, is there a way to have alphafold read the two parts in order to circumvent the filesize limitation?

Thank you for your support,
Fabio

**Comment by andycowie** [comment]
Hi, I'm not sure that it is possible to split HHblits database files - this would be a question for the [hh-suite](https://github.com/soedinglab/hh-suite) authors.

The structural predictions achieved using the `reduced_dbs` setting were found to be less accurate when tried on large datasets, but they are still very high accuracy - I would recommend using this.
