### ISSUE TITLE
number of model 

### ISSUE THREAD

**Issue by nasserhashemi** [deepmind/alphafold#220]
Hi, 
Thanks for sharing your great job;
Can we increase the number of generated models to more than 5? If yes, is there any chance to get a better model?
Thanks 

Nasser

**Comment by nasserhashemi** [comment]
Hi there, 
any opinions about aforementioned question would be really appreciated; 

Thanks 
Nasser

**Comment by andycowie** [comment]
Hi Nasser,

The models that we provide are the best performing models that we could create. We have also provided models for predicting multimer structures - full details are in the readme [here](https://github.com/deepmind/alphafold#model-parameters).

Let me know if that doesn't completely answer your question.

Regards,

Andrew

**Comment by daron-m-standley** [comment]
My reading of the original question is that Nasser is asking if more that 5 *structural* models can be output. It seems that the answer above refers to the number of *ML* models.

By the way, I am also curious if more than 5 structural models can be output for proteins that have significant flexibility.

**Comment by AnyaP** [comment]
To increase the number of structural models you could try running the same ML model with multiple random seeds, varying inference-only hyper-parameters such as the number of recycling, or hacking the input data (by adding or removing some of the MSA sequences or templates). This might bring more diversity in some cases, however we have not validated effects of this procedure in general.
