### ISSUE TITLE
question on splitting bfd database

### ISSUE THREAD

**Issue by 132nd-Entropy** [deepmind/alphafold#222]
Hi all, I read that the bfd database (the big one, not the small one) is about 1.7 TB, so I bought a 2TB SSD but It turned out that the 2TB SSD only holds 1.7 TB..

the bfd folder contains a total of 6 bfd_metaclust_clu... files. 

can I have some of them in one bfd folder in one drive, and the remaining in another bfd folder, and simply modify the run_docker.py so that it points to the bfd folder in two different locations? I know I could simply get a a bigger drive, but as cost increases with volume, I'd rather have the database on different smaller ssds if that makes sense. 

many thanks for the help!

**Comment by Augustin-Zidek** [comment]
Hi, you can achieve that using symlinks, see e.g. https://github.com/soedinglab/hh-suite/issues/281.

**Comment by 132nd-Entropy** [comment]
Thank you @Augustin-Zidek !
