### ISSUE TITLE
RuntimeError with Colab Pro

### ISSUE THREAD

**Issue by sdtruong** [deepmind/alphafold#223]
I am having an issue with a ~13 GB job (~1,100 amino acid long monomer, which others have suggested should be doable):

```
RuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 13657735992 bytes.
```

I thought 13 Gb would be a reasonable amount for Colab Pro? I am also doing only one model (not multiple). Before I potentially upgrade to Colab Pro+, could I check to see how much space you get with each plan?

Thanks.

**Comment by Augustin-Zidek** [comment]
I recommend running such proteins in a local AlphaFold install or looking that sequence up in AFDB.
