### ISSUE TITLE
Error in v2.1.0

### ISSUE THREAD

**Issue by tony9664** [deepmind/alphafold#224]
I1103 10:06:46.762314 140275159511424 run_docker.py:223] 2021-11-03 14:06:46.702685: W external/org_tensorflow/tensorflow/stream_executor/gpu/asm_compiler.cc:235] Falling back to the CUDA driver for PTX compilation; ptxas does not support CC 8.6                                          
I1103 10:06:46.824727 140275159511424 run_docker.py:223] 2021-11-03 14:06:46.702759: W external/org_tensorflow/tensorflow/stream_executor/gpu/asm_compiler.cc:238] Used ptxas at ptxas                                                      
I1103 10:06:46.825056 140275159511424 run_docker.py:223] 2021-11-03 14:06:46.815412: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:625] failed to get PTX kernel "shift_right_logical_4" from module: CUDA_ERROR_NOT_FOUND: named symbol not found                
I1103 10:06:46.825349 140275159511424 run_docker.py:223] 2021-11-03 14:06:46.815546: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:2040] Execution of replica 0 failed: Internal: Could not find the corresponding function                                                 
I1103 10:06:47.950073 140275159511424 run_docker.py:223] Traceback (most recent call last):                                                                                                                                                 
I1103 10:06:47.975005 140275159511424 run_docker.py:223] File "/app/alphafold/run_alphafold.py", line 427, in <module>                                                                                                                      
I1103 10:06:47.975336 140275159511424 run_docker.py:223] app.run(main)                                                                                                                                                                      
I1103 10:06:47.975575 140275159511424 run_docker.py:223] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 312, in run                                                                                                        
I1103 10:06:47.975919 140275159511424 run_docker.py:223] _run_main(main, args)                                                                                                                                                              
I1103 10:06:47.976160 140275159511424 run_docker.py:223] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main                                                                                                  
I1103 10:06:47.976389 140275159511424 run_docker.py:223] sys.exit(main(argv))                                                                                                                                                               
I1103 10:06:47.976614 140275159511424 run_docker.py:223] File "/app/alphafold/run_alphafold.py", line 412, in main                                                                                                                          
I1103 10:06:47.976837 140275159511424 run_docker.py:223] is_prokaryote=is_prokaryote)                                                                                                                                                       
I1103 10:06:47.977102 140275159511424 run_docker.py:223] File "/app/alphafold/run_alphafold.py", line 194, in predict_structure                                                                                                             
I1103 10:06:47.977333 140275159511424 run_docker.py:223] random_seed=model_random_seed)                                                                                                                                                     
I1103 10:06:47.977553 140275159511424 run_docker.py:223] File "/app/alphafold/alphafold/model/model.py", line 167, in predict                                                                                                               
I1103 10:06:47.977771 140275159511424 run_docker.py:223] result = self.apply(self.params, jax.random.PRNGKey(random_seed), feat)                                                                                                            
I1103 10:06:47.977987 140275159511424 run_docker.py:223] File "/opt/conda/lib/python3.7/site-packages/jax/_src/random.py", line 122, in PRNGKey                                                                                             
I1103 10:06:47.978204 140275159511424 run_docker.py:223] key = prng.seed_with_impl(impl, seed)                                                                                                                                              
I1103 10:06:47.978419 140275159511424 run_docker.py:223] File "/opt/conda/lib/python3.7/site-packages/jax/_src/prng.py", line 203, in seed_with_impl                                                                                        
I1103 10:06:47.978636 140275159511424 run_docker.py:223] return PRNGKeyArray(impl, impl.seed(seed))                                                                                                                                         
I1103 10:06:47.978850 140275159511424 run_docker.py:223] File "/opt/conda/lib/python3.7/site-packages/jax/_src/prng.py", line 241, in threefry_seed                                                                                         
I1103 10:06:47.979062 140275159511424 run_docker.py:223] k1 = convert(lax.shift_right_logical(seed_arr, lax._const(seed_arr, 32)))                                                                                                          
I1103 10:06:47.979273 140275159511424 run_docker.py:223] File "/opt/conda/lib/python3.7/site-packages/jax/_src/lax/lax.py", line 408, in shift_right_logical                                                                                
I1103 10:06:47.979485 140275159511424 run_docker.py:223] return shift_right_logical_p.bind(x, y)                                                                                                                                            
I1103 10:06:47.979700 140275159511424 run_docker.py:223] File "/opt/conda/lib/python3.7/site-packages/jax/core.py", line 272, in bind                                                                                                       
I1103 10:06:47.979913 140275159511424 run_docker.py:223] out = top_trace.process_primitive(self, tracers, params)                                                                                                                           
I1103 10:06:47.980123 140275159511424 run_docker.py:223] File "/opt/conda/lib/python3.7/site-packages/jax/core.py", line 624, in process_primitive                                                                                          
I1103 10:06:47.980334 140275159511424 run_docker.py:223] return primitive.impl(*tracers, **params)                                                                                                                                          
I1103 10:06:47.980543 140275159511424 run_docker.py:223] File "/opt/conda/lib/python3.7/site-packages/jax/interpreters/xla.py", line 313, in apply_primitive                                                                                
I1103 10:06:47.980756 140275159511424 run_docker.py:223] return compiled_fun(*args)                                                                                                                                                         
I1103 10:06:47.980967 140275159511424 run_docker.py:223] File "/opt/conda/lib/python3.7/site-packages/jax/interpreters/xla.py", line 337, in <lambda>                                                                                       
I1103 10:06:47.981246 140275159511424 run_docker.py:223] return lambda *args, **kw: compiled(*args, **kw)[0]                                                                                                                                
I1103 10:06:47.981466 140275159511424 run_docker.py:223] File "/opt/conda/lib/python3.7/site-packages/jax/interpreters/xla.py", line 977, in _execute_compiled                                                                              
I1103 10:06:47.981669 140275159511424 run_docker.py:223] out_bufs = compiled.execute(input_bufs)                                                                                                                                            
I1103 10:06:47.981888 140275159511424 run_docker.py:223] RuntimeError: Internal: Could not find the corresponding function

**Comment by Augustin-Zidek** [comment]
Could you try changing CUDA version as suggested in https://github.com/deepmind/alphafold/issues/55#issuecomment-889914885? 

See also https://github.com/deepmind/alphafold/issues/83 or https://github.com/deepmind/alphafold/issues/117.

**Comment by tony9664** [comment]
It works when setting ARG CUDA=11.1. Thanks!
