### ISSUE TITLE
Installation help

### ISSUE THREAD

**Issue by wentski** [deepmind/alphafold#229]
I have followed the instructions for installation on the main page but I am not having any success in downloading the databases. When I run `scripts/download_all_data.sh <DOWNLOAD_DIR> reduced_dbs` I get the error message 

bash: scripts/download_all_data.sh: No such file or directory

I have installed docker successfully, installed the NVIDIA toolkit for GPU support (which is definitly recognising my GPU), installed aria2c and I am running docker as a non-root user. I have also tried the installation process both inside and outside of a virtual environment.

I am not sure if I am just missing an obvious step here as I am still new to command line.

Any help or advice is appreciated.

Thanks!

**Comment by joslynnlee** [comment]
I am on this same step. Can you clarify " The download directory <DOWNLOAD_DIR> should not be a subdirectory in the AlphaFold repository directory."? I am in the alphafold/scripts directory to run the script but do I need to make the <DOWNLOAD_DIR> outside of alphafold?

**Comment by andycowie** [comment]
Hi @joslynnlee, apologies for the delay in responding. You are correct, the `<DOWNLOAD_DIR>` should not be a subdirectory of the cloned AlphaFold GitHub repository. As mentioned in the [README](https://github.com/deepmind/alphafold/blob/main/README.md), this will interfere with the Docker image creation. Will close this issue now, please reopen if this is still a problem.
