### ISSUE TITLE
model names flag is missing in run_alphafold.py

### ISSUE THREAD

**Issue by celalp** [deepmind/alphafold#230]
in `run_alphafold.py` the loop that goes over all the models is there but there is no flag to specify models. In the previous version there was a flag. 

```
flags.DEFINE_list('model_names', None, 'Names of models to use.')
```

**Comment by Augustin-Zidek** [comment]
This is now controlled using the `model_preset` flag. If you want to change the models used for each preset, you can modify the `MODEL_PRESETS` variable in `alphafold/model/config.py`.

I will add this in https://github.com/deepmind/alphafold#api-changes-between-v200-and-v210.
