### ISSUE TITLE
Alphafold Colab Pro + keeps giving error

### ISSUE THREAD

**Issue by Alleko** [deepmind/alphafold#231]
I bought google colab pro. For the last three days I cannot fully execute the folding. At the end of every folding the program returns error even though it gives the structure prediction it does not allow download of the structure. 

Could you please help fix this, thank you 😊 🙏 
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-6-d60eedd3c912> in <module>()
    192   chain_ids = best_unrelaxed_prot.chain_index
    193   for chain_boundary in np.nonzero(chain_ids[:-1] - chain_ids[1:]):
--> 194     plt.plot([0, total_num_res], [chain_boundary, chain_boundary], color='red')
    195     plt.plot([chain_boundary, chain_boundary], [0, total_num_res], color='red')
    196 

4 frames
/usr/local/lib/python3.7/dist-packages/matplotlib/axes/_base.py in <listcomp>(.0)
    362                 "non-matching shapes is deprecated.")
    363         return [func(x[:, j % ncx], y[:, j % ncy], kw, kwargs)
--> 364                 for j in range(max(ncx, ncy))
<img width="1075" alt="Screen Shot 2021-11-04 at 1 25 46 PM" src="https://user-images.githubusercontent.com/81047653/140415740-f2ee1aef-49e9-44b5-adee-f4e47b74b147.png">
]
    365 
    366 

ZeroDivisionError: integer division or modulo by zero

**Comment by Augustin-Zidek** [comment]
Fixed in https://github.com/deepmind/alphafold/commit/91b43223422420d1783ed802c8b3a8382a9309fd.
