### ISSUE TITLE
option to separate msa from prediction, option to specify number of cpus to use

### ISSUE THREAD

**Issue by celalp** [deepmind/alphafold#232]
The issue I'm having has to do with prediction of large proteins in an hpc environment. The msa step requires a lot of memory and I can do that using a queue that has that (but not gpu). I cannot use the gpu queue for the whole pipeline because of resource allocations. If there are scripts that would run msa and structure prediction separately I can chain them on a pipeline. 

Similarly allowing users to set some of the runtime parameters (like #of cpus) would give a lot flexibility. 

Thanks for creating this amazing tool.

**Comment by zephyr221** [comment]
Hi,

To split the CPU and GPU parts, and run on different CPU and GPU nodes on supercomputers,  see https://github.com/Zuricho/ParallelFold

**Comment by Augustin-Zidek** [comment]
Closing this issue, feel free to reopen this issue or open a new issue if this is still a problem.
