### ISSUE TITLE
Extreme amount of clashes in some multimer predictions

### ISSUE THREAD

**Issue by dennissv** [deepmind/alphafold#236]
Sometimes when using the multimer models I get extreme amount of clashes in the predictions to the point where the proteins are just a blob. At first I thought it was a problem with my local installation but I tried running some problematic proteins on the Colab notebook and get similar results there. An example would be the following protein sequence as a heptamer;

`MEENVTEDSILSTELRGQEIRIEEVPNEDTLVVYLSRGGRNAKESQSANSNNTGDIDKHGRHRADNCICLSKVHYEIDGDILCIREMKPFVYINKVSILRRRSTNKTKEDTETQKSP`

<img width="514" alt="clashes" src="https://user-images.githubusercontent.com/22501102/140593732-ca8faa64-66d1-465f-955a-3e013a45f753.png">

The complete disregard for stereochemistry only seem to appear in regions with very low confidence. The only modification I have made is to disable the Amber relaxation step but this never seemed to cause large issues like these in the monomer version nor in the ColabFold multimer version. I also doubt that Amber can resolve these clashes in a meaningful way?

Is this expected behaviour without Amber and for proteins that are hard to model or is something wrong?

**Comment by arashnh11** [comment]
Which model is this from? And do you have an alignment RMSD w.r.t the experimental? 
We are working on an octamer complex and see clashes too. In our case model_3 had the best outcome though still off...

**Comment by tony9664** [comment]
I'm also seeing some similar serious clashes when predicting multimers. Colabfold was good though.

**Comment by arashnh11** [comment]
Aren't thr colabfold and v2.1.0 from the same source code? Not sure about
clashes but an octamer we tried result in poor alignment with pdb > 15A

**Comment by arashnh11** [comment]
OK, here is the comparison of clashes for 7KEU: magenta: v2.1.0 green: RCSB. 

<img width="927" alt="Screen Shot 2021-11-06 at 2 54 50 PM" src="https://user-images.githubusercontent.com/18223861/140620801-fb2e9b15-c1f5-4cec-90a8-cc5715f7a357.png">

**Comment by dennissv** [comment]
@arashnh11 2.1.0 included new multimer models for protein complexes which is where I started observing these issues. ColabFold used a flexible linker solution which didn't provide the same accuracy but also never displayed these clashes.

Some proteins work very well and it's been great seeing these models. But whenever a protein has some region with low confidence it quickly becomes a tangled mess. I've heard several people having the same issues, some examples can be found here; https://twitter.com/RolandDunbrack/status/1457538160561377283

Is there any update on this?

**Comment by arashnh11** [comment]
@dennissv Do you know of some sample multimers with good alignment with reference PDBs? 
Haven't heard any update yet. I can tweet our failed Octamer testcase above, but I believe this is more of a bug...

**Comment by tfgg** [comment]
We think we may have identified the issue with overlapping domains but need to test a bit more. It will take us a few days at least to be sure.

**Comment by arashnh11** [comment]
@tfgg Thanks for the update. Please let us know if there is any information we can provide or any additional tests we can do to help.

**Comment by ValZapod** [comment]
> colabfold and v2.1.0 from the same source code?

I think not.

Actually, deepmind said they are working it on Twitter too.

**Comment by dennissv** [comment]
This seems largely fixed with the new v2 multimer models. Thank you!
