### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by rsg344** [deepmind/alphafold#239]
I'm trying to run AlphaFold on a compute cluster and I keep on getting this error. I'm not sure what the issue is.

INFO:    Using cached image
/opt/conda/lib/python3.8/site-packages/absl/flags/_validators.py:203: UserWarning: Flag --preset has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  warnings.warn(
I1102 01:00:48.103564 140401207433024 templates.py:880] Using precomputed obsolete pdbs /data/pdb_mmcif/obsolete.dat.
I1102 01:00:52.363656 140401207433024 tpu_client.py:54] Starting the local TPU driver.
I1102 01:00:52.606741 140401207433024 xla_bridge.py:231] Unable to initialize backend 'tpu_driver': Not found: Unable to find driver in registry given worker: local://
I1102 01:00:53.333841 140401207433024 xla_bridge.py:231] Unable to initialize backend 'tpu': Invalid argument: TpuPlatform is not available.
I1102 01:01:11.164360 140401207433024 run_alphafold.py:238] Have 5 models: ['model_1', 'model_2', 'model_3', 'model_4', 'model_5']
I1102 01:01:11.164527 140401207433024 run_alphafold.py:251] Using random seed 126052088101883188 for the data pipeline
Traceback (most recent call last):
  File "/app/alphafold/run_alphafold.py", line 283, in <module>
    app.run(main)
  File "/opt/conda/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/app/alphafold/run_alphafold.py", line 255, in main
    predict_structure(
  File "/app/alphafold/run_alphafold.py", line 115, in predict_structure
    feature_dict = data_pipeline.process(
  File "/app/alphafold/alphafold/data/pipeline.py", line 118, in process
    input_seqs, input_descs = parsers.parse_fasta(input_fasta_str)
  File "/app/alphafold/alphafold/data/parsers.py", line 72, in parse_fasta
    sequences[index] += line
IndexError: list index out of range

**Comment by arashnh11** [comment]
Can you share your input FASTA file here? I have seen this error if you have formatting issues there

**Comment by rsg344** [comment]
[A0A0K8P6T7.1.txt](https://github.com/deepmind/alphafold/files/7501450/A0A0K8P6T7.1.txt)
This is the FASTA file I've been using. Thanks!

**Comment by rsg344** [comment]
I was actually able to modify the formatting of my FASTA file and it was an easy fix, so I have it up and running. Thank you!
