### ISSUE TITLE
AlphaFold multimer works brilliantly, but local installation has errors and clashes 

### ISSUE THREAD

**Issue by ConnorArkinson** [deepmind/alphafold#242]
Hi,  

Using AlphaFold-Multimer from link I get great results that match experimental data, for several systems. 
https://colab.research.google.com/github/deepmind/alphafold/blob/main/notebooks/AlphaFold.ipynb

However, when installing AlphaFold-Multimer locally, we are resulting in very poor structure prediction for complexes and many clashes within the models. 

Is their significant changes to the online code that maybe result in this, I like the fact that it doesn't use templates online, but not sure its the only issue. 

Cheers,
Connor

**Comment by arashnh11** [comment]
This is a duplicate. See https://github.com/deepmind/alphafold/issues/236

**Comment by Isabel-ql** [comment]
> Hi,
> 
> Using AlphaFold-Multimer from link I get great results that match experimental data, for several systems. https://colab.research.google.com/github/deepmind/alphafold/blob/main/notebooks/AlphaFold.ipynb
> 
> However, when installing AlphaFold-Multimer locally, we are resulting in very poor structure prediction for complexes and many clashes within the models.
> 
> Is their significant changes to the online code that maybe result in this, I like the fact that it doesn't use templates online, but not sure its the only issue.
> 
> Cheers, Connor

 Hi Connor,

I just tried to use the same link to predict the structures of complexes. But there is an error  in the last step, "5. Run AlphaFold and download prediction". The notice said "NameError: name 'model_type_to_use' is not defined". Have you got similar problem? Do you know how to solve this problem? 

Looking forward to your reply. Thanks a lot!

Best,
Qun 
<img width="1515" alt="AlphaFold Multimer_NameError" src="https://user-images.githubusercontent.com/65905482/204096528-f07db0ce-d119-4bfc-833a-884f75630af3.png">
