### ISSUE TITLE
Running Alphafold-multimer with no template

### ISSUE THREAD

**Issue by gabrielepozzati** [deepmind/alphafold#243]
Hello, 

First of all, at the cost of sounding redundant, great job, you really got out a masterpiece here!

Secondly, I did an ugly hack on the alphafold/data/msa_pairing.py file in order to run the multimer pipeline without templates. 
What I did was basically tracking how the templates are featurized and feeding instead an equivalently shaped zero array.
My question is, can the zero arrays be considered the correct placeholder for the missing template features or are they encoding some wrong information?

I know it's probably not the best way to do it. I also tried setting to 0 the MAX_TEMPLATES variable in the alphafold/data/feature_processing.py file, but that throws an error in the feature merging that I'm not really sure how to get around.
Maybe is something that you want to fix in your next code update!

**Comment by grandrea** [comment]
Hello,

I think the way to do it is to set the -t flag to an early date, for example 01-01-1961 . When I do so, I see all templates get rejected in the log. It is of course less efficient than a flag that lets you switch that off..
Disclaimer: I do not work on alphafold, I just use it

**Comment by Augustin-Zidek** [comment]
I agree with the suggestion from @grandrea: Set the the `max_template_date` flag to e.g. `--max_template_date=1950-01-01` to make sure all templates are filtered out and not used.
