### ISSUE TITLE
ERROR: Detected MOFED driver 5.2-2.2.0, but this container has version 4.6-1.0.1. I1111 19:29:35.992823 139642532415296 run_docker.py:222] 

### ISSUE THREAD

**Issue by JiaqingFu** [deepmind/alphafold#245]
command line
python3 docker/run_docker.py \
>   --fasta_paths=T1050.fasta \
>   --max_template_date=2020-05-14 \
>   --model_preset=monomer \
>   --db_preset=reduced_dbs \
>   --data_dir=/datapath/

**Comment by JiaqingFu** [comment]
@tfgg

**Comment by Augustin-Zidek** [comment]
I think you have a few options:

1. Try to update the MOFED driver version in the docker file, but adding something like
```
RUN wget --quiet https://mellanox.com/downloads/ofed/MLNX_OFED-5.4-3.0.3.0/MLNX_OFED_LINUX-5.4-3.0.3.0-ubuntu18.04-x86_64.tgz && \
        tar -xvf MLNX_OFED_LINUX-5.4-3.0.3.0-ubuntu18.04-x86_64.tgz && \
        MLNX_OFED_LINUX-5.4-3.0.3.0-ubuntu18.04-x86_64/mlnxofedinstall --user-space-only --without-fw-update --all --force
```

2. Try running without a GPU (this will be slow) by passing the `--use_gpu=false` flag to `run_docker.py`.

**Comment by JiaqingFu** [comment]
@Augustin-Zidek  I solve this problem by change 'nvidia/cuda:${CUDA}-cudnn8-runtime-ubuntu18.04'  to 'nvidia/cuda:${CUDA}-cudnn8-devel-ubuntu18.04'  in dockefile. Maybe this can be a pr although devel image cost more disk space(3.6GB→7.41GB)
