### ISSUE TITLE
How to calculate the binding energy from multimer complexes made by Alphafold2

### ISSUE THREAD

**Issue by gundalav** [deepmind/alphafold#247]
I have a structure created with Multimer option.
The complex is created by giving the ligand and receptor amino acid sequences.
I presume it is conceptually the same as 'docking'.

Is there a way I can calculate the binding energy for the complexes
made by AF2?

G.V.

**Comment by Hardlearn** [comment]
You can check GROMACS

**Comment by gundalav** [comment]
Hi Hardlearn, 

Thank you for your reply. I found GROMACS is heavy duty. 
I'm thinking simpler method, that I can command line, or programmatic like ProDy.

There's a web based tool called  [Prodigy](https://wenmr.science.uu.nl/prodigy/)
But since it's web based it's inconvenient, besides I'm not sure how accurate it is. 

By the way, has anybody tested on Multimer output using GROMACS?

G.V.

**Comment by Hardlearn** [comment]
I have used GROMACS to calculate the binding energy for the output PDB format from alphafold2(colab version before alphafold-multimer existed), and now I am trying to use alphafold-multimer model to predict the structure of complexes and calculate the binding energy, and then compare them with previous results
