### ISSUE TITLE
is possible to git clone an earlier version

### ISSUE THREAD

**Issue by ryao-mdanderson** [deepmind/alphafold#249]
Hello alphafold team,

I want to reproduce a test in the initial version. how do I git clone v2.0.0?

I tried the command
git clone https://github.com/deepmind/alphafold.git --branch v2.0.0
 --- this does git clone anything

I saw tar.gz source in v2.0.0, should I use this?

Thank you for your advise.
Rong

**Comment by Augustin-Zidek** [comment]
Could you try:

```
git clone -b 'v2.0.1' --single-branch --depth 1 https://github.com/deepmind/alphafold.git
```

If this doesn't work, downloading the tar.gz should work too. 

I also strongly recommend using v2.0.1 instead of v2.0.0 since it has a lot of fixed bugs.

**Comment by ryao-mdanderson** [comment]
@Augustin-Zidek : Thank you! 👍 
Your git clone command works for me.
