### ISSUE TITLE
running via docker: cannot initialize backend TPU

### ISSUE THREAD

**Issue by chrisroat** [deepmind/alphafold#25]
In trying to repro the Google Cloud setup specified, I am seeing the following log messages using the Docker image approach.  They are "INFO" level -- are they an indication that my setup is incorrect and I would get sub-optimal performance?

```
I0718 14:02:57.560956 139711506118464 run_docker.py:180] I0718 14:02:57.560250 139800994285376 tpu_client.py:54] Starting the local TPU driver.
I0718 14:02:57.561176 139711506118464 run_docker.py:180] I0718 14:02:57.560675 139800994285376 xla_bridge.py:231] Unable to initialize backend 'tpu_driver': Not found: Unable to find driver in registry given worker: local://
I0718 14:02:57.777399 139711506118464 run_docker.py:180] I0718 14:02:57.776700 139800994285376 xla_bridge.py:231] Unable to initialize backend 'tpu': Invalid argument: TpuPlatform is not available.
```

FYI, [my setup instructions](https://docs.google.com/document/d/1IhDO-1bSOZChqZLa0WOtKoAtUu0yuXPtgf_AY7SC88M/edit?usp=sharing)

**Comment by tfgg** [comment]
Hi Chris - no, that's fine if you're intending to run on GPU rather than Cloud TPUs.

INFO level logs usually don't indicate things which are problems.

**Comment by chrisroat** [comment]
I am using the A100 specified in the demo setup in the README.  While it has tensor cores, it is not a TPU per se.
