### ISSUE TITLE
NameError: name 'model_type_to_use' is not defined

### ISSUE THREAD

**Issue by nikithakota** [deepmind/alphafold#254]
Hello, I was using the AlphaFold Collab Notebook. The program successfully ran all the steps up to the MSA. However, I was given this error once proceeding to the final Alphafold prediction step:

NameError                                 Traceback (most recent call last)
<ipython-input-1-52d16bd2cf57> in <module>()
     11 
     12 # --- Run the model ---
---> 13 if model_type_to_use == notebook_utils.ModelType.MONOMER:
     14   model_names = config.MODEL_PRESETS['monomer'] + ('model_2_ptm',)
     15 elif model_type_to_use == notebook_utils.ModelType.MULTIMER:

NameError: name 'model_type_to_use' is not defined

Please advise, thank you

**Comment by SandroNuciforo** [comment]
Hi, I got the same error message, did you solve the problem in the meantime?

**Comment by SandroNuciforo** [comment]
> Hello, I was using the AlphaFold Collab Notebook. The program successfully ran all the steps up to the MSA. However, I was given this error once proceeding to the final Alphafold prediction step:
> 
> NameError Traceback (most recent call last) in () 11 12 # --- Run the model --- ---> 13 if model_type_to_use == notebook_utils.ModelType.MONOMER: 14 model_names = config.MODEL_PRESETS['monomer'] + ('model_2_ptm',) 15 elif model_type_to_use == notebook_utils.ModelType.MULTIMER:
> 
> NameError: name 'model_type_to_use' is not defined
> 
> Please advise, thank you

Hi, I got the same error message, did you solve the problem in the meantime?

**Comment by andyballard** [comment]
Hi,

`model_type_to_use` should be defined two cells above the one that gives you the error. Is it possible you haven't yet run the preceeding cells?

**Comment by SandroNu** [comment]
Hi

Thanks for contacting me. I did run the preceeding cells, indeed I pasted two sequences (they differ in only one AA) and so I assume the multimer model should be used..

**Comment by catenate15** [comment]
> Hi, yes but this is defined based on the sequence used. If only one sequence is used i.e. then it is a monomer model and if multiple sequences are used it is a Multimer model. I am facing the same problem and decided to rerun it but still the same error and I only inserted one sequence. 
> 
> `model_type_to_use` should be defined two cells above the one that gives you the error. Is it possible you haven't yet run the preceding cells?

**Comment by BobLibo-2021** [comment]
Hi, I got the same error. Is there  any update?

> Hello, I was using the AlphaFold Collab Notebook. The program successfully ran all the steps up to the MSA. However, I was given this error once proceeding to the final Alphafold prediction step:
> 
> NameError Traceback (most recent call last) in () 11 12 # --- Run the model --- ---> 13 if model_type_to_use == notebook_utils.ModelType.MONOMER: 14 model_names = config.MODEL_PRESETS['monomer'] + ('model_2_ptm',) 15 elif model_type_to_use == notebook_utils.ModelType.MULTIMER:
> 
> NameError: name 'model_type_to_use' is not defined
> 
> Please advise, thank you

Hi, I got the same error. Is there  any update?

**Comment by Augustin-Zidek** [comment]
Duplicate of https://github.com/deepmind/alphafold/issues/422.
