### ISSUE TITLE
Multiple PDB structures of a single sequence

### ISSUE THREAD

**Issue by KoubaPetr** [deepmind/alphafold#255]
Hello,

I could not find the information how were - in the training of AlphaFold2 - treated the multiple different structures, which are available in the PDB for several proteins. Could you please provide details how you tackled this ambiguity of the labels?

Thanks in advance!
Petr

**Comment by tfgg** [comment]
Hi Petr,

If I understand correctly, your question is answered by the "Training regimen" section of [the paper](https://www.nature.com/articles/s41586-021-03819-2). In particular:

"Chains are sampled in inverse proportion to cluster size of a 40% sequence identity clustering."

Meaning that multiple structures of the same sequence are clustered together.

Tim
