### ISSUE TITLE
Result surrounded by unknown ligands

### ISSUE THREAD

**Issue by Leok90** [deepmind/alphafold#256]
Hello.

I'm new to bioinformatics, so maybe there is my mistake.

I'm using colab to get output and it work well, but visualization of output is surrounded by unknown ligands. 
So I'm confused. Is it normal? Below is a caputured image of output.
[https://drive.google.com/file/d/1-36sUDYwroxUxdpjaK63eUAgupaZXDYA/view?usp=drivesdk](https://drive.google.com/file/d/1-36sUDYwroxUxdpjaK63eUAgupaZXDYA/view?usp=drivesdk)

And I used below code as input.(IL-6R)

"MLAVGCALLAALLAAPGAALAPRRCPAQEVARGVLTSLPGDSVT
                     LTCPGVEPEDNATVHWVLRKPAAGSHPSRWAGMGRRLLLRSVQLHDSGNYSCYRAGRP
                     AGTVHLLVDVPPEEPQLSCFRKSPLSNVVCEWGPRSTPSLTTKAVLLVRKFQNSPAED
                     FQEPCQYSQESQKFSCQLAVPEGDSSFYIVSMCVASSVGSKFSKTQTFQGCGILQPDP
                     PANITVTAVARNPRWLSVTWQDPHSWNSSFYRLRFELRYRAERSKTFTTWMVKDLQHH
                     CVIHDAWSGLRHVVQLRAQEEFGQGEWSEWSPEAMGTPWTESRSPPAENEVSTPMQAL
                     TTNKDDDNILFRDSANATSLPVQDSSSVPLPTFLVAGGSLAFGTLLCIAIVLRFKKTW
                     KLRALKEGKTSMHPPYSLGQLVPERPRPTPVLVPLISPPVSPSSLGSDNTSSHNRPDA
                     RDPRSPYDISNTDYFFPR"
[https://www.ncbi.nlm.nih.gov/nuccore/BC132686.1](https://www.ncbi.nlm.nih.gov/nuccore/BC132686.1)

Here is a Jupyter notebook
[https://drive.google.com/file/d/1-2L8bRJjK3jGVFifVyDuDKd06sJzlS_n/view?usp=drivesdk](https://drive.google.com/file/d/1-2L8bRJjK3jGVFifVyDuDKd06sJzlS_n/view?usp=drivesdk)

Thank you!

**Comment by Rampakslue** [comment]
are you talking about these? 
![image](https://user-images.githubusercontent.com/9345232/141991149-03f35576-8bef-45e5-a65f-a4709b1876b1.png)

Those would be the side chains of the amino acids. Usually most protein viewers only show the backbone of the protein for simplicity sake. But yes, unless I'm missing something that is normal.

**Comment by Leok90** [comment]
> are you talking about these? ![image](https://user-images.githubusercontent.com/9345232/141991149-03f35576-8bef-45e5-a65f-a4709b1876b1.png)
> 
> Those would be the side chains of the amino acids. Usually most protein viewers only show the backbone of the protein for simplicity sake. But yes, unless I'm missing something, that is normal.

Thank you for teaching me!
