### ISSUE TITLE
Results as root

### ISSUE THREAD

**Issue by MrDotOne** [deepmind/alphafold#259]
I understand this is an artifact of docker and the way the container is running, but i was wondering if there was anyway to change the way the results are getting stored. Currently they are being written as root and this is causing some issues for our end users who are running analysis but cant see the results. Is there a way to fix this other than an admin chowning the files afterwards?

**Comment by 132nd-Entropy** [comment]
> I understand this is an artifact of docker and the way the container is running, but i was wondering if there was anyway to change the way the results are getting stored. Currently they are being written as root and this is causing some issues for our end users who are running analysis but cant see the results. Is there a way to fix this other than an admin chowning the files afterwards?

line 184 in run_docker.py , you should be able to change the output path 
output_target_path = os.path.join(_ROOT_MOUNT_DIRECTORY, 'output')

**Comment by tanhevg** [comment]
This is addressed by pull request #87.

**Comment by RodenLuo** [comment]
"cant see the results" did not happen to me. Although the results are written as `root:root`, the `r` (read) permission is given to everyone. So, the end-user should be able to read or copy the file. At least it is the case for me on `Ubuntu 18.04.6 LTS`.

**Comment by MrDotOne** [comment]
Thank you, i will repull and test this myself. Appreciate the responses.

**Comment by MrDotOne** [comment]
Used a fresh pull and it builds rather quickly. The results are indeed being written as 644 and owned by root, but can still be read by the 'world.' Thank you.
