### ISSUE TITLE
Docker image missing cuda libs

### ISSUE THREAD

**Issue by chrisroat** [deepmind/alphafold#26]
When using a docker image created from the repo, libs like cusolver and libcudnn are not installed.  I get the following set of warnings, ending with "Skipping registering GPU devices".  

Was the docker image meant to include these libs?  I see libcusolver.so.10 (a different version than listed in the warning), in the 11.0-runtime image (the Dockerfile is based on 11.0-base).  And cudnn would require an additional install step.

```
I0718 14:20:35.488188 139711506118464 run_docker.py:180] 2021-07-18 14:20:35.487292: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
I0718 14:20:35.632766 139711506118464 run_docker.py:180] 2021-07-18 14:20:35.632116: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
I0718 14:20:35.633013 139711506118464 run_docker.py:180] 2021-07-18 14:20:35.632167: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1766] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
I0718 14:20:35.633130 139711506118464 run_docker.py:180] Skipping registering GPU devices...

**Comment by carbocation** [comment]
I am also encountering the same warning message. For additional context, I am attempting to run this on a GCP machine with the `nvidia-gpu-cloud-image-20200629` boot disk image, with two `nvidia-tesla-v100` GPUs attached.

**Comment by YoshitakaMo** [comment]
> I see libcusolver.so.10 (a different version than listed in the warning), in the 11.0-runtime image (the Dockerfile is based on 11.0-base). And cudnn would require an additional install step.

See https://github.com/deepmind/alphafold/issues/11. Installation of libcudnn and libcusolver is not included in the Dockerfile.

**Comment by chrisroat** [comment]
Thanks for pointing me to the duplicate.  It looks like #11 is an error/crash and using a different cuda version then provided in the repo (11.1 vs 11.0).  

In our setup, with the provided 11.0 image, I get the above reported logging errors, but the process still completes.

I hope DeepMind wants the world to be able to reproduce what they did, so I'm curious what their recommended solution is.

**Comment by carbocation** [comment]
I am also curious as to whether people have had success getting the released Dockerfile to work with GPUs within a CUDA 11.0-based environment.

So far, I have been able to get this Dockerfile working without GPU support (at least, with the same "Skipping registering GPU devices" warnings noted above). I have also gotten this to work without GPU warnings by upgrading the Dockerfile to CUDA 11.1. But ideally I would like to run this with GPU support in a CUDA 11.0-based environment, which seems like it should be possible given the description of this release.

**Comment by chrisroat** [comment]
Given the [requirement of tensorflow-2.5.0](https://github.com/deepmind/alphafold/blob/d26287ea57e1c5a71372f42bf16f486bb9203068/requirements.txt#L12) and the [TF compatibility matrix](https://www.tensorflow.org/install/source#gpu), it seems it should be using cuda-11.2.

The solution I am now trying is #36 , which updates the base image to use nvidia's cuda 11.2 runtime, which brings in the missing libraries and uses versions in agreement with the compatibility matrix.

**Comment by tfgg** [comment]
Hi,

Thank you for the report and discussion. Please see if acf25fc87964cab56b79cc5f5a4929c3805ecbeb fixes this issue and reopen if not. This change moves to using the cudnn base image and works in testing (though we also didn't encounter this issue in testing, so I'm not sure exactly what's causing it).
