### ISSUE TITLE
run Alphafold locally

### ISSUE THREAD

**Issue by ttianchen** [deepmind/alphafold#260]
Hi there,

I'm running Alphafold on a computer cluster, I wanted to make a PAE plot like those shown on Alphafold database and colab results. Where are these PAE data? Which file should I use?
Thanks

**Comment by Zuricho** [comment]
It's in `result_model_{1,2,3,4,5}.pkl`, a pickle file. You can write a script to draw the figure on cluster or download it.
> Present only if using pTM models: predicted pairwise aligned errors (predicted_aligned_error contains a NumPy array of shape [N_res, N_res] with the range of possible values from 0 to max_predicted_aligned_error, where 0 means most confident). This can serve for a visualisation of domain packing confidence within the structure.

**Comment by RodenLuo** [comment]
In the end of #92, there is a guideline on how to make similar plots. But I did not figure out how to `# Color the structure by per-residue pLDDT` and `# Display lines at chain boundaries`.

**Comment by ttianchen** [comment]
> It's in `result_model_{1,2,3,4,5}.pkl`, a pickle file. You can write a script to draw the figure on cluster or download it.
> 
> > Present only if using pTM models: predicted pairwise aligned errors (predicted_aligned_error contains a NumPy array of shape [N_res, N_res] with the range of possible values from 0 to max_predicted_aligned_error, where 0 means most confident). This can serve for a visualisation of domain packing confidence within the structure.

@Zuricho I only find PAE data in multimer results, do you know how to get these data for a monomer run? How do I know if I'm running using pTM models or not? 
Thanks in advance.

**Comment by mattarnoldbio** [comment]
Hi @ttianchen ! You can specify the models used by issuing the `--model_names=model_1_ptm,model_2_ptm,model_3_ptm,model_4_ptm,model_5_ptm` flag. You can also use AlphaFold Multimer (2.1.0) for monomers by issuing the flag `--model_preset=monomer_ptm`.
To plot results, you might find this software that I wrote helpful: https://github.com/mattarnoldbio/alphapickle

**Comment by ttianchen** [comment]
> Hi @ttianchen ! You can specify the models used by issuing the `--model_names=model_1_ptm,model_2_ptm,model_3_ptm,model_4_ptm,model_5_ptm` flag. You can also use AlphaFold Multimer (2.1.0) for monomers by issuing the flag `--model_preset=monomer_ptm`. To plot results, you might find this software that I wrote helpful: https://github.com/mattarnoldbio/alphapickle

**Comment by ttianchen** [comment]
@mattarnoldbio Thanks, I'll give it a try.
