### ISSUE TITLE
How to resolve core dumped issue while running the alphafold2 latest version?

### ISSUE THREAD

**Issue by HimansuKumarIIITA** [deepmind/alphafold#261]
**python3 docker/run_docker.py --fasta_paths=T1050.fasta --max_template_date=2020-05-14 --data_dir=/data/hkumar1/software/AlphaFold2/DataBase/ --output_dir=/data/hkumar1/software/alphafold/OutputAlphafold**

Error:
I1118 10:38:26.208927 139676556441408 run_docker.py:87] Mounting /data/hkumar1/software/alphafold -> /mnt/fasta_path_0
I1118 10:38:26.209047 139676556441408 run_docker.py:87] Mounting /data/hkumar1/software/AlphaFold2/DataBase/uniref90 -> /mnt/uniref90_database_path
I1118 10:38:26.209110 139676556441408 run_docker.py:87] Mounting /data/hkumar1/software/AlphaFold2/DataBase/mgnify -> /mnt/mgnify_database_path
I1118 10:38:26.209167 139676556441408 run_docker.py:87] Mounting /data/hkumar1/software/AlphaFold2 -> /mnt/data_dir
I1118 10:38:26.209252 139676556441408 run_docker.py:87] Mounting /data/hkumar1/software/AlphaFold2/DataBase/pdb_mmcif -> /mnt/template_mmcif_dir
I1118 10:38:26.209304 139676556441408 run_docker.py:87] Mounting /data/hkumar1/software/AlphaFold2/DataBase/pdb_mmcif -> /mnt/obsolete_pdbs_path
I1118 10:38:26.209372 139676556441408 run_docker.py:87] Mounting /data/hkumar1/software/AlphaFold2/DataBase/pdb70 -> /mnt/pdb70_database_path
I1118 10:38:26.209445 139676556441408 run_docker.py:87] Mounting /data/hkumar1/software/AlphaFold2/DataBase/uniclust30/uniclust30_2018_08 -> /mnt/uniclust30_database_path
I1118 10:38:26.209513 139676556441408 run_docker.py:87] Mounting /data/hkumar1/software/AlphaFold2/DataBase/bfd -> /mnt/bfd_database_path
I1118 10:38:57.066114 139676556441408 run_docker.py:226] I1118 16:38:57.064508 139655916111680 templates.py:857] Using precomputed obsolete pdbs /mnt/obsolete_pdbs_path/obsolete.dat.
I1118 10:38:57.425003 139676556441408 run_docker.py:226] I1118 16:38:57.423916 139655916111680 xla_bridge.py:232] Unable to initialize backend 'tpu_driver': Not found: Unable to find driver in registry given worker:
I1118 10:38:57.754481 139676556441408 run_docker.py:226] I1118 16:38:57.753208 139655916111680 xla_bridge.py:232] Unable to initialize backend 'tpu': Invalid argument: TpuPlatform is not available.
I1118 10:38:57.763273 139676556441408 run_docker.py:226] LLVM ERROR: pthread_create failed: Resource temporarily unavailable
I1118 10:38:57.763638 139676556441408 run_docker.py:226] Fatal Python error: Aborted
I1118 10:38:57.763949 139676556441408 run_docker.py:226]
I1118 10:38:57.764223 139676556441408 run_docker.py:226] Current thread 0x00007f042d454740 (most recent call first):
I1118 10:38:57.764483 139676556441408 run_docker.py:226] File "/opt/conda/lib/python3.7/site-packages/jax/interpreters/xla.py", line 369 in backend_compile
I1118 10:38:57.764747 139676556441408 run_docker.py:226] File "/opt/conda/lib/python3.7/site-packages/jax/interpreters/xla.py", line 87 in compile_or_get_cached
I1118 10:38:57.765006 139676556441408 run_docker.py:226] File "/opt/conda/lib/python3.7/site-packages/jax/interpreters/xla.py", line 798 in from_xla_computation
I1118 10:38:57.765314 139676556441408 run_docker.py:226] File "/opt/conda/lib/python3.7/site-packages/jax/interpreters/xla.py", line 770 in compile
I1118 10:38:57.765562 139676556441408 run_docker.py:226] File "/opt/conda/lib/python3.7/site-packages/jax/interpreters/xla.py", line 654 in _xla_callable_uncached
I1118 10:38:57.765806 139676556441408 run_docker.py:226] File "/opt/conda/lib/python3.7/site-packages/jax/interpreters/xla.py", line 335 in xla_primitive_callable
I1118 10:38:57.766059 139676556441408 run_docker.py:226] File "/opt/conda/lib/python3.7/site-packages/jax/_src/util.py", line 180 in cached
I1118 10:38:57.766300 139676556441408 run_docker.py:226] File "/opt/conda/lib/python3.7/site-packages/jax/_src/util.py", line 187 in wrapper
I1118 10:38:57.766541 139676556441408 run_docker.py:226] File "/opt/conda/lib/python3.7/site-packages/jax/interpreters/xla.py", line 312 in apply_primitive
I1118 10:38:57.766820 139676556441408 run_docker.py:226] File "/opt/conda/lib/python3.7/site-packages/jax/core.py", line 624 in process_primitive
I1118 10:38:57.767814 139676556441408 run_docker.py:226] File "/opt/conda/lib/python3.7/site-packages/jax/core.py", line 272 in bind
I1118 10:38:57.768077 139676556441408 run_docker.py:226] File "/opt/conda/lib/python3.7/site-packages/jax/_src/lax/lax.py", line 481 in _convert_element_type
I1118 10:38:57.768325 139676556441408 run_docker.py:226] File "/opt/conda/lib/python3.7/site-packages/jax/_src/numpy/lax_numpy.py", line 3601 in array
I1118 10:38:57.768575 139676556441408 run_docker.py:226] File "/app/alphafold/alphafold/model/utils.py", line 80 in flat_params_to_haiku
I1118 10:38:57.768822 139676556441408 run_docker.py:226] File "/app/alphafold/alphafold/model/data.py", line 39 in get_model_haiku_params
I1118 10:38:57.769085 139676556441408 run_docker.py:226] File "/app/alphafold/run_alphafold.py", line 380 in main
I1118 10:38:57.769331 139676556441408 run_docker.py:226] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 258 in _run_main
I1118 10:38:57.769576 139676556441408 run_docker.py:226] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 312 in run
I1118 10:38:57.769820 139676556441408 run_docker.py:226] File "/app/alphafold/run_alphafold.py", line 427 in <module>
I1118 10:39:17.716646 139676556441408 run_docker.py:226] /app/run_alphafold.sh: line 3:     8 Aborted                 (core dumped) python /app/alphafold/run_alphafold.py "$@"

**Comment by andycowie** [comment]
This seems to be a docker issue related to resource contention on the server your instance is running on. Is there any way you can free more resources on the host?

**Comment by Augustin-Zidek** [comment]
Closing this issue for now, feel free to reopen if this is still a problem.
