### ISSUE TITLE
max_template_date not restricting searches?

### ISSUE THREAD

**Issue by van-richard** [deepmind/alphafold#263]
I installed alphafold v.2.1.0 on hpc, and made a conda environment to run.

My inputs are generally like this ( I excluded the locations for MSA databases, etc).:

python location/to/run_alphafold.py \
        --fasta_paths=${input}.fasta \
        --output_dir=${OUT_DIR} \
        --max_template_date=2015-1-10 \

Everything runs great, I get 5 unrelaxed models, 5 relaxed models, pLDDT, and PAE information. However I noticed that in one of the output folders:

> msas/pdb_hits.hhr

 Include PDBs that are recent (say the top few include PDBS that are 2015+). Am I understanding the max_template_date incorrectly or could this be my set up issue?

**Comment by Augustin-Zidek** [comment]
These are raw template hits coming out of the template search tools (HHSearch or Hmmsearch), they get filtered later on, so everything should be fine. 

See https://github.com/deepmind/alphafold/blob/be37a41d6f83e4145bd4912cbe8bf6a24af80c29/alphafold/data/templates.py#L215
