### ISSUE TITLE
I keep bumping into memory problems

### ISSUE THREAD

**Issue by Alleko** [deepmind/alphafold#265]
If possible, could you please help me with the memory problems? I am running an 1200 aa long protein on alphafold and using highram. I keep getting an error message in the last phase saying out of memory. I purchased pro. Thank you!

**Comment by optiprime8** [comment]
I also have many out of memory issues, even after paying for colab pro+. I am trying to model a 750aa protein as a dimer without success.

**Comment by Alleko** [comment]
Yes I also have Pro+ but still the same issue... Any help will be much appreciated! Thank you! : )

**Comment by hegelab** [comment]
Most likely the MSA file is too large and .read() into the memory.
See my pull request #281 
Try our fork: https://github.com/hegelab/alphafold

**Comment by Augustin-Zidek** [comment]
We improved our memory usage in https://github.com/deepmind/alphafold/releases/tag/v2.1.2. Is this still an issue? Also note that Colab (even the Pro version) has limited GPU memory, hence the best solution might be to use a local AlphaFold installation.
