### ISSUE TITLE
alphafold multimer msa

### ISSUE THREAD

**Issue by edat-uam-es** [deepmind/alphafold#266]
Hi,

    Alphafold method makes extensive use of multiple alignment of sequences.  For the monomer case is clear which MSAs have been used by looking at the files stored in msas directory. I understand that for the multimer case the situation is more complex. Is there any place containing a list of the pairs of sequences used by Alphafold-multimer?

**Comment by AnyaP** [comment]
Hi, we would suggest exploring `features.pkl` - this file contains the outputs of the data pipeline as NumPy arrays which as used by the models to produce the structures (see https://github.com/deepmind/alphafold#alphafold-output). Closing this issue for now, but feel free to reopen if this seems unclear or if you have further questions.
