### ISSUE TITLE
Question: Relaxed or unrelaxed model 

### ISSUE THREAD

**Issue by DiracZhu1998** [deepmind/alphafold#268]
Dear alphafold collaborator, 

Thank you for giving us such wonderful tools! I know the relaxed model is modified by Amber relaxation procedure. But I'm not in this specific field, so I'm wondering which model should I use, relaxed or unrelaxed? I'm testing the 3D influence of one AA substitution.

Best wishes,
Yuanzhen

**Comment by Augustin-Zidek** [comment]
In general we recommend using the relaxed models, they should have less clashes. However, if that causes issues (e.g. running relax is too slow or it crashes), you can disable it using `run_relax=false` flag which we added in AlphaFold v2.1.2.

Also note that AlphaFold is not very sensitive to single-point mutants.

**Comment by pojeda** [comment]
For a protein monomer prediction, I got the ranked_[0-4].pdb files and also the relaxed_model_[1-5]_pred_0.pdb files. According to the ranking_debug.json file the relaxed_model_4_pred_0_pred.pdb has the highest plddts. My question is if this structure was the ranked_0.pdb or if the initial order was changed during relaxation?  How is the correlation between the nomenclature and numbering of ranked_* and relaxed_model_*?

**Comment by tcoates5** [comment]
My experience thus far has been that the structure with the highest overall confidence score has been ranked_0.pdb. If you want to be more certain, you could always run some alignments between ranked_*.pdb and relaxed_*.pdb files, you should have an RMSD of about 0 for the relaxed structures and their renamed equivalents.
