### ISSUE TITLE
predict protein ligand binding sites and do molecular docking

### ISSUE THREAD

**Issue by heeqee** [deepmind/alphafold#269]
Hi
AlphaFold is such a great tool!
But now it can only predict protein structure. May I ask when you will release a version that predicts protein ligand binding sites and molecular docking? I want to know which ligand is bound to the corresponding site.
Thank you very much!

**Comment by abridgland** [comment]
Hi, glad you've found AlphaFold useful! As you suggest, this isn't something AlphaFold can predict, however you could try using AlphaFold structures with external docking tools.

**Comment by justin4ai** [comment]
@abridgland Hi, first and foremost, thanks for providing such a wonderful project as an open source to the world! I'd like to ask you if the functions (predicting protein ligand binding sites) are still not implemented or open.

Best,
Junyeong Ahn

**Comment by abridgland** [comment]
Hi @justin4ai, there is now a new repository for AlphaFold 3, which should be much more relevant to the use cases you mention.

https://github.com/google-deepmind/alphafold3
