### ISSUE TITLE
Question:Install NVIDIA Container Toolkit for GPU support

### ISSUE THREAD

**Issue by sdxCool** [deepmind/alphafold#272]
I'm sorry to disturb you, but I have a question about “install NVIDIA Container Toolkit”, and the specific step is as follows: when i input command "sudo docker run --rm --gpus all nvidia/cuda:11.0-base nvidia-smi",      there is a error:"docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: driver error: failed to process request: unknown."     i was puzzled.   I hope I can get your help. thanks.

**Comment by Sfatihi** [comment]
Did you test run your docker installation?

**Comment by truatpasteurdotfr** [comment]
go back to the installation page and make sure that docker works, then add the nvidia drivers and confirm each steps...
- `docker run --rm hello-world`
- `nvidia-smi`
- Give more details about your configurations both hardware and software, and try to format your text...

**Comment by andycowie** [comment]
Closing this issue for now, feel free to reopen if this is still a problem.
