### ISSUE TITLE
unable to run docker

### ISSUE THREAD

**Issue by amoltej** [deepmind/alphafold#273]
Hi, 
I am trying to run 
`sudo docker build -f docker/Dockerfile -t alphafold .`
but I am receiving the following result
`unable to prepare context: path "." not found`

could you help with a possible solution?

**Comment by tailordresden** [comment]
You're definitely running that command from inside the alphafold directory yes? (also, is there a reason you are using sudo? theoretically it should not need it and is safer if you don't)

**Comment by tomwardio** [comment]
Hi @amoltej, we strongly recommend using [Docker as a non-root user](https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user) to build and run. This may be why you experienced issues preparing the context.
