### ISSUE TITLE
prediction.zip fails to download

### ISSUE THREAD

**Issue by rjboyd00** [deepmind/alphafold#274]
While using Colab pro+ through safari browser MSA completes successfully and AlphaFold runs but 'prediction.zip' never successfully gets downloaded. Also can not reconnect to colab when disconnections happen. This may potentially be a browser compatibility issue. I am testing running with firefox and chrome.

**Comment by ValZapod** [comment]
Try to check whether Chrome blocks multiple downloads from site.

**Comment by AnyaP** [comment]
Yes, this is most likely the browser preventing the download. The solution is to click "allow multiple automatic downloads" in the popup. You can also test this by downloading several empty files before running the AlphaFold prediction. To do this, create a new cell at the beginning of the Colab and run the following code:

```python
import os
from google.colab import files
 
empty_dir = 'empty_prediction'
os.makedirs(empty_dir, exist_ok=True)
!zip -q -r {empty_dir}.zip {empty_dir}
files.download(f'{empty_dir}.zip')
```

This way you should be able to test the browser settings earlier and avoid the disconnection issue. Hope this helps! (please feel free to re-open this issue if not).

**Comment by ValZapod** [comment]
> Hope this helps!

I will also point out that you cannot download http files from https sites if it is from a different domain that cannot be autoupgraded to https. you have to right click it and press save and then allow.
