### ISSUE TITLE
RuntimeError: Jackhmmer failed

### ISSUE THREAD

**Issue by kdpan** [deepmind/alphafold#280]
/home/panfulu/anaconda3/envs/alphafold/lib/python3.8/site-packages/absl/flags/_validators.py:203: UserWarning: Flag --fasta_paths has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  warnings.warn(
/home/panfulu/anaconda3/envs/alphafold/lib/python3.8/site-packages/absl/flags/_validators.py:203: UserWarning: Flag --output_dir has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  warnings.warn(
/home/panfulu/anaconda3/envs/alphafold/lib/python3.8/site-packages/absl/flags/_validators.py:203: UserWarning: Flag --data_dir has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  warnings.warn(
/home/panfulu/anaconda3/envs/alphafold/lib/python3.8/site-packages/absl/flags/_validators.py:203: UserWarning: Flag --uniref90_database_path has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  warnings.warn(
/home/panfulu/anaconda3/envs/alphafold/lib/python3.8/site-packages/absl/flags/_validators.py:203: UserWarning: Flag --mgnify_database_path has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  warnings.warn(
/home/panfulu/anaconda3/envs/alphafold/lib/python3.8/site-packages/absl/flags/_validators.py:203: UserWarning: Flag --template_mmcif_dir has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  warnings.warn(
/home/panfulu/anaconda3/envs/alphafold/lib/python3.8/site-packages/absl/flags/_validators.py:203: UserWarning: Flag --max_template_date has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  warnings.warn(
/home/panfulu/anaconda3/envs/alphafold/lib/python3.8/site-packages/absl/flags/_validators.py:203: UserWarning: Flag --obsolete_pdbs_path has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  warnings.warn(
I1202 16:22:05.057188 140406960498496 templates.py:857] Using precomputed obsolete pdbs /home/panfulu/alphafold_database/pdb_mmcif/obsolete.dat.
I1202 16:22:06.602183 140406960498496 tpu_client.py:50] Starting the local TPU driver.
I1202 16:22:06.680797 140406960498496 xla_bridge.py:212] Unable to initialize backend 'tpu_driver': NOT_FOUND: Unable to find driver in registry given worker: local://
I1202 16:22:06.717052 140406960498496 xla_bridge.py:212] Unable to initialize backend 'gpu': NOT_FOUND: Could not find registered platform with name: "cuda". Available platform names are: Interpreter Host
I1202 16:22:06.717237 140406960498496 xla_bridge.py:212] Unable to initialize backend 'tpu': INVALID_ARGUMENT: TpuPlatform is not available.
W1202 16:22:06.717360 140406960498496 xla_bridge.py:215] No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
I1202 16:22:17.606557 140406960498496 run_alphafold.py:384] Have 5 models: ['model_1', 'model_2', 'model_3', 'model_4', 'model_5']
I1202 16:22:17.607256 140406960498496 run_alphafold.py:397] Using random seed 964966706831919773 for the data pipeline
I1202 16:22:17.608094 140406960498496 run_alphafold.py:150] Predicting P00519-2
I1202 16:22:17.610775 140406960498496 jackhmmer.py:130] Launching subprocess "/home/panfulu/anaconda3/envs/alphafold/bin/jackhmmer -o /dev/null -A /tmp/tmph__wyx2u/output.sto --noali --F1 0.0005 --F2 5e-05 --F3 5e-07 --incE 0.0001 -E 0.0001 --cpu 8 -N 1 P00519-2.fasta /home/panfulu/alphafold_database/uniref90/uniref90.fasta"
I1202 16:22:17.770159 140406960498496 utils.py:36] Started Jackhmmer (uniref90.fasta) query
I1202 16:47:47.703968 140406960498496 utils.py:40] Finished Jackhmmer (uniref90.fasta) query in 1529.933 seconds
Traceback (most recent call last):
  File "run_alphafold.py", line 427, in <module>
    app.run(main)
  File "/home/panfulu/anaconda3/envs/alphafold/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/panfulu/anaconda3/envs/alphafold/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "run_alphafold.py", line 403, in main
    predict_structure(
  File "run_alphafold.py", line 162, in predict_structure
    feature_dict = data_pipeline.process(
  File "/home/panfulu/Alphafold/alphafold-main/alphafold/data/pipeline.py", line 159, in process
    jackhmmer_uniref90_result = run_msa_tool(
  File "/home/panfulu/Alphafold/alphafold-main/alphafold/data/pipeline.py", line 97, in run_msa_tool
    result = msa_runner.query(input_fasta_path)[0]
  File "/home/panfulu/Alphafold/alphafold-main/alphafold/data/tools/jackhmmer.py", line 163, in query
    return [self._query_chunk(input_fasta_path, self.database_path)]
  File "/home/panfulu/Alphafold/alphafold-main/alphafold/data/tools/jackhmmer.py", line 139, in _query_chunk
    raise RuntimeError(
RuntimeError: Jackhmmer failed
stderr:
Fatal exception (source file esl_msafile_stockholm.c, line 1249):
stockholm msa write failed
system error: No space left on device

**But I have enough space.**

**Comment by hegelab** [comment]
MSA-s is written first to the tmp directory. Most likely you are running out of space on the partition where you have the tmp (I think that you will not see it, since tmp is cleaned after failing the program).

If this is the problem, I suggest to edit (I have space on /mnt/afold):
alphafold/alphafold/data/tools/utils.py

< def tmpdir_manager(base_dir: Optional[str] = None):
---
> def tmpdir_manager(base_dir: Optional[str] = "/mnt/afold/tmp"):

**Comment by kdpan** [comment]
Thank you very much !!!

**Comment by prehensilecode** [comment]
Can this be modified to read `$TMP` from the environment, instead? We run AlphaFold containers in an HPC cluster, and each job has a job-specific `TMP` defined (which includes the job ID number), and the job-specific `TMP` is automatically deleted at the end of job.

Or is there a commandline option that can be passed?
