### ISSUE TITLE
HHblits query Running Time

### ISSUE THREAD

**Issue by kdpan** [deepmind/alphafold#282]
**Hi:
    I want to ask how long does it take to run HHblits? 
    I've been running for 15 hours，but I still haven't finished this step.**
![微信截图_20211203103220](https://user-images.githubusercontent.com/42444342/144535102-a44e038f-cea7-4b89-b532-f488387fc38f.png)

**Comment by Lsz-20** [comment]
> **Hi: I want to ask how long does it take to run HHblits? I've been running for 15 hours，but I still haven't finished this step.** ![微信截图_20211203103220](https://user-images.githubusercontent.com/42444342/144535102-a44e038f-cea7-4b89-b532-f488387fc38f.png)

have you solve this problem?I have the same question

**Comment by kdpan** [comment]
No, I've been running for almost 24 hours and haven't finished yet.

**Comment by ojcharles** [comment]
You can try and speed up some of the steps using more cores, or a solid state drive right? Else you might find mmseq2 useful which will return a set of required files which alphafold can consume I believe. Thats faster.

**Comment by AnyaP** [comment]
Hi, 

This sounds too slow, we have the following recommendations:
1. Make sure you are running on a modern CPU with the AVX2 instruction set.
2. Make sure the database is on a fast local disk, ideally an SSD.
3. If you are still seeing these issues after dealing with 1 and 2, could you create an issue in https://github.com/soedinglab/hh-suite/issues?

Thanks,

**Comment by JLHU2021** [comment]
Hi, have been solved this issue?

**Comment by Topdp** [comment]
Hi, have been solved?
