### ISSUE TITLE
Issue reproducing quality of models available on AF DB

### ISSUE THREAD

**Issue by maschka** [deepmind/alphafold#285]
Hi,
I tried to reproduce a protein available on the AF database. I understand that the protein may be different from run to run. However, I have run with 'reduced db' and 'full db' on our clusters (In each case the models generated are fairly similar to each other). My predicted structure is farther from the available crystal structures than the predicted structures that are available for download. I'm wondering if there are specific setting you had to run it on to get these?
Why are my predictions coming out slightly worse? 

For reference the gene is https://alphafold.ebi.ac.uk/entry/Q8TDU6

I am also running a pretty early version of this repository - somewhere near the initial release.

**Comment by MFSeidl** [comment]
Hi all - I would be very much interested in exactly the same question. I observe a similar behaviour for some of my structures and wonder how the structures on alphafold-db were predicted, i.e. which settings and models were used

Thanks a bunch!

**Comment by pykao** [comment]
Actually, I ran the same FASTA sequence twice using the same setting, and AF give me different results (fragments aligned: 74%) for O00141.

**Comment by pykao** [comment]
Dear all, 

I probably find the reason why the resulting structures are different:

https://github.com/deepmind/alphafold/blob/b85ffe10799ca08cc62146f1dabb4e4ee6c0a580/run_alphafold.py#L105-L109

**Comment by Jane333** [comment]
Hi, yes, the random seed is likely to be the culprit if seeing differences between runs. If you see differences with a fixed seed, please re-open the issue.

Also, we advise using the latest version of AlphaFold, which will mostly give structures at least as good as what is seen in AFDB. However, please note that this code is not meant to reproduce the AFDB results 100%.
