### ISSUE TITLE
How can we display model confidence in the output pdb files?

### ISSUE THREAD

**Issue by rainwala** [deepmind/alphafold#286]
Hello, thank you for releasing this wonderful work.

I would like to visualise the model confidence in the 3d structure itself, as done by the EBI (i.e. here: https://alphafold.ebi.ac.uk/entry/Q8W3K0_)

When I run alphafold locally and visualise the ranked_n.pdb files in 3d protein visualisation tools like ChimeraX, I cannot seem to do this.

Is it possible to take the output of docker/run_alphafold.py on a protein of interest and visualise the confidences as EBI have done?

Thank you.

**Comment by AnyaP** [comment]
Hello!

The pLDDT confidence measure is stored in the B-factor field of the output PDB files (note that unlike a B-factor, higher pLDDT is better, as it is a model confidence score). So you should be able to load the predicted .pdb file e.g. into PyMol and colour the structure based on the B-factors. 

The only difference is that in the database viewer we discretize to 4 colour bands, while the B-factors visualised in PyMOL will be “continuous”.  Feel free to also take a look [at the Colab](https://github.com/deepmind/alphafold/blob/main/notebooks/AlphaFold.ipynb) where the colouring is done in the same way as in the database.

**Comment by Ni-Ar** [comment]
FYI, if you're using [ChimeraX](https://www.rbvi.ucsf.edu/chimerax/) v1.3 or higher you can colour your model `#1` with the same https://alphafold.ebi.ac.uk/ palette by typing:

````
color bfactor #1 palette alphafold
````

For the interpretation read [here](https://alphafold.ebi.ac.uk/faq#faq-5), for more info about ChimeraX palettes read [here](https://www.rbvi.ucsf.edu/chimerax/docs/user/commands/color.html#palette-options)

**Comment by chersiakingdom** [comment]
> Hello!
> 
> The pLDDT confidence measure is stored in the B-factor field of the output PDB files (note that unlike a B-factor, higher pLDDT is better, as it is a model confidence score). So you should be able to load the predicted .pdb file e.g. into PyMOL and colour the structure based on the B-factors.
> 
> The only difference is that in the database viewer we discretize to 4 colour bands, while the B-factors visualised in PyMOL will be “continuous”. Feel free to also take a look [at the Colab](https://github.com/deepmind/alphafold/blob/main/notebooks/AlphaFold.ipynb) where the colouring is done in the same way as in the database.

Hello, I have a question.
 If the pLDDT value is stored in the B-factor of the output pdb file, when the Pymolo B-factor is visualized, does the red color mean that the prediction is more accurate?

**Comment by Augustin-Zidek** [comment]
> If the pLDDT value is stored in the B-factor of the output pdb file, when the B-factor is visualized using Pymol, does the red color mean that the prediction is more accurate?

@chersiakingdom Correct.
