### ISSUE TITLE
Reduced Databases with AlphaFold-Multimer

### ISSUE THREAD

**Issue by amorehead** [deepmind/alphafold#287]
Hello.

I was wondering whether there are any plans to make AlphaFold-Multimer compatible with the reduced database feature pipeline that AlphaFold-Monomer currently uses? If not, are there any simple ways you are aware of to use, for example, the Small BFD with AlphaFold-Multimer?

Thank you for your time.

**Comment by AnyaP** [comment]
Hello!

This is already supported (and actually happening in the AlphaFold-Multimer Colab). 

To run this with AF Docker installation you will need to provide the following flags:

```
python3 docker/run_docker.py \
  --model_preset=multimer \
  --db_preset=reduced_dbs \
  --fasta_paths=... \
  --max_template_date=... \
  --data_dir=...
```

Hope this helps! (Feel free to re-open if not).
