### ISSUE TITLE
Fetch prediction using bash or python

### ISSUE THREAD

**Issue by DDudka9** [deepmind/alphafold#288]
Is there a way to use bash or python to fetch a specific prediction from AlphaFold database? I installed AlphaFold from pypi but I didn't find any documentation if that was possible. The goal would be to have a prediction in a pdb format on a local server. Currently I need to download the whole database for a given species and use python to fetch a single prediction from the database.

**Comment by Augustin-Zidek** [comment]
Sure, you can use `wget` or `curl`. 

For instance, to download a cif file for `F4HVG8`, you would do: 

```
wget https://alphafold.ebi.ac.uk/files/AF-F4HVG8-F1-model_v1.cif
```

**Comment by FriedLabJHU** [comment]
This new tool from our lab [affetch](https://github.com/mansanlab/alphafoldfetch)
