### ISSUE TITLE
Disulfide bridges annotation in Alphafold PDB models

### ISSUE THREAD

**Issue by areyesromero** [deepmind/alphafold#289]
Dear all, 

How is the connectivity between the two S atoms indicated in the PDB model file produced by Alphafold?

In the case of the any crystal structure this type of connection between atoms is indicated at the bottom of the file. 
In the case of human insulin (PDB 3I3Z) is

 ```
CONECT 43 76                                                               
CONECT 49 223                                                                
CONECT 76 43                                                               
CONECT 154 320                                                               
CONECT 223 49                                                                
CONECT 320 154 
```

For A0A0A0MRZ7 model there is a clear disulfide connecting residues number 113 and 43 but cannot really find this information in the pdb file. 

How could I find this disulfide bridge annotation within the Alphafold models?
Best regards

**Comment by andyballard** [comment]
Hi, 

The output PDB files contain raw coordinates only. You should be able to assign disulfide bonds via spatial proximity of the relevant sulfer atoms.

**Comment by ajasja** [comment]
Wouldn't the extra H atoms on the sulfur prevent the sulfur atoms from getting very close together?

**Comment by tcoates5** [comment]
While I am not sure how it happens procedurally, most cys that are paired seem to come without the extra hydrogen in the pdb file

**Comment by ajasja** [comment]
Interesting, will double check.
