### ISSUE TITLE
Releasing the AlphaFold package on pypi

### ISSUE THREAD

**Issue by ashrafgt** [deepmind/alphafold#29]
Thank you for sharing the AlphaFold codebase!

I wanted to suggest releasing the package to pypi to make it easier to install especially in production environments, if possible, including the `run_alphafold` script.
 
Please let me know if you'll consider this suggestion.

**Comment by tfgg** [comment]
Hi, it should be available as the `alphafold` package - https://pypi.org/project/alphafold/. Can you test it?

**Comment by ashrafgt** [comment]
@tfgg Oh, thank you! 

It wasn't mentioned in the README or the release page, so I assumed it wasn't hosted on pypi without checking for myself.

**Comment by tfgg** [comment]
Thanks, we'll add to the README.

**Comment by ashrafgt** [comment]
@tfgg This may be worth opening a separate issue, but I'd like to bring your attention to this issue I encountered while trying to run the `run_alphafold.py` script with the `alphafold` package installed (instead of cloning the repo).

```python
# python run_alphafold.py run_alphafold.py 
Traceback (most recent call last):
  File "run_alphafold.py", line 31, in <module>
    from alphafold.data import pipeline
  File "/opt/conda/envs/[CONDA_ENV_NAME]/lib/python3.8/site-packages/alphafold/data/pipeline.py", line 26, in <module>
    from alphafold.data import templates
  File "/opt/conda/envs/[CONDA_ENV_NAME]/lib/python3.8/site-packages/alphafold/data/templates.py", line 31, in <module>
    from alphafold.data.tools import kalign
ModuleNotFoundError: No module named 'alphafold.data.tools
```

And indeed, here are the contents of `alphafold/data/` in the site packages:
```python
# ls /opt/conda/envs/deep_chain/lib/python3.8/site-packages/alphafold/data/
__init__.py  __pycache__  mmcif_parsing.py  parsers.py  pipeline.py  templates.py
```
They're missing the `tools` directory which does exist in the source: https://github.com/deepmind/alphafold/tree/main/alphafold/data

**Comment by Augustin-Zidek** [comment]
This is due to a missing `__init__.py` in `alphafold/data/tools`. We will push a fix for that in the next bugfix release.

**Comment by ashrafgt** [comment]
> This is due to a missing `__init__.py` in `alphafold/data/tools`. We will push a fix for that in the next bugfix release.

TY Augistin!
