### ISSUE TITLE
Question about database compatability

### ISSUE THREAD

**Issue by nhatas** [deepmind/alphafold#290]
If I update our existing 2.0.0 AlphaFold databases to the AlphaFold databases for version 2.1.0, will the database files be compatible with AlphaFold 2.0.0? Or would I have to store two separate databases, one for users using v2.0.0 and the other for v2.1.0?

Thanks in advance for your help!

**Comment by AnyaP** [comment]
Yes, AlphaFold databases for version 2.1.0 will be compatible with AlphaFold 2.0.0 ([instructions here](https://github.com/deepmind/alphafold/blob/main/README.md#updating-existing-alphafold-installation-to-include-alphafold-multimers) for the update). 

Also note that the AlphaFold 2.1.0 release includes the original AlphaFold monomer models (as a preset), so the users of the version 2.0.0 can likely be migrated to the newer version without any implications for their research.
