### ISSUE TITLE
question about loading the database

### ISSUE THREAD

**Issue by jjjscuedu** [deepmind/alphafold#291]
Dear all, 

We have configured a local alphafold in our server, and also download the latest database.

(af2) [root@alphafold test]# ls -lh ../database/
total 8.0K
drwxr-xr-x 2 root root 4.0K Dec  6 19:10 bfd
drwxr-xr-x 2 root root   45 Dec  6 10:17 mgnify
drwxr-xr-x 2 root root 4.0K Dec  2 20:42 params
drwxr-xr-x 2 root root  254 Dec  2 20:13 pdb70
drwxr-xr-x 3 root root   57 Dec  3 11:11 pdb_mmcif
drwxr-xr-x 2 root root   36 Dec  7 10:40 pdb_seqres
drwxr-xr-x 2 root root  115 Dec  7 11:00 small_bfd
drwxr-xr-x 3 root root   40 Dec  2 18:38 uniclust30
drwxr-xr-x 2 root root   98 Dec  7 10:44 uniprot
drwxr-xr-x 2 root root   36 Dec  6 10:44 uniref90

However, when we test the alphafold using one protein sequence,

(af2) [root@alphafold test]# more test.fa 
>test
GWSTELEKHREELKEFLKKEGITNVEIRIDNGRLEVRVEGGTERLKRFLEELRQKLEKKGYTVDIKIE

python ../software/alphafold/run_alphafold.py --fasta_paths=test.fa --data_dir=/root/database/ --output_dir=/root/test/result/  --max_template_date=2021-11-01

![image](https://user-images.githubusercontent.com/5130367/144955235-515bd203-e1aa-4345-8870-6c1b6d3e6c69.png)

(af2) [root@alphafold test]# python ../software/alphafold/run_alphafold.py --fasta_paths=test.fa --data_dir=/root/database/ --output_dir=/root/test/result/  --max_template_date=2021-11-01
2021-12-07 11:02:43.809618: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.11.0
FATAL Flags parsing error:
  flag --uniref90_database_path=None: Flag --uniref90_database_path must have a value other than None.
  flag --mgnify_database_path=None: Flag --mgnify_database_path must have a value other than None.
  flag --template_mmcif_dir=None: Flag --template_mmcif_dir must have a value other than None.
  flag --obsolete_pdbs_path=None: Flag --obsolete_pdbs_path must have a value other than None.
Pass --helpshort or --helpfull to see help on flags.

However, it seems alphafold does't find the database.

Can you help me about how to fix this issue?

Thanks a lot!

Jingjing

**Comment by AnyaP** [comment]
Dear Jingjing,

Please provide paths for each database as a separate flag for `run_alphafold.py`, i.e. running with a command like

```
python ../software/alphafold/run_alphafold.py \
--fasta_paths=test.fa \
--data_dir=/root/database \
--output_dir=/root/test/result \
--max_template_date=2021-11-01 \
--uniref90_database_path=/root/database/uniref90 \
--mgnify_database_path=/root/database/mgnify \
--bfd_database_path=/root/database/bfd \
--small_bfd_database_path=/root/database/small_bfd \
--uniclust30_database_path=/root/database/uniclust30 \
--uniprot_database_path=/root/database/uniprot \
--pdb70_database_path=/root/database/pdb70  \
--pdb_seqres_database_path=/root/database/pdb_seqres \
--template_mmcif_dir=/root/database/pdb_mmcif/mmcif_files \
--obsolete_pdbs_path=/root/database/pdb_mmcif/obsolete.dat
```

You can find more details on each flag in the script documentation, e.g.:
https://github.com/deepmind/alphafold/blob/be37a41d6f83e4145bd4912cbe8bf6a24af80c29/run_alphafold.py#L74-L75 

Alternatively, you can use `run_docker.py` (if you are running within the Docker) and use the example command that you have posted (see README for more details).
