### ISSUE TITLE
FATAL Flags parsing error: Unknown command line flag 'db_preset'. Did you mean: preset ?   i need help

### ISSUE THREAD

**Issue by Wud1** [deepmind/alphafold#294]
run:
python3 run_docker.py --fasta_paths=test.fasta --max_template_date=2021-11-01 --data_dir=/mnt/rhd/database/data_set

err:
 /opt/conda/lib/python3.7/site-packages/absl/flags/_validators.py:206: UserWarning: Flag --preset has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
'command line!' % flag_name)
FATAL Flags parsing error: Unknown command line flag 'db_preset'. Did you mean: preset ?
Pass --helpshort or --helpfull to see help on flags.

**Comment by AnyaP** [comment]
There was [the recent API change](https://github.com/deepmind/alphafold/blob/main/README.md#api-changes-between-v200-and-v210) where the `preset` flag in run_docker.py was split into `db_preset` and `model_preset`.

Is there a possibility that you are running v2.0.0 version of the model with v2.1.0 version of the Docker scripts? 

We would suggest making sure that you are updated to the latest release, and then passing `db_preset` and `model_preset` flags following the README or run_docker documentation (they have sensible defaults too): https://github.com/deepmind/alphafold/blob/be37a41d6f83e4145bd4912cbe8bf6a24af80c29/docker/run_docker.py#L59-L67

**Comment by AnyaP** [comment]
I will close the issue now, but please feel free to re-open it if this did not help!
