### ISSUE TITLE
cuLinkAddData fails

### ISSUE THREAD

**Issue by Lsz-20** [deepmind/alphafold#295]
when I run this code，I got this error：
![image](https://user-images.githubusercontent.com/60343452/145218370-0346f672-da8a-45bb-b27e-d8ba95f770fe.png)
![image](https://user-images.githubusercontent.com/60343452/145218440-e54ede73-e301-4074-8863-8c2388d670d1.png)

![image](https://user-images.githubusercontent.com/60343452/145218762-272db8e8-dde7-490b-8b52-7c8b051e4e3c.png)
![image](https://user-images.githubusercontent.com/60343452/145219057-fef1a6b2-fa3b-47ce-ac46-c75cda840129.png)
tensorflow=2.5.0  jax=0.2.25 jaxlib=0.1.69+cuda111
waiting for advice~

**Comment by Augustin-Zidek** [comment]
This issue was fixed in https://github.com/deepmind/alphafold/releases/tag/v2.1.2.

**Comment by xianyu-123** [comment]
i have the same error, used version is 2.3.1, How did you solve this problem ? thanks
