### ISSUE TITLE
Distribution over multiple GPUs

### ISSUE THREAD

**Issue by georgkempf** [deepmind/alphafold#30]
Hi,
I ran alphafold on a 2k sequence using 2x V100 (32 GB) GPU. Like for shorter sequences, 29 GB are allocated on the first GPU and 300 MB on the other from the start. After hhblits I got an out-of-memory error from JAX that 26 GB couldn't be allocated. Does everything need to be loaded to a single GPU or should it in theory be possible to use the next GPU if the first one runs out of memory? Why are 300 MB allocated to the second GPU from the start?

**Comment by StephanHeijl** [comment]
Same error here, except an error is raised trying to allocate 8GB on a ~1600aa sequence, when working with a 4x A100 setup (40GB). 
```
I0719 14:52:43.337913 139836811884352 run_docker.py:180] 2021-07-19 12:52:43.337083: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:794] 
failed to alloc 8589934592 bytes on host: CUDA_ERROR_OPERATING_SYSTEM: OS call failed or operation not supported on this OS
```
This is inside the docker container.

**Comment by tfgg** [comment]
Hi, we don't parallelize the model itself in JAX over multiple GPUs, but we do [enable unified memory](https://github.com/deepmind/alphafold/blob/main/docker/run_docker.py#L172) which should (CUDA might be smarter) at least be able to use the host RAM as well.

Can you see any logging statements saying how much device memory JAX has access to?
How much RAM does your GPU host have?

**Comment by georgkempf** [comment]
Hi,
I ran it again with a 2.7k sequence on a 48 GB GPU and asked for 80GB RAM on the server. 

I get the following error:
e_aatype': (4, 4, 2799), 'template_all_atom_masks': (4, 4, 2799, 37), 'template_all_atom_positions': (4, 4, 2799, 37, 3), 'template_sum_probs': (4, 4, 1), 'is_distil
lation': (4,), 'seq_mask': (4, 2799), 'msa_mask': (4, 508, 2799), 'msa_row_mask': (4, 508), 'random_crop_to_size_seed': (4, 2), 'template_mask': (4, 4), 'template_ps
eudo_beta': (4, 4, 2799, 3), 'template_pseudo_beta_mask': (4, 4, 2799), 'atom14_atom_exists': (4, 2799, 14), 'residx_atom14_to_atom37': (4, 2799, 14), 'residx_atom37
_to_atom14': (4, 2799, 37), 'atom37_atom_exists': (4, 2799, 37), 'extra_msa': (4, 5120, 2799), 'extra_msa_mask': (4, 5120, 2799), 'extra_msa_row_mask': (4, 5120), 'b
ert_mask': (4, 508, 2799), 'true_msa': (4, 508, 2799), 'extra_has_deletion': (4, 5120, 2799), 'extra_deletion_value': (4, 5120, 2799), 'msa_feat': (4, 508, 2799, 49)
, 'target_feat': (4, 2799, 22)}
2021-07-19 16:40:55.656793: W external/org_tensorflow/tensorflow/core/common_runtime/bfc_allocator.cc:457] Allocator (GPU_0_bfc) ran out of memory trying to allocate
 45.86GiB (rounded to 49244540672)requested by op 
2021-07-19 16:40:55.661892: W external/org_tensorflow/tensorflow/core/common_runtime/bfc_allocator.cc:468] *******************_______________________________________
__________________________________________
2021-07-19 16:40:55.662105: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:1981] Execution of replica 0 failed: Resource exhau
sted: Out of memory while trying to allocate 49244540640 bytes.

[...]

alphafold-conda/lib/python3.6/site-packages/jax/interpreters/xla.py", line 893, in _execute_compiled
    out_bufs = compiled.execute(input_bufs)
jax._src.traceback_util.UnfilteredStackTrace: RuntimeError: Resource exhausted: Out of memory while trying to allocate 49244540640 bytes.

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.


[...]

.../alphafold-conda/lib/python3.6/site-packages/jax/interpreters/xla.py", line 893, in _execute_compiled
    out_bufs = compiled.execute(input_bufs)
RuntimeError: Resource exhausted: Out of memory while trying to allocate 49244540640 bytes.

It seems the maximum RAM usage for this job was 20GB (according to slurm).

I am running alphafold from a conda installation (not the container) and I am using jaxlib==0.1.67+cuda111

**Comment by tfgg** [comment]
You need to be using jaxlib 0.1.69 (as set in the Dockerfile) for CUDA unified memory to work, this was recently added. Can you try that?

**Comment by georgkempf** [comment]
Thanks a lot for the hints, installing jaxlib 0.1.69 and setting the environment variables TF_FORCE_UNIFIED_MEMORY=1, XLA_PYTHON_CLIENT_MEM_FRACTION=4.0 helped to get it to the minimization step. Here it's running now many minimization iterations for the same prediction/model with the following error messages between iterations: 

2021-07-20 11:18:29.326371: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:794] failed to alloc 34359738368 bytes on host: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2021-07-20 11:18:29.326403: W external/org_tensorflow/tensorflow/core/common_runtime/device/device_host_allocator.h:46] could not allocate pinned host memory of size: 34359738368
2021-07-20 11:18:29.326444: W external/org_tensorflow/tensorflow/core/common_runtime/bfc_allocator.cc:457] Allocator (xla_gpu_host_bfc) ran out of memory trying to allocate 5.72GiB (rounded to 6142170624)requested by op 

However the iterations seem to complete since it prints Efinal. For another prediction I saw that it also ran many iterations for the first model (without the above mentioned error/warning messages).

**Comment by tfgg** [comment]
@RodenLuo to run different jobs on different GPUs you'll need to use the `--gpu_devices` devices flag on run_docker, or equivalently set the NVIDIA_VISIBLE_DEVICES environment variable if you're not using docker. From your nvidia-smi, you'd want to set them to "0", "1", "2", and "3" to run four jobs in parallel on different cards.

**Comment by RodenLuo** [comment]
Thanks, this is great! 

I read the doc at home page again, it says "By default, Alphafold will attempt to use all visible GPU devices." It seems not the case for me? So if I want a job to use two GPUs, I would use `--gpu_devices=2,3`, and would expect it will use two?

**Comment by RodenLuo** [comment]
So, I tested it and found that it can at most use one GPU per job. Is this only happening to Ampere cards? Thanks. 

```
$ python3 docker/run_docker.py --fasta_paths=predictions/T4/37_trimer.fasta --max_template_date=2021-08-01 --pr
eset=casp14 --gpu_devices=2,3
```

```
$ nvidia-smi
Thu Aug  5 22:20:57 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA RTX A6000    Off  | 00000000:18:00.0 Off |                  Off |
| 55%   79C    P2   202W / 300W |  48682MiB / 48685MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA RTX A6000    Off  | 00000000:3B:00.0 Off |                  Off |
| 30%   38C    P8     7W / 300W |   2629MiB / 48685MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA RTX A6000    Off  | 00000000:86:00.0 Off |                  Off |
| 59%   83C    P2   298W / 300W |  48681MiB / 48685MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA RTX A6000    Off  | 00000000:AF:00.0 Off |                  Off |
| 30%   28C    P8    17W / 300W |   1011MiB / 48685MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     31505      C   python                           1095MiB |
|    1   N/A  N/A     27949      C   python                            259MiB |
|    1   N/A  N/A     31505      C   python                            447MiB |
|    2   N/A  N/A      9729      C   python                           1093MiB |
|    2   N/A  N/A     31505      C   python                            447MiB |
|    3   N/A  N/A      9729      C   python                            447MiB |
|    3   N/A  N/A     31505      C   python                            447MiB |
+-----------------------------------------------------------------------------+
```

**Comment by zhoujingyu13687306871** [comment]
> @RodenLuo to run different jobs on different GPUs you'll need to use the `--gpu_devices` devices flag on run_docker, or equivalently set the NVIDIA_VISIBLE_DEVICES environment variable if you're not using docker. From your nvidia-smi, you'd want to set it to "0", "1", "2", and "3" for each job to run four jobs in parallel on different cards.

@tfgg NVIDIA_VISIBLE_DEVICES environment variable need to  written in run_alphafold.py , if I use no-docker for multiple gpus?

**Comment by Augustin-Zidek** [comment]
@zhoujingyu13687306871 Yes, you need to set that variable yourself if not using Docker. 

Closing this issue for now, feel free to reopen if this is still a problem and using `--gpu_devices` doesn’t solve it.
