### ISSUE TITLE
HHblits failed because of high ram, then pagefile size.

### ISSUE THREAD

**Issue by Tyler-Jay-Stevahn** [deepmind/alphafold#301]
I just have a question over how much ram I'll need to buy in order to run this correctly. My computer specs are below. I'm running it in a docker image like the tutorial says and am using the T1050.fasta file it says to try with first. I am only beginning to look into cuda and how to use multiple GPU's but from reading others issues it doesn't seem easy to implement. My motherboard supports up to 128Gb but I don't think that is necessary, because of this group of sentences.

Running AlphaFold
The simplest way to run AlphaFold is using the provided Docker script. This was tested on Google Cloud with a machine using the nvidia-gpu-cloud-image with 12 vCPUs, 85 GB of RAM, a 100 GB boot disk, the databases on an additional 3 TB disk, and an A100 GPU.

Would the 85GB of ram be enough to get through this issue on my machine? Or is there a config file where I can set a limit on that Ram that is available? 

Computer specs:

ASRock X570 EXTREME4 AM4 AMD 
X570 SATA 6Gb/s ATX AMD Motherboard
Ryzen 7 5800X Stock 
16Gb Ram 
1 GTX 1080

![Ram and Swap usage](https://user-images.githubusercontent.com/25287690/145482063-0b8cd55d-78f6-424d-870c-577deea0ab91.png)

![Alphafold HHblits failed RuntimeError](https://user-images.githubusercontent.com/25287690/145478599-96dccc28-7cc0-4586-a00e-fd8a7b485441.png)

**Comment by andycowie** [comment]
16 GB is too little RAM to run BFD Uniclust in our experience – your experience of swap file taking over and performance degrading is typical. 32 GB is usually enough for this stage.

Alternatively you could run with `--db_preset=reduced_dbs` as specified in the README which should prevent the excessive RAM usage since it doesn’t search BFD using HHBlits.
