### ISSUE TITLE
No space left on device while creating docker image

### ISSUE THREAD

**Issue by skhatri007** [deepmind/alphafold#303]
I am trying a fresh installation of alpha fold.
I am continuously receiving a same error while I have ample of space in **var** and **home directory**. Furthermore, I know that docker contains images in var directory and I have sufficient 4 Tb of storage for that. Yet I am receiving an error. I have tried numerous things.

**--Step 10/17 : COPY . /app/alphafold
failed to copy files: failed to copy directory: Error processing tar file(exit status 1): write /bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt_a3m.ffdata: no space left on device**

I would kindly request tif anyone can share their valuable suggestions.
Any suggestions would be highly appreciated.

**Comment by Augustin-Zidek** [comment]
Where did you download the databases to? Are they by any chance in a subdirectory of the main AlphaFold GitHub repo? If so, then the solution is to move them elsewhere to prevent Docker packaging them into the image, see https://github.com/deepmind/alphafold/issues/210#issuecomment-949537302.

**Comment by skhatri007** [comment]
Thank you for your reply.
Af - multimer is up and running.
 I solved ut by running without creating docker image..

Thanks.

**Comment by skhatri007** [comment]
I would really like appreciate and thank the efforts of the team that were
involved in the development of this tool. And this is something that is
really quite innovative and believe that it has accelerated the research
especially to the folks like us that deal in the structural biology.

Thanks!!

**Comment by Augustin-Zidek** [comment]
Thank you for your kind word, I am glad you got it working!
