### ISSUE TITLE
cudnn version in Dockfile

### ISSUE THREAD

**Issue by Sunyp-IM** [deepmind/alphafold#309]
Dear all,

In the Dockfile Line 16 is "FROM nvidia/cuda:${CUDA}-cudnn8-runtime-ubuntu18.04". 
However, the linux version in my computer is CentOS 7. So do I need to change Line 16 to something like "FROM nvidia/cuda:${CUDA}--runtime-centos7"?

I will appreciate any help.
All the best~

**Comment by Augustin-Zidek** [comment]
Hi, no need to change this. There is Ubuntu running inside the Docker container, hence the version of CUDA that is fetched is for the Ubuntu inside the container rather than directly for your machine.

**Comment by Sunyp-IM** [comment]
Got it!
Thank you:)
