### ISSUE TITLE
How many GPUs has Alphafold used for training?

### ISSUE THREAD

**Issue by xiongzhp** [deepmind/alphafold#31]
In supplementary Table 4 of the published Nature paper, it says it takes about 7days to train initially and 4 days to fine-tune, but we can't see any message about the number of gpus that were used?  Could you please clarify that?

**Comment by tfgg** [comment]
Hi, this is detailed in the "Training regimen" section in the Methods section:

> We train the model on Tensor Processing Unit (TPU) v3 with a batch size of 1 per TPU core, hence the model uses 128 TPUv3 cores.

(As you can see, we train on TPUs, not GPUs).

**Comment by ValZapod** [comment]
You could have used tensor cores of nvidia though :) Like leela chess did. It is very fast. Like VEERY.
