### ISSUE TITLE
How are pdb_mmcif files chosen?

### ISSUE THREAD

**Issue by mcahn** [deepmind/alphafold#311]
A user ran into this error for when modeling one protein:

`FileNotFoundError: [Errno 2] No such file or directory: '.../pdb_mmcif/mmcif_files/7pju.cif'`

I downloaded that file, and then on another protein, the user ran into another missing pdb_mmcif file:

`FileNotFoundError: [Errno 2] No such file or directory: '.../pdb_mmcif/mmcif_files/7s1g.cif'`

I redownloaded all of pdb_mmcif, which caused some new files to appear, and there haven't been any problems since.

How does AlphaFold decide which pdb_mmcif files to use?  How does it know to look for a file if the file is not present -- is there a list of the files that it uses?  What is the right way to be sure all the files it wants have been downloaded?

Thanks,
Matthew Cahn

**Comment by andycowie** [comment]
The system downloads all of pdb_mmcif, and separately downloads PDB SeqRes. SeqRes is used for template search, returning the pdb_mmcif files to retrieve, and the templates found are looked up in the downloaded copy of pdb_mmcif. So the versions of PDB seqres and pdb_mmcif should ideally be identical. Failing that PDB SeqRes should not be newer than the version of pdb_mmcif, or the templates found in search will fail to load, causing this error.

In this case the problem  could be caused if the download_pdb_files step of the download failed, or possibly if the download_pdb_seqres.sh got a newer version of the pdb_seqres file - it could have been updated midway through the download process.

Either way your solution of rerunning the pdb_mmcif download seems an optimal solution.
