### ISSUE TITLE
Using multiple GPU

### ISSUE THREAD

**Issue by Lsz-20** [deepmind/alphafold#312]
Everything seems well when I run on 1 GPU，to improve the speed，I'm trying to run on 3 GPU by set -a 0,1,2.But I got the errors:
![image](https://user-images.githubusercontent.com/60343452/146517675-7a812287-771e-40fc-b8ba-c2a04de5f240.png)
![image](https://user-images.githubusercontent.com/60343452/146517793-600cd674-a928-4213-95a9-04888787baf5.png)
And the following still running,such as :Searching for template for : ****(my sequence)

How can I solve this?
Thanks for your help.

**Comment by Augustin-Zidek** [comment]
Hi, we don't parallelize the model itself in JAX over multiple GPUs, so running with more than one GPU will not help in terms of speed. I recommend running on a single GPU especially if that works.

**Comment by Lsz-20** [comment]
> Hi, we don't parallelize the model itself in JAX over multiple GPUs, so running with more than one GPU will not help in terms of speed. I recommend running on a single GPU especially if that works. See also #66 and #30.

Thanks for your answer.
