### ISSUE TITLE
GPU problem 

### ISSUE THREAD

**Issue by jjjscuedu** [deepmind/alphafold#314]
Dear all,
I have run as guide. However, during running, there are some issues related to GPU, it seems that it was running on CPU.

This is the configure for the GPU in our server:

(af2) [root@alphafold example]# nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Thu_Jun_11_22:26:38_PDT_2020
Cuda compilation tools, release 11.0, V11.0.194
Build cuda_11.0_bu.TC445_37.28540450_0

The error log is as follows:

![O8OI_$35FEXGS7B21HZX@4X](https://user-images.githubusercontent.com/5130367/146701697-45ccba5b-c064-4b74-96a2-9efee501566b.png)

![FAI8O U@~X}ZX}J%60YANWB](https://user-images.githubusercontent.com/5130367/146701721-db0c590c-26d3-44c0-bad6-79f203fde3da.png)

Can anyone give me some suggestion about how to fix this issue?

Any suggestion is greatly appreciated!

Thanks a lot!

**Comment by th-of** [comment]
What happens if you change lines 93 and 533 in "amber_minimize.py" from:
platform = openmm.Platform.getPlatformByName("CPU")
to 
platform = openmm.Platform.getPlatformByName("CUDA")?

**Comment by jjjscuedu** [comment]
> What happens if you change lines 93 and 533 in "amber_minimize.py" from: platform = openmm.Platform.getPlatformByName("CPU") to platform = openmm.Platform.getPlatformByName("CUDA")?

Thanks a lot!  I have change lines 93 and 533 accroding to your suggestions. However, the error log is that it could find CUDA platform now.

![8ISI9O`}JTRU_OH6H7 KP6X](https://user-images.githubusercontent.com/5130367/146852137-552b8f7e-969b-4a89-b7be-0dfe1d96d17f.png)

![B%RC{`MP9Q@YJF0(X2_5F7M](https://user-images.githubusercontent.com/5130367/146852238-d674e15f-18bf-40b5-8919-7a44aec60460.png)

**Comment by Augustin-Zidek** [comment]
Could you try replacing the following in `run_alphafold.py`?

```py
amber_relaxer = relax.AmberRelaxation(
        max_iterations=RELAX_MAX_ITERATIONS,
        tolerance=RELAX_ENERGY_TOLERANCE,
        stiffness=RELAX_STIFFNESS,
        exclude_residues=RELAX_EXCLUDE_RESIDUES,
        max_outer_iterations=RELAX_MAX_OUTER_ITERATIONS)
```
to

```py
amber_relaxer = None
```

That means the relaxation stage will not run at all which means the output structure might have some structural violations, but might work around the relaxation issue.

**Comment by Augustin-Zidek** [comment]
Hi, relax can now be easily disabled by setting `--run_relax=false`. Feel free to reopen this issue if that doesn't help with your problem.
