### ISSUE TITLE
Support using raw mmcif files

### ISSUE THREAD

**Issue by sbliven** [deepmind/alphafold#316]
It would be much more convenient if alphafold could use the 'raw' mmcif files (e.g. gz compressed and divided by middle 2 characters). This has a number of advantages:

- Considerably smaller (61GB vs 217GB)
- Directories have only hundreds of files as opposed to 185'000 files
- Easy to update with rsync

**Comment by abridgland** [comment]
Hi Spencer, thanks a lot for this suggestion! Unfortunately it's not currently part of our plans due to other ongoing priorities but feature requests like this are much appreciated.
