### ISSUE TITLE
Running alphafold leads to reboot of the system?

### ISSUE THREAD

**Issue by Sunyp-IM** [deepmind/alphafold#317]
Dear every,

I have set up alphafold in my CentOS system, and I have successfully finished one structure prediction task. However, I ran another task and found that the computer reboot automatically 12 after the task started. The phenomenon  have appeared twice. 

Do you have any clue that why this strange thing occurs?

Best regards

**Comment by Augustin-Zidek** [comment]
This might be due to out of memory issues. Could you check if you system was low on RAM prior to the reboot?

**Comment by abiadak** [comment]
Are you using a GPU? We had a similar problem. It was due to the computer's power supply not being beefy enough. The computer rebooted after building the features.pkl, when it begins to build the model. Substituting the power supply with a more capable one solved it.

**Comment by Augustin-Zidek** [comment]
@abiadak Thanks for the fascinating comment which might indeed be the solution to the problem @Sunyp-IM is seeing. Closing this issue now, feel free to re-open if using a beefier power supply doesn't help. Alternatively, you could also try running with
