### ISSUE TITLE
Self-distillation MSAs

### ISSUE THREAD

**Issue by gahdritz** [deepmind/alphafold#319]
Was the self-distillation MSA search run using the same HHblits settings as in previous steps (i.e. -n 3 -e 0.001 -realign_max 100000 -maxfilt 100000 -min_prefilter_hits 1000 -maxseq 1000000)?

**Comment by zj-liu** [comment]
Hi, I have a related question. Were the structures in the self-distillation dataset relaxed with OpenMM?

**Comment by Augustin-Zidek** [comment]
>Was the self-distillation MSA search run using the same HHblits settings as in previous steps (i.e. -n 3 -e 0.001 -realign_max 100000 -maxfilt 100000 -min_prefilter_hits 1000 -maxseq 1000000)?

To produce the self-distillation set, we ran HHBlits 3.0-beta.3 with the following flags: `-cpu 4 -n 3 -e 0.001`, all other flags were left to their defaults. Note that we used only UniClust MSAs for the self-distillation set.

> Hi, I have a related question. Were the structures in the self-distillation dataset relaxed with OpenMM?

No, they were not.
