### ISSUE TITLE
Evaluation on CASP14

### ISSUE THREAD

**Issue by nnnwyn** [deepmind/alphafold#322]
Hello everyone. I am doing some evaluation jobs of the inference pipeline. I am wondering how to evaluate the result pdb file such like TM-score, for those proteins that CASP14 doesn't provide the remarking pdb file.

**Comment by abridgland** [comment]
Hi, unfortunately not all of the CASP14 structures are publicly available online. You should still be able to use the available ones for evaluation, and if you have any further questions about specific structures I recommend contacting the CASP organisers.
