### ISSUE TITLE
How to train the model

### ISSUE THREAD

**Issue by JoursBleu** [deepmind/alphafold#323]
Is there any training script for alphafold available?

**Comment by JoursBleu** [comment]
We are trying to reproduce & accelerate major models in different application fields on Intel accelerators and servers.
Is there any official implementation of AlphaFold2 training?

**Comment by abridgland** [comment]
This repository doesn't contain a training script and there is no official implementation. However all the details are in our paper and there are some reproductions with training scripts, such as OpenFold.
