### ISSUE TITLE
Editing MODEL_PRESETS

### ISSUE THREAD

**Issue by amoltej** [deepmind/alphafold#325]
Hi, I am working on insect proteins and having CAPS14 may not be the best model preset.
Can you please provide guidelines and steps to modify MODEL_PRESETS dictionary in alphafold/model/config.py?

Thanks
Amol

**Comment by AnyaP** [comment]
Hi Amol,

MODEL_PRESETS dictionary corresponds to the released model weights. You can select a preset with --model_preset flag as described in step 5 of https://github.com/deepmind/alphafold/blob/main/README.md#running-alphafold. However, we would expect the CASP14 models to be best validated for the performance. 

Closing this issue for now, feel free to reopen if this seems unclear or you have further questions.

**Comment by amoltej** [comment]
Hi Anya, Thanks for reply. I tried following the steps described there. My question is - 
1) How to specify other preset model? 
2) How do I make sure it is in the database? 
3) What if the protein model is not in the original database because it has been recently published? how can I set and model_preset?
4) How to specify the model in command, e.g. by default we specify it using "CASP14 (is it uniprot name or what?)"? To specify any other specific protein model, how do I find the identifier for that protein model in any specific database? is it from Uniprot database? or something else?

**Comment by amoltej** [comment]
> Hi Amol,
> 
> MODEL_PRESETS dictionary corresponds to the released model weights. You can select a preset with --model_preset flag as described in step 5 of https://github.com/deepmind/alphafold/blob/main/README.md#running-alphafold. However, we would expect the CASP14 models to be best validated for the performance.
> 
> Closing this issue for now, feel free to reopen if this seems unclear or you have further questions.

Hi Anya, Thanks for reply. I tried following the steps described there. My question is -

    How to specify other preset model?
    How do I make sure it is in the database?
    What if the protein model is not in the original database because it has been recently published? how can I set and model_preset?
    How to specify the model in command, e.g. by default we specify it using "CASP14 (is it uniprot name or what?)"? To specify any other specific protein model, how do I find the identifier for that protein model in any specific database? is it from Uniprot database? or something else?
