### ISSUE TITLE
Trouble downloading pdb_mmcif database

### ISSUE THREAD

**Issue by NMMQ** [deepmind/alphafold#327]
Hi, I'm having some issues using the downoad_pdb_mmcif.sh script. When I run it i get the following response: 

Running rsync to fetch all mmCIF files (note that the rsync progress estimate might be inaccurate)...
rsync: safe_read failed to read 1 bytes [Receiver]: Connection reset by peer (104)
rsync error: error in rsync protocol data stream (code 12) at io.c(276) [Receiver=3.1.2]

Please let me know is there is any other way that I can download the database
Thank you

**Comment by Augustin-Zidek** [comment]
Hi,

I recommend taking a look at https://www.wwpdb.org/ftp/pdb-ftp-sites. You could either try some of the other rsync mirrors listed there or try to download the files from their FTP mirrors.

**Comment by Zoidmania** [comment]
Sorry to necro this thread, but I thought I'd mention: the `downoad_pdb_mmcif.sh` script uses [rsync double-colon][1] over port 33444, which was blocked on my corporate network. For anyone running into these sorts of issues in the future, check with your networking team if that port is blocked for the rsync protocol.

[1]: https://superuser.com/questions/736067/difference-between-and-in-ssh

**Comment by calebcodes01** [comment]
@Zoidmania Any suggestions on how to bypass this? Currently experiencing exactly this problem.
