### ISSUE TITLE
CUDA error out of memory

### ISSUE THREAD

**Issue by vhu43** [deepmind/alphafold#33]
Hello,

Right now, we have a machine with 12 GB vRAM, and we get the error CUDA error out of memory. when folding with model 4 or 5.  We suspect this is because the GPU does not have enough memory for the model.  If so, our lab is wondering if there are ways to decrease the memory requirements.  If not, we can try to find a different machine or GPU to run it.

Thanks!

**Comment by jeffm14** [comment]
That's my guess, the GPU they mention in the readme has at least 40 GB of video RAM.

**Comment by ashrafgt** [comment]
For me, the out-of-memory error occurred after many runs. This could mean that the GPU memory isn't being fully released at the end of the prediction. Though, this is not a problem that happens just with the Alphafold model.

**Comment by vhu43** [comment]
What I'm confused about is that unified memory should be on, so shouldn't that allow the use of system memory?  We have 128GB of system memory.  Does unified memory also apply to the other jax libraries, like jax.numpy?

**Comment by biohegedus** [comment]
Hi,

Could you resolve it? Can you use a GPU with less than 40GB RAM?
Do you have any experiences with the system RAM? Do you need 85G or can you go with smaller? 32 or 64G?
Thanks.

**Comment by ashrafgt** [comment]
> Hi,
> 
> Could you resolve it? Can you use a GPU with less than 40GB RAM?
> Do you have any experiences with the system RAM? Do you need 85G or can you go with smaller? 32 or 64G?
> Thanks.

The required GPU memory depends on the length of the sequences you're trying to fold. Sequences containing 500 amino-acids ran just fine on a GPU with 10 GB of memory.

**Comment by vhu43** [comment]
> 
> 
> Hi,
> 
> Could you resolve it? Can you use a GPU with less than 40GB RAM?
> Do you have any experiences with the system RAM? Do you need 85G or can you go with smaller? 32 or 64G?
> Thanks.

Hello.

Alphafold works fine for us except for the largest proteins we want to fold.  We have done proteins up to 600AA without problem, but we have some that total 900AA that we would like to fold as well. 

My concern now is that reading through #20 I'm under the impression that unified memory is enabled, and should allow for folding of larger proteins, but this does not seem to be the case for us.

**Comment by ashrafgt** [comment]
Consider fiddling with these options to be able to run the prediction with limited resources: https://jax.readthedocs.io/en/latest/gpu_memory_allocation.html#gpu-memory-allocation

**Comment by biohegedus** [comment]
Thanks for the feedback.
My targets are up to 1500 a.a. :-(
I have a 24GB GPU, so I cross my fingers.

**Comment by Augustin-Zidek** [comment]
Sorry for a very late reply. Is this still an issue we could help with?

**Comment by hegelab** [comment]
It was addressed in #216 and included in AlphaFold v2.1.0

**Comment by hegelab** [comment]
the correction was included

**Comment by Augustin-Zidek** [comment]
Thanks, closing this issue now.
