### ISSUE TITLE
Why use `f.islower()` here?

### ISSUE THREAD

**Issue by yuw444** [deepmind/alphafold#334]
https://github.com/deepmind/alphafold/blob/be37a41d6f83e4145bd4912cbe8bf6a24af80c29/alphafold/data/parsers.py#L176

As far as I know, lower case letters represent the insert, not the deletion in `a3m` format. Could you help clarify here? 

Thanks

**Comment by andycowie** [comment]
The use of `f.lower()` is intentional.

We delete any residues inserted into the alignment and assign the number of deleted residues (`deletion_count`) to the relevant cell in the deletion matrix.

Closing this issue for now, feel free to reopen if this is still a problem.
