### ISSUE TITLE
Are there resources providing the precomputed features.pkl files given the protein IDs or sequences?

### ISSUE THREAD

**Issue by qwu01** [deepmind/alphafold#335]
I'm working with yeast proteins, trying to use the generated protein representations (features.pkl). 
I found some servers with the predicted protein structures available, but none provided the features.pkl files.
Are there resources where I can download the pre-computed features.pkl files given the protein IDs or protein sequences?
Thanks!

**Comment by Augustin-Zidek** [comment]
Hi, `features.pkl` is not a standard format for protein structures. It is just a serialisation of AlphaFold features in case users are interested in inspecting them. 

Moreover, its format is specific to AlphaFold, hence any other protein prediction software will not provide such file. 

The most important AlphaFold outputs are the coordinates, pLDDT and PAE, all of which should be provided.
