### ISSUE TITLE
RESOURCE_EXHAUSTED: Out of memory

### ISSUE THREAD

**Issue by arneelof** [deepmind/alphafold#340]
I have problem running systems larger than approximately 5000 residues. It seems to be a CPU-limit of 190Gb somehow (I have been running on a node with 1Tb of memory and 8*40GB of GPU memory), but the limit seems to be similar even if I use only 2 GPUs. I have tried some different jax versions but the error is always the same,
[output.log](https://github.com/deepmind/alphafold/files/7888128/output.log)
[outpur.err.txt](https://github.com/deepmind/alphafold/files/7888136/outpur.err.txt)

Any ideas how to solve this ?

Yours

Arne

**Comment by a-pritzel** [comment]
Hi Arne,

AlphaFold doesn't support using multiple GPUs when inferencing a single example. 
We do allow the model to use host memory, which means AlphaFold can use the RAM on the machine it is running on, however it can not use the RAM of any other GPUs on the same machine.

The amount of host memory AlphaFold can use is controlled by the XLA_PYTHON_CLIENT_MEM_FRACTION environment variable.
If you are using the docker container to run the model you can change it in this line:
https://github.com/deepmind/alphafold/blob/be37a41d6f83e4145bd4912cbe8bf6a24af80c29/docker/run_docker.py#L214
The value refers to the total amount of memory AlphaFold can use relative to the size of the GPU, so in your case 4 would mean AlphaFold can use 40 GB of GPU and another 120 GB of host memory.
You can try setting this to a larger value, which should allow to infer larger proteins, however generally the model will be slower the more it needs to rely on host memory.

Best,
Alex

**Comment by AnyaP** [comment]
Closing this issue for now, feel free to reopen if this is still a problem.

**Comment by yubene** [comment]
I use RTX2080 8GB, 128G RAM to run alphafold3, it running success for example and get right results, but for 2000bp protein fold have following Error, anyone who can help me solve it?
``` bash
Featurising data for seeds (2024,) took  39.35 seconds.
Running model inference for seed 2024...
Traceback (most recent call last):
  File "/mnt/d/alphafold3/run_alphafold.py", line 678, in <module>
    app.run(main)
  File "/mnt/d/alphafold3/.venv/lib/python3.11/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/mnt/d/alphafold3/.venv/lib/python3.11/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/mnt/d/alphafold3/run_alphafold.py", line 663, in main
    process_fold_input(
  File "/mnt/d/alphafold3/run_alphafold.py", line 542, in process_fold_input
    all_inference_results = predict_structure(
                            ^^^^^^^^^^^^^^^^^^
  File "/mnt/d/alphafold3/run_alphafold.py", line 375, in predict_structure
    result = model_runner.run_inference(example, rng_key)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/d/alphafold3/run_alphafold.py", line 313, in run_inference
    result = self._model(rng_key, featurised_example)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 6710886400 bytes.
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
```
