### ISSUE TITLE
issue in installing AlphaFold on Linux Ubuntu

### ISSUE THREAD

**Issue by Maryamtarazkar** [deepmind/alphafold#342]
Hi, I am trying to install AlphaFold on Linux machine, but when I execute the file "./install_on_local.sh" only the first steps moves forward and "af2" is created. I tried to proceed step by step and I am stopped in following step. 
conda install -y -c bioconda hmmer hhsuite==3.3.0 kalign2

I get following error:

"""
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: |
Found conflicts! Looking for incompatible packages.                                                                                                        failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package libgcc-ng conflicts for:
python=3.8 -> zlib[version='>=1.2.11,<1.3.0a0'] -> libgcc-ng[version='>=7.2.0']
python=3.8 -> libgcc-ng[version='>=7.3.0|>=7.5.0']
hhsuite==3.3.0 -> libgcc-ng[version='>=7.5.0|>=9.3.0|>=9.4.0']
hhsuite==3.3.0 -> python[version='>=3.7,<3.8.0a0'] -> libgcc-ng[version='>=7.2.0|>=7.3.0']
hmmer -> libgcc-ng[version='>=4.9|>=7.3.0|>=7.5.0|>=9.3.0']
kalign2 -> libgcc-ng[version='>=4.9|>=7.5.0|>=9.3.0']

Package libstdcxx-ng conflicts for:
python=3.8 -> libffi[version='>=3.2.1,<3.3a0'] -> libstdcxx-ng[version='>=7.2.0']
hhsuite==3.3.0 -> python[version='>=3.7,<3.8.0a0'] -> libstdcxx-ng[version='>=7.2.0|>=7.3.0']
hmmer -> libstdcxx-ng[version='>=4.9|>=7.3.0|>=7.5.0|>=9.3.0']
hhsuite==3.3.0 -> libstdcxx-ng[version='>=7.5.0|>=9.3.0|>=9.4.0']
python=3.8 -> libstdcxx-ng[version='>=7.3.0|>=7.5.0']The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - feature:|@/linux-64::__glibc==2.31=0
  - hhsuite==3.3.0 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - hmmer -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - kalign2 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']

Your installed version is: 2.31
"""

I mostly appreciate to help me how I can resolve this issue and install the software with no error. 
Thanks so much for your helps in advance
Maryam

**Comment by Aminelahlou** [comment]
I am no alphafold official, but I am willing to helpon the week end if you didnt already resolve your issue. just dm me

**Comment by tfgg** [comment]
Hi,

`./install_on_local.sh` isn't a file in this repository - are you using a non-official version of the AlphaFold code?

We recommend following the instructions in the [README.md](https://github.com/deepmind/alphafold/blob/main/README.md) of this repository to install AlphaFold with Docker. This minimizes the chance of version conflicts.

**Comment by andycowie** [comment]
Closing this issue for now, feel free to reopen if this is still a problem.
