### ISSUE TITLE
Relaxation failing due to max_attempts value

### ISSUE THREAD

**Issue by meh47336** [deepmind/alphafold#343]
Currently trying to run AlphaFold Multimer to produce five predictions for 38 interaction hits that I've narrowed it down to. The hits were chosen by evaluating unrelaxed output structures. So, for the 5 x 38 predictions produced I'd also like to run AMBER relaxation on each.

This is being run with local GPUs on Linux. I've edited the script so that num_relax is now "Top5" (have also tried "All").

That said, for every set of predictions I receive the following output:

Traceback (most recent call last):
  File "runner_batch.py", line 817, in <module>
    relaxed_pdb_lines, _, _ = amber_relaxer.process(prot=outs[key]["unrelaxed_protein"])
  File "/share/apps/colab/colabfold/alphafold/relax/relax.py", line 58, in process
    out = amber_minimize.run_pipeline(
  File "/share/apps/colab/colabfold/alphafold/relax/amber_minimize.py", line 469, in run_pipeline
    ret = _run_one_iteration(
  File "/share/apps/colab/colabfold/alphafold/relax/amber_minimize.py", line 415, in _run_one_iteration
    raise ValueError(f"Minimization failed after {max_attempts} attempts.")
ValueError: Minimization failed after 100 attempts.

Is this typical? Couldn't find other people running into similar problems via Google searches. Is it worth increasing the max_attempts value? Any other suggestions?

Thank you.

**Comment by meh47336** [comment]
`add-labels: 'usage question, error`

**Comment by Augustin-Zidek** [comment]
We added a flag to disable the relaxation stage in 57a2455. Running with `run_relax=false` should help with this issue (but since not running relax, there might slightly more clashes in the predicted structure).
