### ISSUE TITLE
pdb_mmcif files are taking forever to download

### ISSUE THREAD

**Issue by diegop2211** [deepmind/alphafold#345]
pdb_mmcif files are taking forever to download, I could only do 15G in 10 hours. BFD, magnify, parms, pdb70 all downloaded in a reasonable amount of time, I am running on AWS I don't know if it's a memory issue but please help. Also, I am following this tutorial and have the same configurations and followed all the same steps.

https://aws.amazon.com/blogs/machine-learning/run-alphafold-v2-0-on-amazon-ec2/

**Comment by Augustin-Zidek** [comment]
I recommend using a different mirror as documented on PDB's website: https://www.rcsb.org/docs/programmatic-access/file-download-services

See also these issues with concrete instructions:
https://github.com/deepmind/alphafold/issues/40
https://github.com/deepmind/alphafold/issues/94

It is also possible the PDB server is temporarily overloaded, so trying again a few days later might resolve the issue.

I will close the issue for now, but feel free to re-open if none of my suggestions help!

**Comment by wttat** [comment]
Maybe you could try my batch solution : )
https://github.com/wttat/af2-batch-cdk
or just download my dataset: s3://alphafold2/dataset3.tar.gz
