### ISSUE TITLE
Alphafold doesn't recognize K80 GPUs

### ISSUE THREAD

**Issue by pojeda** [deepmind/alphafold#347]
I am trying the T1050.fasta example mentioned the in README file of Alphafold. The version of Alphafold I am using is 2.1.1. The way I run the script (using SLURM) is:

```
module load AlphaFold/2.1.1
export ALPHAFOLD_HHBLITS_N_CPU=14
run_alphafold.py --fasta_paths=T1050.fasta --max_template_date=2020-05-14 --model_preset=monomer --db_preset=reduced_dbs
```

This script runs but it doesn't use the 2 K80 GPUs available on a node (I have monitored the GPU usage). The  output file of Alphafold says:

```
I0125 11:45:30.356643 22974736108416 xla_bridge.py:236] Unable to initialize backend 'tpu_driver': Not found: Unable to find driver in re
gistry given worker: 
I0125 11:45:30.821589 22974736108416 xla_bridge.py:236] Unable to initialize backend 'tpu': Invalid argument: TpuPlatform is not availabl
e.

jackhmmer.py:133] Launching subprocess "/bin/jackhmmer -o
 /dev/null -A /output.sto --noali --F1 0.0005 --F2 5e-05 --F3 5e-07 --incE 0.0001 -E 0.0001 --cpu 8 -N 1 T1050.fasta 
/uniref90/uniref90.fasta"
```

The same script recognizes V100 GPUs. Is there anything in the K80 that is not supported by Alphafold or anything that needs to be upgraded? Thanks.

**Comment by josomir** [comment]
Following, same thing happens with my 2 x K40 while using SLURM and singularity. GPU is recognized but not utilized.

**Comment by tomwardio** [comment]
Hi both!

By default, AlphaFold uses CUDA 11 which [doesn't support Kepler GPUs](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#title-new-cuda-libraries). You could try running with an older CUDA version, but unfortunately we can't ensure that there won't be performance or accuracy differences.

Hope this helps!
