### ISSUE TITLE
To select the top ranking structure or the structure with highest average pLDDT confidence score

### ISSUE THREAD

**Issue by cgseitz** [deepmind/alphafold#348]
I have a simple question that I can't seem to find the answer to. After predicting structures through AlphaFold, is it better to use the top ranking structure (assuming it has no structural flaws) or the structure with the highest average pLDDT score after minimization? Thanks!

**Comment by pojeda** [comment]
But for instance, ranked_0.pdb which initially has the highest plddt corresponds to relaxed_model_1_pred_0.pdb? Or is the ordering mixed?
