### ISSUE TITLE
Donload data "uniclust30" problem 

### ISSUE THREAD

**Issue by NITROGENousFish** [deepmind/alphafold#35]
Hi,

I cannot download **uniclust30**, Dataset from the script. Also from another repository [RoseTTAFold](https://github.com/RosettaCommons/RoseTTAFold), I cannot download uniref30 either. 

I'm not major in biology, I do not familiar with this organization **wwwuser.gwdg.de**.
Can anyone really download these datasets?

Thanks!!!

Following are the download URLs:
**uniclust30**: http://wwwuser.gwdg.de/~compbiol/uniclust/2018_08/uniclust30_2018_08_hhsuite.tar.gz
**uniref30**: http://wwwuser.gwdg.de/~compbiol/uniclust/2020_06/UniRef30_2020_06_hhsuite.tar.gz

**Comment by tfgg** [comment]
Hi,

We've made a mirror for Uniclust30 here:
https://storage.googleapis.com/alphafold-databases/casp14_versions/uniclust30_2018_08_hhsuite.tar.gz

That should work. We don't have a Uniref30 mirror as AlphaFold 2 doesn't use it.

This link provides:
“[Uniclust30: v2018_08](http://wwwuser.gwdg.de/~compbiol/uniclust/2018_08/)” (unmodified), by Mirdita M. et al., available under a [Creative Commons Attribution-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-sa/4.0/).

**Comment by NITROGENousFish** [comment]
THANKS A LOT!!

This works well for me 😆

**Comment by hussainiat** [comment]
> https://storage.googleapis.com/alphafold-databases/casp14_versions/uniclust30_2018_08_hhsuite.tar.gz

Thank you so much for this. This saves a lot of time, from 6-7 hrs to just 7 minutes.
