### ISSUE TITLE
RuntimeError: jaxlib/cusolver_kernels.cc:44: operation cusolverDnCreate(&handle) failed: cuSolver internal error

### ISSUE THREAD

**Issue by chersiakingdom** [deepmind/alphafold#351]
Hello. I have been suffering for over a week or two due to an error when installing Alphafold. I hope you can tell me the solution.

Below is the error I am getting.

`RuntimeError: jaxlib/cusolver_kernels.cc:44: operation cusolverDnCreate(&handle) failed: cuSolver internal error`

Docker build works normally, but the above error occurs when run_docker.py is executed.

Here's my environment:
1. Ubuntu 18.04.01
2. Conda 3.9.2
3. Nvidia-driver-465
4. CUDA 11.3
5. cuDNN 8.2.1
6. Pytorch 1.9.0

and, I changed line 68 of the dockerfile because of jaxlib and jax version issues, 
(pip3 install ---upgrade jax jaxlib== 0.1.69
to
pip3 install ---upgrade jax jaxlib=>=0.1.69)

and also changed the cuda version of the dockerfile from 11.0 to 11.1.

Any help would be greatly appreciated.

**Comment by Augustin-Zidek** [comment]
Hi, sorry to hear that! Could you try with the newly released AlphaFold v2.1.2? We addressed some JAX/CUDA issues, so that might help with the issue you are seeing.

**Comment by chersiakingdom** [comment]
> Hi, sorry to hear that! Could you try with the newly released AlphaFold v2.1.2? We addressed some JAX/CUDA issues, so that might help with the issue you are seeing.

Thank you for answer.
I installed and ran the AlphaFold v2.1.2 you mentioned, the docker build works, but when I run run_docker.py I get the following error:
`
PermissionError: [Errno 13] Permission denied: '/mnt/output/T1050/msas/uniref90_hits.sto'
`
I tried the following to solve this, but all of them gave the same error.

1. It seems to be a problem that the folder does not have permission, so give permission using chmod command (failed)
2. To give permission to my account, I unmounted the /mnt folder, and created a subfolder and tried to mount it there (failed)

It's really frustrating that I keep trying to fix the error and it doesn't work.
In addition, there was an additional problem that the unmounted folder was not even remounted.
.........
please help me.. :'-(

**Comment by Augustin-Zidek** [comment]
It seems that AlphaFold doesn't have permissions to write to the output directory. Could you run:

```
chmod -R 777 /mnt/output/
```

and then try running AlphaFold again.

Alternative 1: Could you try specifying a subdirectory inside your home directory as the AlphaFold output directory? You should definitely have permissions to write into such directory.
Alternative 2: You could try running AlphaFold as root, i.e. with `docker_user=0`.

**Comment by chersiakingdom** [comment]
The cause of the error was not setting --output_dir! 
All errors have been fixed with the new Alphafold v2.1.2, and it works fine on my computer. 
Thanks so much for your advice.
