### ISSUE TITLE
Resource exhausted error

### ISSUE THREAD

**Issue by rdean064** [deepmind/alphafold#355]
Trying to fold a 2510 aa pentamer, I get the following errors and then the code exits:
 Allocator (GPU_0_bfc) ran out of memory trying to allocate 34.71GiB (rounded to 37274034432)requested by op
Execution of replica 0 failed: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 37274034352 bytes.

I am running it locally on a 64 GiB machine with 16 cpus and an nvidia Geforce RTX 2060. Any help would be appreciated.

**Comment by Augustin-Zidek** [comment]
Hi, the sequence you are trying to fold is probably too long for the GPU that you have. I recommend splitting the sequence in two overlapping halves (e.g. residues 1-1400 and 1110-2510), fold each separately and then manually assemble them back together. The other option is to run on a GPU that has more GPU RAM. Hope this helps, feel free to reopen this issue if not.

**Comment by dltacube** [comment]
> Hi, the sequence you are trying to fold is probably too long for the GPU that you have. I recommend splitting the sequence in two overlapping halves (e.g. residues 1-1400 and 1110-2510), fold each separately and then manually assemble them back together. The other option is to run on a GPU that has more GPU RAM. Hope this helps, feel free to reopen this issue if not.

I know this issue is old and closed but does that yield the same result as running it once without reassembly?
