### ISSUE TITLE
Non-docker support?

### ISSUE THREAD

**Issue by Toseph** [deepmind/alphafold#356]
Hello, I was looking to see if this program can be used with just a python venv or with singularity. 
The systems I am working on do not allow for docker/root exposure but there are requests to use alphafold in our environment. I am having trouble identifying any documentation that reveals a non-dockerized use of this software.

**Comment by Augustin-Zidek** [comment]
Hi, this is possible, it just requires more work to get things set up and we currently provide support only for running via Docker. Assuming your system has all the needed software and libraries, you can just run `run_alphafold.py`.

You can find more information about running under Singularity here: https://github.com/deepmind/alphafold/issues/10 and https://github.com/deepmind/alphafold/issues/24.
