### ISSUE TITLE
Editing model preset

### ISSUE THREAD

**Issue by amoltej** [deepmind/alphafold#357]
Hi this is referring back to issue #325 Thanks for reply there. 
Since I can not reopen that issue, I think my reply hasn't reached to you. Hence creating this thread.
So in order to edit model preset, I followed the steps described the user manual but still couldn't get it done. 
Answers to my following question would put some more light and bring clarity to how it can be achieved. 
    1) How to specify other preset model?
    2) How do I make sure it is in the database?
    3) What if the protein model is not in the original database because it has been recently published? how can I set and model_preset?
    4) How to specify the model in command, e.g. by default we specify it using "CASP14 (is it uniprot name or what?)"? To specify any other specific protein model, how do I find the identifier for that protein model in any specific database? is it from Uniprot database? or something else?
Hope I have reasonably clear to describe the issue. please let me know if you need any further information from my side
thanks
Amol

**Comment by andycowie** [comment]
Hi Amol,
The available model presets are described in https://github.com/deepmind/alphafold/blob/main/alphafold/model/config.py, however this only lists the models we have created for AlphaFold. Based on your questions I am not sure if this is the setting you need.

Based on your previous question (https://github.com/deepmind/alphafold/issues/325) CASP14 settings should be a good choice for you - insect proteins are part of the remit for that competition.

**Comment by andycowie** [comment]
Closing this issue for now, feel free to reopen if this is still a problem.
