### ISSUE TITLE
git clone an earlier version

### ISSUE THREAD

**Issue by ryao-mdanderson** [deepmind/alphafold#359]
Hello alphafold support, I wonder if there is a command that I can check out version 2.1.1, for example:
 $ git clone -b 2.1.1 https://github.com/deepmind/alphafold.git
Cloning into 'alphafold'...
fatal: Remote branch 2.1.1 not found in upstream origin
Unexpected end of command stream

I want to reproduce a result from 2.1.1; Thank you!

**Comment by Augustin-Zidek** [comment]
Hi, there is a small typo in your command -- the branch is called `v2.1.1` instead of `2.1.1`.

The correct command is:

```
git clone -b 'v2.1.1' https://github.com/deepmind/alphafold.git
```
