### ISSUE TITLE
Unknown runtime specified nvidia (docker 20)

### ISSUE THREAD

**Issue by aburger** [deepmind/alphafold#361]
hi there,

on fedora with docker version 20.10.12, build e91ed57  i get 

requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.41/containers/create
...
docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.41/containers/create: Bad Request ("Unknown runtime specified nvidia")

most comments i did find end with 2 solutions, one to install nvidia-dock2, which is a solution for older docker or set runtime to none, wht does not seem usefull, as one wants to use the gpu.

the comand is this:

```
$ python3 docker/run_docker.py --fasta_paths=/alpha2/Ami2638A.fasta --max_template_date=2020-05-14 --data_dir=/alpha2/
I0209 14:02:55.306046 139629798868800 run_docker.py:107] Mounting /alpha2 -> /mnt/fasta_path_0
I0209 14:02:55.306111 139629798868800 run_docker.py:107] Mounting /alpha2/uniref90 -> /mnt/uniref90_database_path
I0209 14:02:55.306147 139629798868800 run_docker.py:107] Mounting /alpha2/mgnify -> /mnt/mgnify_database_path
I0209 14:02:55.306176 139629798868800 run_docker.py:107] Mounting / -> /mnt/data_dir
I0209 14:02:55.306214 139629798868800 run_docker.py:107] Mounting /alpha2/pdb_mmcif -> /mnt/template_mmcif_dir
I0209 14:02:55.306245 139629798868800 run_docker.py:107] Mounting /alpha2/pdb_mmcif -> /mnt/obsolete_pdbs_path
I0209 14:02:55.306274 139629798868800 run_docker.py:107] Mounting /alpha2/pdb70 -> /mnt/pdb70_database_path
I0209 14:02:55.306309 139629798868800 run_docker.py:107] Mounting /alpha2/uniclust30/uniclust30_2018_08 -> /mnt/uniclust30_database_path
I0209 14:02:55.306342 139629798868800 run_docker.py:107] Mounting /alpha2/bfd -> /mnt/bfd_database_path
```

The mount of `/` instead of `/alpha2`  as `/mnt/data_dir` seems to be strange, but not related, right?

The connection from docker to the nvidia-driver seems to work in general:

```
$ docker run --gpus all nvidia/cuda:11.0-base nvidia-smi
Wed Feb  9 13:06:28 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
|  0%   33C    P8    N/A /  72W |     45MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1185      G                                      42MiB |
+-----------------------------------------------------------------------------+
```

what part do i miss?

best regards
andreas

**Comment by Augustin-Zidek** [comment]
Could you try running these two commands?

```
sudo systemctl daemon-reload
sudo systemctl restart docker
```

Have you also completed all steps in the [first time setup](https://github.com/deepmind/alphafold#first-time-setup)?

**Comment by aburger** [comment]
hi there,

i did this again, but that does not change the behaviour

as far as i can say i did all, yes

**Comment by aburger** [comment]
is there a version ready for docker newer than 19?  as runtime=nvidia seems to be for the old docker-serions with nvida-docker2, what is no longer needed, nor supported.  instead gpus=all should be used ..

**Comment by aburger** [comment]
and an update with new question:

by setting FLAGS.use_gpu  it goes further, but seems t have problems with the proxy, witch is set for docker and for git and works for both, but:
docker.errors.ImageNotFound: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=latest&fromImage=alphafold: Not Found ("pull access denied for alphafold, repository does not exist or may require 'docker login': denied: requested access to the resource is denied")

(and i suppose, gpus would not be used ...)

**Comment by aburger** [comment]
hi augustin,

this one still open.

i can run the solution by setting
 'use_gpu', False

instead of nvidia, as in docker newer than 19 the nvidia-docker is no longer needed.
i do not see, if the run is now with the ise or without the use of installed gpus

is the solution aware of the newer docker or leads this to cpu-only processing?

regards
andreas

**Comment by Augustin-Zidek** [comment]
Hi, sorry for the delay, we are investing compatibility with Docker 20. As a quick workaround I recommend using Docker 19 in the meanwhile if that is possible.

**Comment by aburger** [comment]
ciao augustin,

isnt it that from 19 on the gpu-support chanched?

on some installations this is possible, but i hope you will find a way soon, thanks.


regards
andreas
