### ISSUE TITLE
hhsearch problem, _cs219.ffdata, Could find neither hhm_db nor a3m_db!

### ISSUE THREAD

**Issue by bzdet99** [deepmind/alphafold#367]
Dear users, 
For some time I'm fighting with af2 and hhsearch. Let me define the problem:

1. ERROR
 hhsearch -i ./sylwia1.fasta -d /alpha2/xukui/alphafold/pdb70
- 09:56:43.878 INFO: Search results will be written to ./sylwia1.hhr
- 09:56:43.878 ERROR: Could find neither hhm_db nor a3m_db!

2. SUCCESS
hhsearch -i ./sylwia1.fasta -d /alpha2/xukui/alphafold/pdb70/pdb70
- 09:57:06.444 INFO: Search results will be written to ./sylwia1.hhr
- 09:57:06.533 INFO: ./sylwia1.fasta is in A2M, A3M or FASTA format

This is with the system hhsearch in version 3.2.

So I've decided to compile from the source version 3.3. (the same with conda)

1. ERROR
~/hh-suite/build/src/hhsearch -i ./sylwia1.fasta -d /alpha2/xukui/alphafold/pdb70/
- 10:00:39.455 INFO: Search results will be written to ./sylwia1.hhr
- 10:00:39.455 ERROR: In /home/lukasz/hh-suite/src/ffindexdatabase.cpp:11: FFindexDatabase:
- 10:00:39.455 ERROR:   could not open file '/alpha2/xukui/alphafold/pdb70/_cs219.ffdata'

2. SUCCESS
~/hh-suite/build/src/hhsearch -i ./sylwia1.fasta -d /alpha2/xukui/alphafold/pdb70/pdb70
- 10:02:30.372 INFO: Search results will be written to ./sylwia1.hhr
- 10:02:30.459 INFO: ./sylwia1.fasta is in A2M, A3M or FASTA format
- 10:02:30.463 INFO: Searching 80799 database HHMs without prefiltering

In the run_docker.py I have this:

```
# Path to the PDB70 database for use by HHsearch.
pdb70_database_path = os.path.join(FLAGS.data_dir, 'pdb70', 'pdb70')
```

[I've got the same errors running alphafold with docker after 10 min of computation]

So, the question is, what should I change in the docker file to make it work....

**Comment by Augustin-Zidek** [comment]
The path in `run_docker.py` is correct - it has to include not only the directory where the HHSearch database is, but also the common filename prefix shared by all of the 6 HHSearch database files. That is why we append the `pdb70` twice.

Is it possible you are getting slightly different error when running AlphaFold, i.e. the error when running AlphaFold is not caused by a wrong HHSearch database path?

**Comment by bzdet99** [comment]
I0215 13:06:02.384482 140153447797568 run_docker.py:247] - 12:06:02.376 ERROR: In /tmp/hh-suite/src/ffindexdatabase.cpp:11: FFindexDatabase:
I0215 13:06:02.384616 140153447797568 run_docker.py:247] 
I0215 13:06:02.384788 140153447797568 run_docker.py:247] - 12:06:02.376 ERROR:  could not open file '/mnt/pdb70_database_path/pdb70_cs219.ffdata'

permission problem, chmod a+r......
