### ISSUE TITLE
RuntimeError: Jackhmmer failed

### ISSUE THREAD

**Issue by Maiya19724** [deepmind/alphafold#368]
I0215 16:34:45.436311 139979926566720 run_docker.py:87] Mounting /home/fungi/fasta -> /mnt/fasta_path_0
I0215 16:34:45.436401 139979926566720 run_docker.py:87] Mounting /media/fungi/ssd2/uniref90 -> /mnt/uniref90_database_path
I0215 16:34:45.436440 139979926566720 run_docker.py:87] Mounting /media/fungi/ssd2/mgnify -> /mnt/mgnify_database_path
I0215 16:34:45.436476 139979926566720 run_docker.py:87] Mounting /media/fungi -> /mnt/data_dir
I0215 16:34:45.436514 139979926566720 run_docker.py:87] Mounting /media/fungi/ssd2/pdb_mmcif -> /mnt/template_mmcif_dir
I0215 16:34:45.436546 139979926566720 run_docker.py:87] Mounting /media/fungi/ssd2/pdb_mmcif -> /mnt/obsolete_pdbs_path
I0215 16:34:45.436580 139979926566720 run_docker.py:87] Mounting /media/fungi/ssd2/pdb70 -> /mnt/pdb70_database_path
I0215 16:34:45.436616 139979926566720 run_docker.py:87] Mounting /media/fungi/ssd2/uniclust30/uniclust30_2018_08 -> /mnt/uniclust30_database_path
I0215 16:34:45.436648 139979926566720 run_docker.py:87] Mounting /media/fungi/ssd1/bfd -> /mnt/bfd_database_path
I0215 16:34:49.093734 139979926566720 run_docker.py:222] I0215 08:34:49.093063 140012632056000 templates.py:857] Using precomputed obsolete pdbs /mnt/obsolete_pdbs_path/obsolete.dat.
I0215 16:34:49.313503 139979926566720 run_docker.py:222] I0215 08:34:49.312897 140012632056000 xla_bridge.py:248] Unable to initialize backend 'tpu_driver': NOT_FOUND: Unable to find driver in registry given worker:
I0215 16:34:50.146334 139979926566720 run_docker.py:222] I0215 08:34:50.145854 140012632056000 xla_bridge.py:248] Unable to initialize backend 'tpu': INVALID_ARGUMENT: TpuPlatform is not available.
I0215 16:34:53.612527 139979926566720 run_docker.py:222] I0215 08:34:53.611907 140012632056000 run_alphafold.py:385] Have 5 models: ['model_1', 'model_2', 'model_3', 'model_4', 'model_5']
I0215 16:34:53.612718 139979926566720 run_docker.py:222] I0215 08:34:53.612032 140012632056000 run_alphafold.py:397] Using random seed 491548932261010582 for the data pipeline
I0215 16:34:53.612806 139979926566720 run_docker.py:222] I0215 08:34:53.612170 140012632056000 run_alphafold.py:150] Predicting ABC
I0215 16:34:53.620984 139979926566720 run_docker.py:222] I0215 08:34:53.620578 140012632056000 jackhmmer.py:130] Launching subprocess "/usr/bin/jackhmmer -o /dev/null -A /tmp/tmps8v2axev/output.sto --noali --F1 0.0005 --F2 5e-05 --F3 5e-07 --incE 0.0001 -E 0.0001 --cpu 8 -N 1 /mnt/fasta_path_0/ABC.fasta /mnt/uniref90_database_path/uniref90.fasta"
I0215 16:34:53.674891 139979926566720 run_docker.py:222] I0215 08:34:53.674264 140012632056000 utils.py:36] Started Jackhmmer (uniref90.fasta) query
I0215 17:03:48.766989 139979926566720 run_docker.py:222] I0215 09:03:48.756095 140012632056000 utils.py:40] Finished Jackhmmer (uniref90.fasta) query in 1735.081 seconds
I0215 17:03:48.768690 139979926566720 run_docker.py:222] Traceback (most recent call last):
I0215 17:03:48.768762 139979926566720 run_docker.py:222] File "/app/alphafold/run_alphafold.py", line 427, in <module>
I0215 17:03:48.768816 139979926566720 run_docker.py:222] app.run(main)
I0215 17:03:48.768878 139979926566720 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 312, in run
I0215 17:03:48.768925 139979926566720 run_docker.py:222] _run_main(main, args)
I0215 17:03:48.768970 139979926566720 run_docker.py:222] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
I0215 17:03:48.769017 139979926566720 run_docker.py:222] sys.exit(main(argv))
I0215 17:03:48.769064 139979926566720 run_docker.py:222] File "/app/alphafold/run_alphafold.py", line 412, in main
I0215 17:03:48.769109 139979926566720 run_docker.py:222] is_prokaryote=is_prokaryote)
I0215 17:03:48.769153 139979926566720 run_docker.py:222] File "/app/alphafold/run_alphafold.py", line 164, in predict_structure
I0215 17:03:48.769197 139979926566720 run_docker.py:222] msa_output_dir=msa_output_dir)
I0215 17:03:48.769242 139979926566720 run_docker.py:222] File "/app/alphafold/alphafold/data/pipeline.py", line 161, in process
I0215 17:03:48.769286 139979926566720 run_docker.py:222] 'sto', self.use_precomputed_msas)
I0215 17:03:48.769331 139979926566720 run_docker.py:222] File "/app/alphafold/alphafold/data/pipeline.py", line 97, in run_msa_tool
I0215 17:03:48.769375 139979926566720 run_docker.py:222] result = msa_runner.query(input_fasta_path)[0]
I0215 17:03:48.769420 139979926566720 run_docker.py:222] File "/app/alphafold/alphafold/data/tools/jackhmmer.py", line 163, in query
I0215 17:03:48.769464 139979926566720 run_docker.py:222] return [self._query_chunk(input_fasta_path, self.database_path)]
I0215 17:03:48.769509 139979926566720 run_docker.py:222] File "/app/alphafold/alphafold/data/tools/jackhmmer.py", line 140, in _query_chunk
I0215 17:03:48.769554 139979926566720 run_docker.py:222] 'Jackhmmer failed\nstderr:\n%s\n' % stderr.decode('utf-8'))
I0215 17:03:48.769598 139979926566720 run_docker.py:222] RuntimeError: Jackhmmer failed
I0215 17:03:48.769642 139979926566720 run_docker.py:222] stderr:
I0215 17:03:48.769687 139979926566720 run_docker.py:222] 
I0215 17:03:48.769731 139979926566720 run_docker.py:222]

**Comment by Augustin-Zidek** [comment]
The stderr from Jackhmmer is empty which makes this tricky to debug. One possible explanation is that the resulting MSA is massive and you run out of space. Could that be the reason?

Alternatively, you can try to debug this by running the Jackhmmer command that AlphaFold runs in the background yourself and see if it produces any errors. Here is the command:

```
/usr/bin/jackhmmer -o /dev/null -A /tmp/tmps8v2axev/output.sto \
--noali --F1 0.0005 --F2 5e-05 --F3 5e-07 --incE 0.0001 -E 0.0001 \
--cpu 8 -N 1 /mnt/fasta_path_0/ABC.fasta /mnt/uniref90_database_path/uniref90.fasta
```

You will have to change the following three things in the command:
* the output path `-A /tmp/tmps8v2axev/output.sto` -> `-A /tmp/test_jh.sto`
* the input path `/mnt/fasta_path_0/ABC.fasta` -> `/home/fungi/fasta/ABC.fasta`
* the database path `/mnt/uniref90_database_path/uniref90.fasta` -> `/media/fungi/ssd2/uniref90/uniref90.fasta`

Make sure I got the input fasta and the db fasta paths correct based on the logs you posted :)

Could you try running this command and report the error it gives?

**Comment by Maiya19724** [comment]
Thank you for your help！ 
After running the command you provided, I got a 64gb output file with no error message during running. 
Now I will try to expand my space then run docker.py again.
I will submit it if there are any other problems. Thank you！

**Comment by Augustin-Zidek** [comment]
Glad to hear running it separately worked. I will close the issue now, but feel free to comment / re-open / open a new issue if running that query in AlphaFold doesn't work. 

If it still fails within AlphaFold, you can use the `use_precomputed_msas` flag (see https://github.com/deepmind/alphafold/blob/main/docker/run_docker.py#L82) to pass the MSA you generated in the manual Jackhmmer run to AlphaFold.
