### ISSUE TITLE
full_dbs setting requires no creative commons license only Apache?

### ISSUE THREAD

**Issue by effectsToCause** [deepmind/alphafold#37]
If running alphafold using the full_dbs setting does that mean only the apache license applies? Is it only the casp14 parameters that are covered under the creative commons license?

**Comment by Augustin-Zidek** [comment]
No, in all cases you use the AlphaFold parameters, no matter what database settings you use.

However, we have recently changed the license terms for the AlphaFold weights to CC BY 4.0, which permits commercial use.

**Comment by effectsToCause** [comment]
Great thanks!
