### ISSUE TITLE
ImportError: cannot import name 'protein' from 'alphafold.common' (unknown location)

### ISSUE THREAD

**Issue by aburger** [deepmind/alphafold#373]
hi there,

with some time investing in proxy-setup-problems, i was able to build the docker-part, there are some warnings, but at the end no errors and the output like this:

Successfully built d7c0d12e6ef3
Successfully tagged alphafold:latest

by running with a testfile i get an error from inside:

python3 docker/run_docker.py --fasta_paths=/alpha/Ami2638A.fasta --max_template_date=2020-05-14 --data_dir=/alpha2/
I0218 16:45:07.208508 139948052997952 run_docker.py:107] Mounting /alpha -> /mnt/fasta_path_0
I0218 16:45:07.208594 139948052997952 run_docker.py:107] Mounting /alpha2/uniref90 -> /mnt/uniref90_database_path
I0218 16:45:07.208647 139948052997952 run_docker.py:107] Mounting /alpha2/mgnify -> /mnt/mgnify_database_path
I0218 16:45:07.208686 139948052997952 run_docker.py:107] Mounting / -> /mnt/data_dir
I0218 16:45:07.208730 139948052997952 run_docker.py:107] Mounting /alpha2/pdb_mmcif -> /mnt/template_mmcif_dir
I0218 16:45:07.208762 139948052997952 run_docker.py:107] Mounting /alpha2/pdb_mmcif -> /mnt/obsolete_pdbs_path
I0218 16:45:07.208794 139948052997952 run_docker.py:107] Mounting /alpha2/pdb70 -> /mnt/pdb70_database_path
I0218 16:45:07.208827 139948052997952 run_docker.py:107] Mounting /alpha2/uniclust30/uniclust30_2018_08 -> /mnt/uniclust30_database_path
I0218 16:45:07.208871 139948052997952 run_docker.py:107] Mounting /alpha2/bfd -> /mnt/bfd_database_path
I0218 16:45:07.532549 139948052997952 run_docker.py:247] Traceback (most recent call last):
I0218 16:45:07.532670 139948052997952 run_docker.py:247] File "/app/alphafold/run_alphafold.py", line 29, in <module>
I0218 16:45:07.532715 139948052997952 run_docker.py:247] from alphafold.common import protein
I0218 16:45:07.532754 139948052997952 run_docker.py:247] ImportError: cannot import name 'protein' from 'alphafold.common' (unknown location)

a new git pull gives no newer files and the requirements are avilable.

any hints on this?

btw: is the mounte og / to /mnt/data_dir expected?

regards
andreas

**Comment by aburger** [comment]
no hints to this?

**Comment by Augustin-Zidek** [comment]
Could you take a look at https://github.com/deepmind/alphafold/issues/369 and try their solution?

**Comment by aburger** [comment]
ciao augustin,

sorry, i did fount the solution there and did a chmod, was fixed this issue.

the other still open, willupdate there.

this one can be marked as solved, thanks
andreas
