### ISSUE TITLE
Ranking Algorithm based on pLDDT and pTM scores

### ISSUE THREAD

**Issue by what-is-what** [deepmind/alphafold#386]
I have a question about the ranking pipeline, which is based on pLDDT scores.
However, is there any reason why this pipeline uses pLDDT scores on the monomer pipeline?
Because I thought that sorting pTM could be more suitable than the mean value of pLDDT because of its definition of TM-score.

**Comment by AnyaP** [comment]
Hi, we used the average pLDDT for scoring our original CASP14 submissions and thus we are sticking to this score for the monomer system. For multimers, we found using newer pTM-based scores beneficial, as we can also have a weight on the interfaces confidence. In practice, both scores provide model predicted confidence and can be used for scoring.
