### ISSUE TITLE
error when docker build stereo_chemical_props.txt' returned a non-zero code: 4 

### ISSUE THREAD

**Issue by liuqs1990** [deepmind/alphafold#393]
Hi 
I was building the latest version of AF2 2.2 and had the following error when building the docker image:

`
The command '/bin/bash -c wget -q -P /app/alphafold/alphafold/common/   https://git.scicore.unibas.ch/schwede/openstructure/-/raw/7102c63615b64735c4941278d92b554ec94415f8/modules/mol/alg/src/stereo_chemical_props.txt' returned a non-zero code: 4 
`

Could you have a look at that?
Thanks.

**Comment by liuqs1990** [comment]
> The `wget` error code 4 signals a network failure (see https://www.gnu.org/software/wget/manual/html_node/Exit-Status.html).
> 
> * Could you check you can access the URL from your browser: https://git.scicore.unibas.ch/schwede/openstructure/-/raw/7102c63615b64735c4941278d92b554ec94415f8/modules/mol/alg/src/stereo_chemical_props.txt?
> * Could you check you can `wget` the file on your machine?
> * Could you check you can `wget` the file inside the Docker container?
> 
> If you can't access the file from your browser or can't download it using `wget` from your machine, then it is unfortunately a network issue we can't unfortunately help with.


Thanks for the reply.
I am able to open that file on my browser and `wget` works fine in my WSL2.
As for the docker container, after the error, the container exited. Then I run `docker start <CONTAINER_ID>` and then `docker attach <CONTAINER_ID>` and then `wget --help` and I do see the manual for `wget`. So I assume the `wget` command also works inside the container?

However, I still couldn't docker build the image. I updated and restarted my Windows 11 with no luck.

I run:
`wget https://git.scicore.unibas.ch/schwede/openstructure/-/raw/7102c63615b64735c4941278d92b554ec94415f8/modules/mol/alg/src/stereo_chemical_props.txt`
works fine.

I run:
`
/bin/bash -c wget -q -P /app/alphafold/alphafold/common/ https://git.scicore.unibas.ch/schwede/openstructure/-/raw/7102c63615b64735c4941278d92b554ec94415f8/modules/mol/alg/src/stereo_chemical_props.txt
`
showed: 
`wget: missing URL`

I know the question is kind of dull but any suggestions on how to move forward would be great.

**Comment by Augustin-Zidek** [comment]
I see you are running AlphaFold in WSL2 -- I recommend running AlphaFold in Linux, if that is possible.

**Comment by liuqs1990** [comment]
> I see you are running AlphaFold in WSL2 -- I recommend running AlphaFold in Linux, if that is possible.

I cleaned the images and change the network and it's runs again. thank you for the reply anyway.

**Comment by Lili-irtyd** [comment]
> > I see you are running AlphaFold in WSL2 -- I recommend running AlphaFold in Linux, if that is possible.
> 
> I cleaned the images and change the network and it's runs again. thank you for the reply anyway.

Hello, I also meet the same problem, I want to know how to solve this, thanks for your help
