### ISSUE TITLE
FATAL Flags parsing error: flag --use_precomputed_msas=se_gpu_relax=True

### ISSUE THREAD

**Issue by SheeryLau** [deepmind/alphafold#395]
Hello, I follow the installation step from [https://github.com/amorehead/alphafold_non_docker](url) and install the non-docker version. 

However when I run the tool using code:
`bash run_alphafold.sh -d $databd -o OUTPUT_DIR -f test.fa -t 2020-05-14 -u True --use_gpu_relax=True`
It gives out error below:
`FATAL Flags parsing error: flag --use_precomputed_msas=se_gpu_relax=True: ('Non-boolean argument to boolean flag', 'se_gpu_relax=True')`

Also, if I run code:
`bash run_alphafold.sh -d $databd -o OUTPUT_DIR -f test.fa -t 2020-05-14 -u True`
It gives out error:
`FATAL Flags parsing error: flag --use_gpu_relax=None: Flag --use_gpu_relax must have a value other than None.`

I hope anyone can help me
Thank you!

**Comment by tfgg** [comment]
Hi,

The error looks like the two flags (use_precomputed_msas and use_gpu_relax) have been mashed together

run_alphafold.sh isn't a file in this repository. I recommend you file and issue or contact the owner of amorehead/alphafold_non_docker.

**Comment by SheeryLau** [comment]
Update about this problem:
The problem have been solve by changing run_alphafold.py.
`flags.DEFINE_boolean('use_gpu_relax', None, 'Whether to relax on GPU. '
                     'Relax on GPU can be much faster than CPU, so it is '
                     'recommended to enable if possible. GPUs must be available'
                     ' if this setting is enabled.')`
Change the None to True, but not try to change it on command line, then the problem could solve.
Thanks for your kind help!

**Comment by liuqs1990** [comment]
> Update about this problem: The problem have been solve by changing run_alphafold.py. `flags.DEFINE_boolean('use_gpu_relax', None, 'Whether to relax on GPU. ' 'Relax on GPU can be much faster than CPU, so it is ' 'recommended to enable if possible. GPUs must be available' ' if this setting is enabled.')` Change the None to True, but not try to change it on command line, then the problem could solve. Thanks for your kind help!

hi SheeryLau,
Could you please put your full code that was working and paste it here?
I am also using the non-docker version and I have similar issue and still not working..
thanks.
