### ISSUE TITLE
Error downloading PDB mmCIF 

### ISSUE THREAD

**Issue by shlomita** [deepmind/alphafold#40]
[](url)
When I run the scripts/download_all_data.sh to download the databases I get the error:

> Downloading PDB mmCIF files...
> Running rsync to fetch all mmCIF files (note that the rsync progress estimate might be inaccurate)...
> rsync: failed to connect to rsync.rcsb.org (132.249.210.234): Connection timed out (110)
> rsync error: error in socket IO (code 10) at clientserver.c(125) [Receiver=3.1.2]

**Comment by gabrielctn** [comment]
Same issue here ! Maybe servers are overloaded ?

**Comment by SSchott** [comment]
You are probably in a network where FTP is blocked. Check with your IT dep.

**Comment by reiverjohn** [comment]
I believe the URL has changed.  I see http and ftp but the rsync option doesn't seem to be available.

**Comment by DininduSenanayake** [comment]
I ran the same script (ran from a GPFS ) which worked fine but mmCIF took about 5.5 days. Going from 98-100% tool nearly 4 days

**Comment by YaoYinYing** [comment]
got the same problem. any available mirrors?

**Comment by YaoYinYing** [comment]
alright i think this may work:
use ftp client to the link:
`ftp://rsync.rcsb.org/pub/pdb/data/structures/divided/`
clone the subfolder `mmCIF` to the exactly same dir used by the download script.
just remember comment the rsync line



> I believe the URL has changed. I see http and ftp but the rsync option doesn't seem to be available.

**Comment by shlomita** [comment]
Solved - It was Firewall problem. port opened and I was able to download the database

**Comment by ctmckee** [comment]
Any updates on speeding up this download.  Currently downloading at 300kB/s.  Taking a very long time?

**Comment by YaoYinYing** [comment]
> Any updates on speeding up this download. Currently downloading at 300kB/s. Taking a very long time?

Use PDBj archive instead.
`rsync --recursive --links --perms --times --compress --info=progress2 --delete data.pdbj.org::ftp_data/structures/divided/mmCIF/ "${RAW_DIR}"`

**Comment by tomlue** [comment]
> Use PDBj archive instead. `rsync --recursive --links --perms --times --compress --info=progress2 --delete data.pdbj.org::ftp_data/structures/divided/mmCIF/ "${RAW_DIR}"`

This gives me 
```
> rsync --recursive --links --perms --times --compress --info=progress2 --delete \
  data.pdbj.org::ftp_data ./download 
@ERROR: Unknown module 'ftp_data'
rsync error: error starting client-server protocol (code 5) at main.c(1666) [Receiver=3.1.2] 
```

But the `pdbjsnap.protein.osaka-u.ac.jp` snapshots server was much faster for me than the `snapshotrsync.rcsb.org` server (for downloading snapshots obviously)

**Comment by YaoYinYing** [comment]
Well i believe the downloading speed depends on multiple factors like where server locates, the bandwidth and the maximum number of occurrences. Also some anonymous mirrors may work better then the officials. 

for self-hosted PDB mmcif weekly mirror against the official, you may check out this script[this link](https://github.com/YaoYinYing/alphafold/blob/main/scripts/setup_self_hosted_pdb-mmcif_mirror.sh). Although it has not been seriously tested from top to bottom, the workflow works very well and may help.
