### ISSUE TITLE
CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered

### ISSUE THREAD

**Issue by JuhoChoi17** [deepmind/alphafold#406]
Hi, I'm a beginning user of AlphaFold2. I have a question.
When I run the AlphaFold2 to predict the 3D structure of 1442 amino acid protein, there is something problem.
My system is..
OS: Ubuntu 20.04.4 LTS
CPU: Intel Core i9-9900K 3.60 GHz x 16
GPU: NVIDIA RTX 3060 12 GB
Driver version: 510.54
CUDA version: 11.6
RAM: 32 GB
SSD: 4.5 TB 

Error code as followed
I0322 05:41:47.767822 140571547043648 run_docker.py:222] 2022-03-21 20:41:47.403578: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_event.cc:29] Error polling for event status: failed to query event: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
I0322 05:41:47.767898 140571547043648 run_docker.py:222] 2022-03-21 20:41:47.403587: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:699] could not allocate CUDA stream for context 0x55f29504cc50: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
I0322 05:41:47.767974 140571547043648 run_docker.py:222] 2022-03-21 20:41:47.403595: E external/org_tensorflow/tensorflow/stream_executor/stream.cc:310] failed to allocate stream during initialization
I0322 05:41:47.768085 140571547043648 run_docker.py:222] 2022-03-21 20:41:47.403604: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:699] could not allocate CUDA stream for context 0x55f29504cc50: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
I0322 05:41:47.768164 140571547043648 run_docker.py:222] 2022-03-21 20:41:47.403612: E external/org_tensorflow/tensorflow/stream_executor/stream.cc:310] failed to allocate stream during initialization
I0322 05:41:47.768241 140571547043648 run_docker.py:222] 2022-03-21 20:41:47.403623: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:618] unable to add host callback: CUDA_ERROR_INVALID_HANDLE: invalid resource handle
I0322 05:41:47.768317 140571547043648 run_docker.py:222] 2022-03-21 20:41:47.526868: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:1047] could not synchronize on CUDA context: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered :: *** Begin stack trace ***
I0322 05:41:47.768393 140571547043648 run_docker.py:222] 
I0322 05:41:47.768469 140571547043648 run_docker.py:222] 
I0322 05:41:47.768544 140571547043648 run_docker.py:222] 
I0322 05:41:47.768619 140571547043648 run_docker.py:222] 
I0322 05:41:47.768692 140571547043648 run_docker.py:222] 
I0322 05:41:47.768767 140571547043648 run_docker.py:222] 
I0322 05:41:47.768841 140571547043648 run_docker.py:222] 
I0322 05:41:47.768916 140571547043648 run_docker.py:222] 
I0322 05:41:47.768991 140571547043648 run_docker.py:222] 
I0322 05:41:47.769066 140571547043648 run_docker.py:222] 
I0322 05:41:47.769140 140571547043648 run_docker.py:222] 
I0322 05:41:47.769215 140571547043648 run_docker.py:222] 
I0322 05:41:47.769290 140571547043648 run_docker.py:222] 
I0322 05:41:47.769368 140571547043648 run_docker.py:222] 
I0322 05:41:47.769445 140571547043648 run_docker.py:222] 
I0322 05:41:47.769521 140571547043648 run_docker.py:222] 
I0322 05:41:47.769597 140571547043648 run_docker.py:222] 
I0322 05:41:47.769673 140571547043648 run_docker.py:222] 
I0322 05:41:47.769747 140571547043648 run_docker.py:222] 
I0322 05:41:47.769822 140571547043648 run_docker.py:222] 
I0322 05:41:47.769898 140571547043648 run_docker.py:222] 
I0322 05:41:47.769973 140571547043648 run_docker.py:222] 
I0322 05:41:47.770048 140571547043648 run_docker.py:222] PyDict_SetItem
I0322 05:41:47.770124 140571547043648 run_docker.py:222] _PyModule_ClearDict
I0322 05:41:47.770200 140571547043648 run_docker.py:222] PyImport_Cleanup
I0322 05:41:47.770274 140571547043648 run_docker.py:222] Py_FinalizeEx
I0322 05:41:47.770350 140571547043648 run_docker.py:222] 
I0322 05:41:47.770431 140571547043648 run_docker.py:222] _Py_UnixMain
I0322 05:41:47.770508 140571547043648 run_docker.py:222] __libc_start_main
I0322 05:41:47.770583 140571547043648 run_docker.py:222] 
I0322 05:41:47.770658 140571547043648 run_docker.py:222] *** End stack trace ***
I0322 05:41:47.770735 140571547043648 run_docker.py:222] 
I0322 05:41:47.770811 140571547043648 run_docker.py:222] 2022-03-21 20:41:47.526954: F external/org_tensorflow/tensorflow/compiler/xla/service/gpu/gpu_executable.cc:141] Check failed: pair.first->SynchronizeAllActivity()
I0322 05:41:47.770888 140571547043648 run_docker.py:222] Fatal Python error: Aborted
I0322 05:41:47.770964 140571547043648 run_docker.py:222] 
I0322 05:41:47.771039 140571547043648 run_docker.py:222] Current thread 0x00007fcb45a97740 (most recent call first):
I0322 05:41:48.407148 140571547043648 run_docker.py:222] /app/run_alphafold.sh: line 3:     8 Aborted                 (core dumped) python /app/alphafold/run_alphafold.py "$@"

Please give me any advice on how to fix this error.
Thank you.

**Comment by Augustin-Zidek** [comment]
Are you using the latest AlphaFold version (v2.2.0)?

Also, could you try running 

```bash
unset TF_FORCE_UNIFIED_MEMORY
```

before running AlphaFold to disable using unified memory?

More information possibly in https://github.com/deepmind/alphafold/issues/140 and in https://github.com/deepmind/alphafold/issues/20.

**Comment by JuhoChoi17** [comment]
> Are you using the latest AlphaFold version (v2.2.0)?
> A. Yes, I am using the latest AlphaFold version.
> Also, could you try running unset TF_FORCE_UNIFIED_MEMORY before running AlphaFold to disable using unified memory?
>A. Let me teach how to unset TF_FORCE_UNIFIED_MEMORY. Is there any command to unset TF_FORCE_UNIFIED_MEMORY ?
Thank you for your kind reply.

**Comment by Augustin-Zidek** [comment]
Try running `unset TF_FORCE_UNIFIED_MEMORY` in your Linux command line.

**Comment by chenshixinnb** [comment]
> Try running `unset TF_FORCE_UNIFIED_MEMORY` in your Linux command line.

How do I set this variable when I'm running docker ,thanks

**Comment by chenshixinnb** [comment]
This is also version 2.2.0,
320AA

**Comment by z4f1r0v** [comment]
For what is worth, @Augustin-Zidek 's suggestion helped me execute AlphaFold successfully after struggling to get through the same error as highlighted in this issue. 

For reference, I am running the latest version (2.2.0) on an Azure Machine Learning `Standard_NC12` instance. This entails:
```
Virtual machine size: Standard_NC12 (12 cores, 112 GB RAM, 680 GB disk)
Processing unit:      GPU - 2 x NVIDIA Tesla K80
```

@chenshixinnb if you are running AlphaFold's docker implementation, you can go to [this line](https://github.com/deepmind/alphafold/blob/main/docker/run_docker.py#L246) and set the value to `0`.

**Comment by Augustin-Zidek** [comment]
Closing this issue now as there is a workaround.
