### ISSUE TITLE
Flags parsing error

### ISSUE THREAD

**Issue by cparsania** [deepmind/alphafold#407]
I am trying to do test run for just installed Alphafold.  However, stuck with the below error message ?

```
FATAL Flags parsing error:
  flag --output_dir=None: Flag --output_dir must have a value other than None.
  flag --uniref90_database_path=None: Flag --uniref90_database_path must have a value other than None.
  flag --mgnify_database_path=None: Flag --mgnify_database_path must have a value other than None.
  flag --template_mmcif_dir=None: Flag --template_mmcif_dir must have a value other than None.
  flag --obsolete_pdbs_path=None: Flag --obsolete_pdbs_path must have a value other than None.

```

below is the command I submitted through a job submission file. 

```
module load python/3.7.7 cuda/10.2.89 gcc/7.4.0
source ~/alphafold-env/bin/activate 
cd <path/to/alphafold/install/dir>



python run_alphafold.py \
--fasta_paths=/scratch/intronret/chiragp/2_programs/1_AlphaFold2/test_run/T1050.fa \
--max_template_date=2020-05-14 \
--model_preset=monomer \
--db_preset=reduced_dbs \
--data_dir=<path/to/database/dir>

```
database dir contains below databases. 

```
params
small_bfd
pdb70
mgnify
uniclust30
uniref90
uniprot
pdb_seqres
pdb_mmcif

```
Any help will be appreciated.

**Comment by Augustin-Zidek** [comment]
I strongly recommend running AlphaFold using the way described in the readme, i.e. using `docker/run_docker.py` which will set a lot of things up for you, including many of the flags you are missing.

As for your problem, AlphaFold is complaining that some of the flags that must be set are not being set, you must run the `run_alphafold` script with all of the 5 flags set.
