### ISSUE TITLE
Continue model prediction of multiple targets after failure of one

### ISSUE THREAD

**Issue by ctueting** [deepmind/alphafold#408]
Dear deepmind devs,

I have a suggestion for updating your code.

I run alphafold locally, to predict multiple multimeric assemblies, by executing it with multiple fasta files. Unfortunately, one of the assemblies was obviously too large and exhausted the available GPU memory, and eventually failed. 

It would be good in this case, if not the entire code stops, but AlphaFold just continues with the next fasta, as I don't check the server that often to directly restart the remaining sequences.

To overcome my issue, I can write a shell script, to execute alphafold with a single fasta each to overcome this issue, but it would be handier, to have this implemented in alphafold directly. It felt like running multiple fastas might be advantageous, as the databases, etc. are already mounted. 

Best
Christian

**Comment by AnyaP** [comment]
Hi Christian,

Sorry for a slow reply. I agree this would be a useful inference feature, but as far as I know this is not something we can currently work on. I think sticking to the orchestration through the shell scripts as you suggest, or adding this feature to a fork of the repository could be the ways to go.

Thanks,
Anna
