### ISSUE TITLE
downloading database runs into stall at pdb_mmcif. the script does not work either with 

### ISSUE THREAD

**Issue by as7a5** [deepmind/alphafold#411]
the script does not work either with the default or alternative mirror.

**Comment by as7a5** [comment]
It times out on rsync

**Comment by KayDiederichs** [comment]
I've seen this happening but usually the rsync server (at EBI) returned after some time.

**Comment by Augustin-Zidek** [comment]
Have you tried any of the alternative servers as suggested by the script?

```
If the download speed is too slow, try changing the mirror to:
  * rsync.ebi.ac.uk::pub/databases/pdb/data/structures/divided/mmCIF/ (Europe)
  * ftp.pdbj.org::ftp_data/structures/divided/mmCIF/ (Asia)
or see https://www.wwpdb.org/ftp/pdb-ftp-sites for more download options.
```

**Comment by Augustin-Zidek** [comment]
Closing this now as this is unfortunately outside our control. I hope some of the alternative mirrors would work.

**Comment by alirizaaribas-ibg** [comment]
We have the same problem. How can we manage it?

**Comment by as7a5** [comment]
We use another server. There is a firewall block I believe.

**Comment by RJ3** [comment]
> We use another server. There is a firewall block I believe.

Can you recommend a server or protocol that works? rsync is blocked by my institution proxy.
