### ISSUE TITLE
Does this software support concurrent multitasking

### ISSUE THREAD

**Issue by chenqp-git** [deepmind/alphafold#415]
Does this software support concurrent multitasking？

**Comment by Augustin-Zidek** [comment]
You can run multiple AlphaFold instances at the same time, but keep in mind that some parts of AlphaFold are rather IO/CPU/GPU intensive, so you will need a fast multi-CPU and multi-GPU machine to do that.

**Comment by chenqp-git** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
