### ISSUE TITLE
Is there a way to modulate / check template PDB used for modeling ?

### ISSUE THREAD

**Issue by jongseo-park** [deepmind/alphafold#416]
Hi,

I have two questions.

### 1

When I want to run the alphafold modeling without using template,

I set the argument `max_template_date` to `1900-01-01`.

However, when I check the `pdb_hits.sto` file in the `msas` directory, there is several results for pdb searches.

I want to know whether the set of `max_template_date` to `1900-01-01` is a right way to avoid using template during modeling

<br>
<br>

### 2

I want to check the template PDB ID used for modeling.

Is there any log file (or something else) about it ?

Thanks.

**Comment by AnyaP** [comment]
1. Yes, setting the `max_template_date` to a date in the past such as 1000-01-01 is sufficient to exclude templates from the modeling (we search first, then do the filtering, so `pdb_hits.sto` is expected to be populated in any case). 
2. Apart from `pdb_hits.sto`, you could also check `features.pkl` - this is the dump of the features passed to the model from the data stage.

**Comment by AlexB05** [comment]
> 1. Yes, setting the `max_template_date` to a date in the past such as 1000-01-01 is sufficient to exclude templates from the modeling (we search first, then do the filtering, so `pdb_hits.sto` is expected to be populated in any case).
> 2. Apart from `pdb_hits.sto`, you could also check `features.pkl` - this is the dump of the features passed to the model from the data stage.
@AnyaP Is there any chance you might also know the answer to this one? #438

**Comment by Aroids** [comment]
Anya, Would you mind expanding on which key in features.pkl provides the PDB IDs of the post-filtered templates used for modelling? 

I went through the key-value pairs in my features.pkl file output by Alphafold 2.3.1 (multimer) and can't seem to find it.

Potentially related: [Issue#625 (2022-11)](https://github.com/deepmind/alphafold/issues/625) mentions that the key 'template_domain_names' is found within features.pkl when --model_preset=monomer but not when --model_preset=multimer.
