### ISSUE TITLE
peptide-protein structure prediction-one protein,  numerous peptides

### ISSUE THREAD

**Issue by tamaransbacher** [deepmind/alphafold#419]
Hi 
I  have a few peptides that bind to the same protein, and I would like to predict each protein-peptide structure. 
Is it possible to use a solved protein structure (pdb or a previous alphaafold calculation ) and only predict the peptide structure and its relative  position to the protein? 
if so - what flags should I use when running alphafold locally (docker script) ?
 Thanks 
Tamar

**Comment by AnyaP** [comment]
Hi Tamar,

There is no such mode of prediction available.

You could try hacking the system by supplying the solved structure as a template (if it is not present in the templates database already), but this won't save any computation (coordinates for both the protein and the peptide will be produced).

In general, AlphaFold provides better predictions when given as much context as possible, so I would recommend running protein+peptide through the system each time.
