### ISSUE TITLE
how to get databases without aria2?

### ISSUE THREAD

**Issue by ctmckee** [deepmind/alphafold#42]
I cannot get aria2 to install (sudo yum install aria2).  Is there a way to get the databases without aria2?

**Comment by SSchott** [comment]
You can just mod the provided scripts and use wget. Though figuring out an alternate repository would be probably easier depending on your distro.

**Comment by ctmckee** [comment]
Thanks.

**Comment by gaorongchao** [comment]
Read the download file in script and get the url, then you can download by ftp

**Comment by ctmckee** [comment]
Still trying to get through the database downloads.  Current issue is:  rsync: --info=progress2: unknown option

**Comment by ctmckee** [comment]
Switching platform to Ubuntu appears to solve all issues (no modification necessary to scripts) and download is proceeding correctly.
