### ISSUE TITLE
About representations of alphafold2

### ISSUE THREAD

**Issue by ParkSJ-91** [deepmind/alphafold#420]
Hi ! 

In the paper, I got interested in its evolutionary and structural representations (msa and pair representations, respectively) to predict highly accurate structure of each proteins. 

If representations can be obtained, it can be applied to many studies.

Is it possible to get information about representations ? 

Thanks,
Seokju.

**Comment by AnyaP** [comment]
Hi Seokju,

Yes indeed, the representations can be requested from AlphaFold with ```return_representations=True```:
https://github.com/deepmind/alphafold/blob/b85ffe10799ca08cc62146f1dabb4e4ee6c0a580/alphafold/model/modules.py#L287 

You'd need to set this argument to True in the model runner [here](https://github.com/deepmind/alphafold/blob/b85ffe10799ca08cc62146f1dabb4e4ee6c0a580/alphafold/model/model.py#L77) or [here](https://github.com/deepmind/alphafold/blob/b85ffe10799ca08cc62146f1dabb4e4ee6c0a580/alphafold/model/model.py#L83) depending on whether you are using Monomer or Multitmer system.

You should then expect to have the representations returned (among other things) from the model predict call in cell 5 of the AlphaFold Colab (or in a similar place of the non-Colab workflow):
```
model_runner.predict(processed_feature_dict, random_seed=random.randrange(sys.maxsize))
```
Thanks,
Anna

**Comment by AnyaP** [comment]
Closing this issue for now, feel free to reopen if this is still a problem.

**Comment by cirdeCyL** [comment]
Hi.

in the case of AF-multimer, I am confused what the reprsentations mean.
For example the single representation in the monomer system is quite clear with it being of dimension (r,384). r being the number of residue.
I was getting the representationusing AF-multimer and the dimension is (rhat,384), where rhat is in between the two chains of my heterodimer.
Can you please elaborate on the representation the multimer System returns?

Thanks,
Cedric
