### ISSUE TITLE
tensorflow ERROR while NVIDIA Container Toolkit is working properly

### ISSUE THREAD

**Issue by genomicsgroup** [deepmind/alphafold#423]
I0407 10:26:52.695398 139753170155328 run_docker.py:113] Mounting /data/ppi/A100 -> /mnt/fasta_path_0
I0407 10:26:52.695593 139753170155328 run_docker.py:113] Mounting /data/alphafold/uniref90 -> /mnt/uniref90_database_path
I0407 10:26:52.695678 139753170155328 run_docker.py:113] Mounting /data/alphafold/mgnify -> /mnt/mgnify_database_path
I0407 10:26:52.695742 139753170155328 run_docker.py:113] Mounting /data/alphafold -> /mnt/data_dir
I0407 10:26:52.695805 139753170155328 run_docker.py:113] Mounting /data/alphafold/pdb_mmcif/mmcif_files -> /mnt/template_mmcif_dir
I0407 10:26:52.695875 139753170155328 run_docker.py:113] Mounting /data/alphafold/pdb_mmcif -> /mnt/obsolete_pdbs_path
I0407 10:26:52.695946 139753170155328 run_docker.py:113] Mounting /data/alphafold/uniprot -> /mnt/uniprot_database_path
I0407 10:26:52.696016 139753170155328 run_docker.py:113] Mounting /data/alphafold/pdb_seqres -> /mnt/pdb_seqres_database_path
I0407 10:26:52.696091 139753170155328 run_docker.py:113] Mounting /data/alphafold/uniclust30/uniclust30_2018_08 -> /mnt/uniclust30_database_path
I0407 10:26:52.696166 139753170155328 run_docker.py:113] Mounting /data/alphafold/bfd -> /mnt/bfd_database_path
I0407 10:26:55.747741 139753170155328 run_docker.py:255] I0407 02:26:55.746643 140317005801280 templates.py:857] Using precomputed obsolete pdbs /mnt/obsolete_pdbs_path/obsolete.dat.
I0407 10:26:56.017539 139753170155328 run_docker.py:255] I0407 02:26:56.016888 140317005801280 tpu_client.py:54] Starting the local TPU driver.
I0407 10:26:56.017780 139753170155328 run_docker.py:255] I0407 02:26:56.017272 140317005801280 xla_bridge.py:212] Unable to initialize backend 'tpu_driver': Not found: Unable to find driver in registry given worker: local://
I0407 10:26:56.018094 139753170155328 run_docker.py:255] 2022-04-07 02:26:56.017712: W external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
I0407 10:26:56.018174 139753170155328 run_docker.py:255] 2022-04-07 02:26:56.017761: W external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
I0407 10:26:56.018241 139753170155328 run_docker.py:255] I0407 02:26:56.017858 140317005801280 xla_bridge.py:212] Unable to initialize backend 'gpu': Failed precondition: No visible GPU devices.
I0407 10:26:56.018314 139753170155328 run_docker.py:255] I0407 02:26:56.017982 140317005801280 xla_bridge.py:212] Unable to initialize backend 'tpu': Invalid argument: TpuPlatform is not available.
I0407 10:26:56.018646 139753170155328 run_docker.py:255] W0407 02:26:56.018047 140317005801280 xla_bridge.py:215] No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)

**Comment by Augustin-Zidek** [comment]
Hi, the NVIDIA CUDA Toolkit may sometimes appear to be set up correctly but some CUDA libraries may still fail to load. Just to rule out that this is happening, could you please test whether you accelerator is available? For example, run `tf.config.list_physical_devices()` to see if your GPU/TPU is visible to your host runtime.

**Comment by Augustin-Zidek** [comment]
Closing this issue now, feel free to open a new one if this is still a problem.
