### ISSUE TITLE
How reliable is Alphafold2 for folding random-coil peptide

### ISSUE THREAD

**Issue by gundalav** [deepmind/alphafold#424]
I have a peptide X of length 50aa. Alphafold2 predicted the structure which takes a helix form and with high average  pLDDT score (>90).

But during actual experiment (e.g. crystallography, spectroscopy), peptide X is determined to have a *[random coil][1]* structure.

My question is how can I resolve the difference between AF2 prediction and crystallography?
To what extend we can use AF2 peptide structure prediction for downstream analysis (e.g. docking, etc)?

  [1]: https://en.wikipedia.org/wiki/Random_coil

**Comment by AnyaP** [comment]
Hi gundalav,

For a short peptide I'd be hesitant to rely only on the AlphaFold prediction, even if its pLDDT is high. Firstly, it's not a structured domain, which makes this a less typical use case for the model. Secondly, AlphaFold is making this prediction in isolation, without any biological context. In specific environments / in complex with a binding partner the peptide might adopt a different conformation.

Hope that helps,

**Comment by gundalav** [comment]
> Hi gundalav,
> 
> For a short peptide I'd be hesitant to rely only on the AlphaFold prediction, even if its pLDDT is high. Firstly, it's not a structured domain, which makes this a less typical use case for the model. Secondly, AlphaFold is making this prediction in isolation, without any biological context. In specific environments / in complex with a binding partner the peptide might adopt a different conformation.
> 
> Hope that helps,

Hi Anya, 

Thanks. Then what approach do you suggest for short peptide?

G.V.

**Comment by okovalevskiy** [comment]
Hi @gundalav, sorry for late reply. As Anna has mentioned before, AlphaFold can make mistakes for short peptides. You can use a trick and make a chimeric construct - add sequence of your peptide to the C- or N- terminus of a sequence of some normal-sized protein. Try to fold such chimeric construct with AlphaFold and see what's happened with the structure of your peptide. However, I suggest to take results of the modelling with caution and trust experimental data more.
