### ISSUE TITLE
Is it possible to change the number of models produced per run?

### ISSUE THREAD

**Issue by SheeryLau** [deepmind/alphafold#430]
In the source code, each run plan to produce 5 models. Here I plan to produce a large number of protein models, so in order to save time, I want to reduce the number of models produced per run to 2.
In some online versions, this could be achieved by changing the parameter "num_models". But I found that this value in the source code here is related to "model_runners" and ultimately relates to "class RunModel".
I'm not sure if reducing the number will affect the accuracy of the predictions, but I'd like to try it first. I hope anyone can give some suggestions for changing the code.
And thanks for your kind help!

**Comment by Augustin-Zidek** [comment]
You can do that by modifying https://github.com/deepmind/alphafold/blob/main/alphafold/model/config.py#L39 and removing some models from the preset you would like to run with.
