### ISSUE TITLE
Batch processing multiple sequences in alphafold colab?

### ISSUE THREAD

**Issue by CameronWeller** [deepmind/alphafold#431]
Hi I have a class that I am trying to fold a bunch of protein fragments for, as part of a larger research project. I would be really nice if there was some way to batch process a list of sequences. Any advice on how to do this from the alphafold colab notebook ?

**Comment by Augustin-Zidek** [comment]
I recommend using local installation of AlphaFold for that, using AlphaFold Colab for batch processing is rather inefficient as it has to stream the whole database for each protein.

**Comment by denizkavi** [comment]
It's possible to do this through the [Tamarind Bio](https://www.tamarind.bio/app) website if you don't want to deal with setting up the local installation of AlphaFold or ColabFold.

There also this Colab notebook: https://colab.research.google.com/github/sokrypton/ColabFold/blob/main/batch/AlphaFold2_batch.ipynb, although it has the same time and GPU limitations as the previous Colab.

**Comment by beyzoskaya** [comment]
I uploaded my files in notebook you shared but all the files elapsed, how can I solve that for processing several sequences with automation instead of changing query_sequence with hand one by one in original ColabFold notebookl?
