### ISSUE TITLE
Should I regularly update my locally downloaded databases?

### ISSUE THREAD

**Issue by albasaezmat** [deepmind/alphafold#443]
This is probably a very stupid question but I need an answer.

Databases are growing exponentially, even the ones AlphaFold uses. If I work locally with the software, the databases are not updated since the day I downloaded AlphaFold. Should I update them manually, right?

**Comment by Augustin-Zidek** [comment]
Yes, we recommend updating MSA databases once in a while, especially if you know sequences similar to your query have been added. We did this recently in the v2.3.0 update and hardcoded new versions in the database download scripts.
