### ISSUE TITLE
Download Charts after fold?

### ISSUE THREAD

**Issue by alanclayrichard** [deepmind/alphafold#444]
Hello! Is there a way to download the charts containing predicted LDDT and predicted aligned error and such after the protein has been folded? I would like to have them as .png or .pdf or something similar.

**Comment by dm-kuba** [comment]
Hi, @alanclayrichard, thank you for the question. You can refer to the [AlphaFold notebook](https://github.com/deepmind/alphafold/blob/a3941673e90b8d1d75c60b16a4b3707ebf7ba527/notebooks/AlphaFold.ipynb) to see example code for plotting the PAE and pLDDT. You can add your code to save the plot image in there, or use the notebook as a reference for your own code. The function for saving a plot as image is: `plt.savefig('filename.png')`.

I'll close this issue, feel free to reopen this issue or open a new issue if this is still a problem.
