### ISSUE TITLE
version mismatch in setup.py

### ISSUE THREAD

**Issue by cmeesters** [deepmind/alphafold#447]
Hi,

the current `setup.py` in the master branch shows `version='2.1.0'`. The version indicator in the v2.2.0 release is '2.1.0', too.

Best regards,
Christian Meesters

**Comment by cmeesters** [comment]
(I could change that and make a PR, but I do not feel confident enough to tinker with your version strings)

**Comment by cmeesters** [comment]
PS

`alphafold cm$ git describe --tags --abbrev=0
v2.2.0

**Comment by Augustin-Zidek** [comment]
Thanks, nice catch. Fixed in https://github.com/deepmind/alphafold/commit/197bd19ee371ebac1942951b49a01848d2c9c6fc.
