### ISSUE TITLE
Visualization PDB

### ISSUE THREAD

**Issue by Lsz-20** [deepmind/alphafold#452]
Thanks for the software I got the files shown in README after I finished running but when I tried to visualize the PDB using D the following error statement appears.
`
~/apps/DaliLite.v5/bin/dali.pl --cd1 1989A --dat1 DAT/ --cd2 3916A --dat2 DAT/
# sub wolf(WOLF, DaliLite.v5/bin/serialcompare,DAT/,DAT/,0)
wolf: DaliLite.v5/bin/serialcompare DAT/ DAT/ WOLF > /dev/null ; 
cat fort.1[0-9][0-9] > wolf_output ; rm fort.1[0-9][0-9] ; 
DaliLite.v5/bin/serialcompare DAT/ DAT/ DP < wolf_output > /dev/null ; cat fort.1[0-9][0-9] | perl DaliLite.v5/bin/dccp2dalicon.pl > dalicon_input ; 
rm -f fort.1[0-9][0-9] 
cat: fort.1[0-9][0-9]: No such file or directory
rm: cannot remove `fort.1[0-9][0-9]': No such file or directory
cat: fort.1[0-9][0-9]: No such file or directory
# sub dalicon(dalicon_input,T,
DaliLite.v5/bin/serialcompare,DAT/,DAT/,0)
#DaliLite.v5/bin/serialcompare DAT/ DAT/ DALICON T < dalicon_input > /dev/null
# cat fort.1[0-9][0-9] > dp_input ; rm fort.* ; 
/DaliLite.v5/bin/serialcompare DAT/ DAT/ DP < dp_input > /dev/null
cat: fort.1[0-9][0-9]: No such file or directory
rm: cannot remove `fort.*': No such file or directory
rm -f fort.* ;
DaliLite.v5/bin/serialcompare DAT/ DAT/ PARSI > /dev/null
cat fort.1[0-9][0-9] > filter_input ; rm -f fort.*
DaliLite.v5/bin/serialcompare DAT/ DAT/ FILTER95 < filter_input 
cat: fort.1[0-9][0-9]: No such file or directory
sort -nr fort.1[0-9][0-9] | uniq | perl DaliLite.v5/bin/pipe96-free.pl 1.0 2 > dalicon_input ; rm -f fort.* 
sort: open failed: fort.1[0-9][0-9]: No such file or directory
/DaliLite.v5/bin/serialcompare DAT/ DAT/ DP < dp_input > /dev/null
cat: fort.1[0-9][0-9]: No such file or directory
rm: cannot remove `fort.*': No such file or directory
# sub wolf(WOLF,DaliLite.v5/bin/serialcompare,DAT/,DAT/,2)
wolf: DaliLite.v5/bin/serialcompare DAT/ DAT/ WOLF > /dev/null ; 
cat fort.1[0-9][0-9] > wolf_output ; rm fort.1[0-9][0-9] ; 
DaliLite.v5/bin/serialcompare DAT/ DAT/ DP < wolf_output > /dev/null ; cat fort.1[0-9][0-9] | perl 
DaliLite.v5/bin/dccp2dalicon.pl > dalicon_input ; rm -f fort.1[0-9][0-9] 
cat: fort.1[0-9][0-9]: No such file or directory
rm: cannot remove `fort.1[0-9][0-9]': No such file or directory
cat: fort.1[0-9][0-9]: No such file or directory
# sub dalicon(dalicon_input,T,
DaliLite.v5/bin/serialcompare,DAT/,DAT/,2)
# DaliLite.v5/bin/serialcompare DAT/ DAT/ DALICON T < dalicon_input > /dev/null
# cat fort.1[0-9][0-9] > dp_input ; rm fort.* ; 
DaliLite.v5/bin/serialcompare DAT/ DAT/ DP < dp_input > /dev/null
cat: fort.1[0-9][0-9]: No such file or directory
rm: cannot remove `fort.*': No such file or directory
rm -f fort.* ; 
DaliLite.v5/bin/serialcompare DAT/ DAT/ PARSI > /dev/null
cat fort.1[0-9][0-9] > filter_input ; rm -f fort.*; 
DaliLite.v5/bin/serialcompare DAT/ DAT/ FILTER95 < filter_input 
cat: fort.1[0-9][0-9]: No such file or directory
sort -nr fort.1[0-9][0-9] | uniq | perl DaliLite.v5/bin/pipe96-free.pl 1.0 2 > dalicon_input ; rm -f fort.* 
sort: open failed: fort.1[0-9][0-9]: No such file or directory
# sub dalicon(dalicon_input,T,DaliLite.v5/bin/serialcompare,DAT/,DAT/,2)
# DaliLite.v5/bin/serialcompare DAT/ DAT/ DALICON T < dalicon_input > /dev/null
# cat fort.1[0-9][0-9] > dp_input ; rm fort.* ;
DaliLite.v5/bin/serialcompare DAT/ DAT/ DP < dp_input > /dev/null
cat: fort.1[0-9][0-9]: No such file or directory
rm: cannot remove `fort.*': No such file or directory
# 1989A generate_FSSP
perl DaliLite.v5/bin/sortdccp.pl < 1989A.dccp | perl 
DaliLite.v5/bin/fsspfilter.pl 1989A 2 1 1 | DaliLite.v5/bin/fssp 1989A 1 DAT/ DAT/ | perl DaliLite.v5/bin/fsspselect.pl input2.list 2 1 | perl 
DaliLite.v5/bin/htmljs.pl DAT/ DAT/ test "test" "summary"  > 1989A.html 2> 1989A.txt
sh: 1989A.dccp: No such file or directory
`

But the strange thing is that very few PDB files can be visualized, and most still can't open properly?Are there perhaps any limitations related to visualization?
Looking forward to your reply

**Comment by abridgland** [comment]
Hi, I'm afraid I haven't come across issues visualising the predicted structures, so I can't help in this specific case. I suspect there is some issue with your visualisation tool's ability to parse these files, or some other issue with the external tool. I'd suggest trying an alternative visualisation tool, such as PyMOL or NGL.
