### ISSUE TITLE
Question about the PAE values

### ISSUE THREAD

**Issue by Jack3D67** [deepmind/alphafold#455]
Hi all,

Thanks for your work,
I was wondering in order to classify predictions of Alphafold2, what is the treshold value of a PAE matrix where any values below is considered as significantly reliable for the relative positioning of atoms.

Thanks,
Best regards.

**Comment by okovalevskiy** [comment]
Hi @Jack3D67, sorry for late reply. From my experience PAE values below (or equal to) 5A indicate reliable relative positioning of the atoms (relative positions of two domains are predicted with high certainty), above 15 indicate that relative positions of these atoms are nearly random (modelled position of two domains relative to each other is not predicted with any certainty). Values between 5 and 15 are gray zone. If no confident connections with PAE <= 5A are observed between domains, I would consider relative position of such two domains as uncertain.
