### ISSUE TITLE
Trimming not possible

### ISSUE THREAD

**Issue by polinanvkv** [deepmind/alphafold#460]
I am using the AlphaFold2 advanced notebook.

When trying to trim the sequence I get this error:

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
[<ipython-input-11-336d8cd9d929>](https://ox5jwwb24vk-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20220504-060046-RC00_446421109#) in <module>()
     11 #@markdown - `qid` minimum sequence identity with query (%)
     12 
---> 13 mod_I = cf_af.prep_filter(I, trim, trim_inverse, cov, qid)
     14 
     15 if I["msas"] != mod_I["msas"]:

1 frames
[/content/colabfold_alphafold.py](https://ox5jwwb24vk-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20220504-060046-RC00_446421109#) in trim_inputs(trim, msas, deletion_matrices, ori_seq, inverse)
    407     trim_idx_i = trim_idx_j = global_idx
    408     if i != "" and i[0] in ascii_uppercase:
--> 409       trim_idx_i,i = chain_idx[i[0]], i[1:]
    410     if j != "" and j[0] in ascii_uppercase:
    411       trim_idx_j,j = chain_idx[j[0]], j[1:]

KeyError: 'T'
```

Could you please suggest what's wrong and whether it's my fault or the code doesn't's deprecated? 

And thank you!

**Comment by Meghpal** [comment]
Hey @polinanvkv, I believe the advanced notebook is not part of this repo.

You might want to raise this issue on [ColabFold](https://github.com/sokrypton/ColabFold) instead. Your issue does seem very similar to [this issue](https://github.com/sokrypton/ColabFold/issues/135#issue-1096890182) already on ColabFold.

**Comment by abridgland** [comment]
Hi @polinanvkv, as @meghpal helpfully commented, the notebook you're referring to is not part of this repository so please raise the issue in the external repository if you still need help with this!
