### ISSUE TITLE
An error on openmm

### ISSUE THREAD

**Issue by nnnwyn** [deepmind/alphafold#462]
Hi, when i used openmm to relax the structure, i sometimes met a cuda error as metioned below. Could anyone give me a help?
`Error loading CUDA module: CUDA_ERROR_UNSUPPORTED_PTX_VERSION (222)`

**Comment by sbodenstein** [comment]
This has been reported before on the OpenMM Github page, with the resolution being to upgrade the machines NVIDIA driver: https://github.com/openmm/openmm/issues/3585 Does this solve your issue?
