### ISSUE TITLE
Minimization failed after 100 attempts

### ISSUE THREAD

**Issue by Lsz-20** [deepmind/alphafold#466]
When I run, the following error report occurs, and the GPU resource is abundant：
`
I0515 02:09:16.177335 139851152588992 amber_minimize.py:413] No template found for residue 31 (CYS).  The set of atoms matches CYM, but the bonds are different.
I0515 02:09:16.179151 139851152588992 amber_minimize.py:404] Minimizing protein, attempt 37 of 100.
I0515 02:09:16.495803 139851152588992 amber_minimize.py:413] No template found for residue 31 (CYS).  The set of atoms matches CYM, but the bonds are different.
I0515 02:09:16.497945 139851152588992 amber_minimize.py:404] Minimizing protein, attempt 38 of 100.
I0515 02:09:16.810261 139851152588992 amber_minimize.py:413] No template found for residue 31 (CYS).  The set of atoms matches CYM, but the bonds are different.
I0515 02:09:16.812105 139851152588992 amber_minimize.py:404] Minimizing protein, attempt 39 of 100.
I0515 02:09:17.130047 139851152588992 amber_minimize.py:413] No template found for residue 31 (CYS).  The set of atoms matches CYM, but the bonds are different.
···············
I0515 02:09:57.981949 139851152588992 amber_minimize.py:404] Minimizing protein, attempt 97 of 100.
I0515 02:09:58.303379 139851152588992 amber_minimize.py:413] No template found for residue 31 (CYS).  The set of atoms matches CYM, but the bonds are different.
I0515 02:09:58.305302 139851152588992 amber_minimize.py:404] Minimizing protein, attempt 98 of 100.
I0515 02:09:58.622733 139851152588992 amber_minimize.py:413] No template found for residue 31 (CYS).  The set of atoms matches CYM, but the bonds are different.
I0515 02:09:58.624582 139851152588992 amber_minimize.py:404] Minimizing protein, attempt 99 of 100.
I0515 02:09:58.947734 139851152588992 amber_minimize.py:413] No template found for residue 31 (CYS).  The set of atoms matches CYM, but the bonds are different.
I0515 02:09:58.949591 139851152588992 amber_minimize.py:404] Minimizing protein, attempt 100 of 100.
I0515 02:09:59.263663 139851152588992 amber_minimize.py:413] No template found for residue 31 (CYS).  The set of atoms matches CYM, but the bonds are different.
Traceback (most recent call last):
  File "/nfs/my/lsz/alphafold1/alphafold-main/run_alphafold.py", line 427, in <module>
    app.run(main)
  File "/opt/conda/envs/alphafold1/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/opt/conda/envs/alphafold1/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/nfs/my/lsz/alphafold1/alphafold-main/run_alphafold.py", line 403, in main
    predict_structure(
  File "/nfs/my/lsz/alphafold1/alphafold-main/run_alphafold.py", line 237, in predict_structure
    relaxed_pdb_str, _, _ = amber_relaxer.process(prot=unrelaxed_protein)
  File "/nfs/my/lsz/alphafold1/alphafold-main/alphafold/relax/relax.py", line 58, in process
    out = amber_minimize.run_pipeline(
  File "/nfs/my/lsz/alphafold1/alphafold-main/alphafold/relax/amber_minimize.py", line 469, in run_pipeline
    ret = _run_one_iteration(
  File "/nfs/my/lsz/alphafold1/alphafold-main/alphafold/relax/amber_minimize.py", line 415, in _run_one_iteration
    raise ValueError(f"Minimization failed after {max_attempts} attempts.")
ValueError: Minimization failed after 100 attempts.
`
What should I do with it？

**Comment by avilella** [comment]
I see this error as well.

**Comment by Augustin-Zidek** [comment]
Most likely AlphaFold produced a prediction that is bad and relax is having issues fixing it. I recommend running with `--run_relax=false` to get rid of this error, but note that the output prediction will likely contain some structural clashes.

**Comment by Lsz-20** [comment]
> Most likely AlphaFold produced a prediction that is bad and relax is having issues fixing it. I recommend running with `--run_relax=false` to get rid of this error, but note that the output prediction will likely contain some structural clashes.

I have tried this method，but it show me the same question.

**Comment by lptfpRCB** [comment]
# '/path/to/your/colabfold_batch' should be substituted to your path, e.g. '/home/moriwaki/Desktop/colabfold_batch'
# install GPU-supported jaxlib
COLABFOLDDIR="/path/to/your/colabfold_batch"
${COLABFOLDDIR}/colabfold-conda/bin/python3.7 -m pip uninstall "colabfold[alphafold] @ git+https://github.com/sokrypton/ColabFold" -y
${COLABFOLDDIR}/colabfold-conda/bin/python3.7 -m pip uninstall alphafold-colabfold -y
${COLABFOLDDIR}/colabfold-conda/bin/python3.7 -m pip install "colabfold[alphafold] @ git+https://github.com/sokrypton/ColabFold"
${COLABFOLDDIR}/colabfold-conda/bin/python3.7 -m pip install https://storage.googleapis.com/jax-releases/cuda11/jaxlib-0.3.25+cuda11.cudnn82-cp37-cp37m-manylinux2014_x86_64.whl
${COLABFOLDDIR}/colabfold-conda/bin/python3.7 -m pip install jax==0.3.25 biopython==1.79
# fix jax.tree_(un)flatten warnings (ad hoc)
sed -i -e "s/jax.tree_flatten/jax.tree_util.tree_flatten/g" ${COLABFOLDDIR}/colabfold-conda/lib/python3.7/site-packages/alphafold/model/mapping.py
sed -i -e "s/jax.tree_unflatten/jax.tree_util.tree_unflatten/g" ${COLABFOLDDIR}/colabfold-conda/lib/python3.7/site-packages/alphafold/model/mapping.py

Try this already mentioned fix for gpu errors in colabfold
