### ISSUE TITLE
extending database with own sequences - how?

### ISSUE THREAD

**Issue by avilella** [deepmind/alphafold#468]
We have a collection of about 100,000 sequences (Fv antibody-looking) and we are wondering if we could use these to enhance the database so that the MSAs coming out the querying these are bigger enhanced representations of the sequence universe, an AF2 returns better models. This is in the context of attempting to use AF2-multimer (v2.2.0) to predict antibody Fv versus antigen folding (and interactions).

Where would be add these 100K sequences in the different files in the db folder? Would it be just a matter of appending them to the `uniprot.fasta` file? Or do we need to add them somewhere else? E.g. the Mgnify files? Thanks.

**Comment by Augustin-Zidek** [comment]
Yes, appending those sequences in the fasta format in either the UniProt or the MGnify fasta should work. You could also modify the code to allow a new database and search that separately, but the approach you are suggesting should work just fine and would be significantly simpler.
