### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by cdaversin** [deepmind/alphafold#47]
Hi,
Following the steps to run AlphaFold via the Colab module, the "Search against genetic databases" cell cannot find the 'alphafold.model' module. Note : the "Download AlphaFold" code ran without problem so I assume the module should be installed.
```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-22-1640ae7ce3a3> in <module>()
     24 import py3Dmol
     25 
---> 26 from alphafold.model import model
     27 from alphafold.model import config
     28 from alphafold.model import data

ModuleNotFoundError: No module named 'alphafold.model'
```

**Comment by Nisha20591** [comment]
Hi,
I had a similar issue. Unable to run the code

**Comment by yamule** [comment]
Can you add following cells anywhere & run & paste the outputs after you encounter the error.
1.
`!ls /opt/conda/lib/python3.7/site-packages |head`
2.
`print(sys.path)`

**Comment by cdaversin** [comment]
I added this after the "Download AlphaFold" cell, and here is the output I get : 
1. 
``` 
brotli
brotlipy-0.7.0-py3.7.egg-info
certifi
certifi-2021.5.30-py3.7.egg-info
cffi
cffi-1.14.6.dist-info
_cffi_backend.cpython-37m-x86_64-linux-gnu.so
chardet
chardet-4.0.0.dist-info
conda
``` 
2.  `['', '/content', '/env/python', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/usr/local/lib/python3.7/dist-packages', '/usr/lib/python3/dist-packages', '/usr/local/lib/python3.7/dist-packages/IPython/extensions', '/root/.ipython'] ` Note : I had to import sys first;)

**Comment by yamule** [comment]
print(sys.path) does not work before you run the cell "Search against genetic databases" thus I wrote "after you  encounter the error" (sorry it must be 'encountered').
Anyway it looks like the cell 'Download AlphaFold' failed (Modules are not installed).
Did you try
 Runtime > Factory reset runtime 
& re-run as described in https://github.com/deepmind/alphafold/issues/45#issuecomment-885585043 ?

**Comment by cdaversin** [comment]
Indeed, it seems that AlphaFold modules were not properly installed, even if I didn't get any error there.
Doing Runtime -> Factory reset runtime solves the problem.
Thanks!

**Comment by Nisha20591** [comment]
Runtime > Factory reset runtime
for the third time worked!
Thank you
