### ISSUE TITLE
strict_error_check

### ISSUE THREAD

**Issue by georgkempf** [deepmind/alphafold#470]
I don't understand the purpose of the following except block:
https://github.com/deepmind/alphafold/blob/c42a96f3a5b6179484b5f0b936e3dd0c9b08fde1/alphafold/data/templates.py#L716

When strict_error_check is set to False then the result would still be empty because below the conditional another empty SingleHitResult is returned in any condition. So I think this conditional does not have much effect other than including the error messages.

Also I think in case of the multimer pipeline it might be ok to allow templates identical to the sequence?

**Comment by andycowie** [comment]
`strict_error_check` is used in benchmarking, it "hard fails" in cases where a template may leak information on a target.

Unless you are running AlphaFold to benchmark its performance then it is ok to allow templates that are identical. In this case you could do that by changing the value of max_subsequence_ratio to a high value.
