### ISSUE TITLE
Confidence scales for monomers and multimers

### ISSUE THREAD

**Issue by josomir** [deepmind/alphafold#472]
Hello, I have been using AlphaFold from container on HPC system for a couple of months and it has really shown to be useful. Just recently started doing predictions on multimers (in my case mAb drugs) and have noticed that prediction confidence scores are on different scales for monomers (1-100) and multimers (0-1).

Can please someone confirm that so I can be sure that my prediction scores are not in fact extremely low? :)

**Comment by tcoates5** [comment]
I recently ran the multimer prediction on an antibody, the overall score was about .9, the per residue scores were in the normal range though (average about 90)

**Comment by josomir** [comment]
> I recently ran the multimer prediction on an antibody, the overall score was about .9, the per residue scores were in the normal range though (average about 90)

so .9 in fact means that confidence score for that protein is 90%?

**Comment by tcoates5** [comment]
As far as I can tell, yes, it seems to just be off by that factor of 100

**Comment by tcoates5** [comment]
You can go through the pdb files and see the per-residue confidence (stored as the b-factor). In general that seems to do a better job of really explaining the confidence in the structure, as there are often at least small pieces with low confidence.

**Comment by yamule** [comment]
I think it is because confidence scores for monomer is 'plddt' and for multimer is 'iptm+ptm'.
https://github.com/deepmind/alphafold/blob/c42a96f3a5b6179484b5f0b936e3dd0c9b08fde1/run_alphafold.py#L267
The values in the b-factor columns are 'plddt' for both modes.
https://github.com/deepmind/alphafold/blob/main/run_alphafold.py#L231

**Comment by okovalevskiy** [comment]
Hi @josomir, sorry for late reply. The difference is: for the monomers AlphaFold reports average pLDDT score, confidence score for predicting positions of amino acid residues (scale 0-100). However, for multimers AlphaFold reports pTM and ipTM scores - confidence of the protein-protein interface prediction. It also shall be on the scale 0-100, but if you were using ColabFold (a separate tool not developed by DeepMind, but based on the AlphaFold), ColabFold indeed reports pTM and ipTM scores in the scale 0-1. So please just multiply these scores by a 100. Hope this helps.
