### ISSUE TITLE
dockerignore: permission denied

### ISSUE THREAD

**Issue by Maryamtarazkar** [deepmind/alphafold#473]
Dear Alphafold support team, 
I am trying to install alphafold on my local Ubuntu machine. I am stopped in the very first steps "Build the Docker image" when I apply following command:
docker build -f docker/Dockerfile -t alphafold .
I get this error:
user/alphafold/.dockerignore: permission denied
I appreciate to help me how to fix this error.

**Comment by Maiya19724** [comment]
sudo docker build -f docker/Dockerfile -t alphafold .

**Comment by andycowie** [comment]
It should not be necessary to have superuser permissions to run this. Did you already try the [link for running Docker as a non-root user](https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user) from the README?

**Comment by Maiya19724** [comment]
> It should not be necessary to have superuser permissions to run this. Did you already try the [link for running Docker as a non-root user](https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user) from the README?

Thanks! Already added user to the docker group.

**Comment by Maryamtarazkar** [comment]
@Maiya19724" Thank you for your note. I applied the command and it says 
"""
"docker build" requires exactly 1 argument.
See 'docker build --help'.

Usage:  docker build [OPTIONS] PATH | URL | -

Build an image from a Dockerfile
"""

**Comment by Maiya19724** [comment]
@Maryamtarazkar 
What is your command?
Make sure you're in the alphafold folder and run the complete command.
If you don't have superuser permissions on your machine, you can read this document in the comments above:


> It should not be necessary to have superuser permissions to run this. Did you already try the [link for running Docker as a non-root user](https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user) from the README?

**Comment by aputron** [comment]
@Maryamtarazkar 
I think you're probably missing the final `.` that indicates that you want to build the docker image from the folder you currently are in.

**Comment by Maryamtarazkar** [comment]
@Maiya19724 
Thank you for our note my command is:
sudo docker build -f docker/Dockerfile -t alphafold .
And now I get this error; 
open /media/labuser/HDD/MT/alphafold/.dockerignore: permission denied

**Comment by Maryamtarazkar** [comment]
@aputron 
Thank you for your note. My command is:
sudo docker build -f docker/Dockerfile -t alphafold .
And now I get this error;
open /media/labuser/HDD/MT/alphafold/.dockerignore: permission denied

**Comment by tomwardio** [comment]
Hi @Maryamtarazkar, this looks like `/media/labuser/HDD/MT/alphafold` isn't accessible by the docker daemon, likely not having read permissions when running through sudo. Make sure you've followed the advice [here](https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user) to manage docker as a non-root user.

Also note that network drives may also not be accessible from the Docker daemon (tho this looks to be running from local disk, going on the path). Hope this helps!
