### ISSUE TITLE
ImportError: cannot import name 'types' from 'docker' (/home/user/applications/alphafold/docker/__init__.py)

### ISSUE THREAD

**Issue by davidyanglee** [deepmind/alphafold#474]
Error message when running "python3 docker/run_docker.py \ ..." which had previously run without issues:

Traceback (most recent call last):
  File "/home/user/applications/alphafold/docker/run_docker.py", line 26, in <module>
    from docker import types
ImportError: cannot import name 'types' from 'docker' (/home/dlee/applications/Alphafold/docker/__init__.py)

Docker complied without error msg and "docker images" showed docker container name is present. output_dir also created and permitted for read and write by chmod. "__init__.py" files are present in both the alphafold/docker and alphafold/alphafold subdirectories. Repeat git clone did not resolve this issue. Any idea what could be causing this? Thank you!

**Comment by shahryary** [comment]
@davidyanglee  did you try to install libraries? if not try this:

pip3 install -r /data/alphafold/docker/requirements.txt

**Comment by davidyanglee** [comment]
Thank you, @shahryary. Turned out in ~/.bashrc there was one line of "export PYTHONPATH=..." set to an unrelated directory. So despite "pip3 install -r docker/requirements.txt" and docker build running successfully, Python was looking for the requirement libraries in the wrong PATH. At least that's what I think because once that's removed, everything ran fine just like my other machine.
