### ISSUE TITLE
protocol buffers error

### ISSUE THREAD

**Issue by britnyblu** [deepmind/alphafold#478]
Hi
When running alphafold with run_docker.py I received the following error:
I0526 06:08:25.468181 140470932322112 run_docker.py:255] _message.Message._CheckCalledFromGeneratedFile()
I0526 06:08:25.468281 140470932322112 run_docker.py:255] TypeError: Descriptors cannot not be created directly.
I0526 06:08:25.468383 140470932322112 run_docker.py:255] If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
I0526 06:08:25.468482 140470932322112 run_docker.py:255] If you cannot immediately regenerate your protos, some other possible workarounds are:
I0526 06:08:25.468592 140470932322112 run_docker.py:255] 1. Downgrade the protobuf package to 3.20.x or lower.
I0526 06:08:25.468696 140470932322112 run_docker.py:255] 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

I fixed this by adding the following to the Dockerfile:
&& pip3 install --upgrade protobuf==3.20.0

Maybe this or an alternative solution should be updated in the repository?
thanks
Britny

**Comment by ShoufaChen** [comment]
```
pip3 install --upgrade protobuf==3.20.0
```
solved my problem. Thanks @britnyblu .

**Comment by carrellsj** [comment]
I'm still having this error. Running on WSL on windows 10. run from a conda environment. 

I0529 14:26:50.882265 140336145225536 run_docker.py:113] Mounting /mnt/b/ALPHAFOLDTEST/alphafold -> /mnt/fasta_path_0
I0529 14:26:50.885260 140336145225536 run_docker.py:113] Mounting /mnt/d/WORKING2/DATA/uniref90 -> /mnt/uniref90_database_path
I0529 14:26:50.887961 140336145225536 run_docker.py:113] Mounting /mnt/d/WORKING2/DATA/mgnify -> /mnt/mgnify_database_path
I0529 14:26:50.889641 140336145225536 run_docker.py:113] Mounting /mnt/d/WORKING2/DATA -> /mnt/data_dir
I0529 14:26:50.892182 140336145225536 run_docker.py:113] Mounting /mnt/d/WORKING2/DATA/pdb_mmcif -> /mnt/template_mmcif_dir
I0529 14:26:50.894763 140336145225536 run_docker.py:113] Mounting /mnt/d/WORKING2/DATA/pdb_mmcif -> /mnt/obsolete_pdbs_path
I0529 14:26:50.897026 140336145225536 run_docker.py:113] Mounting /mnt/d/WORKING2/DATA/pdb70 -> /mnt/pdb70_database_path
I0529 14:26:50.900008 140336145225536 run_docker.py:113] Mounting /mnt/d/WORKING2/DATA/uniclust30/uniclust30_2018_08 -> /mnt/uniclust30_database_path
I0529 14:26:50.902319 140336145225536 run_docker.py:113] Mounting /mnt/d/WORKING2/DATA/bfd -> /mnt/bfd_database_path
I0529 14:26:52.410578 140336145225536 run_docker.py:255] Traceback (most recent call last):
I0529 14:26:52.410748 140336145225536 run_docker.py:255] File "/app/alphafold/run_alphafold.py", line 38, in <module>
I0529 14:26:52.410840 140336145225536 run_docker.py:255] from alphafold.model import model
I0529 14:26:52.410923 140336145225536 run_docker.py:255] File "/app/alphafold/alphafold/model/model.py", line 20, in <module>
I0529 14:26:52.410997 140336145225536 run_docker.py:255] from alphafold.model import features
I0529 14:26:52.411071 140336145225536 run_docker.py:255] File "/app/alphafold/alphafold/model/features.py", line 19, in <module>
I0529 14:26:52.411145 140336145225536 run_docker.py:255] from alphafold.model.tf import input_pipeline
I0529 14:26:52.411217 140336145225536 run_docker.py:255] File "/app/alphafold/alphafold/model/tf/input_pipeline.py", line 17, in <module>
I0529 14:26:52.411290 140336145225536 run_docker.py:255] from alphafold.model.tf import data_transforms
I0529 14:26:52.411363 140336145225536 run_docker.py:255] File "/app/alphafold/alphafold/model/tf/data_transforms.py", line 18, in <module>
I0529 14:26:52.411433 140336145225536 run_docker.py:255] from alphafold.model.tf import shape_helpers
I0529 14:26:52.411505 140336145225536 run_docker.py:255] File "/app/alphafold/alphafold/model/tf/shape_helpers.py", line 16, in <module>
I0529 14:26:52.411578 140336145225536 run_docker.py:255] import tensorflow.compat.v1 as tf
I0529 14:26:52.411651 140336145225536 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/tensorflow/__init__.py", line 41, in <module>
I0529 14:26:52.411723 140336145225536 run_docker.py:255] from tensorflow.python.tools import module_util as _module_util
I0529 14:26:52.411808 140336145225536 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 40, in <module>
I0529 14:26:52.411911 140336145225536 run_docker.py:255] from tensorflow.python.eager import context
I0529 14:26:52.411981 140336145225536 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/context.py", line 32, in <module>
I0529 14:26:52.412053 140336145225536 run_docker.py:255] from tensorflow.core.framework import function_pb2
I0529 14:26:52.412125 140336145225536 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/tensorflow/core/framework/function_pb2.py", line 16, in <module>
I0529 14:26:52.412198 140336145225536 run_docker.py:255] from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
I0529 14:26:52.412269 140336145225536 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
I0529 14:26:52.412342 140336145225536 run_docker.py:255] from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
I0529 14:26:52.412413 140336145225536 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
I0529 14:26:52.412485 140336145225536 run_docker.py:255] from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
I0529 14:26:52.412558 140336145225536 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/tensorflow/core/framework/resource_handle_pb2.py", line 16, in <module>
I0529 14:26:52.412630 140336145225536 run_docker.py:255] from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
I0529 14:26:52.412703 140336145225536 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/tensorflow/core/framework/tensor_shape_pb2.py", line 42, in <module>
I0529 14:26:52.412774 140336145225536 run_docker.py:255] serialized_options=None, file=DESCRIPTOR),
I0529 14:26:52.412915 140336145225536 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/google/protobuf/descriptor.py", line 560, in __new__
I0529 14:26:52.412988 140336145225536 run_docker.py:255] _message.Message._CheckCalledFromGeneratedFile()
I0529 14:26:52.413060 140336145225536 run_docker.py:255] TypeError: Descriptors cannot not be created directly.
I0529 14:26:52.413133 140336145225536 run_docker.py:255] If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
I0529 14:26:52.413205 140336145225536 run_docker.py:255] If you cannot immediately regenerate your protos, some other possible workarounds are:
I0529 14:26:52.413276 140336145225536 run_docker.py:255] 1. Downgrade the protobuf package to 3.20.x or lower.
I0529 14:26:52.413346 140336145225536 run_docker.py:255] 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
I0529 14:26:52.413418 140336145225536 run_docker.py:255]
I0529 14:26:52.413490 140336145225536 run_docker.py:255] More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

**Comment by ddelange** [comment]
upstream issue ref https://github.com/protocolbuffers/protobuf/issues/10051#issuecomment-1138671075

to include security patches for v3, a safe upper pin would be `protobuf<4`

**Comment by Maiya19724** [comment]
> I'm still having this error. Running on WSL on windows 10. run from a conda environment.
> 
> I0529 14:26:50.882265 140336145225536 run_docker.py:113] Mounting /mnt/b/ALPHAFOLDTEST/alphafold -> /mnt/fasta_path_0 I0529 14:26:50.885260 140336145225536 run_docker.py:113] Mounting /mnt/d/WORKING2/DATA/uniref90 -> /mnt/uniref90_database_path I0529 14:26:50.887961 140336145225536 run_docker.py:113] Mounting /mnt/d/WORKING2/DATA/mgnify -> /mnt/mgnify_database_path I0529 14:26:50.889641 140336145225536 run_docker.py:113] Mounting /mnt/d/WORKING2/DATA -> /mnt/data_dir I0529 14:26:50.892182 140336145225536 run_docker.py:113] Mounting /mnt/d/WORKING2/DATA/pdb_mmcif -> /mnt/template_mmcif_dir I0529 14:26:50.894763 140336145225536 run_docker.py:113] Mounting /mnt/d/WORKING2/DATA/pdb_mmcif -> /mnt/obsolete_pdbs_path I0529 14:26:50.897026 140336145225536 run_docker.py:113] Mounting /mnt/d/WORKING2/DATA/pdb70 -> /mnt/pdb70_database_path I0529 14:26:50.900008 140336145225536 run_docker.py:113] Mounting /mnt/d/WORKING2/DATA/uniclust30/uniclust30_2018_08 -> /mnt/uniclust30_database_path I0529 14:26:50.902319 140336145225536 run_docker.py:113] Mounting /mnt/d/WORKING2/DATA/bfd -> /mnt/bfd_database_path I0529 14:26:52.410578 140336145225536 run_docker.py:255] Traceback (most recent call last): I0529 14:26:52.410748 140336145225536 run_docker.py:255] File "/app/alphafold/run_alphafold.py", line 38, in I0529 14:26:52.410840 140336145225536 run_docker.py:255] from alphafold.model import model I0529 14:26:52.410923 140336145225536 run_docker.py:255] File "/app/alphafold/alphafold/model/model.py", line 20, in I0529 14:26:52.410997 140336145225536 run_docker.py:255] from alphafold.model import features I0529 14:26:52.411071 140336145225536 run_docker.py:255] File "/app/alphafold/alphafold/model/features.py", line 19, in I0529 14:26:52.411145 140336145225536 run_docker.py:255] from alphafold.model.tf import input_pipeline I0529 14:26:52.411217 140336145225536 run_docker.py:255] File "/app/alphafold/alphafold/model/tf/input_pipeline.py", line 17, in I0529 14:26:52.411290 140336145225536 run_docker.py:255] from alphafold.model.tf import data_transforms I0529 14:26:52.411363 140336145225536 run_docker.py:255] File "/app/alphafold/alphafold/model/tf/data_transforms.py", line 18, in I0529 14:26:52.411433 140336145225536 run_docker.py:255] from alphafold.model.tf import shape_helpers I0529 14:26:52.411505 140336145225536 run_docker.py:255] File "/app/alphafold/alphafold/model/tf/shape_helpers.py", line 16, in I0529 14:26:52.411578 140336145225536 run_docker.py:255] import tensorflow.compat.v1 as tf I0529 14:26:52.411651 140336145225536 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/tensorflow/**init**.py", line 41, in I0529 14:26:52.411723 140336145225536 run_docker.py:255] from tensorflow.python.tools import module_util as _module_util I0529 14:26:52.411808 140336145225536 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/**init**.py", line 40, in I0529 14:26:52.411911 140336145225536 run_docker.py:255] from tensorflow.python.eager import context I0529 14:26:52.411981 140336145225536 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/context.py", line 32, in I0529 14:26:52.412053 140336145225536 run_docker.py:255] from tensorflow.core.framework import function_pb2 I0529 14:26:52.412125 140336145225536 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/tensorflow/core/framework/function_pb2.py", line 16, in I0529 14:26:52.412198 140336145225536 run_docker.py:255] from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2 I0529 14:26:52.412269 140336145225536 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/tensorflow/core/framework/attr_value_pb2.py", line 16, in I0529 14:26:52.412342 140336145225536 run_docker.py:255] from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2 I0529 14:26:52.412413 140336145225536 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/tensorflow/core/framework/tensor_pb2.py", line 16, in I0529 14:26:52.412485 140336145225536 run_docker.py:255] from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2 I0529 14:26:52.412558 140336145225536 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/tensorflow/core/framework/resource_handle_pb2.py", line 16, in I0529 14:26:52.412630 140336145225536 run_docker.py:255] from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2 I0529 14:26:52.412703 140336145225536 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/tensorflow/core/framework/tensor_shape_pb2.py", line 42, in I0529 14:26:52.412774 140336145225536 run_docker.py:255] serialized_options=None, file=DESCRIPTOR), I0529 14:26:52.412915 140336145225536 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/google/protobuf/descriptor.py", line 560, in **new** I0529 14:26:52.412988 140336145225536 run_docker.py:255] _message.Message._CheckCalledFromGeneratedFile() I0529 14:26:52.413060 140336145225536 run_docker.py:255] TypeError: Descriptors cannot not be created directly. I0529 14:26:52.413133 140336145225536 run_docker.py:255] If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0. I0529 14:26:52.413205 140336145225536 run_docker.py:255] If you cannot immediately regenerate your protos, some other possible workarounds are: I0529 14:26:52.413276 140336145225536 run_docker.py:255] 1. Downgrade the protobuf package to 3.20.x or lower. I0529 14:26:52.413346 140336145225536 run_docker.py:255] 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower). I0529 14:26:52.413418 140336145225536 run_docker.py:255] I0529 14:26:52.413490 140336145225536 run_docker.py:255] More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
@carrellsj 
try modify the alphafold/docker/Dockerfile then built local image using docker.
`&& pip3 install --upgrade protobuf==3.20.0`

**Comment by carrellsj** [comment]
I tried reinstalling protobuf 3.20.0 3.20.1, and 3.19.0, and rebuilding with dockerfile. I'm trying to avoid  : Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python  to avoid slowing down the process, although working on an AMD threadripper 3960x, 256gb of ram and an RTX 3080 shouldn't slow it down too much? What is run time for a 1kb protein model with " Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python "?

**Comment by aputron** [comment]
Additionally, you can add `protobuf==3.20.1` to the `requirements.txt` file in the primary `alphafold` folder.

**Comment by sumai-1998** [comment]
> 

solved

**Comment by AbhijitManepatil** [comment]
> ```
> pip3 install --upgrade protobuf==3.20.0
> ```
> 
> solved my problem. Thanks @britnyblu .

Thanks issue resolved

**Comment by ericmjl** [comment]
@Augustin-Zidek would it be possible to have the fix updated in `requirements.txt`? If you'd like a PR, I'm happy to do it, please let me know.

**Comment by ddelange** [comment]
the relevant upstream fix comes with tf 2.7.3 ref https://github.com/tensorflow/tensorflow/releases/tag/v2.7.3

updating the tf dependency would be the preferred fix over introducing a new dependency in this library

**Comment by kushan-gunasekera** [comment]
For anyone who is looking for a proper solution,

answer:- [https://stackoverflow.com/a/72493690/6194097](https://stackoverflow.com/a/72493690/6194097)
