### ISSUE TITLE
Alphafold protein domain compartmentalization

### ISSUE THREAD

**Issue by jnielsen20** [deepmind/alphafold#48]
Alphafold has an issue when it comes to a class of proteins known as membrane proteins. Briefly, membrane proteins are located in multiple cell compartments where the domains of the membrane protein are separated by a physical barrier. 

I have encountered multiple examples of alphafold becoming confused and trying to get domains that are biologically seperated to interact. Luckily a large training set of annotated proteins already exists in the uniprot database. For example, the insulin receptor (https://www.uniprot.org/uniprot/P06213#subcellular_location) have extracellular domains a transmembrane domain and a intra cellular domain. Thus only domains in the same compartments needs to be close to each other in the final fold, whereas domains in separate compartments need only be within a distance that can be spanned by the peptide chain.

Additionally, some protein are modified after translation. These modification include formation of disulfide bridges, which locks the distance and geometry of the two involved cysteine residues. This information is also available in uniprot (https://www.uniprot.org/uniprot/P06213#ptm_processing)

While I recognize that alphafold was designed for de novo prediction, I wonder how more powerful it could become if it were allowed to incorporate known biochemical information into its predictions.

While this is not per say an issue, it is something that should be tried.

**Comment by abridgland** [comment]
Thanks for this comment. We’d like to keep GitHub issues to software questions — please direct scientific and machine learning questions to the corresponding authors on the manuscript (https://www.nature.com/articles/s41586-021-03819-2#author-information).  Thanks!
