### ISSUE TITLE
Full vs Reduced Databases

### ISSUE THREAD

**Issue by suhailislam** [deepmind/alphafold#481]
In order to have the option of running Alphafold using
the Full and Reduced versions of the databases, do I need to download
    1) BOTH full (2.4TB) AND Reduced (617GB) as separate DBs
    or simply
    2) the full version (2.4TB) + small_bfd (17GB)
Other than bfd & small_bfd, the other directories (mgnify  params 
pdb70  pdb_mmcif  pdb_seqres  uniclust30  uniprot  uniref90) look the same
in both the downloads. However, would like to be sure.

Thank you

**Comment by Augustin-Zidek** [comment]
Just 2). The reduced databases preset just swaps the full BFD for the small one.
