### ISSUE TITLE
Fasta file format for predicting homomers

### ISSUE THREAD

**Issue by Sameerpython** [deepmind/alphafold#487]
Hi,
For my study I am trying to predict the structure of five homomeric structure. We have the Alphafold installed on our server. I would like to know how to provide a fasta file with multiple copies of the same sequence for predicting the structure. Currently I tried providing ‘:’ between each of the monomer and the program throws an error as illegal character ‘:’.

Sequence file:
>seq1
MKAPVRVAVTGAAGQIGYSLLFRIAAGEMLGKDQPVIL:MKAPVRVAVTGAAGQIGYSLLFRIAAGEMLGKDQPVIL:MKAPVRVAVTGAAGQIGYSLLFRIAAGEMLGKDQPVIL:MKAPVRVAVTGAAGQIGYSLLFRIAAGEMLGKDQPVIL:MKAPVRVAVTGAAGQIGYSLLFRIAAGEMLGKDQPVIL

The command i am using is 
alphafold -d  $ALPHAFOLD_DATASET   -f  sequence.fasta -o out_folder  -t 2022-04-26 -m model_1,model_2,model_3,model_4,model_5  -g false

I would appreciate your help in solving this issue.

Thanks in advance!

**Comment by Aroids** [comment]
When predicting homomers, is it necessary for each 'definition line' within a fasta file to be unique?

For example, would the following be acceptable:

>seq1
MKAPVRVAVTGAAGQIGYSLLFRIAAGEMLGKDQPVIL
>seq1
MKAPVRVAVTGAAGQIGYSLLFRIAAGEMLGKDQPVIL
>seq1
MKAPVRVAVTGAAGQIGYSLLFRIAAGEMLGKDQPVIL
>seq1
MKAPVRVAVTGAAGQIGYSLLFRIAAGEMLGKDQPVIL
>seq1
MKAPVRVAVTGAAGQIGYSLLFRIAAGEMLGKDQPVIL
