### ISSUE TITLE
ValueError when Running AlphaFold

### ISSUE THREAD

**Issue by claire-ceresa** [deepmind/alphafold#489]
**Hello everyone,**

**When I execute AlphaFold from Google Colab, I have a Future Warning :**
"/usr/local/lib/python3.7/dist-packages/jax/_src/tree_util.py:189: FutureWarning: jax.tree_util.tree_multimap() is deprecated. Please use jax.tree_util.tree_map() instead as a drop-in replacement. 'instead as a drop-in replacement.', FutureWarning)"

**And the code fail with a Value Error :** 

"ValueError                                Traceback (most recent call last)

[<ipython-input-5-f89616eedc2d>](https://localhost:8080/#) in <module>()
     88         max_outer_iterations=3,
     89         use_gpu=True)
---> 90     relaxed_pdb, _, _ = amber_relaxer.process(prot=unrelaxed_proteins[best_model_name])
     91   else:
     92     print('Warning: Running without the relaxation stage.')

2 frames

[/opt/conda/lib/python3.7/site-packages/alphafold/relax/amber_minimize.py](https://localhost:8080/#) in _run_one_iteration(pdb_string, max_iterations, tolerance, stiffness, restraint_set, max_attempts, use_gpu, exclude_residues)
    417       logging.info(e)
    418   if not minimized:
--> 419     raise ValueError(f"Minimization failed after {max_attempts} attempts.")
    420   ret["opt_time"] = time.time() - start
    421   ret["min_attempts"] = attempts

ValueError: Minimization failed after 100 attempts."

**Did anyone know what's happening ?**

**Comment by Htomlinson14** [comment]
Thanks for raising this issue! Closing as this duplicates https://github.com/deepmind/alphafold/issues/383
