### ISSUE TITLE
About RuntimeError of hhsearch

### ISSUE THREAD

**Issue by Maikuraky** [deepmind/alphafold#49]
Due to the network, I use non-docker version. But in the process of Inference, there was a problem with hhsearch：
RuntimeError: HHSearch failed:
stdout:
stderr:
- 00:22:03.447 INFO: /tmp/tmpkkewtvxt/query.a3m is in A2M, A3M or FASTA format
- 00:22:03.593 INFO: Searching 80799 database HHMs without prefiltering
- 00:22:03.629 INFO: Iteration 1
- 00:22:03.986 INFO: Scoring 80799 HMMs using HMM-HMM Viterbi alignment
- 00:22:04.056 INFO: Alternative alignment: 0
- 00:23:25.517 INFO: 80799 alignments done
- 00:23:25.786 INFO: Alternative alignment: 1
- 00:23:30.387 INFO: 3802 alignments done
- 00:23:30.391 INFO: Alternative alignment: 2
- 00:23:31.297 INFO: 438 alignments done
- 00:23:31.297 INFO: Alternative alignment: 3

Can someone give me some suggestions or solutions? thanks

**Comment by 7itrees** [comment]
> I am seeing the same issue, was it solved for you? What was the problem?
> Thank you!

I have the same error，was it solved for you?

**Comment by SoniaAndrys** [comment]
Hi @Maikuraky, I encountered the same problem while running alphafold2 on supercomputer (non-docker version here as well). 
Do you have any tips on how to solve the issue?

Best regards,
Sonia

**Comment by yunxiangz** [comment]
I am seeing the same issue, was it solved for you? What was the problem?

Best regards,
Frank

**Comment by AaronFeller** [comment]
I also just hit this error running in singularity. Any fix?

**Comment by wdlingit** [comment]
Hi people! I just got the same error, either using the full database or using the reduced database. Just noticed that this might be simple. Alphafold seemed working just after I removed the terminal * from the input sequence file. Hope this would work for your situation.

**Comment by wdlingit** [comment]
Hi people! I am using the docker version and I got the same error (ONLY for the first line "INFO: /tmp/tmp2wr1c410/query.a3m is in A2M, A3M or FASTA format"), either using the full database or using the reduced database. Just noticed that this might be simple. Alphafold seemed working after I removed the terminal * from the input sequence file. Hope this would work for your situation.

**Comment by wttat** [comment]
what does terminal * means?> Hi people! I am using the docker version and I got the same error (ONLY for the first line "INFO: /tmp/tmp2wr1c410/query.a3m is in A2M, A3M or FASTA format"), either using the full database or using the reduced database. Just noticed that this might be simple. Alphafold seemed working after I removed the terminal * from the input sequence file. Hope this would work for your situation.

**Comment by wttat** [comment]
> Hi people! I am using the docker version and I got the same error (ONLY for the first line "INFO: /tmp/tmp2wr1c410/query.a3m is in A2M, A3M or FASTA format"), either using the full database or using the reduced database. Just noticed that this might be simple. Alphafold seemed working after I removed the terminal * from the input sequence file. Hope this would work for your situation.

could you explain what is the **terminal * from the input sequence file** means, thanks

Best regards
Tong

**Comment by wdlingit** [comment]
> > Hi people! I am using the docker version and I got the same error (ONLY for the first line "INFO: /tmp/tmp2wr1c410/query.a3m is in A2M, A3M or FASTA format"), either using the full database or using the reduced database. Just noticed that this might be simple. Alphafold seemed working after I removed the terminal * from the input sequence file. Hope this would work for your situation.
> 
> could you explain what is the **terminal * from the input sequence file** means, thanks
> 
> Best regards Tong

For example:

>MCHU
MADQLTEEQIAEFKEAFSLFDKDGDGTITTKELGTVMRSLGQNPTEAELQDMINEVDADGNGTID
FPEFLTMMARKMKDTDSEEEIREAFRVFDKDGNGYISAAELRHVMTNLGEKLTDEEVDEMIREA
DIDGDGQVNYEEFVQMMTAK*

The very last asterisk.

**Comment by wttat** [comment]
> > > Hi people! I am using the docker version and I got the same error (ONLY for the first line "INFO: /tmp/tmp2wr1c410/query.a3m is in A2M, A3M or FASTA format"), either using the full database or using the reduced database. Just noticed that this might be simple. Alphafold seemed working after I removed the terminal * from the input sequence file. Hope this would work for your situation.
> > 
> > 
> > could you explain what is the **terminal * from the input sequence file** means, thanks
> > Best regards Tong
> 
> For example:
> 
> `>`MCHU MADQLTEEQIAEFKEAFSLFDKDGDGTITTKELGTVMRSLGQNPTEAELQDMINEVDADGNGTID FPEFLTMMARKMKDTDSEEEIREAFRVFDKDGNGYISAAELRHVMTNLGEKLTDEEVDEMIREA DIDGDGQVNYEEFVQMMTAK*
> 
> The very last asterisk.

really appreciate that.

I have found the reason why I countered  this. I used AWS CodeBuild to build my alphafold2 image, but it runs on a amd64 instance, so somehow it went wrong.

solution :
https://github.com/wttat/alphafold/commit/51afdd7060fa0cefa0df7c2a8dfd26f6c5a1ea73

**Comment by mohsenumn** [comment]
Make sure you have given the necessary permissions to the alphafold_data files. 
You can grant permission using chmod g+r * when you're in pdb70 directory, for example.
