### ISSUE TITLE
mkdir: illegal option -- -

### ISSUE THREAD

**Issue by gweeish** [deepmind/alphafold#494]
Hi alphafold experts, 

I am trying to download the databases using the following command: scripts/download_all_data.sh databases but facing the current issue:

Downloading AlphaFold parameters...
mkdir: illegal option -- -
usage: mkdir [-pv] [-m mode] directory ...

Any help would be appreciated. Thank you.

**Comment by Augustin-Zidek** [comment]
I believe this indicates you are running the scripts on Mac (or BSD perhaps?), which doesn't support the `--parents` option of `mkdir`. I recommend:
1. Running AlphaFold on Linux, Mac is not supported and you will run into further issues down the line.
2. If you still want to run AlphaFold on Mac, change the line in this and all other scripts from `mkdir --parents ...` to `mkdir -p ...`.
