### ISSUE TITLE
HHblits fails on specific GPU- Nvidia V100 model

### ISSUE THREAD

**Issue by shahryary** [deepmind/alphafold#499]
I'm using amazon cloud to do the predictions, recently I configured EC2 instance p3.8xlarge- (the GPU model is Nvidia 4X V100)
After the setup everything, I got error in hhblits part, here is the last part of the error: 

```
stdout.decode('utf-8'), stderr[:500_000].decode('utf-8'))) untimeError: HHblits failed
```
I checked for every issue regarding the GPU/ docker/ cuda driver/ ...here, but couldn't  find the right answer. many solutions referring to the VRAM or GPU RAM but in my case I have plenty of the resources.  

but the story is going more interesting when I created another instance "g4dn.8xlarge" and did all the my predictions perfectly, without any error or interruption. (This instance has only one GPU NVIDIA T4!!) 

I did all the steps same for both instances but seems some how it doesn't work well on V100 GPUs. 

BTW, I used the same kernel, same GPU driver, etc. 

Any idea/ hints appreciated.

**Comment by Augustin-Zidek** [comment]
HHBlits doesn't use GPUs, so it is definitely something else about the machines that is causing the difference. The most common HHBlits error is running out of RAM.

**Comment by shahryary** [comment]
By increasing the server RAM from 64 GB to 256 GB I could generate the results. so the problem is not about the specific GPU  model but the RAM. seems in some point HHBlits needs more RAM to keep running the application.
