### ISSUE TITLE
Database disk type

### ISSUE THREAD

**Issue by chrisroat** [deepmind/alphafold#5]
The README states the need to put "the databases on an additional 3 TB disk".   Should this be an SSD?

**Comment by Augustin-Zidek** [comment]
Hi Chris,

Ideally yes, the genetic search tools are very IO intensive, hence having an SSD helps.

For more details see e.g. the HH Suite wiki that discusses HHBlits performance: https://github.com/soedinglab/hh-suite/wiki#running-hhblits-efficiently-on-a-computer-cluster

**Comment by chrisroat** [comment]
Thanks.  Is a persistent SSD sufficient, or did you all use a set of local SSD?  Table of comparison:
https://cloud.google.com/compute/docs/disks/performance#type_comparison

If local SSD, was NVME or SCSI used?  (I'm not sure which drivers are even available on `nvidia-gpu-cloud-image`)

**Comment by Augustin-Zidek** [comment]
I recommend using the fastest possible option, but the sequence search should work in either case – it is just a matter of speed.

**Comment by chrisroat** [comment]
From an engineering perspective, speed needs to be weighed against other factors.  The fastest SSDs on GCP are the local SSDs, but they are harder to use since data is not persisted and multiple volumes need to be managed (they have a max size of 375GB).

If the local SSDs give only a small bump in performance, they would not be worth it compared to persistent SSDs.  If there is a relative benchmark, that will be useful to people.  We may test it at some point and report back, unless someone beats us to it.

**Comment by AndreTomasGraca** [comment]
I am considering which  storage device option to buy for my own workstation to store the databases.

I understand that the genetic search tool will be very I/O intensive, leaving me undecided: I have the possibility of taking a 4TB NVMe PCI Express 4.0 x4 in my setup, but those are considerably more expensive than a 4TB or 8TB SSD SATA 6Gb/s.
Did anyone see justifiable performance difference between those two types of devices?
