### ISSUE TITLE
Is there a way to get per-residue embeddings from the model?

### ISSUE THREAD

**Issue by aghanbar** [deepmind/alphafold#50]
Pretty much self-explanatory.

**Comment by xinformatics** [comment]
I have tried a workaround, available on my github at [Alphafold Embeddings](https://github.com/xinformatics/alphafold_embeddings)

**Comment by abridgland** [comment]
This has been discussed in issue #15 — by adding `return_representations=True` in model.py you should get a number of representations that you might find useful.
