### ISSUE TITLE
Can AlphaFold be ran using an AMD GPU?

### ISSUE THREAD

**Issue by caom92** [deepmind/alphafold#503]
From what I've seen in the dependencies installed in the Dockerfile, I understand that AlphaFold utilizes Nvidia CUDA, but I was wondering if it's possible to run AlphaFold using OpenCL in an AMP GPU without modifying the code too much (since CUDA is abstracted by Tensorflow; i.e., AlphaFold doesn't use CUDA directly, but rather indirectly, through Tensorflow).

**Comment by emirzakh** [comment]
I tried adapting the system to use an AMD GPU, but ended up with so many problems and inconsistencies between various packages that I switched to running tasks on the CPU while we worked on building a PC with a NVIDIA GPU. You might have better luck than I did.

**Comment by Augustin-Zidek** [comment]
Sorry, AlphaFold supports only NVIDIA GPUs. See also http://go/gh/deepmind/alphafold/issues/384.
