### ISSUE TITLE
FututreWarning

### ISSUE THREAD

**Issue by Smithova** [deepmind/alphafold#504]
Hi,

I get this warning while running AlphaFold.ipynb:
/usr/local/lib/python3.7/dist-packages/jax/_src/tree_util.py:189: FutureWarning: jax.tree_util.tree_multimap() is deprecated. Please use jax.tree_util.tree_map() instead as a drop-in replacement.
  'instead as a drop-in replacement.', FutureWarning)

What does it mean?

Thank you,
Andrea

**Comment by Augustin-Zidek** [comment]
This is a deprecation warning that is safe to ignore (they renamed the `tree_multimap` function to `tree_map`). Moreover, it has been fixed in https://github.com/deepmind/alphafold/commit/d9e5e1d9c65ff339328c0fb7078057593eecd043.
