### ISSUE TITLE
GPU supported

### ISSUE THREAD

**Issue by q1134269149** [deepmind/alphafold#51]
Hi, 
   I want to use alphafold2, but the Linux server has no GPU and only CPU. Is it OK? Thank you!
hqin

**Comment by FilomenoSanchez** [comment]
As discussed [here](https://github.com/deepmind/alphafold/issues/12#issuecomment-881894209), AF2 can run on CPUs, just pass the `--use_gpu=False` keyword. From my personal experience it will be much slower than running it on a GPU.

**Comment by aghozlane** [comment]
Hi
We don't have docker and we don't use conda too (I built my own singularity recipe). I want to run the cpu version. The flag --use_gpu is marked in the script run_docker.py, and is missing in run_alphafold.py. I tried to use the option --flagfile=flags.txt but it says: Unknown command line flag 'use_gpu'. How can I notify the script run_alphafold.py for no gpu usage ?

**Comment by FilomenoSanchez** [comment]
My guess is that if you don't have a GPU you can set `export CUDA_VISIBLE_DEVICES=0` and tensorflow will fall back to CPU by default.

**Comment by tfgg** [comment]
Hi,

You can run outside Docker without GPU by setting CUDA_VISIBLE_DEVICES to be empty (`0` will correspond to the first GPU). If your machine doesn't have a GPU, this won't be necessary and it will run on CPU.

It will be much slower, though - in some other issues people have made some measurements.
