### ISSUE TITLE
bugfix for latest jax version (jnp.take() in version jax>=0.3.8 return nans)

### ISSUE THREAD

**Issue by sokrypton** [deepmind/alphafold#513]
alphafold+multimer+templates returns NAN, starting with jax version 0.3.8
@YoshitakaMo traced it down to def batched_gather() in alphafold/model/utils.py 

you need to change:
```jnp.take(p, i, axis=axis)```
to
```jnp.take(p, i, axis=axis, mode="clip")```

https://jax.readthedocs.io/en/latest/changelog.html#jax-0-3-8-april-29-2022
The reason this bug occurs is that starting in jax 0.3.8, jnp.take() now returns NaNs for indices that do not exist.

the alphafold pinned version of jax:
<img width="501" alt="image" src="https://user-images.githubusercontent.com/4187522/174230879-a6aae0e5-c3a3-4459-b47a-f840de09df17.png">

the output starting with jax=>0.3.8:
<img width="535" alt="image" src="https://user-images.githubusercontent.com/4187522/174231104-cd55a476-8e8e-4344-991e-12d5b328cae3.png">

**Comment by Htomlinson14** [comment]
Thanks for this suggestion! This has been fixed in https://github.com/deepmind/alphafold/releases/tag/v2.2.4
