### ISSUE TITLE
AttributeError: module 'jaxlib.pocketfft' has no attribute 'pocketfft'

### ISSUE THREAD

**Issue by Cozmm** [deepmind/alphafold#515]
Hi, 
while trying to run alpha fold on wsl with the following command : 

docker/run_docker.py 
--fasta_paths=test.faa  \
--max_template_date=2022-06-20  \
 --db_preset=reduced_dbs \
--model_preset=monomer \
--data_dir=/mnt/d/bdd/ 

my databases seemed to be ok : 

I0621 08:53:04.706321 140132597880640 run_docker.py:113] Mounting /mnt/wsl/docker-desktop-bind-mounts/Ubuntu/e57b3e898498e83a2664754df629383dc3e176211d7a71400da5c40c6109af8a -> /mnt/fasta_path_0
I0621 08:53:04.707824 140132597880640 run_docker.py:113] Mounting /mnt/d/bdd/uniref90 -> /mnt/uniref90_database_path
I0621 08:53:04.708882 140132597880640 run_docker.py:113] Mounting /mnt/d/bdd/mgnify -> /mnt/mgnify_database_path
I0621 08:53:04.709391 140132597880640 run_docker.py:113] Mounting /mnt/d/bdd -> /mnt/data_dir
I0621 08:53:04.709931 140132597880640 run_docker.py:113] Mounting /mnt/d/bdd/pdb_mmcif/mmcif_files -> /mnt/template_mmcif_dir
I0621 08:53:04.710874 140132597880640 run_docker.py:113] Mounting /mnt/d/bdd/pdb_mmcif -> /mnt/obsolete_pdbs_path
I0621 08:53:04.711456 140132597880640 run_docker.py:113] Mounting /mnt/d/bdd/pdb70 -> /mnt/pdb70_database_path
I0621 08:53:04.712447 140132597880640 run_docker.py:113] Mounting /mnt/d/bdd/small_bfd -> /mnt/small_bfd_database_path
I0621 08:53:06.373428 140132597880640 run_docker.py:255] /sbin/ldconfig.real: /usr/lib/x86_64-linux-gnu/libcuda.so.1 is not a symbolic link
I0621 08:53:06.373654 140132597880640 run_docker.py:255]

but then i got this issue :

I0621 08:53:06.983418 140132597880640 run_docker.py:255] Traceback (most recent call last):
I0621 08:53:06.983701 140132597880640 run_docker.py:255] File "/app/alphafold/run_alphafold.py", line 37, in <module>
I0621 08:53:06.983829 140132597880640 run_docker.py:255] from alphafold.model import data
I0621 08:53:06.983942 140132597880640 run_docker.py:255] File "/app/alphafold/alphafold/model/data.py", line 19, in <module>
I0621 08:53:06.984042 140132597880640 run_docker.py:255] from alphafold.model import utils
I0621 08:53:06.984129 140132597880640 run_docker.py:255] File "/app/alphafold/alphafold/model/utils.py", line 22, in <module>
I0621 08:53:06.984225 140132597880640 run_docker.py:255] import haiku as hk
I0621 08:53:06.984316 140132597880640 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/haiku/__init__.py", line 17, in <module>
I0621 08:53:06.984405 140132597880640 run_docker.py:255] from haiku import data_structures
I0621 08:53:06.984505 140132597880640 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/haiku/data_structures.py", line 17, in <module>
I0621 08:53:06.984632 140132597880640 run_docker.py:255] from haiku._src.data_structures import to_immutable_dict
I0621 08:53:06.984747 140132597880640 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/haiku/_src/data_structures.py", line 30, in <module>
I0621 08:53:06.984860 140132597880640 run_docker.py:255] from haiku._src import utils
I0621 08:53:06.984965 140132597880640 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/haiku/_src/utils.py", line 24, in <module>
I0621 08:53:06.985076 140132597880640 run_docker.py:255] import jax
I0621 08:53:06.985179 140132597880640 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/jax/__init__.py", line 108, in <module>
I0621 08:53:06.985273 140132597880640 run_docker.py:255] from .experimental.maps import soft_pmap
I0621 08:53:06.985368 140132597880640 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/jax/experimental/maps.py", line 25, in <module>
I0621 08:53:06.985467 140132597880640 run_docker.py:255] from .. import numpy as jnp
I0621 08:53:06.985567 140132597880640 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/jax/numpy/__init__.py", line 16, in <module>
I0621 08:53:06.985681 140132597880640 run_docker.py:255] from . import fft
I0621 08:53:06.985782 140132597880640 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/jax/numpy/fft.py", line 17, in <module>
I0621 08:53:06.985883 140132597880640 run_docker.py:255] from jax._src.numpy.fft import (
I0621 08:53:06.985981 140132597880640 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/jax/_src/numpy/fft.py", line 19, in <module>
I0621 08:53:06.986096 140132597880640 run_docker.py:255] from jax import lax
I0621 08:53:06.986198 140132597880640 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/jax/lax/__init__.py", line 330, in <module>
I0621 08:53:06.986300 140132597880640 run_docker.py:255] from jax._src.lax.fft import (
I0621 08:53:06.986401 140132597880640 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/jax/_src/lax/fft.py", line 144, in <module>
I0621 08:53:06.986495 140132597880640 run_docker.py:255] xla.backend_specific_translations['cpu'][fft_p] = pocketfft.pocketfft
I0621 08:53:06.986621 140132597880640 run_docker.py:255] AttributeError: module 'jaxlib.pocketfft' has no attribute 'pocketfft'

I tried to find what it means but got no result,
thanks for your help

**Comment by epenning** [comment]
Although I am not using Docker, I had this error recently - it happens when there's a version incompatibility between jax and jaxlib. You should probably make sure you're using the latest Alphafold version, and consider if the solution provided here might fix your issue too: https://github.com/deepmind/alphafold/issues/510

**Comment by Cozmm** [comment]
it worked well, thanks
