### ISSUE TITLE
AlphaFold Colab ValueError Step 5

### ISSUE THREAD

**Issue by theflyelectric** [deepmind/alphafold#519]
Can someone explain why this error occurred?
I would also like to know how to fix it. Should I just with run_relax turned off?
Thanks,
Nigel

AMBER relaxation: 86%
6/7 [elapsed: 30:40 remaining: 04:45]
/usr/local/lib/python3.7/dist-packages/jax/_src/tree_util.py:189: FutureWarning: jax.tree_util.tree_multimap() is deprecated. Please use jax.tree_util.tree_map() instead as a drop-in replacement.
  'instead as a drop-in replacement.', FutureWarning)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-5-f89616eedc2d>](https://localhost:8080/#) in <module>()
     88         max_outer_iterations=3,
     89         use_gpu=True)
---> 90     relaxed_pdb, _, _ = amber_relaxer.process(prot=unrelaxed_proteins[best_model_name])
     91   else:
     92     print('Warning: Running without the relaxation stage.')

2 frames
[/opt/conda/lib/python3.7/site-packages/alphafold/relax/amber_minimize.py](https://localhost:8080/#) in _run_one_iteration(pdb_string, max_iterations, tolerance, stiffness, restraint_set, max_attempts, use_gpu, exclude_residues)
    417       logging.info(e)
    418   if not minimized:
--> 419     raise ValueError(f"Minimization failed after {max_attempts} attempts.")
    420   ret["opt_time"] = time.time() - start
    421   ret["min_attempts"] = attempts

ValueError: Minimization failed after 100 attempts.

**Comment by CameronWeller** [comment]
having the same issue. looks like some dependency is out of date. Kinda have to just wait for the devs to fix it it seems. Or, hopefully someone posts a workaround.

**Comment by Htomlinson14** [comment]
Thanks for raising this issue! Closing as this duplicates https://github.com/deepmind/alphafold/issues/383
