### ISSUE TITLE
run alphafold2 error"AttributeError: module 'jaxlib.pocketfft' has no attribute 'pocketfft'"

### ISSUE THREAD

**Issue by zcswnm** [deepmind/alphafold#523]
(alphafold) [zcs@love alphafold]$ python3 docker/run_docker.py --fasta_paths=H.fasta --max_template_date=2020-05-14
/home/zcs/anaconda3/envs/alphafold/lib/python3.7/site-packages/absl/flags/_validators.py:206: UserWarning: Flag --data_dir has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  'command line!' % flag_name)
I0630 03:14:13.838727 139649146304320 run_docker.py:113] Mounting /mnt/data1/alphafold -> /mnt/fasta_path_0
I0630 03:14:13.838894 139649146304320 run_docker.py:113] Mounting /mnt/data1/database/uniref90 -> /mnt/uniref90_database_path
I0630 03:14:13.838981 139649146304320 run_docker.py:113] Mounting /mnt/data1/database/mgnify -> /mnt/mgnify_database_path
I0630 03:14:13.839050 139649146304320 run_docker.py:113] Mounting /mnt/data1/database -> /mnt/data_dir
I0630 03:14:13.839133 139649146304320 run_docker.py:113] Mounting /mnt/data1/database/pdb_mmcif/mmcif_files -> /mnt/template_mmcif_dir
I0630 03:14:13.839210 139649146304320 run_docker.py:113] Mounting /mnt/data1/database/pdb_mmcif -> /mnt/obsolete_pdbs_path
I0630 03:14:13.839290 139649146304320 run_docker.py:113] Mounting /mnt/data1/database/pdb70 -> /mnt/pdb70_database_path
I0630 03:14:13.839372 139649146304320 run_docker.py:113] Mounting /mnt/data1/database/uniclust30/uniclust30_2018_08 -> /mnt/uniclust30_database_path
I0630 03:14:13.839447 139649146304320 run_docker.py:113] Mounting /mnt/data1/database/bfd -> /mnt/bfd_database_path
I0630 03:14:15.125524 139649146304320 run_docker.py:255] Traceback (most recent call last):
I0630 03:14:15.125784 139649146304320 run_docker.py:255] File "/app/alphafold/run_alphafold.py", line 37, in <module>
I0630 03:14:15.125889 139649146304320 run_docker.py:255] from alphafold.model import data
I0630 03:14:15.125967 139649146304320 run_docker.py:255] File "/app/alphafold/alphafold/model/data.py", line 19, in <module>
I0630 03:14:15.126039 139649146304320 run_docker.py:255] from alphafold.model import utils
I0630 03:14:15.126106 139649146304320 run_docker.py:255] File "/app/alphafold/alphafold/model/utils.py", line 22, in <module>
I0630 03:14:15.126170 139649146304320 run_docker.py:255] import haiku as hk
I0630 03:14:15.126261 139649146304320 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/haiku/__init__.py", line 17, in <module>
I0630 03:14:15.126324 139649146304320 run_docker.py:255] from haiku import data_structures
I0630 03:14:15.126392 139649146304320 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/haiku/data_structures.py", line 17, in <module>
I0630 03:14:15.126454 139649146304320 run_docker.py:255] from haiku._src.data_structures import to_immutable_dict
I0630 03:14:15.126514 139649146304320 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/haiku/_src/data_structures.py", line 30, in <module>
I0630 03:14:15.126573 139649146304320 run_docker.py:255] from haiku._src import utils
I0630 03:14:15.126633 139649146304320 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/haiku/_src/utils.py", line 24, in <module>
I0630 03:14:15.126695 139649146304320 run_docker.py:255] import jax
I0630 03:14:15.126755 139649146304320 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/jax/__init__.py", line 108, in <module>
I0630 03:14:15.126816 139649146304320 run_docker.py:255] from .experimental.maps import soft_pmap
I0630 03:14:15.126875 139649146304320 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/jax/experimental/maps.py", line 25, in <module>
I0630 03:14:15.126934 139649146304320 run_docker.py:255] from .. import numpy as jnp
I0630 03:14:15.126993 139649146304320 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/jax/numpy/__init__.py", line 16, in <module>
I0630 03:14:15.127053 139649146304320 run_docker.py:255] from . import fft
I0630 03:14:15.127113 139649146304320 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/jax/numpy/fft.py", line 17, in <module>
I0630 03:14:15.127171 139649146304320 run_docker.py:255] from jax._src.numpy.fft import (
I0630 03:14:15.127231 139649146304320 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/jax/_src/numpy/fft.py", line 19, in <module>
I0630 03:14:15.127290 139649146304320 run_docker.py:255] from jax import lax
I0630 03:14:15.127350 139649146304320 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/jax/lax/__init__.py", line 330, in <module>
I0630 03:14:15.127413 139649146304320 run_docker.py:255] from jax._src.lax.fft import (
I0630 03:14:15.127472 139649146304320 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/jax/_src/lax/fft.py", line 144, in <module>
I0630 03:14:15.127532 139649146304320 run_docker.py:255] xla.backend_specific_translations['cpu'][fft_p] = pocketfft.pocketfft
I0630 03:14:15.127591 139649146304320 run_docker.py:255] AttributeError: module 'jaxlib.pocketfft' has no attribute 'pocketfft'
(alphafold) [zcs@love alphafold]$

*https://github.com/deepmind/alphafold/issues/510  not work

**Comment by tomwardio** [comment]
Hello @zcswnm,

This should now be resolved, but you might need to rebuild your docker image.

Thanks for the report!
