### ISSUE TITLE
ValueError: Could not find path to the "jackhmmer" binary. Make sure it is installed on your system

### ISSUE THREAD

**Issue by pariskang** [deepmind/alphafold#525]
I installed alphafold2 step by step, but I found an error as the following:
```
(base) [root@adf alphafold-2.2.0]#  bash run_alphafold.sh -d ./alphafold_data/ -o ./dummy_test/ -f ./example/query.fasta -t 2020-05-14 -g False
which: no jackhmmer in (/root/miniconda3/bin:/root/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)
Traceback (most recent call last):
  File "/root/alphafold-2.2.0/run_alphafold.py", line 422, in <module>
    app.run(main)
  File "/root/miniconda3/lib/python3.9/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/root/miniconda3/lib/python3.9/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/root/alphafold-2.2.0/run_alphafold.py", line 285, in main
    raise ValueError(f'Could not find path to the "{tool_name}" binary. Make '
ValueError: Could not find path to the "jackhmmer" binary. Make sure it is installed on your system.
```
How to resolve this problem, I sincerely need u help. Thank u~

**Comment by tomwardio** [comment]
Hi @pariskang, 

Thanks for the question! We'd strongly recommend using the Docker workflow, as this will ensure jackhmmr is installed correctly within the running container, but if not you can pass `--jackhmmer_binary_path=/path/to/jackhmmr` to set the location of the jackhmmr binary.

Hope that helps!

**Comment by aloshbau** [comment]
Where does one get the jackhmmer binary? I haven't been able to find it.

**Comment by Augustin-Zidek** [comment]
We recommend using the Docker container which installs it for you. But if you prefer not to, you can install jackhmmer using this command (on a Debian-based Linux distribution): 

```bash
sudo apt install hmmer
```
