### ISSUE TITLE
GDT Score

### ISSUE THREAD

**Issue by Planet-KIM** [deepmind/alphafold#53]
Hi,
I want to get gdt and lddt score 
- How to get gdt and lddt score 
   - use the pdb files
   - and any support this issue?

please give me this solutions.

**Comment by abridgland** [comment]
There are a number of external tools available for computing these metrics. For GDT consider using LGA (http://proteinmodel.org/AS2TS/LGA/lga.html) and for lDDT consider the SWISS-MODEL server (https://swissmodel.expasy.org/lddt). These tools are reference implementations for their respective metrics. Please note that the lDDT scores will be computed on all atoms, not just C-alpha atoms. When we use the latter in our paper it is referred to as lDDT-Ca.
