### ISSUE TITLE
Is Linux ARM64 an officially supported platform ?

### ISSUE THREAD

**Issue by julien-faye** [deepmind/alphafold#530]
Hello,

I'd like to ask whether Linux ARM64 is an officially supported CPU platform ?

I've seen someone else tried to build it on ARM64 and faced a problem: https://github.com/deepmind/alphafold/issues/528

Thank you!

**Comment by tomwardio** [comment]
Hi @julien-faye, Thanks for the question! Unfortunately we currently don't support running AlphaFold on ARM machines. We don't believe there's anything with the AlphaFold codebase itself that explicitly requires x86 CPUs, but getting all the transitive dependencies to support ARM might prove challenging.

Would be interested if you were able to get this working!

Thanks
