### ISSUE TITLE
ValueError: Minimization failed after 100 attempts.

### ISSUE THREAD

**Issue by Belfield** [deepmind/alphafold#534]
Alphafold team I need help please. The Colab tream say my issue is not related to them and need your assistance.

When running protein structure predictions I'm getting the following error (see screengrab) on the last part of the analyses (Run AlphaFold and download prediction). I have repeated this several times and get the same error (in Chrome, Firefox, using Linux and Windows). I didn't used to get this issue when I was running similar jobs ~6 months so I presume something has changed.

Can you help?

![image](https://user-images.githubusercontent.com/108519825/178957264-ff9faa0c-b8a9-4abc-b8b5-584b17e8c799.png)

**Comment by Htomlinson14** [comment]
Closing as this duplicates https://github.com/deepmind/alphafold/issues/383
