### ISSUE TITLE
V2.2.2  Hash Sum mismatch

### ISSUE THREAD

**Issue by Sabertli** [deepmind/alphafold#535]
Hi, alphafold team

When I installed version 2.2.2, it was prompted that the hash value of a certain file is wrong. How should I solve it?

Sending build context to Docker daemon  13.35MB
Step 1/18 : ARG CUDA=11.1.1
Step 2/18 : FROM nvidia/cuda:${CUDA}-cudnn8-runtime-ubuntu18.04
11.1.1-cudnn8-runtime-ubuntu18.04: Pulling from nvidia/cuda
40dd5be53814: Pull complete
b6f8396e6f3c: Pull complete
3c444d3bc7b1: Pull complete
4b27d231d2cd: Pull complete
035911917ab7: Pull complete
d2cd37fe954b: Pull complete
6f16144b6364: Pull complete
ddab44155817: Pull complete
Digest: sha256:996e500db01edfaa1c87f5772b367896e1b87dba556279756b086250be2c1ae1
Status: Downloaded newer image for nvidia/cuda:11.1.1-cudnn8-runtime-ubuntu18.04
 ---> a6b5e71b6a39
Step 3/18 : ARG CUDA
 ---> Running in cedd091cff5e
Removing intermediate container cedd091cff5e
 ---> 93dd130bd1b1
Step 4/18 : SHELL ["/bin/bash", "-c"]
 ---> Running in 73e36e38e9c6
Removing intermediate container 73e36e38e9c6
 ---> 873a8d6a6c5a
Step 5/18 : RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y         build-essential         cmake         cuda-command-line-tools-$(cut -f1,2 -d- <<< ${CUDA//./-})         git         hmmer         kalign         tzdata         wget     && rm -rf /var/lib/apt/lists/*
 ---> Running in 618eb197c449
Get:1 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:2 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  InRelease [1581 B]
Get:4 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Packages [816 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:6 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [22.8 kB]
Get:7 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:8 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [1057 kB]
Get:9 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
Err:4 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  Packages
  Hash Sum mismatch
  Hashes of expected file:
   - Filesize:815853 [weak]
   - SHA256:66e891d82894f08ecedac13c4e058ce5ea21882032c66a5b4d981cc2552f94a1
   - SHA1:7cc76dbdc9d32d50cf5a1d377c8c877bcef23dcd [weak]
   - MD5Sum:dc953e306c3b53f23ccdbe433881a800 [weak]
  Hashes of received file:
   - SHA256:989834105adeb2987d44b3da1cf0bd621e4a86a260f5790dd2f865105d231efe
   - SHA1:da0b54ecbb7f3dd76602bef508e9a8df901d1cd2 [weak]
   - MD5Sum:aa04b5a6fb8ceb8c4c0676ce2c144903 [weak]
   - Filesize:815853 [weak]
  Last modification reported: Mon, 11 Jul 2022 23:01:57 +0000
  Release file created at: Tue, 12 Jul 2022 15:01:44 +0000
Get:10 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [1526 kB]
Get:11 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [2897 kB]
Get:12 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1344 kB]
Get:13 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
Get:14 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
Get:15 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [3329 kB]
Get:16 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [1101 kB]
Get:17 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [29.8 kB]
Get:18 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [2302 kB]
Get:19 http://archive.ubuntu.com/ubuntu bionic-backports/main amd64 Packages [12.2 kB]
Get:20 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [12.9 kB]
Fetched 26.5 MB in 12s (2292 kB/s)
Reading package lists...
E: Failed to fetch https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/Packages.gz  Hash Sum mismatch
   Hashes of expected file:
    - Filesize:815853 [weak]
    - SHA256:66e891d82894f08ecedac13c4e058ce5ea21882032c66a5b4d981cc2552f94a1
    - SHA1:7cc76dbdc9d32d50cf5a1d377c8c877bcef23dcd [weak]
    - MD5Sum:dc953e306c3b53f23ccdbe433881a800 [weak]
   Hashes of received file:
    - SHA256:989834105adeb2987d44b3da1cf0bd621e4a86a260f5790dd2f865105d231efe
    - SHA1:da0b54ecbb7f3dd76602bef508e9a8df901d1cd2 [weak]
    - MD5Sum:aa04b5a6fb8ceb8c4c0676ce2c144903 [weak]
    - Filesize:815853 [weak]
   Last modification reported: Mon, 11 Jul 2022 23:01:57 +0000
   Release file created at: Tue, 12 Jul 2022 15:01:44 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
The command '/bin/bash -c apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y         build-essential         cmake         cuda-command-line-tools-$(cut -f1,2 -d- <<< ${CUDA//./-})         git         hmmer         kalign         tzdata         wget     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

**Comment by Augustin-Zidek** [comment]
This has been fixed on nVIDIA's side. Feel free to reopen this issue if still a problem.
