### ISSUE TITLE
Running out of memory when predicting large multimers

### ISSUE THREAD

**Issue by yogesh-dhande** [deepmind/alphafold#536]
I was able to run predictions for a dimer with 4 cores and 16 GB memory. When I attempted that with a multimer that contains 12 units, the process runs out of memory even if I upgrade the machine to 16 cores and 128 GB of memory and reduce the number of predictions from the default value to 1. Has anyone else tried predicting large complexes like these and are there any known limitations in running predictions like these? Any ideas on how to improve the memory usage or guidelines on how much memory is needed for a task like this would be very valuable. Thank you!

**Comment by lucajovine** [comment]
You could try OpenFold (https://github.com/aqlaboratory/openfold) with described tweaks to minimize memory usage...

**Comment by BastianKalcher** [comment]
Hi yogesh-dhande,

I also had problems with the RAM. 
After I increased the value of the following variable from 4 to 10, the calculation worked for me. 
 https://github.com/deepmind/alphafold/blob/624a44966619218f546852863f0f9220fc9c2849/docker/run_docker.py#L247

From the Jax documentation it appears that this value determines how much memory may be used to cache the data that does not fit into the VRAM.

https://jax.readthedocs.io/en/latest/gpu_memory_allocation.html#gpu-memory-allocation

In my case, I have a Quadro RTX 5000 with 16GB VRAM 
 'XLA_PYTHON_CLIENT_MEM_FRACTION': '10.0', -> My AlphaFOld is allowed to use 160GB RAM for swapping.
64 Hyper-V virtual cores and 160GB RAM. 
I am using Hyper-V Server 2019 as host system. 
The VM is running Ubuntu 22.04

**Comment by Augustin-Zidek** [comment]
Closing this issue for now, feel free to reopen if this is still a problem.
