### ISSUE TITLE
Bad performance on RTX A6000 during relax ?

### ISSUE THREAD

**Issue by tubiana** [deepmind/alphafold#537]
Hi :) 

I'm using AlphaFold2 Through a local colabfold implementation on Singularity (the receipe is present here https://github.com/tubiana/colabfold_singularity). 
I know it's colabfold and not alphafold directly but I'm experiencing performance issues, especially for relaxation with openMM where the relaxation time is 3 to 4 times slower than on another desktop with an RTXA5000 or RTXA4000.  The usage of the GPU is also very low (< 5%).
It's the same singularity image than it is used and I only experience issue on the desktop with an RTXA6000. The only difference is the cuda driver version (I used the 515 while other desktop are a bit older). 

Is anyone got similar issue ? Because I tried to reinstall singularity, all the drivers, use openMM 7.7 (and patching Alphafold relaxation code) but without luck and I'm bit lost in what I should try now...

Thank you for your help :) 
Thibault.

**Comment by tomwardio** [comment]
Hi @tubiana, Thanks for reporting the issue!

Unfortunately we're currently not able to support testing newer Ampere based GPUs, but are unaware of any issues pertaining specifically to the AlphaFold model itself. For OpenMM issues, please do raise a bug with their team to fix any slowdowns.

Thanks!

**Comment by tubiana** [comment]
Thank you very much for your answer, I will open an issue in their github :smiley: 

Best,
Thibault.
