### ISSUE TITLE
Docker build issue with 2.2.2 Step 14

### ISSUE THREAD

**Issue by MrDotOne** [deepmind/alphafold#538]
Just pulled down the latest from github and tried to build 2.2.2 but got this error:

Step 14/18 : RUN patch -p0 < /app/alphafold/docker/openmm.patch
 ---> Running in 08a4b9f1fb2c
/bin/bash: /app/alphafold/docker/openmm.patch: No such file or directory
The command '/bin/bash -c patch -p0 < /app/alphafold/docker/openmm.patch' returned a non-zero code: 1

**Comment by tomwardio** [comment]
Hi @MrDotOne, this error usually happens if you try to build the image not from the root directory. The following commands should work:

```
$ git clone https://github.com/deepmind/alphafold.git
$ cd alphafold
$ docker build -f docker/Dockerfile -t alphafold .
```

Hope that helps!
