### ISSUE TITLE
Error encountered in build the Nvidia-container-toolkit

### ISSUE THREAD

**Issue by sippmilkwolf** [deepmind/alphafold#540]
Dear all:
    I encountered an error when I try to test whether the nvidia-container-toolkit will rum properly. The error message is as follows:

"# docker run --rm --gpus all nvidia/cuda:11.0-base nvidia-smi
Unable to find image 'nvidia/cuda:11.0-base' locally
11.0-base: Pulling from nvidia/cuda
54ee1f796a1e: Pull complete 
f7bfea53ad12: Pull complete 
46d371e02073: Pull complete 
b66c17bbf772: Pull complete 
3642f1a6dfb3: Pull complete 
e5ce55b8b4b9: Pull complete 
155bc0332b0a: Pull complete 
Digest: sha256:774ca3d612de15213102c2dbbba55df44dc5cf9870ca2be6c6e9c627fa63d67a
Status: Downloaded newer image for nvidia/cuda:11.0-base
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: driver rpc error: timed out: unknown."
"
The docker has correctly installed and gives a correct response when I use 'hello-world" tested it 
I run the nvidia-smi, and got the following information:
" NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6 "

THere are eight A40 GPU on the server.

The information about install nvidia-docker2 is as follows:

"# dnf install -y nvidia-docker2
Last metadata expiration check: 1:59:23 ago on Thu 21 Jul 2022 12:27:22 PM CST.
Module yaml error: Unexpected key in data: static_context [line 9 col 3]
Module yaml error: Unexpected key in data: static_context [line 9 col 3]
Dependencies resolved.
=======================================================================================================================
 Package                          Architecture  Version                  Repository                               Size
=======================================================================================================================
Installing:
 nvidia-docker2                   noarch        2.11.0-1                 libnvidia-container                      12 k
Installing dependencies:
 libnvidia-container-tools        x86_64        1.10.0-1                 libnvidia-container                      53 k
 libnvidia-container1             x86_64        1.10.0-1                 libnvidia-container                     1.0 M
 nvidia-container-toolkit         x86_64        1.11.0-0.1.rc.1          libnvidia-container-experimental        3.2 M

Transaction Summary
=======================================================================================================================
Install  4 Packages

Total download size: 4.3 M
Installed size: 12 M
Downloading Packages:
(1/4): nvidia-docker2-2.11.0-1.noarch.rpm                                               23 kB/s |  12 kB     00:00    
(2/4): libnvidia-container-tools-1.10.0-1.x86_64.rpm                                    89 kB/s |  53 kB     00:00    
(3/4): libnvidia-container1-1.10.0-1.x86_64.rpm                                        1.2 MB/s | 1.0 MB     00:00    
(4/4): nvidia-container-toolkit-1.11.0-0.1.rc.1.x86_64.rpm                             2.3 MB/s | 3.2 MB     00:01    
-----------------------------------------------------------------------------------------------------------------------
Total                                                                                  2.3 MB/s | 4.3 MB     00:01     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                               1/1 
  Installing       : libnvidia-container1-1.10.0-1.x86_64                                                          1/4 
  Running scriptlet: libnvidia-container1-1.10.0-1.x86_64                                                          1/4 
  Installing       : libnvidia-container-tools-1.10.0-1.x86_64                                                     2/4 
  Installing       : nvidia-container-toolkit-1.11.0-0.1.rc.1.x86_64                                               3/4 
  Installing       : nvidia-docker2-2.11.0-1.noarch                                                                4/4 
  Running scriptlet: nvidia-container-toolkit-1.11.0-0.1.rc.1.x86_64                                               4/4 
  Running scriptlet: nvidia-docker2-2.11.0-1.noarch                                                                4/4 
  Verifying        : libnvidia-container-tools-1.10.0-1.x86_64                                                     1/4 
  Verifying        : libnvidia-container1-1.10.0-1.x86_64                                                          2/4 
  Verifying        : nvidia-docker2-2.11.0-1.noarch                                                                3/4 
  Verifying        : nvidia-container-toolkit-1.11.0-0.1.rc.1.x86_64                                               4/4 
Installed products updated.

Installed:
  libnvidia-container-tools-1.10.0-1.x86_64                       libnvidia-container1-1.10.0-1.x86_64                
  nvidia-container-toolkit-1.11.0-0.1.rc.1.x86_64                 nvidia-docker2-2.11.0-1.noarch                      

Complete!"

Anyone can give me a help? Thanks

**Comment by tomwardio** [comment]
Thanks for the feedback! We recently moved to a better supported `11.1.1` cuda base image, which should resolve this issue.

**Comment by ulupo** [comment]
Should the relevant line in the [README](https://github.com/deepmind/alphafold/blob/4494af848e41f3acd51a190d4c78d38cb1a7f85d/README.md?plain=1#L52) be updated to reflect this change?  I also encountered an error (though not exactly the same as @sippmilkwolf's) when running that line, but things so far seem error-free when replacing `11.0` with `11.1.1`.
