### ISSUE TITLE
hhalignment.cpp:3539: MergeMasterSlave error

### ISSUE THREAD

**Issue by derf0** [deepmind/alphafold#541]
I have generated more than 20,000 structures with alphafold, now running alphafold 2.2.1, but have three particular protein sequences, Ashbya gossypii proteins AFL131W,  ADL346W, and AGR113W, where alphafold fails, and I get the following error message. This problem also occurred when running alphafold 2.1. While these proteins are on the large size, I have generated hundreds of structures for proteins larger than these.

The brief version of the error message is:

...
I0721 07:22:02.937924 139643735058240 run_docker.py:256] - 11:21:59.174 ERROR: Error in /tmp/hh-suite/src/hhalignment.cpp:3539: MergeMasterSlave:
I0721 07:22:02.937985 139643735058240 run_docker.py:256]
I0721 07:22:02.938046 139643735058240 run_docker.py:256] - 11:21:59.174 ERROR: 	did not find 243 match states in sequence 1 of SRR5579859_7281350. Sequence:
...

Two problems. 
1) How to fix this problem.

2) Why is the term "MasterSlave" used in the code? I personally find the term offensive and inappropriate to use in the code at all, and particularly to use as an output message.

linked below is the more complete error message:

[AGR113Wnohup.txt](https://github.com/deepmind/alphafold/files/9167877/AGR113Wnohup.txt)

**Comment by Augustin-Zidek** [comment]
Could you raise this issue with the authors of the [HH Suite](https://github.com/soedinglab/hh-suite)? HHAlign is part of HHBlits, which is a third party protein sequence search tool that we use within AlphaFold. This is also the reason the problematic term is used in the code - it is not in code that we produced.

**Comment by aseedb** [comment]
Is it possible to re-open this issue? it seems to stem partially from the way alphafold launches hhalignment

**Comment by TizianaRicciardelli** [comment]
Hi, I have tried to model different multimers but only on 1 a got an error. The AF2 multimer version is 2.3.1 and I got this error:

ERROR: Error in /opt/conda/conda-bld/hhsuite_1645696999782/work/src/hhalignment.cpp:3539: MergeMasterSlave:
ERROR:   did not find 240 match states in sequence 1 of SRR5262245_40669095.

Does anyone know how to solve this issue?

**Comment by mtiberti** [comment]
Hi, we are also having this same issue - I agree maybe worth reopening? In the [HHsuite issue connected to this](https://github.com/soedinglab/hh-suite/issues/277) they say 

> The multi-database feature of HH-suite seems the be the problem. If you search against the Uniref30 and the BFD separately it works without crashing. Please do not use this feature.

is AlphaFold still using it?
