### ISSUE TITLE
can not download files using specific taxid

### ISSUE THREAD

**Issue by Ezio0o** [deepmind/alphafold#545]
I follow the instruction and fix the internet bugs, however, the gsutil code doesn't work for me
for example: 
`gsutil -m cp gs://public-datasets-deepmind-alphafold/proteomes/proteome-tax_id-10002-*.tar .`

It gives out an error that said:
"tuple index out of range
CommandException: 1 file/object could not be transferred."

**Comment by Ezio0o** [comment]
my gsutil version is 5.11

**Comment by Augustin-Zidek** [comment]
Hi @Ezio0o, I can't unfortunately reproduce that, the command runs fine for me and downloads the file.

Two questions:
1. Is it possible that access to Google Cloud is being blocked by your network/firewall?
2. Have you set up `gsutil` correctly?

**Comment by Ezio0o** [comment]
sorry I still cannot find a solution. I reinstall the Google Cloud and set the proxy, and run 'gcloud init' it shows:
"Your Google Cloud SDK is configured and ready to use!".

However, the same error shows again, and the output of my proxy shows:
"[2022-07-29 20:08:19] [ERROR] 127.0.0.1:50320 unknown protocol
[2022-07-29 20:08:19] [INFO] 127.0.0.1:50320 disconnected, 0 bytes received, 0 bytes sent, lasted for 0 seconds"

I set the socks5 as the gcloud configuration of proxy, and it works fine during the gcloud authentication. Maybe it is caused by the different protocols gsutil use? Since I am new to Google Cloud, sorry I am not familiar with that.

**Comment by Ezio0o** [comment]
Cheers, I finally made it by using the `gcloud alpha storage cp` command instead of the `gsutil cp` option. Still confuse about the error information. 

Maybe adding this `gcloud alpha` command line option is helpful for Chinese researchers like me.
