### ISSUE TITLE
Does AFDB include the virus proteomes?

### ISSUE THREAD

**Issue by Ezio0o** [deepmind/alphafold#547]
I browsed the AFDB bucket and searched using the virus taxid (species or strain level), but I can not retrieve their proteome. for example, the SARS-related virus with `taxid:694009` is unavailable.

I use the `gcloud` batch download for thousands of virus species, but surprisingly, there is no record. Should I download these viral proteomes using their `Uniprot id`? Or AlphaFold DB does not include viral proteomes for some reason?

Appreciate your help in advance!

**Comment by Augustin-Zidek** [comment]
No, viral proteomes are not included, see https://alphafold.com/faq#faq-1 for more details.
