### ISSUE TITLE
New MacBook pros?

### ISSUE THREAD

**Issue by Wonderingforever** [deepmind/alphafold#553]
Does alpha fold work on the newest (2022) MacBooks that have the proprietary Apple m1 chips in them?  I saw it wanted Nivda gpu seeing if there was a work around

**Comment by tomwardio** [comment]
Hi @Wonderingforever, unfortunately we only support Linux operating systems, as per [README](https://github.com/deepmind/alphafold/blob/main/README.md#first-time-setup).
