### ISSUE TITLE
AlphaFold Colab: Minimisation failed after 100 runs - disable amber relax - prediction does not download

### ISSUE THREAD

**Issue by sw249** [deepmind/alphafold#555]
I have had this issue for a while now using AlphaFold Colab (for some reason not AlphaFold2 Colab though) where I try and run a prediction, it tells me minimisation has failed after 100 runs which leads me to disable run relax and then it creates the prediction but doesn't download it
(I am connected to a custom GCE VM)
Anyone got any ideas about what the issue might be?

**Comment by Htomlinson14** [comment]
Thanks for raising this! This duplicates https://github.com/deepmind/alphafold/issues/483 and https://github.com/deepmind/alphafold/issues/550 so closing this issue.
