### ISSUE TITLE
Alphafold 2 error - ValueError: Minimization failed after 100 attempts.

### ISSUE THREAD

**Issue by saarajgupta** [deepmind/alphafold#556]
Hello, I tried running Alphafold2 on colab tool. At the 5th step, I got the error: ValueError: Minimization failed after 100 attempts.
The structure was not obtained.
How to resolve this?  Please refer the pic attached.
![image](https://user-images.githubusercontent.com/16572083/183074847-4dd8ec19-233d-4b49-89e6-5f7fedbf9ec8.png)

**Comment by Htomlinson14** [comment]
Closing as this issue duplicates https://github.com/deepmind/alphafold/issues/550
