### ISSUE TITLE
Setup - Download error CUID#7...unable to get local issuer certificate

### ISSUE THREAD

**Issue by SodaPopinski** [deepmind/alphafold#559]
Very new to Linux, and a bit overwhelmed.  Setting things up on my home desktop with a new Ubuntu 22.04 installation.  While going through the installation instructions and while running download_all_data.sh, I got this error:
08/10 16:40:53 [ERROR] CUID#7 - Download aborted. URI=http://wwwuser.gwdg.de/~compbiol/data/hhsuite/databases/hhsuite_dbs/old-releases/pdb70_from_mmcif_200401.tar.gz
Exception: [AbstractCommand.cc:351] errorCode=1 URI=https://wwwuser.gwdg.de/~compbiol/data/hhsuite/databases/hhsuite_dbs/old-releases/pdb70_from_mmcif_200401.tar.gz
  -> [SocketCore.cc:1021] errorCode=1 SSL/TLS handshake failure: unable to get local issuer certificate
  
Upon running download_pdb70.sh by itself, I got the same error.

**Comment by LeeCW89** [comment]
Got the same error for this file. I just right click on the link showing in your terminal and download it manually. Then don't forget to extract it to pdb70 folder that the script created already.

**Comment by SodaPopinski** [comment]
> Got the same error for this file. I just right click on the link showing in your terminal and download it manually. Then don't forget to extract it to pdb70 folder that the script created already.

Thanks.  I'll give it a try.

**Comment by SodaPopinski** [comment]
I pasted into the browser to download, and it was incredibly slow. I ended up --check-certificate=false to the bash file, and re-ran the script download_all script with all the downloads but pdb70 commented out. That did the trick.
