### ISSUE TITLE
Parse failed with pdb_seqres.txt

### ISSUE THREAD

**Issue by SodaPopinski** [deepmind/alphafold#560]
Hey folks,

Every time I try AlphaFold 2 with the multimer flag set, I get this error:
Parse failed (sequence file /mnt/pdb_seqres_database_path/pdb_seqres.txt):
Line 1360400: illegal character 0

Should I re-download pdb_seqres.txt?

I tried opening up pdb_seqres.txt in Text Editor, but it froze before fully loading it.

**Comment by SodaPopinski** [comment]
I'm not sure if this is really a fix, but at least I got past that issue before running into another one.

I loaded up the file in Nano, and deleted 1360399 and 1360400.  Then I got the error again on line 1364492, and did the same thing.

I re-ran it and it didn't error out after the usual 15 minutes, so I let the batch of several trimers run overnight.  I may have been pushing things a bit, since I'm using the full database on my single 8-core CPU desktop.  In the morning, it looks like the system rebooted, as all my windows were gone, and Alphafold no longer works.  That's a whole other issue, as my GPU no longer shows up....

**Comment by SodaPopinski** [comment]
So I've got it running now.  If I used the modified pdb_seqres.txt, where I removed the offending lines, it works.  The other issues had to do with an incompatibility with the wrong version of docker and NVidia.

So to re-iterate, I used Nano to delete lines 1360399, 1360400, got the errors at 1364492, so I deleted 1364491 and 1364492.  The first line, of course, had the sequence name, and the second line, had a sequence which included "0" in the sequence.  The "0" was causing the problem.

**Comment by swanss** [comment]
I just had the same issue. I followed your advice and removed lines in `pdb_seqres.txt` corresponding to entries with "0" in the sequence. My error file mentioned a slightly different line number, so I used a vim search (`/^\w*0`) to locate the exact lines.

I think you should re-open this issue. Editing the database file after downloading it works for now, but is not a great long-term solution to the problem.

**Comment by maximinio** [comment]
indeed removing the 4 sequences harboring 0s let it work! thank you

**Comment by ssn1771** [comment]
thanks, removing the lines include "0" works
