### ISSUE TITLE
Protein residue breaks after AMBER relaxation step

### ISSUE THREAD

**Issue by avwillems** [deepmind/alphafold#564]
I'm running alphafold locally on a ubuntu machine equipped with a quadro RTX 5000 GPU. Up until this point there haven't been any issues with the output data, however after my most recent structure prediction of a ~600 residue protein, between the "unrelaxed_model_X.pdb" and "relaxed_model_x.pdb", two of the five predictions have one particular residue (a histidine) broken. Specifically, the τ nitrogen and the 2 carbon of the imidazole ring have swapped positions with the hydrogen atoms that are bound to them (see attached jpg's of the unrelaxed and the relaxed structures). There are no abnormalities in the .fasta file. Is this a known issue in either alphafold or amber? I would be happy to attach any other data or files that might help clarify this.
![relaxed_model_1](https://user-images.githubusercontent.com/111376331/184926648-713ea270-0253-400b-9a20-145aa5a5e07e.png)
![unrelaxed_model_1](https://user-images.githubusercontent.com/111376331/184926656-66859c4f-a63b-4e09-a304-9d9ff7de4c89.png)

**Comment by ValZapod** [comment]
Why do not you report it to Amber?

Attach unrelaxed_model_X.pdb and relaxed_model_x.pdb.

**Comment by ValZapod** [comment]
So can you give pdbs? Is this related? https://twitter.com/structplantbio/status/1598658668576342019?t=bXdGuRHnqY0kI2PNV2SQrw&s=19

**Comment by Augustin-Zidek** [comment]
We fixed this in [v2.3.0](https://github.com/deepmind/alphafold/releases/tag/v2.3.0) - thanks for reporting!
