### ISSUE TITLE
Multimer run seems to be hung

### ISSUE THREAD

**Issue by epetersen-sci** [deepmind/alphafold#565]
I have started a multimer run but it seems to have hung. In my output folder I have the 'unrelaxed...prediction_0.pdb' file, but it's not complete. It's been here for almost a week. 

Since one of the proteins is very large, I tried with a truncated version which also hung in the same place.

Previously, since the proteins are so large, I was getting OOM errors and I have been messing around with unified memory variables. They are currently:
export TF_FORCE_UNIFIED_MEMORY=1
export XLA_PYTHON_CLIENT_MEM_FRACTION=7
export XLA_PYTHON_CLIENT_ALLOCATOR=platform

You can see the runtime here:
![image](https://user-images.githubusercontent.com/111191178/185211266-b7c93db1-d971-475a-bffe-9e1bee02b46f.png)

Here is a screenshot of nvidia-smi to show both what it's doing and what I'm working with:
![image](https://user-images.githubusercontent.com/111191178/185211423-81ae2204-c246-4257-8b84-be26542cda9f.png)
![image](https://user-images.githubusercontent.com/111191178/185211478-f591595c-ed0e-424f-9fa2-659b2ab149ef.png)

I do currently have multiple runs going with different memory variables.

I am using alphafold v2.2.0

**Comment by Augustin-Zidek** [comment]
We improved the GPU usage for AlphaFold-Multimer in [v2.3.0](https://github.com/deepmind/alphafold/releases/tag/v2.3.0) - so that might help.

Judging by the output though, this might be a relaxation issue, so you could also try running with `--run_relax=false`.

**Comment by Augustin-Zidek** [comment]
Closing this issue, feel free to reopen this issue or open a new issue if this is still a problem.
