### ISSUE TITLE
About AlphaDatabase

### ISSUE THREAD

**Issue by nnnwyn** [deepmind/alphafold#567]
Hello everyone, I saw that AlphaDataBase showed the structure with the 30000AAs. I am wondering how they did this. Is it an end to end structure prediction? If so,  how to deal with the CUDA Out of Memory Error?

**Comment by Augustin-Zidek** [comment]
I recommend taking a look at https://alphafold.com/faq#faq-2. Note that longer human proteins were folded as fragments.

**Comment by nnnwyn** [comment]
Great answer, thanks.
