### ISSUE TITLE
Is there any advice on reassemble the splitted protein chunks?

### ISSUE THREAD

**Issue by nnnwyn** [deepmind/alphafold#568]
Hello, I used your way to predict long protein. I am wondering is there any advice on reassemble the splitted protein chunks?

> Hi,
> 
> Thanks for your question. This does indeed look like the GPU OOM error, and for a protein of this size (2500 amino acids), it is not uncommon. Unfortunately, running the inference on the CPU (with RAM) would not be a good option either, as it would take many-many hours, if not days. 
> 
> You could try folding the protein in chunks by manually splitting it and then re-assembling the results, but this approach involves manual interventions and has not been validated for quality. 
> 
> Thus, I'm afraid there are no good solutions, other than getting access to a GPU with more memory.

_Originally posted by @AnyaP in https://github.com/deepmind/alphafold/issues/417#issuecomment-1091992815_

**Comment by Augustin-Zidek** [comment]
I recommend taking a look at https://github.com/deepmind/alphafold/issues/172#issuecomment-920083414.
