### ISSUE TITLE
bug in backbone_loss of alphafold_multimer

### ISSUE THREAD

**Issue by sokrypton** [deepmind/alphafold#570]
`frame_aligned_point_error()` function does not have a `loss_unit_distance` argument.
Should `loss_unit_distance` be `length_scale` ?

<img width="548" alt="image" src="https://user-images.githubusercontent.com/4187522/185800985-71b8883d-56fc-4141-ae3b-5306295812a7.png">
<img width="583" alt="image" src="https://user-images.githubusercontent.com/4187522/185801010-ca888b21-fcbb-40b9-ab42-eef6d6e8a74f.png">

**Comment by Htomlinson14** [comment]
Thanks for this suggestion! This has been fixed in https://github.com/deepmind/alphafold/releases/tag/v2.2.4
