### ISSUE TITLE
Jackhmmer/UniRef90 Issue

### ISSUE THREAD

**Issue by ena2016** [deepmind/alphafold#571]
Hi all, I ran into this issue running .fasta for a DRA/B pMHC TRA/B complex model.

### Input- 
`python3 docker/run_docker.py \
  --data_dir=/media/eric/NewCupcake \
  --output_dir=/media/eric/OldCupcake/tmp/alphafold \
  --fasta_paths=/media/eric/OldCupcake/FastaFiles/TRpep79_HLA–DQB10201DQA10201.fasta\
    --max_template_date=2020-08-20 \
    --model_preset=multimer
`
### Output-
`I0822 10:24:30.640870 139730341103424 run_docker.py:255] max_sto_sequences=self.uniref_max_hits)
I0822 10:24:30.640907 139730341103424 run_docker.py:255] File "/app/alphafold/alphafold/data/pipeline.py", line 94, in run_msa_tool
I0822 10:24:30.640944 139730341103424 run_docker.py:255] result = msa_runner.query(input_fasta_path, max_sto_sequences)[0]  # pytype: disable=wrong-arg-count
I0822 10:24:30.640981 139730341103424 run_docker.py:255] File "/app/alphafold/alphafold/data/tools/jackhmmer.py", line 172, in query
I0822 10:24:30.641017 139730341103424 run_docker.py:255] input_fasta_path, self.database_path, max_sequences)
I0822 10:24:30.641054 139730341103424 run_docker.py:255] File "/app/alphafold/alphafold/data/tools/jackhmmer.py", line 143, in _query_chunk
I0822 10:24:30.641093 139730341103424 run_docker.py:255] 'Jackhmmer failed\nstderr:\n%s\n' % stderr.decode('utf-8'))
I0822 10:24:30.641130 139730341103424 run_docker.py:255] RuntimeError: Jackhmmer failed
I0822 10:24:30.641168 139730341103424 run_docker.py:255] stderr:
I0822 10:24:30.641204 139730341103424 run_docker.py:255] Fatal exception (source file p7_alidisplay.c, line 728):
I0822 10:24:30.641240 139730341103424 run_docker.py:255] backconverted trace didn't end at expected place on model (UniRef90_S9X7U2/chain_D)
I0822 10:24:30.641277 139730341103424 run_docker.py:255] 
I0822 10:24:30.641314 139730341103424 run_docker.py:255] 
`

I'm running source code from v2.2.2
I tried opening UniRef90 and deleting the sequences but it did not work.
I tried redownloading from UnitProt and that didn't solve the issue.
I redownloaded the whole database and this did not work either. 

I'm stuck on what to try next.  Any help is appreciated.

UPDATE 8/23/2022
The culprit is the MHCII molecules these are the sequences:
>DQA102:01
`EDIVADHVASYGVNLYQSYGPSGQFTHEFDGDEEFYVDLERKETVWKLPLFHRLR.FDPQFALTNIAVLKHNLNILIKRSNSTAATNEVPEVTVFSKSPVTLGQPNTLICLVDNIFPPVVNITWLSNGHSVTEGVSETSFLSKSDHSFFKISYLTFLPSADEIYDCKVEHWGLDEPLLKHWEPEIPAPMSEVDGGGGGAQLEKELQALEKENAQLEWELQALEKELAQ`
>DQB102:01
`RDSPEDFVYQFKGMCYFTNGTERVRLVSRSIYNREEIVRFDSDVGEFRAVTLLGLPAAEYWNSQKDILERKRAAVDRVCRHNYQLELRTTLQRRVEPTVTISPSRTEALNHHNLLVCSVTDFYPAQIKVRWFRNDQEETAGVVSTPLIRNGDWTFQILVMLEMTPQRGDVYTCHVEHPSLQSPITVEWRAQSESAQSKVDGGGGGAQLKKKLQALKKKNAQLKWKLQALKKKLAQ`

Is there a way to have Jackhmmer skip sequences that have utf-8 errors?

Update 8/24/2022
I was reading HMMER Userguide and I'm going to try --noali flag, will update to see if it worked.

Update 8/24/2022
It didn't work. :/

Gonna try these next..
Find any utf-8 in fasta file
`grep -axv '.*' /media/eric/NewCupcake/uniref90/uniref90.fasta`

Remove any utf-8 in fasta file
`iconv -f utf-8 -t utf-8 -c /media/eric/NewCupcake/uniref90/uniref90.fasta  -o /media/eric/NewCupcake/uniref90/uniref90v2.fasta`

Update:
It also did not work

**Comment by ena2016** [comment]
Okay, I'm running the idea that this runtime error could be a lack of vRAM. Going to plug in my dinosaur GPU acc and see if it does the trick. I'm praying it doesn't short or explode while running.

**Comment by ena2016** [comment]
Updated to v2.2.3 and attempted to truncate the TR/pMHCII as much as possible. it gets stuck on the alpha chain and stops there. I'm switching the order to beta first. Probably wont do anything but trying everything here.

**Comment by ena2016** [comment]
Figured out my issue, my TRpMHCII complex sequences had to be cleaned up using one of the scripts above. Everything is working now. 

It could be an interesting feature to have AF validate fasta files before running the MSAs, there are open source Fasta validators on GitHub too, maybe a collab, then create a script to clean the files before the run. 

Script flow
Check/validate fasta file -> clean up fasta file script (while depositing cleaned up fasta file in the output path, to create reproducibility folder) -> run AF

This was a headache but definitely made me go through all the issues on AF related to jackhmmer, will leave this issue here in case people run into same error.

**Comment by fuxuliu** [comment]
@ena2016 hi, I also meet this issue, and I try some method, but all not work, would you share your methods or relative scripts about `Check/validate fasta file -> clean up fasta file script`.
Thanks.
