### ISSUE TITLE
DeepMind AlphaFold2 colab notebook already crashes during 3rd party software installation cell

### ISSUE THREAD

**Issue by MWNautilus** [deepmind/alphafold#573]
Here is the log:

`17%
17/100 [elapsed: 05:10 remaining: 02:43]

Found existing installation: tensorflow 2.8.2+zzzcolab20220719082949
Uninstalling tensorflow-2.8.2+zzzcolab20220719082949:
  Successfully uninstalled tensorflow-2.8.2+zzzcolab20220719082949
Reading package lists...
Building dependency tree...
Reading state information...
The following package was automatically installed and is no longer required:
  libnvidia-common-460
Use 'sudo apt autoremove' to remove it.
The following additional packages will be installed:
  libdivsufsort3
Suggested packages:
  hmmer-doc
The following NEW packages will be installed:
  hmmer libdivsufsort3
0 upgraded, 2 newly installed, 0 to remove and 20 not upgraded.
Need to get 1,164 kB of archives.
After this operation, 11.9 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic/universe amd64 libdivsufsort3 amd64 2.0.1-3 [44.4 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic/universe amd64 hmmer amd64 3.1b2+dfsg-5ubuntu1 [1,119 kB]
Fetched 1,164 kB in 0s (9,405 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 2.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
Selecting previously unselected package libdivsufsort3:amd64.
(Reading database ... 155676 files and directories currently installed.)
Preparing to unpack .../libdivsufsort3_2.0.1-3_amd64.deb ...
Unpacking libdivsufsort3:amd64 (2.0.1-3) ...
Selecting previously unselected package hmmer.
Preparing to unpack .../hmmer_3.1b2+dfsg-5ubuntu1_amd64.deb ...
Unpacking hmmer (3.1b2+dfsg-5ubuntu1) ...
Setting up libdivsufsort3:amd64 (2.0.1-3) ...
Setting up hmmer (3.1b2+dfsg-5ubuntu1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Processing triggers for libc-bin (2.27-3ubuntu1.5) ...
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting py3dmol
  Downloading py3Dmol-1.8.1-py2.py3-none-any.whl (6.5 kB)
Installing collected packages: py3dmol
Successfully installed py3dmol-1.8.1
PREFIX=/opt/conda
Unpacking payload ...
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /opt/conda

  added / updated specs:
    - _libgcc_mutex==0.1=main
    - _openmp_mutex==4.5=1_gnu
    - brotlipy==0.7.0=py39h27cfd23_1003
    - ca-certificates==2022.3.29=h06a4308_1
    - certifi==2021.10.8=py39h06a4308_2
    - cffi==1.15.0=py39hd667e15_1
    - charset-normalizer==2.0.4=pyhd3eb1b0_0
    - colorama==0.4.4=pyhd3eb1b0_0
    - conda-content-trust==0.1.1=pyhd3eb1b0_0
    - conda-package-handling==1.8.1=py39h7f8727e_0
    - conda==4.12.0=py39h06a4308_0
    - cryptography==36.0.0=py39h9ce1e76_0
    - idna==3.3=pyhd3eb1b0_0
    - ld_impl_linux-64==2.35.1=h7274673_9
    - libffi==3.3=he6710b0_2
    - libgcc-ng==9.3.0=h5101ec6_17
    - libgomp==9.3.0=h5101ec6_17
    - libstdcxx-ng==9.3.0=hd4cf53a_17
    - ncurses==6.3=h7f8727e_2
    - openssl==1.1.1n=h7f8727e_0
    - pip==21.2.4=py39h06a4308_0
    - pycosat==0.6.3=py39h27cfd23_0
    - pycparser==2.21=pyhd3eb1b0_0
    - pyopenssl==22.0.0=pyhd3eb1b0_0
    - pysocks==1.7.1=py39h06a4308_0
    - python==3.9.12=h12debd9_0
    - readline==8.1.2=h7f8727e_1
    - requests==2.27.1=pyhd3eb1b0_0
    - ruamel_yaml==0.15.100=py39h27cfd23_0
    - setuptools==61.2.0=py39h06a4308_0
    - six==1.16.0=pyhd3eb1b0_1
    - sqlite==3.38.2=hc218d9a_0
    - tk==8.6.11=h1ccaba5_0
    - tqdm==4.63.0=pyhd3eb1b0_0
    - tzdata==2022a=hda174b7_0
    - urllib3==1.26.8=pyhd3eb1b0_0
    - wheel==0.37.1=pyhd3eb1b0_0
    - xz==5.2.5=h7b6447c_0
    - yaml==0.2.5=h7b6447c_0
    - zlib==1.2.12=h7f8727e_1

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  _openmp_mutex      pkgs/main/linux-64::_openmp_mutex-4.5-1_gnu
  brotlipy           pkgs/main/linux-64::brotlipy-0.7.0-py39h27cfd23_1003
  ca-certificates    pkgs/main/linux-64::ca-certificates-2022.3.29-h06a4308_1
  certifi            pkgs/main/linux-64::certifi-2021.10.8-py39h06a4308_2
  cffi               pkgs/main/linux-64::cffi-1.15.0-py39hd667e15_1
  charset-normalizer pkgs/main/noarch::charset-normalizer-2.0.4-pyhd3eb1b0_0
  colorama           pkgs/main/noarch::colorama-0.4.4-pyhd3eb1b0_0
  conda              pkgs/main/linux-64::conda-4.12.0-py39h06a4308_0
  conda-content-tru~ pkgs/main/noarch::conda-content-trust-0.1.1-pyhd3eb1b0_0
  conda-package-han~ pkgs/main/linux-64::conda-package-handling-1.8.1-py39h7f8727e_0
  cryptography       pkgs/main/linux-64::cryptography-36.0.0-py39h9ce1e76_0
  idna               pkgs/main/noarch::idna-3.3-pyhd3eb1b0_0
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.35.1-h7274673_9
  libffi             pkgs/main/linux-64::libffi-3.3-he6710b0_2
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-9.3.0-h5101ec6_17
  libgomp            pkgs/main/linux-64::libgomp-9.3.0-h5101ec6_17
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.3.0-hd4cf53a_17
  ncurses            pkgs/main/linux-64::ncurses-6.3-h7f8727e_2
  openssl            pkgs/main/linux-64::openssl-1.1.1n-h7f8727e_0
  pip                pkgs/main/linux-64::pip-21.2.4-py39h06a4308_0
  pycosat            pkgs/main/linux-64::pycosat-0.6.3-py39h27cfd23_0
  pycparser          pkgs/main/noarch::pycparser-2.21-pyhd3eb1b0_0
  pyopenssl          pkgs/main/noarch::pyopenssl-22.0.0-pyhd3eb1b0_0
  pysocks            pkgs/main/linux-64::pysocks-1.7.1-py39h06a4308_0
  python             pkgs/main/linux-64::python-3.9.12-h12debd9_0
  readline           pkgs/main/linux-64::readline-8.1.2-h7f8727e_1
  requests           pkgs/main/noarch::requests-2.27.1-pyhd3eb1b0_0
  ruamel_yaml        pkgs/main/linux-64::ruamel_yaml-0.15.100-py39h27cfd23_0
  setuptools         pkgs/main/linux-64::setuptools-61.2.0-py39h06a4308_0
  six                pkgs/main/noarch::six-1.16.0-pyhd3eb1b0_1
  sqlite             pkgs/main/linux-64::sqlite-3.38.2-hc218d9a_0
  tk                 pkgs/main/linux-64::tk-8.6.11-h1ccaba5_0
  tqdm               pkgs/main/noarch::tqdm-4.63.0-pyhd3eb1b0_0
  tzdata             pkgs/main/noarch::tzdata-2022a-hda174b7_0
  urllib3            pkgs/main/noarch::urllib3-1.26.8-pyhd3eb1b0_0
  wheel              pkgs/main/noarch::wheel-0.37.1-pyhd3eb1b0_0
  xz                 pkgs/main/linux-64::xz-5.2.5-h7b6447c_0
  yaml               pkgs/main/linux-64::yaml-0.2.5-h7b6447c_0
  zlib               pkgs/main/linux-64::zlib-1.2.12-h7f8727e_1

Preparing transaction: done
Executing transaction: done
installation finished.
WARNING:
    You currently have a PYTHONPATH environment variable set. This may cause
    unexpected behavior when running the Python interpreter in Miniconda3.
    For best results, please verify that your PYTHONPATH only points to
    directories of packages that are compatible with the Python interpreter
    in Miniconda3: /opt/conda
env: PATH=/opt/conda/bin:/opt/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tools/node/bin:/tools/google-cloud-sdk/bin
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /opt/conda

  added / updated specs:
    - conda

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _openmp_mutex-5.1          |            1_gnu          21 KB
    ca-certificates-2022.07.19 |       h06a4308_0         124 KB
    certifi-2022.6.15          |   py39h06a4308_0         153 KB
    cffi-1.15.1                |   py39h74dc2b5_0         228 KB
    conda-4.14.0               |   py39h06a4308_0         915 KB
    cryptography-37.0.1        |   py39h9ce1e76_0         1.3 MB
    cytoolz-0.11.0             |   py39h27cfd23_0         350 KB
    ld_impl_linux-64-2.38      |       h1181459_1         654 KB
    libgcc-ng-11.2.0           |       h1234567_1         5.3 MB
    libgomp-11.2.0             |       h1234567_1         474 KB
    libstdcxx-ng-11.2.0        |       h1234567_1         4.7 MB
    ncurses-6.3                |       h5eee18b_3         781 KB
    openssl-1.1.1q             |       h7f8727e_0         2.5 MB
    pip-22.1.2                 |   py39h06a4308_0         2.5 MB
    requests-2.28.1            |   py39h06a4308_0          92 KB
    setuptools-63.4.1          |   py39h06a4308_0         1.1 MB
    sqlite-3.39.2              |       h5082296_0         1.1 MB
    tk-8.6.12                  |       h1ccaba5_0         3.0 MB
    toolz-0.11.2               |     pyhd3eb1b0_0          49 KB
    tqdm-4.64.0                |   py39h06a4308_0         126 KB
    urllib3-1.26.11            |   py39h06a4308_0         182 KB
    xz-5.2.5                   |       h7f8727e_1         339 KB
    zlib-1.2.12                |       h7f8727e_2         106 KB
    ------------------------------------------------------------
                                           Total:        25.9 MB

The following NEW packages will be INSTALLED:

  cytoolz            pkgs/main/linux-64::cytoolz-0.11.0-py39h27cfd23_0
  toolz              pkgs/main/noarch::toolz-0.11.2-pyhd3eb1b0_0

The following packages will be REMOVED:

  colorama-0.4.4-pyhd3eb1b0_0
  conda-content-trust-0.1.1-pyhd3eb1b0_0
  six-1.16.0-pyhd3eb1b0_1

The following packages will be UPDATED:

  _openmp_mutex                                   4.5-1_gnu --> 5.1-1_gnu
  ca-certificates                      2022.3.29-h06a4308_1 --> 2022.07.19-h06a4308_0
  certifi                          2021.10.8-py39h06a4308_2 --> 2022.6.15-py39h06a4308_0
  cffi                                1.15.0-py39hd667e15_1 --> 1.15.1-py39h74dc2b5_0
  conda                               4.12.0-py39h06a4308_0 --> 4.14.0-py39h06a4308_0
  cryptography                        36.0.0-py39h9ce1e76_0 --> 37.0.1-py39h9ce1e76_0
  ld_impl_linux-64                        2.35.1-h7274673_9 --> 2.38-h1181459_1
  libgcc-ng                               9.3.0-h5101ec6_17 --> 11.2.0-h1234567_1
  libgomp                                 9.3.0-h5101ec6_17 --> 11.2.0-h1234567_1
  libstdcxx-ng                            9.3.0-hd4cf53a_17 --> 11.2.0-h1234567_1
  ncurses                                    6.3-h7f8727e_2 --> 6.3-h5eee18b_3
  openssl                                 1.1.1n-h7f8727e_0 --> 1.1.1q-h7f8727e_0
  pip                                 21.2.4-py39h06a4308_0 --> 22.1.2-py39h06a4308_0
  requests           pkgs/main/noarch::requests-2.27.1-pyh~ --> pkgs/main/linux-64::requests-2.28.1-py39h06a4308_0
  setuptools                          61.2.0-py39h06a4308_0 --> 63.4.1-py39h06a4308_0
  sqlite                                  3.38.2-hc218d9a_0 --> 3.39.2-h5082296_0
  tk                                      8.6.11-h1ccaba5_0 --> 8.6.12-h1ccaba5_0
  tqdm               pkgs/main/noarch::tqdm-4.63.0-pyhd3eb~ --> pkgs/main/linux-64::tqdm-4.64.0-py39h06a4308_0
  urllib3            pkgs/main/noarch::urllib3-1.26.8-pyhd~ --> pkgs/main/linux-64::urllib3-1.26.11-py39h06a4308_0
  xz                                       5.2.5-h7b6447c_0 --> 5.2.5-h7f8727e_1
  zlib                                    1.2.12-h7f8727e_1 --> 1.2.12-h7f8727e_2

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /opt/conda

  added / updated specs:
    - openmm=7.5.1
    - pdbfixer
    - python=3.7

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2022.6.15  |       ha878542_0         149 KB  conda-forge
    certifi-2022.6.15          |   py37h89c1867_0         155 KB  conda-forge
    cffi-1.14.6                |   py37hc58025e_0         225 KB  conda-forge
    colorama-0.4.5             |     pyhd8ed1ab_0          18 KB  conda-forge
    conda-4.14.0               |   py37h89c1867_0        1010 KB  conda-forge
    conda-package-handling-1.8.1|   py37h540881e_1         1.0 MB  conda-forge
    cryptography-37.0.2        |   py37h38fbfac_0         1.5 MB  conda-forge
    cudatoolkit-11.7.0         |      hd8887f6_10       831.6 MB  conda-forge
    fftw-3.3.10                |nompi_h77c792f_102         6.4 MB  conda-forge
    libblas-3.9.0              |15_linux64_openblas          12 KB  conda-forge
    libcblas-3.9.0             |15_linux64_openblas          12 KB  conda-forge
    libgfortran-ng-12.1.0      |      h69a702a_16          23 KB  conda-forge
    libgfortran5-12.1.0        |      hdcd56e2_16         1.8 MB  conda-forge
    liblapack-3.9.0            |15_linux64_openblas          12 KB  conda-forge
    libopenblas-0.3.20         |pthreads_h78a6416_0        10.1 MB  conda-forge
    numpy-1.21.6               |   py37h976b520_0         6.1 MB  conda-forge
    ocl-icd-2.3.1              |       h7f98852_0         119 KB  conda-forge
    ocl-icd-system-1.0.0       |                1           4 KB  conda-forge
    openmm-7.5.1               |   py37h96c4ddf_1        10.7 MB  conda-forge
    openssl-1.1.1o             |       h166bdaf_0         2.1 MB  conda-forge
    pdbfixer-1.7               |     pyhd3deb0d_0         167 KB  conda-forge
    pip-22.2.2                 |     pyhd8ed1ab_0         1.5 MB  conda-forge
    pycosat-0.6.3              |py37h540881e_1010         107 KB  conda-forge
    pysocks-1.7.1              |   py37h89c1867_5          28 KB  conda-forge
    python-3.7.10              |hffdb5ce_100_cpython        57.3 MB  conda-forge
    python_abi-3.7             |          2_cp37m           4 KB  conda-forge
    requests-2.28.1            |     pyhd8ed1ab_0          53 KB  conda-forge
    ruamel_yaml-0.15.80        |py37h5e8e339_1006         270 KB  conda-forge
    setuptools-65.2.0          |   py37h89c1867_0         1.4 MB  conda-forge
    six-1.16.0                 |     pyh6c4a22f_0          14 KB  conda-forge
    tqdm-4.64.0                |     pyhd8ed1ab_0          81 KB  conda-forge
    urllib3-1.25.8             |   py37hc8dfbb8_1         160 KB  conda-forge
    ------------------------------------------------------------
                                           Total:       934.1 MB

The following NEW packages will be INSTALLED:

  colorama           conda-forge/noarch::colorama-0.4.5-pyhd8ed1ab_0
  cudatoolkit        conda-forge/linux-64::cudatoolkit-11.7.0-hd8887f6_10
  fftw               conda-forge/linux-64::fftw-3.3.10-nompi_h77c792f_102
  libblas            conda-forge/linux-64::libblas-3.9.0-15_linux64_openblas
  libcblas           conda-forge/linux-64::libcblas-3.9.0-15_linux64_openblas
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-12.1.0-h69a702a_16
  libgfortran5       conda-forge/linux-64::libgfortran5-12.1.0-hdcd56e2_16
  liblapack          conda-forge/linux-64::liblapack-3.9.0-15_linux64_openblas
  libopenblas        conda-forge/linux-64::libopenblas-0.3.20-pthreads_h78a6416_0
  numpy              conda-forge/linux-64::numpy-1.21.6-py37h976b520_0
  ocl-icd            conda-forge/linux-64::ocl-icd-2.3.1-h7f98852_0
  ocl-icd-system     conda-forge/linux-64::ocl-icd-system-1.0.0-1
  openmm             conda-forge/linux-64::openmm-7.5.1-py37h96c4ddf_1
  pdbfixer           conda-forge/noarch::pdbfixer-1.7-pyhd3deb0d_0
  python_abi         conda-forge/linux-64::python_abi-3.7-2_cp37m
  six                conda-forge/noarch::six-1.16.0-pyh6c4a22f_0

The following packages will be REMOVED:

  brotlipy-0.7.0-py39h27cfd23_1003
  cytoolz-0.11.0-py39h27cfd23_0

The following packages will be UPDATED:

  conda-package-han~ pkgs/main::conda-package-handling-1.8~ --> conda-forge::conda-package-handling-1.8.1-py37h540881e_1
  cryptography       pkgs/main::cryptography-37.0.1-py39h9~ --> conda-forge::cryptography-37.0.2-py37h38fbfac_0
  pip                pkgs/main/linux-64::pip-22.1.2-py39h0~ --> conda-forge/noarch::pip-22.2.2-pyhd8ed1ab_0
  pycosat            pkgs/main::pycosat-0.6.3-py39h27cfd23~ --> conda-forge::pycosat-0.6.3-py37h540881e_1010
  pysocks            pkgs/main::pysocks-1.7.1-py39h06a4308~ --> conda-forge::pysocks-1.7.1-py37h89c1867_5
  setuptools         pkgs/main::setuptools-63.4.1-py39h06a~ --> conda-forge::setuptools-65.2.0-py37h89c1867_0

The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates    pkgs/main::ca-certificates-2022.07.19~ --> conda-forge::ca-certificates-2022.6.15-ha878542_0
  certifi            pkgs/main::certifi-2022.6.15-py39h06a~ --> conda-forge::certifi-2022.6.15-py37h89c1867_0
  cffi                pkgs/main::cffi-1.15.1-py39h74dc2b5_0 --> conda-forge::cffi-1.14.6-py37hc58025e_0
  conda              pkgs/main::conda-4.14.0-py39h06a4308_0 --> conda-forge::conda-4.14.0-py37h89c1867_0
  openssl              pkgs/main::openssl-1.1.1q-h7f8727e_0 --> conda-forge::openssl-1.1.1o-h166bdaf_0
  python                pkgs/main::python-3.9.12-h12debd9_0 --> conda-forge::python-3.7.10-hffdb5ce_100_cpython
  requests           pkgs/main/linux-64::requests-2.28.1-p~ --> conda-forge/noarch::requests-2.28.1-pyhd8ed1ab_0
  ruamel_yaml        pkgs/main::ruamel_yaml-0.15.100-py39h~ --> conda-forge::ruamel_yaml-0.15.80-py37h5e8e339_1006
  tqdm               pkgs/main/linux-64::tqdm-4.64.0-py39h~ --> conda-forge/noarch::tqdm-4.64.0-pyhd8ed1ab_0
  urllib3            pkgs/main::urllib3-1.26.11-py39h06a43~ --> conda-forge::urllib3-1.25.8-py37hc8dfbb8_1

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions of the CUDA End User License Agreement (EULA): https://docs.nvidia.com/cuda/eula/index.html

done
Retrieving notices: ...working... failed
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/conda/exceptions.py", line 1125, in __call__
  File "/opt/conda/lib/python3.9/site-packages/conda/cli/main.py", line 86, in main_subshell
  File "/opt/conda/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 93, in do_call
  File "/opt/conda/lib/python3.9/site-packages/conda/notices/core.py", line 75, in wrapper
  File "/opt/conda/lib/python3.9/site-packages/conda/notices/core.py", line 39, in display_notices
  File "/opt/conda/lib/python3.9/site-packages/conda/notices/http.py", line 36, in get_notice_responses
  File "/opt/conda/lib/python3.9/site-packages/conda/notices/http.py", line 39, in <genexpr>
  File "/opt/conda/lib/python3.9/concurrent/futures/_base.py", line 609, in result_iterator
  File "/opt/conda/lib/python3.9/concurrent/futures/_base.py", line 446, in result
  File "/opt/conda/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
  File "/opt/conda/lib/python3.9/concurrent/futures/thread.py", line 58, in run
  File "/opt/conda/lib/python3.9/site-packages/conda/notices/http.py", line 42, in <lambda>
  File "/opt/conda/lib/python3.9/site-packages/conda/notices/cache.py", line 37, in wrapper
  File "/opt/conda/lib/python3.9/site-packages/conda/notices/http.py", line 58, in get_channel_notice_response
  File "/opt/conda/lib/python3.9/site-packages/requests/sessions.py", line 600, in get
  File "/opt/conda/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
  File "/opt/conda/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
  File "/opt/conda/lib/python3.9/site-packages/requests/adapters.py", line 460, in send
  File "/opt/conda/lib/python3.9/site-packages/requests/adapters.py", line 263, in cert_verify
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /opt/conda/lib/python3.9/site-packages/certifi/cacert.pem

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.9/site-packages/conda/cli/main.py", line 129, in main
  File "/opt/conda/lib/python3.9/site-packages/conda/exceptions.py", line 1413, in conda_exception_handler
  File "/opt/conda/lib/python3.9/site-packages/conda/exceptions.py", line 1128, in __call__
  File "/opt/conda/lib/python3.9/site-packages/conda/exceptions.py", line 1170, in handle_exception
  File "/opt/conda/lib/python3.9/site-packages/conda/exceptions.py", line 1181, in handle_unexpected_exception
  File "/opt/conda/lib/python3.9/site-packages/conda/exceptions.py", line 1251, in print_unexpected_error_report
ModuleNotFoundError: No module named 'conda.cli.main_info'

---------------------------------------------------------------------------

CalledProcessError                        Traceback (most recent call last)

[<ipython-input-1-0c215f21152d>](https://localhost:8080/#) in <module>
     35       PATH=get_ipython().run_line_magic('env', 'PATH')
     36       get_ipython().run_line_magic('env', 'PATH=/opt/conda/bin:{PATH}')
---> 37       get_ipython().run_line_magic('shell', 'conda update -qy conda            && conda install -qy -c conda-forge              python=3.7              openmm=7.5.1              pdbfixer')
     38       pbar.update(80)
     39 

2 frames

[/usr/local/lib/python3.7/dist-packages/google/colab/_system_commands.py](https://localhost:8080/#) in check_returncode(self)
    133     if self.returncode:
    134       raise subprocess.CalledProcessError(
--> 135           returncode=self.returncode, cmd=self.args, output=self.output)
    136 
    137   def _repr_pretty_(self, p, cycle):  # pylint:disable=unused-argument

CalledProcessError: Command 'conda update -qy conda            && conda install -qy -c conda-forge              python=3.7              openmm=7.5.1              pdbfixer' returned non-zero exit status 1.`

Michael.

**Comment by Meghpal** [comment]
The latest version (4.14.0) of conda is in some way causing this. This is auto-installed when we run `conda update -qy conda` in the "Install 3rd part software" section. There is a workaround:

In the section you want to locate this piece of code:

```python
%shell conda update -qy conda \
          && conda install -qy -c conda-forge \
            python=3.7 \
            openmm=7.5.1 \
            pdbfixer
```

and change it with 

```python
%shell conda install-qy conda=4.13.0 \
          && conda install -qy -c conda-forge \
            python=3.7 \
            openmm=7.5.1 \
            pdbfixer
```

**Comment by michaelkeith18** [comment]
Note: the workaround code should have a space between "install" and "-qy"!

**Comment by Meghpal** [comment]
Thanks Michael! I've corrected the snippet for everyone's comfort.

**Comment by Augustin-Zidek** [comment]
Fixed in https://github.com/deepmind/alphafold/commit/dad1f286aeaa158702a98aeee0f5661f30de6da8. Many thanks @Meghpal.

**Comment by tsucheta** [comment]
my !gget setup alphafold on google colab invariably fails with these comments

Thu Oct  6 12:51:12 2022 ERROR 
        Please install AlphaFold third-party dependency openmm v7.5.1 by running the following command from the command line: 
        'conda install -qy conda==4.13.0 && conda install -qy -c conda-forge openmm=7.5.1' 
        (Recommendation: Follow with 'conda update -qy conda' to update conda to the latest version afterwards.)

Inspite of me doing 

!conda install -qy conda==4.13.0 && conda install -qy -c conda-forge openmm=7.5.1
followed  by !conda update -qy conda

Any suggestions as what might begoing wrong? My runs on 

!conda install -qy conda==4.13.0 && conda install -qy -c conda-forge openmm=7.5.1
!conda update -qy conda 

always runs fine without having any brush of error.

Thanks in advance

Sucheta

**Comment by lauraluebbert** [comment]
> my !gget setup alphafold on google colab invariably fails with these comments
> 
> Thu Oct 6 12:51:12 2022 ERROR Please install AlphaFold third-party dependency openmm v7.5.1 by running the following command from the command line: 'conda install -qy conda==4.13.0 && conda install -qy -c conda-forge openmm=7.5.1' (Recommendation: Follow with 'conda update -qy conda' to update conda to the latest version afterwards.)
> 
> Inspite of me doing
> 
> !conda install -qy conda==4.13.0 && conda install -qy -c conda-forge openmm=7.5.1 followed by !conda update -qy conda
> 
> Any suggestions as what might begoing wrong? My runs on
> 
> !conda install -qy conda==4.13.0 && conda install -qy -c conda-forge openmm=7.5.1 !conda update -qy conda
> 
> always runs fine without having any brush of error.
> 
> Thanks in advance



> my !gget setup alphafold on google colab invariably fails with these comments
> 
> Thu Oct 6 12:51:12 2022 ERROR Please install AlphaFold third-party dependency openmm v7.5.1 by running the following command from the command line: 'conda install -qy conda==4.13.0 && conda install -qy -c conda-forge openmm=7.5.1' (Recommendation: Follow with 'conda update -qy conda' to update conda to the latest version afterwards.)
> 
> Inspite of me doing
> 
> !conda install -qy conda==4.13.0 && conda install -qy -c conda-forge openmm=7.5.1 followed by !conda update -qy conda
> 
> Any suggestions as what might begoing wrong? My runs on
> 
> !conda install -qy conda==4.13.0 && conda install -qy -c conda-forge openmm=7.5.1 !conda update -qy conda
> 
> always runs fine without having any brush of error.
> 
> Thanks in advance
> 
> Sucheta

Hi Sucheta, 

Thank you for your inquiry! [This notebook](https://colab.research.google.com/github/pachterlab/gget_examples/blob/main/gget_alphafold.ipynb) (and [this longer tutorial](https://colab.research.google.com/github/pachterlab/gget_examples/blob/main/protein_structure_prediction_comparison.ipynb)) show how to setup a Colab notebook to use gget alphafold. For gget issues please post the issue on the [gget repo](https://github.com/pachterlab/gget) for a faster response. 

All the best,

Laura
