### ISSUE TITLE
gzip: database//mgnify/mgy_clusters_2018_12.fa.gz: No such file or directory

### ISSUE THREAD

**Issue by tianrenmaogithub** [deepmind/alphafold#575]
I got this error when running download_all_data.sh, which runs download_mgnify.sh.
I looked into the latter and these lines were causing the error.

pushd "${ROOT_DIR}"
gunzip "${ROOT_DIR}/${BASENAME}"
popd

It went to the directory to unzip the file, but the path was wrong. The ${ROOT_DIR}/ should be removed.

**Comment by ena2016** [comment]
Did you run the command line like this. I had the same error but it worked when I assigned a directory.

`download_pdb70.sh directory_path`

**Comment by tianrenmaogithub** [comment]
> Did you run the command line. I had the same error but it worked when I assigned a directory. `/home/usrn/alphafold/scripts/download_pdb70.sh directory_path`
> 
> If you are in the alphafold directory then it should look like this `scripts/download_pdb70.sh directory_path`
> 
> One thing also is that the directory_path should have a lot of storage. I got an error when the directory I chose was sub 2TB, I had to get a 8TB SSD to not run across the same issue using the full database.

Sorry for the typo. I meant download_mgnify.sh should be edited.

**Comment by ena2016** [comment]
Oh it should still work just edit the .sh file and your directory_path. Hopefully it works for you.

**Comment by Augustin-Zidek** [comment]
Did you use full path or relative path? You should use the full directory path for this to work.

**Comment by tianrenmaogithub** [comment]
> Did you use full path or relative path? You should use the full directory path for this to work.

I see. I used a relative path. Thank you!
Since an absolute path is required, the pushd and popd statements are actually removable because gunzip decompresses a zip file in the same place and you don't need to go to that directory.
Because many people prefer to feed a relative path, I think it is better to make it accept relative path by removing the "${ROOT_DIR}/" from the gunzip "${ROOT_DIR}/${BASENAME}" while keeping the pusd and popd. It will work for both absolute and relative paths.
