### ISSUE TITLE
I am using alphafold to predict protein structure. while running the first step, i found the error int he comment. Can anyone help me with this error? 

### ISSUE THREAD

**Issue by jeid94** [deepmind/alphafold#578]
Hello everyone, 

I am using alphafold to predict protein structure. while running the first step, i found the following error. Can anyone helps me please. 

CalledProcessError                        Traceback (most recent call last)
[<ipython-input-1-0c215f21152d>](https://localhost:8080/#) in <module>
     35       PATH=get_ipython().run_line_magic('env', 'PATH')
     36       get_ipython().run_line_magic('env', 'PATH=/opt/conda/bin:{PATH}')
---> 37       get_ipython().run_line_magic('shell', 'conda update -qy conda            && conda install -qy -c conda-forge              python=3.7              openmm=7.5.1              pdbfixer')
     38       pbar.update(80)
     39 

2 frames
[/usr/local/lib/python3.7/dist-packages/google/colab/_system_commands.py](https://localhost:8080/#) in check_returncode(self)
    133     if self.returncode:
    134       raise subprocess.CalledProcessError(
--> 135           returncode=self.returncode, cmd=self.args, output=self.output)
    136 
    137   def _repr_pretty_(self, p, cycle):  # pylint:disable=unused-argument

CalledProcessError: Command 'conda update -qy conda            && conda install -qy -c conda-forge              python=3.7              openmm=7.5.1              pdbfixer' returned non-zero exit status 1.

**Comment by Augustin-Zidek** [comment]
Sorry about this! See https://github.com/deepmind/alphafold/issues/573 for a workaround, we are working on a fix.

**Comment by jeid94** [comment]
> Sorry about this! See #573 for a workaround, we are working on a fix.

thank you !!

**Comment by Augustin-Zidek** [comment]
Fixed in https://github.com/deepmind/alphafold/commit/dad1f286aeaa158702a98aeee0f5661f30de6da8
