### ISSUE TITLE
Merge docking, complexes and homooligomeric prediction (Alphafold DB too)

### ISSUE THREAD

**Issue by ValZapod** [deepmind/alphafold#58]
Read all thread about docking. https://mobile.twitter.com/HawkswoodDrew/status/1419032019313610758

About complexes: https://mobile.twitter.com/sokrypton/status/1417628739828162565

About homooligomeric prediction: https://mobile.twitter.com/sokrypton/status/1418042967517016067

Regeneration of AlphaFold DB is also needed. Will ping @alexbateman1 for Alphafold. It is interesting that your .tar has more folded proteins than DB too!

P.S. The key hack is described here. https://twitter.com/sokrypton/status/1417724691419209728?s=20

P.S.2. See also https://twitter.com/avibpatel_/status/1418675228146900996?s=20

**Comment by huhlim** [comment]
They are their applications of AlphaFold. Not by the AlphaFold team. Someone may use the idea or their [Google Colab services](https://colab.research.google.com/github/sokrypton/ColabFold/blob/main/AlphaFold2.ipynb). However, in my opinion, they should not be merged to the official AlphaFold repository unless the AlphaFold team tested/validated the ideas by themselves.

Also, I guess the AlphaFold team is trying to implement protein complex-version of AlphaFold.

**Comment by ValZapod** [comment]
> their applications

It is just a very small hack see last link in my poat. Docking is just connecting two proteins by hand, BUT IT can work even without that!

**Comment by ValZapod** [comment]
Wow. complexes prediction is pretty good, see https://github.com/normandavey/AlphaFold2-IDR-complex-prediction

https://mobile.twitter.com/_BalintMeszaros/status/1422630616164675595 and even online server.http://slim.icr.ac.uk/projects/alphafold?page=alphafold_IDR_interface_prediction

**Comment by abridgland** [comment]
This repo is an implementation of the published AlphaFold system which was not used for multimeric predictions. We’re really excited by the work that’s been done in this area but since it diverges from the published system we won’t be merging those changes into our codebase.
