### ISSUE TITLE
protein protein interaction Indexeror

### ISSUE THREAD

**Issue by hellorp1990** [deepmind/alphafold#582]
Hi, I am new to protein folding area and I am having a little issue with running protein protein interaction with Alphafold. 

My inputs:

```
 >EUXXXX
MKMASNDATPSDGSTANLVPEVNNEVMALEPVVGAAIAAPVAGQQNVIDPWIRNNFVQAPGGEFTVSPRNAPGEILWSAPLGPDLNPYLSHLARMYNGYAGGFEVQVILAGNAFTAGKIIFAAVPPNFPTEGLSPSQVTMFPHIIVDVRQLEPVLIPLPDVRNNFYHYNQSNDPTIKLIAMLYTPLRANNAGDDVFTVSCRVLTRPSPDFDFIFLVPPTVESRTKPFSVPILTVEEMTNSRFPIPLEKLFTGPSSAFVVQPQNGRCTTDGVL
 >12H
MEWNWVVLFLLSLTAGVYAQGQMQQSGAELVKPKLSCKTSGF
```

I am having an error:  IndexError: list index out of range (i believe this error is  related to input file formatting). 

Can anyone help with this issue?

**Comment by hellorp1990** [comment]
@Augustin-Zidek Yes they are started with > (i added them here as well, but for some reason > is removed from the comment)

**Comment by Augustin-Zidek** [comment]
I see, `>` is a special character in Markdown so it didn't render properly -- I fixed that in your comment. Could you try without spaces before the `>` characters?

**Comment by Augustin-Zidek** [comment]
Could you also post the full command you are using to launch this and the full error?

**Comment by hellorp1990** [comment]
@Augustin-Zidek When i ran the first sequence ( > EUXXXX) alone -monomer pipeline. And it ran fine but when i tried to ran multimer or protein protein interaction pipeline its showed error. 

Full error:
![error](https://user-images.githubusercontent.com/19805255/187233664-ebea41dd-6f8a-479b-ad56-f3efb4f097c8.PNG)

**Comment by hellorp1990** [comment]
@Augustin-Zidek input command:

--fasta_paths=input.fasta \
  --max_template_date=2022-08-29 \
  --model_preset=multimer \
