### ISSUE TITLE
Different output from the same sequence

### ISSUE THREAD

**Issue by barbarashih** [deepmind/alphafold#583]
Hi, 
Thank you for sharing this great tool. I noticed that when I run Alphafold2 on the same sequence, I would get slightly different result each time. Is there any way we can ensure getting identical output from identical sequence, or is that something that's unavoidable?

Thank you

Barbara

**Comment by tcoates5** [comment]
Lines 105-109 in run_alphafold.py seem very relevant, and the README also has a note on reproducibility that is important. As interpreted by me, the gist of it is that runs are consistently similar, but not identical. You can make the runs even more consistent by setting the random seed used, but GPU inference is nondeterministic so very slight differences will still likely occur. In my experience, after aligning the structures in PyMOL, most structures with decent confidence scores are extremely similar even without setting the seed.

**Comment by barbarashih** [comment]
Thank you very much for your answer @tcoates5 !
