### ISSUE TITLE
Alphafold2 Modulenotfound

### ISSUE THREAD

**Issue by SolkenSlibs** [deepmind/alphafold#587]
Hi, I'm new to using Alphafold2 and I have been looking for the solution for this problem but haven't found it so sorry in advance if it has already been posted. I am running 3 sequences and around halfway through the second or third sequence I keep getting this error when I do the whole thing just stops working for a couple of hours and I am not sure what to do.

ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-1-c47351bef025>](https://localhost:8080/#) in <module>
     19 import matplotlib.pyplot as plt
     20 import numpy as np
---> 21 import py3Dmol
     22 
     23 from alphafold.model import model

ModuleNotFoundError: No module named 'py3Dmol'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.

**Comment by Htomlinson14** [comment]
Hi! Is it possible that your colab runtime restarted? When this happens, you will need to rerun steps 1 and 2 to make sure that the relevant packages have been installed, as these do not persist between sessions. Thanks!

**Comment by SolkenSlibs** [comment]
I would rerun steps 1 and 2 but unfortunately would get a separate error for the second one. Unfortunately, I am now receiving a different error and am unable to get past download alphafold.

RuntimeError                              Traceback (most recent call last)
[<ipython-input-2-90a6e6d547f8>](https://localhost:8080/#) in <module>
     46   raise RuntimeError('Colab TPU runtime not supported. Change it to GPU via Runtime -> Change Runtime Type -> Hardware accelerator -> GPU.')
     47 elif jax.local_devices()[0].platform == 'cpu':
---> 48   raise RuntimeError('Colab CPU runtime not supported. Change it to GPU via Runtime -> Change Runtime Type -> Hardware accelerator -> GPU.')
     49 else:
     50   print(f'Running with {jax.local_devices()[0].device_kind} GPU')

RuntimeError: Colab CPU runtime not supported. Change it to GPU via Runtime -> Change Runtime Type -> Hardware accelerator -> GPU.

When I do go into runtime type it is already set to GPU and I haven't changed anything in there previously I am not sure what I am doing wrong as I really only found out about this site recently.

**Comment by SolkenSlibs** [comment]
> Hi! Is it possible that your colab runtime restarted? When this happens, you will need to rerun steps 1 and 2 to make sure that the relevant packages have been installed, as these do not persist between sessions. Thanks!

I would rerun steps 1 and 2 but unfortunately would get a separate error for the second one. Unfortunately, I am now receiving a different error and am unable to get past download alphafold.

RuntimeError Traceback (most recent call last)
in
46 raise RuntimeError('Colab TPU runtime not supported. Change it to GPU via Runtime -> Change Runtime Type -> Hardware accelerator -> GPU.')
47 elif jax.local_devices()[0].platform == 'cpu':
---> 48 raise RuntimeError('Colab CPU runtime not supported. Change it to GPU via Runtime -> Change Runtime Type -> Hardware accelerator -> GPU.')
49 else:
50 print(f'Running with {jax.local_devices()[0].device_kind} GPU')

RuntimeError: Colab CPU runtime not supported. Change it to GPU via Runtime -> Change Runtime Type -> Hardware accelerator -> GPU.

When I do go into runtime type it is already set to GPU and I haven't changed anything in there previously I am not sure what I am doing wrong as I really only found out about this site recently.

**Comment by Htomlinson14** [comment]
Hi! I haven't been able to reproduce your issue. Are you still having this problem? Thanks!

**Comment by SolkenSlibs** [comment]
> Hi! I haven't been able to reproduce your issue. Are you still having this problem? Thanks!

Not sure what changed but it seems to be working fine right now. I am currently running 3 structures and I am currently at 6% hopefully nothing happens.

**Comment by Htomlinson14** [comment]
Thats great thanks! I will close the issue but feel free to reopen if it comes back.
