### ISSUE TITLE
 115 protein genes from finally completed human genome (May 2021) for AlphaFold DB

### ISSUE THREAD

**Issue by ValZapod** [deepmind/alphafold#59]
In 1.1 version of (since that version) "Complete genome" assembly of homo sapiens (never achieved before) compared to 1.0 (previous version) 5 last gaps in rDNA were fixed and now it all **is** there!

https://www.ncbi.nlm.nih.gov/assembly/GCA_009914755.3

Delta from 1.0 version is there https://s3-us-west-2.amazonaws.com/human-pangenomics/T2T/CHM13/assemblies/changes/v1.0_to_v1.1/v1.0_to_v1.1.chain and delta from patch 13 of GRCh38 is here: https://t2t.gi.ucsc.edu/chm13/hub/t2t-chm13-v1.0/hg38Lastz/t2t-chm13-v1.0.hg38.over.chain.gz

What AlphaFold uses is "just" GRCh38 patch 13. @alexbateman1, CHM13 is better, I suppose that you should update Alphafold DB for that. 115 exclusive new protein coding genes in CHM1.3 see: https://www.biorxiv.org/content/10.1101/2021.05.26.445798v1

But some others are there too.

**Comment by abridgland** [comment]
Thanks for this comment! We’d like to keep GitHub issues to software questions — please direct AlphaFold database feedback and suggestions to alphafold@deepmind.com.
