### ISSUE TITLE
How does AlphaFold2 determine the protonation state/hydrogen

### ISSUE THREAD

**Issue by shaoqx** [deepmind/alphafold#598]
Hi! I'm working on projects related to protonating the protein under a specific pH. I found outputs of AlphaFold2 prediction contain hydrogens in the model and I wonder how AlphaFold2 determines the protonation state of residues?

I traced back to the feature of AlphaFold2 used for training and found in the Nature paper it says `"one is atom37 where each heavy atom ... The other representation we employ is called atom14 ... 14 is chosen because it is the maximum number of heavy atoms for any standard amino acid."` But I found in the feature map from intermediate files that there are features for hydrogen atoms. 

So I wonder if AlphaFold2 predicts positions of hydrogen atoms by training on datasets with existing hydrogens? If so, how are those hydrogens determined in the training set? If not, how is positions of hydrogens determined.

(I also tested some predictions for systems like 1NVG, the protonation state around the Zn center is not correct.)

**Comment by Augustin-Zidek** [comment]
Hi @shaoqx and thank you for the question. AlphaFold2 is not aimed at protonation state prediction; however hydrogens could be introduced during the relaxation (energy minimisation) step; they are aimed at improving overall geometrical quality of the predicted model. I suggest to ignore these predicted hydrogens for the sensitive applications like you have described. Sorry about the confusion.
