### ISSUE TITLE
How long does it take on T1050 (779 residues)

### ISSUE THREAD

**Issue by kuixu** [deepmind/alphafold#6]
It is still in extracting MSA.
Could anyone share the running time on T1050 (779 residues)? Thanks very much!

**Comment by Augustin-Zidek** [comment]
Hi Kui,

this is hard to answer without more context, especially without knowing the speed of your CPU and your hard drive (whether it is an SSD or an HDD).

But in general, you can expect the time to grow with the length of the protein and the MSA search taking up to a few hours with a slow disk / CPU.

For the actual folding (i.e. running the AlphaFold model), the disk speed doesn't matter anymore, what matters is whether you are using a GPU and its performance.
