### ISSUE TITLE
Running on CUDA 10.X

### ISSUE THREAD

**Issue by skyungyong** [deepmind/alphafold#60]
Hi!

It looks like our server's GPU nodes only support up to CUDA 10.2. With the downgraded versions of tensorflow and other modules/packages, will be output consistent with those produced from the default set-up? 

Thanks!

**Comment by tfgg** [comment]
Hi,

Looking at

https://storage.googleapis.com/jax-releases/jax_releases.html

it appears that JAX 1.69 supports CUDA 10.1 and 10.2 - you could try those. We don't use TensorFlow much except for the data pipeline, so I'd expect that the outputs would be fine. We haven't fully validated this setup, though.
