### ISSUE TITLE
Can I use cudatoolkit==11.7.0 instead of cudatoolkit==11.1.1 ?

### ISSUE THREAD

**Issue by therealchrisneale** [deepmind/alphafold#602]
Hello,

our cluster has nvidia kernel driver version 510.85.02. I can build the container with cudatoolkit 11.1.1, but when I run I get the errors listed below and the GPUs are not found/used. When I modify the Dockerfile to use cuda 11.7.0, it builds and runs just fine and the output structure is sensible. Is there any reason to be cautious of using cudatoolkit 11.7.0 instead of 11.1.1 ?

In case it matters:
(1) I am building this on charliecloud instead of docker
(2) I modified the LD_LIBRARY_PATH a bit because it listed /usr/local/nvidia/lib:/usr/local/nvidia/lib64 but out of conda the libcuda.so.1 was actually in /usr/local/cuda/compat

### Here's the issue I was having when using cudatoolkit 11.1.1 inside the container:
I0929 20:05:58.839441 140412502734656 xla_bridge.py:350] Unable to initialize backend 'tpu_driver': NOT_FOUND: Unable to find driver in registry given worker:
2022-09-29 20:05:59.142936: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:265] failed call to cuInit: CUDA_ERROR_SYSTEM_DRIVER_MISMATCH: system has unsupported display driver / cuda driver combination
2022-09-29 20:05:59.146190: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_diagnostics.cc:313] kernel version 510.85.2 does not match DSO version 455.45.1 -- cannot find working devices in this configuration
I0929 20:05:59.189327 140412502734656 xla_bridge.py:350] Unable to initialize backend 'cuda': FAILED_PRECONDITION: No visible GPU devices.
I0929 20:05:59.189445 140412502734656 xla_bridge.py:350] Unable to initialize backend 'rocm': NOT_FOUND: Could not find registered platform with name: "rocm". Available platform names are: CUDA Host Interpreter
I0929 20:05:59.189768 140412502734656 xla_bridge.py:350] Unable to initialize backend 'tpu': module 'jaxlib.xla_extension' has no attribute 'get_tpu_client'
W0929 20:05:59.189845 140412502734656 xla_bridge.py:357] No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)

### When I build the container with cudatoolkit 11.7.0 and run it, the GPUs are found and the lack of TPUs is expected on this system:
I0929 13:37:31.731364 140268510418752 xla_bridge.py:356] Unable to initialize backend 'tpu_driver': NOT_FOUND: Unable to find driver in registry given worker:
I0929 13:37:33.668347 140268510418752 xla_bridge.py:356] Unable to initialize backend 'rocm': NOT_FOUND: Could not find registered platform with name: "rocm". Available platform names are: Interpreter Host CUDA
I0929 13:37:33.668632 140268510418752 xla_bridge.py:356] Unable to initialize backend 'tpu': module 'jaxlib.xla_extension' has no attribute 'get_tpu_client'
I0929 13:37:33.668713 140268510418752 xla_bridge.py:356] Unable to initialize backend 'plugin': xla_extension has no attributes named get_plugin_device_client. Compile TensorFlow with //tensorflow/compiler/xla/python:enable_plugin_device set to true (defaults to false) to enable this. 

Thank you for your advice,
Chris.

**Comment by Htomlinson14** [comment]
Hi Chris thanks for reaching out. We haven't tested AlphaFold with this version of Cuda. I would recommend running some test structures and checking that the metrics match what is expected. We have recently seen some variability depending on hardware https://github.com/deepmind/alphafold/issues/597 so its worth checking this.
