### ISSUE TITLE
Running "run_docker.py" says ModuleNotFoundError: No module named 'asbl' 

### ISSUE THREAD

**Issue by Aaronro16** [deepmind/alphafold#607]
I just installed AlphaFold and for the first time that I tried to run it gived to me the next error:

  File "alphafold/docker/run_docker.py", line 22, in <module>
    from absl import app
ModuleNotFoundError: No module named 'absl'

I used:
pip uninstall absl-py
pip install absl-py
pip3 uninstall absl-py
pip3 install absl-py

and didn't work, later I tried with the next command and was solved:

python3 -m pip install absl-py

The same issue happened for the docker library:

  File "docker/run_docker.py", line 25, in <module>
    import docker
ModuleNotFoundError: No module named 'docker'

And again solved with the same command but specifying the library docker:

python3 -m pip install docker

**Comment by Aaronro16** [comment]
I created this thread for those that are having the same issue

**Comment by adalal78** [comment]
@Aaronro16, I'm just running into this error on Docker.  What did you do to resolve it?
