### ISSUE TITLE
Carriage returns in pdb_seqres.txt

### ISSUE THREAD

**Issue by therealchrisneale** [deepmind/alphafold#608]
Hello,

I see carriage returns in some database input files:

$ ./alphafold/scripts/download_pdb_seqres.sh TEST
$ grep -r $'\r' TEST/pdb_seqres/pdb_seqres.txt | wc -l
1476032

Should I remove them (e.g., sed -i "s/\r$//" TEST/pdb_seqres/pdb_seqres.txt) or is it not expected to represent any problem?

Thank you,
Chris.

**Comment by Augustin-Zidek** [comment]
Carriage returns should be handled ok by the MSA search tools, fine to leave as is.
