### ISSUE TITLE
Is there any solution that we can run AF2 by using GCP TPU vm?

### ISSUE THREAD

**Issue by edwardlo12** [deepmind/alphafold#611]
We are trying to infer a sequence with 5000 amino acids. But AF2 can only support single GPU, so we think we can try to use TPU.

**Comment by Augustin-Zidek** [comment]
Hi @edwardlo12. Unfortunately this doesn't support running on TPU but you should be able to run 5000 residues using AF-multimer in the latest (v2.3.0+) release.
