### ISSUE TITLE
GPU Memory Resource Exhaustion issue

### ISSUE THREAD

**Issue by bijuissacch224610** [deepmind/alphafold#612]
I am running a multimer analysis using local AlphaFold 2.2.2 installed on our server and have successfully predicted structures for monomer and multimer analyses. Recently I need to predict a protein complex using 3 protein sequences, one of which is 2482 amino acids long while other two are shorter.

I have provided adequate memory as seen here
<img width="569" alt="Screen Shot 2022-10-18 at 4 08 25 PM" src="https://user-images.githubusercontent.com/83024487/196695740-c47553c0-e986-48a2-9159-f7be5b484773.png">

I have tried running variations of various solutions provided here on Github issues but keep getting same error about resource exhaustion. When I look at log file, the GPU RAM is not being fully utilized.
<img width="931" alt="Screen Shot 2022-10-18 at 4 05 54 PM" src="https://user-images.githubusercontent.com/83024487/196696465-da305b12-3cb6-4197-8910-5446c9cbbb42.png">

My configurations are as below
<img width="514" alt="Screen Shot 2022-10-19 at 8 52 30 AM" src="https://user-images.githubusercontent.com/83024487/196696500-a4f76297-52af-4593-8dd7-b6c593b5fa36.png">

<img width="332" alt="Screen Shot 2022-10-19 at 8 52 45 AM" src="https://user-images.githubusercontent.com/83024487/196696523-00da029b-7be5-42ab-b7a4-2e0e790ebe7e.png">

Can you help me with this? The error seems to be from AlphaFold is analyzing the longest protein sequence in the complex. To reduce the load on memory, I am running my multimer analysis using "-db_preset=reduced_dbs" parameter

Any help from the developers or the community is deeply appreciated

Thanks
-B. Issac

**Comment by Augustin-Zidek** [comment]
We improved the GPU usage for AlphaFold-Multimer in [v2.3.0](https://github.com/deepmind/alphafold/releases/tag/v2.3.0) - hopefully this addresses your issue. Closing this issue now, feel free to reopen if you still encounter this in v2.3.0.
