### ISSUE TITLE
400 Client Error

### ISSUE THREAD

**Issue by lukaszsobala** [deepmind/alphafold#62]
Hello,

I am trying to run AlphaFold using docker (command: `python3 docker/run_docker.py --use_gpu=False --fasta_paths=seq.fa --max_template_date=2021-12-12`) and I get this error:

> 
> Traceback (most recent call last):
>   File "[HOME_dir_redacted]/.local/lib/python3.9/site-packages/docker/api/client.py", line 268, in _raise_for_status
>     response.raise_for_status()
>   File "/usr/lib/python3/dist-packages/requests/models.py", line 943, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.41/containers/create
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "[HOME_dir_redacted]/Software/alphafold/docker/run_docker.py", line 201, in <module>
>     app.run(main)
>   File "[HOME_dir_redacted]/.local/lib/python3.9/site-packages/absl/app.py", line 312, in run
>     _run_main(main, args)
>   File "[HOME_dir_redacted]/.local/lib/python3.9/site-packages/absl/app.py", line 258, in _run_main
>     sys.exit(main(argv))
>   File "[HOME_dir_redacted]/Software/alphafold/docker/run_docker.py", line 173, in main
>     container = client.containers.run(
>   File "[HOME_dir_redacted]/.local/lib/python3.9/site-packages/docker/models/containers.py", line 811, in run
>     container = self.create(image=image, command=command,
>   File "[HOME_dir_redacted]/.local/lib/python3.9/site-packages/docker/models/containers.py", line 870, in create
>     resp = self.client.api.create_container(**create_kwargs)
>   File "[HOME_dir_redacted]/.local/lib/python3.9/site-packages/docker/api/container.py", line 430, in create_container
>     return self.create_container_from_config(config, name)
>   File "[HOME_dir_redacted]/.local/lib/python3.9/site-packages/docker/api/container.py", line 441, in create_container_from_config
>     return self._result(res, True)
>   File "[HOME_dir_redacted]/.local/lib/python3.9/site-packages/docker/api/client.py", line 274, in _result
>     self._raise_for_status(response)
>   File "[HOME_dir_redacted]/.local/lib/python3.9/site-packages/docker/api/client.py", line 270, in _raise_for_status
>     raise create_api_error_from_http_exception(e)
>   File "[HOME_dir_redacted]/.local/lib/python3.9/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
>     raise cls(e, response=response, explanation=explanation)
> docker.errors.APIError: 400 Client Error for http+docker://localhost/v1.41/containers/create: Bad Request ("invalid mount config for type "bind": bind source path does not exist: /tmp/alphafold")
> 

I did not set up any keys for Docker. Is this related? And how to fix this? I tried removing the alphafold image and purging/reinstalling docker. Still, nothing helps.

Thanks,
Lukasz

**Comment by gaorongchao** [comment]
Please modify docker/run_dockery.py  output_dir. the default is /tmp/alphafold cause this problem.

**Comment by Newlcg** [comment]
Hello,

May I ask you, do you fix this problem?

After I creat a new file place, and change my out_dir to new place, it also show the same problem.

And, what's meaning of  'clone this project'?

Wish you best,
Yuan licheng

**Comment by lukaszsobala** [comment]
> Please modify docker/run_dockery.py line 37 output_dir. the default is /tmp/alphafold cause this problem.
> 
> or this project has updated , you can clone this project and run again.

Modifying the output_dir worked. Thank you, I am closing the issue.
