### ISSUE TITLE
compare the predicted and actual structure?

### ISSUE THREAD

**Issue by mukulem** [deepmind/alphafold#621]
Hi, I was wondering which python library did you use to compare the predicted and actual structure.
<img width="692" alt="image" src="https://user-images.githubusercontent.com/105665325/199346204-4843da4c-808a-4231-aed9-78cd723b25b3.png">
something similar to this.

Thanks

**Comment by Augustin-Zidek** [comment]
You can use e.g. [Theseus](https://theobald.brandeis.edu/theseus/) or [PyMOL align](https://pymolwiki.org/index.php/Align) to align the two structures.
