### ISSUE TITLE
Locally install and run AlphaFold

### ISSUE THREAD

**Issue by galshuler** [deepmind/alphafold#622]
Hi,
It is possible to install and run Alpha Fold on my local computer (not on VM or cloud) with the given specification:
I9-12900 CPU
128gb ddr4-3200
Asus Prime Z690P 2tb NVME + 8TB HDD

Regards,
Gal.

**Comment by tcoates5** [comment]
Based on those specs, you can probably run AlphaFold with reduced databases on your local computer, though if you do not have a dedicated graphics card it will probably be very slow.

**Comment by tcoates5** [comment]
Assuming you have a dedicated graphics card and do not need high speed results, you could also run with full databases on the HDD

**Comment by Augustin-Zidek** [comment]
I agree with @tcoates5: It should be possible to run AlphaFold on your machine, but without an (NVIDIA) GPU it will run the model inference and relaxation parts rather slowly. I recommend getting a GPU, ideally with a lot of GPU RAM.
