### ISSUE TITLE
Erros while predicting the structures

### ISSUE THREAD

**Issue by jeid9** [deepmind/alphafold#626]
Dear alphafold developers, 

I faced some errors while trying to predict protein structures. Finally, I obtained a predicted structure so alphafold ran normally. I am just wondering if these errors will have a major effect on the prediction or not? 

Thank you so much for your help, 

Best regrards, 

Here are the errors : 

NameError                                 Traceback (most recent call last)
<ipython-input-3-d068b61051d4> in <module>
     40 # --- Search against genetic databases ---
     41 
---> 42 I = cf_af.prep_msa(I, msa_method, add_custom_msa, msa_format,
     43                    pair_mode, pair_cov, pair_qid, TMP_DIR=TMP_DIR)
     44 mod_I = I
NameError: name 'cf_af' is not defined

 

NameError                                 Traceback (most recent call last)

[<ipython-input-4-bdca699a292d>](https://localhost:8080/#) in <module>
     11 #@markdown - `qid` minimum sequence identity with query (%)
     12 
---> 13 mod_I = cf_af.prep_filter(I, trim, trim_inverse, cov, qid)
     14 
     15 if I["msas"] != mod_I["msas"]:

NameError: name 'cf_af' is not defined

NameError                                 Traceback (most recent call last)

[<ipython-input-2-f9c7eceac359>](https://localhost:8080/#) in <module>
     16 #@markdown  - For example, **sequence:**`ABC:DEF`, **homooligomer:** `2:1`, the first protein `ABC` will be modeled as a homodimer (2 copies) and second `DEF` a monomer (1 copy).
     17 
---> 18 I = cf_af.prep_inputs(sequence, jobname, homooligomer, clean=IN_COLAB)
NameError: name 'cf_af' is not defined

NameError                                 Traceback (most recent call last)

[<ipython-input-5-74c943a59072>](https://localhost:8080/#) in <module>
     38 
     39 # prep input features
---> 40 feature_dict = cf_af.prep_feats(mod_I, clean=IN_COLAB)
     41 Ls_plot = feature_dict["Ls"]
     42 

NameError: name 'cf_af' is not defined

**Comment by Htomlinson14** [comment]
Hi! This looks like its in ColabFold so I would suggest raising a question there. It does look like you need to rerun the earlier cells to define cf_af. Thanks!
