### ISSUE TITLE
An error occurred while downloading the database

### ISSUE THREAD

**Issue by Caiguoyu** [deepmind/alphafold#627]
When I download the database, I get the following error: download_db.sh：行 82: 2358338 段错误               （核心已转储） wget -P "$pdb70" "http://wwwuser.gwdg.de/~compbiol/data/hhsuite/databases/hhsuite_dbs/old-releases/${pdb70_filename}" , How do I fix this error?

**Comment by Augustin-Zidek** [comment]
This looks like a `wget` issue. Could you try downloading e.g. using `curl`, `aria2c` or just manually through the web browser?

**Comment by Augustin-Zidek** [comment]
Closing this now as this is something outside our control - I hope you managed to download the database in the end.
