### ISSUE TITLE
how to continue predicting without repeating msas

### ISSUE THREAD

**Issue by GuShaocheng** [deepmind/alphafold#63]
Hi,

Can I run_docker.py again skipping the masa if they are already generated in the past?
Sometimes programs died for some reason, then it takes time to repeat generating masa.
I so appreciate it if you can let me know how to achieve this!

Besides, will you set --delay for running Alphafold with command parallel considering the intensive I/O or you take other ways? The key of the question is about how to quickly predict several proteins one time.

Many thanks!

Best,
Shaocheng

**Comment by Zuricho** [comment]
I write a program based on a non_docker build. I divided CPU part (MSA and template searching) and GPU part (prediction model). If you already have the `feature.pkl` which collect data from MSA and template search, you can skip the featuring steps and start directly from prediction models. 
You can find it here: https://github.com/Zuricho/ParallelFold

**Comment by GuShaocheng** [comment]
> I write a program based on a non_docker build. I divided CPU part (MSA and template searching) and GPU part (prediction model). If you already have the `feature.pkl` which collect data from MSA and template search, you can skip the featuring steps and start directly from prediction models.
> You can find it here: https://github.com/Zuricho/ParallelFold

Cool! I will try it!
