### ISSUE TITLE
Alphafold broken on Colab

### ISSUE THREAD

**Issue by danjaco** [deepmind/alphafold#638]
This issue is reported by others earlier, but I rase this separately as a more permanent solution is needed. I've come to rely on Colab version of Alphafold but a couple of times recently it's been down for over a week without us having any idea when it would be fixed 

Would it be possible to make a second version available, that is known to be stable, so that if a new rollout fails there is something to fall back to? Or some other solution that could make it more reliable?

Thanks,
Dan

**Comment by under-score** [comment]
Colab is also broken here

![Bildschirmfoto 2022-11-28 um 15 48 55](https://user-images.githubusercontent.com/2796454/204308967-4ec9e2b6-37f2-4a92-bf15-94426b57f4a2.jpg)

**Comment by Htomlinson14** [comment]
Hi Dan, thanks for raising this. The python dependencies in colab change over time, which means that the environment that the code runs in may diverge from alphafold, even if the alphafold code itself is stable. We will update the requirements when this happens. The most recent commit updated jax and haiku to match the colab versions, so this issue should be fixed

**Comment by under-score** [comment]
sorry, there is just a new error

![Bildschirmfoto 2022-12-01 um 08 54 55](https://user-images.githubusercontent.com/2796454/204997369-f6e2b4ee-c88a-4d44-9254-349c8154c5cf.jpg)

**Comment by marmilani** [comment]
I have an error:
![Screenshot 2022-12-05 at 15 53 33](https://user-images.githubusercontent.com/119873986/205669165-f3331938-8b3a-4faf-bbe6-61908541d928.png)
