### ISSUE TITLE
AlphaFold multimer has name error in the last step

### ISSUE THREAD

**Issue by Isabel-ql** [deepmind/alphafold#639]
Hi,

I have tried to use AlphaFold-Multimer to predict the structures of complexes, I did the prediction from the following link:
https://colab.research.google.com/github/deepmind/alphafold/blob/main/notebooks/AlphaFold.ipynb

However, problem appeared in the last step, "Run AlphaFold and download prediction". The notice said "NameError: name 'model_type_to_use' is not defined". How to solve this problem? 

Thanks very much!

Cheers,
Qun

<img width="1515" alt="AlphaFold Multimer_NameError" src="https://user-images.githubusercontent.com/65905482/204093603-ca29246b-1a42-466f-9a52-2b860e54a732.png">

**Comment by anupam-tiwari** [comment]
Did you run all the cells properly, especially the second one "2. Download AlphaFold"?

**Comment by Isabel-ql** [comment]
> Did you run all the cells properly, especially the second one "2. Download AlphaFold"?

Yes, the other steps are all successful. Only the last step failed. 
<img width="719" alt="AlphaFold Multimer_Step2" src="https://user-images.githubusercontent.com/65905482/204095350-b0e68050-8404-4846-bb36-1c44df44d31d.png">

**Comment by anupam-tiwari** [comment]
Did you get it running? if now try this version: https://colab.research.google.com/drive/1J1G8OC6LZwT6Tqdz4uLRmnVzj7WWgUg1?usp=sharing

**Comment by Isabel-ql** [comment]
> Did you get it running? if now try this version: https://colab.research.google.com/drive/1J1G8OC6LZwT6Tqdz4uLRmnVzj7WWgUg1?usp=sharing

The old one is still problematic, but the new link you sent me works! I just finished the prediction. Thanks so much!

**Comment by Htomlinson14** [comment]
Hi thanks for this. This may have been due to the colab kernel restarting, so that whilst the previous cells had run correctly they have since had their output cleared. When this happens, the colab needs to be rerun from the beginning.

**Comment by Isabel-ql** [comment]
> Did you get it running? if now try this version: https://colab.research.google.com/drive/1J1G8OC6LZwT6Tqdz4uLRmnVzj7WWgUg1?usp=sharing

Hi,  a new problem appeared with the new link. In step 5, "Search against genetic database", there's an import error. See below. The problem started from yesterday, and still exists now. How to fix it? Thanks!

Cheers,
Qun

<img width="1381" alt="AlphaFold Multimer_step5" src="https://user-images.githubusercontent.com/65905482/205282261-502402d8-f5b4-4742-a10d-51d8628cca67.png">
