### ISSUE TITLE
Can I customize the database?

### ISSUE THREAD

**Issue by dahaigui** [deepmind/alphafold#642]
My protein sequence is from a mutant library, is it possible to speed up my protein structure prediction by changing the dataset? For example, without using the BFD dataset, if it is possible, how should I implement it?

**Comment by Augustin-Zidek** [comment]
You can use the `--db_preset=reduced_dbs` flag to run a slightly more lightweight MSA search (doesn't search BFD, only its small clustered version).

However, running without these databases either requires modifying the data pipeline code to skip the databases you are not interested in searching, or by modifying the databases to contain only a single sequence (open the database fasta file in a text editor and remove all but the first two lines or use `head -n2 <fasta file>`).
