### ISSUE TITLE
ImportError: Python version mismatch: module was compiled for Python 3.7, but the interpreter version is incompatible: 3.8.15 (default, Oct 12 2022, 19:14:39)  [GCC 7.5.0].

### ISSUE THREAD

**Issue by itheod04** [deepmind/alphafold#648]
a) ImportError: Python version mismatch: module was compiled for Python 3.7, but the interpreter version is incompatible: 3.8.15 (default, Oct 12 2022, 19:14:39) 
[GCC 7.5.0]. 
![image](https://user-images.githubusercontent.com/119576148/205002064-d5bbf345-cfd1-4e23-b969-9dfdf9c67a34.png)

b) ImportError: Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 62, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: Python version mismatch: module was compiled for Python 3.7, but the interpreter version is incompatible: 3.8.15 (default, Oct 12 2022, 19:14:39) 
![image](https://user-images.githubusercontent.com/119576148/205002389-8074eb0c-8cb4-4744-84e5-f12847582ca6.png)

[GCC 7.5.0].

**Comment by MelanieBazin** [comment]
I have the same issue :/

**Comment by juanorl** [comment]
Same issue

**Comment by Daboshu** [comment]
+1

**Comment by Htomlinson14** [comment]
Hi thanks for raising this. We've updated to 3.8 in the latest [commit](https://github.com/deepmind/alphafold/commit/4494af848e41f3acd51a190d4c78d38cb1a7f85d) to match colab
