### ISSUE TITLE
Reason behind 'msa_channel': 256 and 'seq_channel': 384 in config.py?

### ISSUE THREAD

**Issue by xinformatics** [deepmind/alphafold#65]
Hi, Could anyone tell the reason behind setting up such values for msa_channel and seq_channel? 

I am asking this question because the msa_channel and seq_channel dimension determines the shape of the representations learned by the model.

**Comment by abridgland** [comment]
We’d like to keep GitHub issues to software questions — please direct scientific and machine learning questions to the corresponding authors on the manuscript (https://www.nature.com/articles/s41586-021-03819-2#author-information).  Thanks!
