### ISSUE TITLE
jax.tree_flatten is deprecated, and will be removed in a future release. Use jax.tree_util.tree_flatten instead.

### ISSUE THREAD

**Issue by MasterNivek** [deepmind/alphafold#650]
any one knows of a solution please 
![image](https://user-images.githubusercontent.com/108690998/205595181-458c56f7-912d-48e0-a004-78b9d6ead83c.png)

**Comment by jinmingyi1998** [comment]
solved in pr #630 

just replace all tree_utils

**Comment by Augustin-Zidek** [comment]
Thanks, fixed in v2.3.0.
