### ISSUE TITLE
GPU ran out of memory!

### ISSUE THREAD

**Issue by shahryary** [deepmind/alphafold#651]
`Allocator (GPU_0_bfc) ran out of memory trying to allocate 163.17GiB (rounded to 175203296000) requested by op`

I've been using the Alphafold for more than a year, and the GPU problem is annoying many users to run complex/ long sequences. 

Alphafold is not supporting multi GPUs, and it's only using one GPU core - although, in the documentation, they mentioned it would attempt to use all available GPU cores!

I tried to run Alphafold(conda-based, docker/ singularity) in different instances from Amazon, G5.48x /G4 series. Still, I couldn't get results because only one GPU core taking into account instead of all of them. 

The most significant target users of Alphafold are scientists who are more interested in running 'real' long samples rather than just a few lines of sequences. Without supporting multi-GPU mode, the tools are hopeless.

**Comment by Augustin-Zidek** [comment]
We improved the GPU usage for AlphaFold-Multimer in [v2.3.0](https://github.com/deepmind/alphafold/releases/tag/v2.3.0) - hopefully this addresses your issue. Closing this issue now, feel free to reopen if you still encounter this in v2.3.0.
