### ISSUE TITLE
A new problem occurred while I was running the Alphafold

### ISSUE THREAD

**Issue by pujialin** [deepmind/alphafold#655]
When I entered the amino acid sequence, the program reported an error：

AttributeError                            Traceback (most recent call last)
[<ipython-input-4-6962bd6ebd6c>](https://localhost:8080/#) in <module>
     23 
     24 # Validate the input.
---> 25 sequences, model_type_to_use = notebook_utils.validate_input(
     26     input_sequences=input_sequences,
     27     min_length=MIN_SINGLE_SEQUENCE_LENGTH,

AttributeError: module 'alphafold.notebooks.notebook_utils' has no attribute 'validate_input'
I don't know what's going on, I hope everyone can help me.

**Comment by Augustin-Zidek** [comment]
I think this was caused by the changes in v2.3.0 which happened recently - your Colab notebook likely got out of sync with the code. Could you try running in a fresh notebook?
 https://colab.research.google.com/github/deepmind/alphafold/blob/main/notebooks/AlphaFold.ipynb
