### ISSUE TITLE
uniref30_database_path issue

### ISSUE THREAD

**Issue by limh25** [deepmind/alphafold#656]
Hi,

I am trying to run the new ver. 2.3.0 for multimer predictions.
I had no issue with previous versions, including 2.2.4.

I tried to use direct download from the releases, and I also tried to use from git clone repository.
In both cases, I get an error message and the job terminates.

`I1215 18:59:41.374994 140456684652352 run_docker.py:255] FATAL Flags parsing error: Unknown command line flag 'uniref30_database_path'. Did you mean: uniref90_database_path ?`

It seems the directories are correctly mounted.
`I1215 18:59:37.418998 140456684652352 run_docker.py:113] Mounting /home/ec2-user/input_fasta/part1 -> /mnt/fasta_path_0
I1215 18:59:37.419240 140456684652352 run_docker.py:113] Mounting /disk1/databases/uniref90 -> /mnt/uniref90_database_path
I1215 18:59:37.419375 140456684652352 run_docker.py:113] Mounting /disk1/databases/mgnify -> /mnt/mgnify_database_path
I1215 18:59:37.419479 140456684652352 run_docker.py:113] Mounting /disk1/databases -> /mnt/data_dir
I1215 18:59:37.419581 140456684652352 run_docker.py:113] Mounting /disk1/databases/pdb_mmcif/mmcif_files -> /mnt/template_mmcif_dir
I1215 18:59:37.419708 140456684652352 run_docker.py:113] Mounting /disk1/databases/pdb_mmcif -> /mnt/obsolete_pdbs_path
I1215 18:59:37.419818 140456684652352 run_docker.py:113] Mounting /disk1/databases/uniprot -> /mnt/uniprot_database_path
I1215 18:59:37.419928 140456684652352 run_docker.py:113] Mounting /disk1/databases/pdb_seqres -> /mnt/pdb_seqres_database_path
I1215 18:59:37.420024 140456684652352 run_docker.py:113] Mounting /disk1/databases/uniref30/UniRef30_2021_03 -> /mnt/uniref30_database_path
I1215 18:59:37.420170 140456684652352 run_docker.py:113] Mounting /disk1/databases/bfd -> /mnt/bfd_database_path
I1215 18:59:41.374994 140456684652352 run_docker.py:255] FATAL Flags parsing error: Unknown command line flag 'uniref30_database_path'. Did you mean: uniref90_database_path ?
I1215 18:59:41.375221 140456684652352 run_docker.py:255] Pass --helpshort or --helpfull to see help on flags.`

I updated the databases:
- mgnify
- params
- pdb_mmcif
- pdb_seqres
- uniref30
- uniref90

Please help.

**Comment by AChatzigoulas** [comment]
You need to rebuild after pulling the newest version  

```docker build -f docker/Dockerfile -t alphafold .```

**Comment by limh25** [comment]
Hi @AChatzigoulas
Thank you for your help.
I still have a problem in building the docker image.

`Step 11/18 : RUN wget -q -P /app/alphafold/alphafold/common/   https://git.scicore.unibas.ch/schwede/openstructure/-/raw/7102c63615b64735c4941278d92b554ec94415f8/modules/mol/alg/src/stereo_chemical_props.txt
 ---> Running in 9b77342609c3
The command '/bin/bash -o pipefail -c wget -q -P /app/alphafold/alphafold/common/   https://git.scicore.unibas.ch/schwede/openstructure/-/raw/7102c63615b64735c4941278d92b554ec94415f8/modules/mol/alg/src/stereo_chemical_props.txt' returned a non-zero code: 5`

Do you know the cause or the solution?

Thanks.

**Comment by AChatzigoulas** [comment]
This is an SSL verification failure. Sadly, I do not know the cause or the solution for this one.

**Comment by limh25** [comment]
I was able to solve by modifying the Dockerfile

```
RUN wget --no-check-certificate -q -P /app/alphafold/alphafold/common/ \
  https://git.scicore.unibas.ch/schwede/openstructure/-/raw/7102c63615b64735c4941278d92b554ec94415f8/modules/mol/alg/src/stereo_chemical_props.txt
```

The "--no-check-certificate" option solved the issue.

Thanks.

**Comment by satya1102** [comment]
Hi, 

I am also facing the same problem during running predictions with new ver. 2.3.0
Although I have installed everything from scratch after removing the previous image of alphafold in docker and rebuilding new image after pulling the newest version but still its not working the error message is 

run_docker.py:258] FATAL Flags parsing error: Unknown command line flag 'uniref30_database_path'. Did you mean: uniref90_database_path ?


Directories are also mounted correctly 
python3 docker/run_docker.py --fasta_paths=/mnt/DATABIG/monomers_new/NOS1.fasta --max_template_date=2023-01-01 --model_preset=monomer --db_preset full_dbs --data_dir=/mnt/DATABIG/databases/ --gpu_devices=1 --models_to_relax=best 
I0302 11:27:01.387156 139961187600192 run_docker.py:116] Mounting /mnt/DATABIG/monomers_new -> /mnt/fasta_path_0
I0302 11:27:01.387369 139961187600192 run_docker.py:116] Mounting /mnt/DATABIG/databases/uniref90 -> /mnt/uniref90_database_path
I0302 11:27:01.387476 139961187600192 run_docker.py:116] Mounting /mnt/DATABIG/databases/mgnify -> /mnt/mgnify_database_path
I0302 11:27:01.387561 139961187600192 run_docker.py:116] Mounting /mnt/DATABIG/databases -> /mnt/data_dir
I0302 11:27:01.387643 139961187600192 run_docker.py:116] Mounting /mnt/DATABIG/databases/pdb_mmcif/mmcif_files -> /mnt/template_mmcif_dir
I0302 11:27:01.387732 139961187600192 run_docker.py:116] Mounting /mnt/DATABIG/databases/pdb_mmcif -> /mnt/obsolete_pdbs_path
I0302 11:27:01.387845 139961187600192 run_docker.py:116] Mounting /mnt/DATABIG/databases/pdb70 -> /mnt/pdb70_database_path
I0302 11:27:01.387944 139961187600192 run_docker.py:116] Mounting /mnt/DATABIG/databases/uniref30 -> /mnt/uniref30_database_path
I0302 11:27:01.388038 139961187600192 run_docker.py:116] Mounting /mnt/DATABIG/databases/bfd -> /mnt/bfd_database_path
I0302 11:27:05.063709 139961187600192 run_docker.py:258] /opt/conda/lib/python3.7/site-packages/haiku/_src/data_structures.py:37: FutureWarning: jax.tree_structure is deprecated, and will be removed in a future release. Use jax.tree_util.tree_structure instead.
I0302 11:27:05.064102 139961187600192 run_docker.py:258] PyTreeDef = type(jax.tree_structure(None))
I0302 11:27:05.064320 139961187600192 run_docker.py:258] FATAL Flags parsing error: Unknown command line flag 'uniref30_database_path'. Did you mean: uniref90_database_path ?
I0302 11:27:05.064502 139961187600192 run_docker.py:258] Pass --helpshort or --helpfull to see help on flags.

Please help me in this regard 

Thank you
