### ISSUE TITLE
error when running alphafold multimer

### ISSUE THREAD

**Issue by lamyankin** [deepmind/alphafold#659]
I am running the alphafold multimer to predict a complex composed of A and B and the problem occurs , here are the error message:

1218 18:46:51.980194 139874231673472 run_docker.py:255] Traceback (most recent call last):
I1218 18:46:51.980485 139874231673472 run_docker.py:255] File "/app/alphafold/run_alphafold.py", line 422, in <module>
I1218 18:46:51.980680 139874231673472 run_docker.py:255] app.run(main)
I1218 18:46:51.980863 139874231673472 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 312, in run
I1218 18:46:51.981044 139874231673472 run_docker.py:255] _run_main(main, args)
I1218 18:46:51.981219 139874231673472 run_docker.py:255] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
I1218 18:46:51.981395 139874231673472 run_docker.py:255] sys.exit(main(argv))
I1218 18:46:51.981570 139874231673472 run_docker.py:255] File "/app/alphafold/run_alphafold.py", line 406, in main
I1218 18:46:51.981745 139874231673472 run_docker.py:255] random_seed=random_seed)
I1218 18:46:51.981920 139874231673472 run_docker.py:255] File "/app/alphafold/run_alphafold.py", line 174, in predict_structure
I1218 18:46:51.982094 139874231673472 run_docker.py:255] msa_output_dir=msa_output_dir)
I1218 18:46:51.982327 139874231673472 run_docker.py:255] File "/app/alphafold/alphafold/data/pipeline_multimer.py", line 269, in process
I1218 18:46:51.982502 139874231673472 run_docker.py:255] is_homomer_or_monomer=is_homomer_or_monomer)
I1218 18:46:51.982620 139874231673472 run_docker.py:255] File "/app/alphafold/alphafold/data/pipeline_multimer.py", line 214, in _process_single_chain
I1218 18:46:51.982703 139874231673472 run_docker.py:255] msa_output_dir=chain_msa_output_dir)
I1218 18:46:51.982784 139874231673472 run_docker.py:255] File "/app/alphafold/alphafold/data/pipeline.py", line 225, in process
I1218 18:46:51.982866 139874231673472 run_docker.py:255] hits=pdb_template_hits)
I1218 18:46:51.982964 139874231673472 run_docker.py:255] File "/app/alphafold/alphafold/data/templates.py", line 968, in get_templates
I1218 18:46:51.983068 139874231673472 run_docker.py:255] kalign_binary_path=self._kalign_binary_path)
I1218 18:46:51.983152 139874231673472 run_docker.py:255] File "/app/alphafold/alphafold/data/templates.py", line 737, in _process_single_hit
I1218 18:46:51.983233 139874231673472 run_docker.py:255] cif_string = _read_file(cif_path)
I1218 18:46:51.983314 139874231673472 run_docker.py:255] File "/app/alphafold/alphafold/data/templates.py", line 681, in _read_file
I1218 18:46:51.983396 139874231673472 run_docker.py:255] with open(path, 'r') as f:
I1218 18:46:51.983479 139874231673472 run_docker.py:255] FileNotFoundError: [Errno 2] No such file or directory: '/mnt/template_mmcif_dir/7u0h.cif'

Then I have try searching the 7u0h.cif in the /path/alphafold/pdb_mmcif/mmcif_files, but i didn't found it.
What should i do to solve this problem? looking forward to your reply.

**Comment by leiterenato** [comment]
Hi @lamyankin 
I had the same issue with a different file from `pdb_mmcif`.   
I solved this problem by downloading a newer version of the database.

**Comment by lamyankin** [comment]
Hi, glad to hear your reply!
Did you download the newer pdb_mmcif database or all databases ?

**Comment by leiterenato** [comment]
I downloaded the full database again (but I don't think it is necessary).

**Comment by Augustin-Zidek** [comment]
The suggestion by @leiterenato is correct -- your pdb_seqres and the PDB mmCIF files have to be synced to the same version. In case they got out of sync, you are expected to see these issues. Updating both to the same version should address the issue.
