### ISSUE TITLE
[BUG] Relaxation not working for Multimers on v2.3.0

### ISSUE THREAD

**Issue by leiterenato** [deepmind/alphafold#660]
Relaxation step is failing for multimers using AlphaFold v2.3.0.
Monomers are working fine.

Error:
```
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: Failed to load in-memory CUBIN: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:1043] could not synchronize on CUDA context: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
```

I tested the relaxation with up to 8 x A100 GPUs, but it failed (apparently there is a memory leak somewhere).
If I run the inference with v2.3.0 and relaxation with v2.2.4, it works fine.

I attached a sequence that returned this error (changed the suffix to txt to work on github UI).
[1S78.txt](https://github.com/deepmind/alphafold/files/10271938/1S78.txt)

**Comment by joshabramson** [comment]
we are looking into this, but might not come back with something until after the holiday period.

can i check: if you run inference+relax all in v2.2.4, rather than inference and then separately relax, it does work?

**Comment by leiterenato** [comment]
Hi @joshabramson 

I tried to run v2.3.0 using the `run_docker.py` from `https://github.com/deepmind/alphafold/tree/main/docker/run_docker.py`.

I tried with both full_bfd and reduced_bfd without any success.

First try:
```
nohup python3 docker/run_docker.py \
  --fasta_paths=/home/renatoleite/workspace/vertex-ai-alphafold-inference-pipeline/sequences/1S78.fasta \
  --output_dir=/home/renatoleite/workspace/outputs \
  --max_template_date=2030-01-01 \
  --model_preset=multimer \
  --data_dir=/mnt/nfs/alphafold \
  --num_multimer_predictions_per_model=1 &
```
Second try:
```
nohup python3 docker/run_docker.py \
  --fasta_paths=/home/renatoleite/workspace/vertex-ai-alphafold-inference-pipeline/sequences/1S78.fasta \
  --output_dir=/home/renatoleite/workspace/outputs \
  --max_template_date=2030-01-01 \
  --model_preset=multimer \
  --data_dir=/mnt/nfs/alphafold \
  --num_multimer_predictions_per_model=1 \
  --db_preset=reduced_dbs &  
```

I also tried with my pipeline (separated prediction and relaxation), but got the same error.
https://github.com/GoogleCloudPlatform/vertex-ai-alphafold-inference-pipeline

For v2.2.4 it worked with both solutions (separated and inference+relax).

**Comment by alexanderimanicowenrivers** [comment]
The latest [fix](https://github.com/deepmind/alphafold/commit/8f1ebd58960b7eed708cf5eebcc88a7e6a3bf8a6) should solve this issue. Thank you for your patience.

**Comment by leiterenato** [comment]
@alexanderimanicowenrivers Thank you very much!
