### ISSUE TITLE
HHblits error "sequences in merged A3M file do not all have the same number of columns,"

### ISSUE THREAD

**Issue by ajbordner** [deepmind/alphafold#661]
AlphaFold is crashing due to an HHblits error in v2.3.0 but not in v2.2.4. This happens, for example, with the input sequence:
>chain_A
LEVQVPEDPVVALVGTDATLCCSFSPEPGFSLAQLNLIWQLTDTKQLVHSFAEGQDQGSAYANRTALFPDLLAQGNASLRLQRVRVADEGSFTCFVSIRDFGSAAVSLQVAAPYSKPSMTLEPNKDLRPGDTVTITCSSYQGYPEAEVFWQDGQGVPLTGNVTTSQMANEQGLFDVHSILRVVLGANGTYSCLVRNPVLQQDAHSSVTITPQRSPTGAVEVQVPEDPVVALVGTDATLRCSFSPEPGFSLAQLNLIWQLTDTKQLVHSFTEGRDQGSAYANRTALFPDLLAQGNASLRLQRVRVADEGSFTCFVSIRDFGSAAVSLQVAAPYSKPSMTLEPNKDLRPGDTVTITCSSYRGYPEAEVFWQDGQGVPLTGNVTTSQMANEQGLFDVHSVLRVVLGANGTYSCLVRNPVLQQDAHGSVTITGQPMTFPPEA

There are many long titin sequences in HHblits hits, which may be causing the issue.  I have included an excerpt of the output log.

[test.log](https://github.com/deepmind/alphafold/files/10272808/test.log)

**Comment by joshabramson** [comment]
The uniref30 db has been updated in v2.3.0 which can cause different behaviour for this hhblits search. HHBlits is sensitive and the new db can cause errors for some targets which did not error before.

A suggested workaround is to try with the db_preset flag set to 'reduced_dbs'.

**Comment by ajbordner** [comment]
There seems to be another issue causing the hhblits error. The hhblits command that AlphaFold runs completes without an error when run outside of the docker container. The same version of hhblits as in the Dockerfile (3.3.0), same database files, and input sequence file were used for the test.

hhblits -i <FASTA input sequence file> -cpu 4 -oa3m /tmp/output.a3m -o /dev/null -n 3 -e 0.001 -maxseq 1000000 -realign_max 100000 -maxfilt 100000 -min_prefilter_hits 1000 -d <alphafold data directory>/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt -d <alphafold data directory>/uniref30/UniRef30_2021_03

**Comment by joshabramson** [comment]
we tried running hhblits directly too, but got the same error that you (and we) see when running the target in docker.

can you double check that your hhblits run was with the exact same sequence? and did it also give warnings about the titin results (ours did)?

assuming it was the same sequence, something funny might be happening with ram usage, but im afraid using reduced_dbs is the only workaround for now.

**Comment by ajbordner** [comment]
I now also get the same error messages. I must have run hhblits for only 1 db since it only generates errors when run with both dbs. Thank you for your help.

**Comment by joshabramson** [comment]
Closing this issue - please re-open or open a new issue if there are continuing problems.
