### ISSUE TITLE
Calculate mean and per residue pLDDT scores of AlphaFold's model PDBs (post-prediction)

### ISSUE THREAD

**Issue by meh47336** [deepmind/alphafold#662]
Hello,

I've found the lddt script here but am unsure how to implement it outside of the AlphaFold. Recently I've obtained many predictions using a variant of AlphaFold, however it did not include pLDDT scores in the PDB outputs. Is there a way to calculate the scores retroactively using the PDB outputs?

Thank you for any help or suggestions,

**Comment by joshabramson** [comment]
If the pdb files come from a non-Alphafold model, any confidence metrics will be output by that other model.

One has to run the alphafold model to get alphafold confidence metrics, since those metrics are the models own measure of its certainty.

**Comment by tcoates5** [comment]
If you have the .npz files from the AlphaFold variant, you might be able to build something analogous to pLDDT scores based on that. The pdb simply does not have any of the information needed to estimate error in a quantified way.

**Comment by meh47336** [comment]
The PDB are created by AlphaFold however it's just a Singularity container composed of the ML parts of AF (no MSA, etc). More specifically it's on Summit at OLCF (I asked the question here because things are a bit more active over here.

The output at Summit gives a pkl file and a PDB. The b-factor column of the PDBs contains all zero values rather than pLDDT scores. Any idea why this would not have been calculated or am I just missing something?

**Comment by meh47336** [comment]
The per-residue pLDDT values are stored in a numpy array within the .pkl output!
