### ISSUE TITLE
Colab pro + failing to predict >2000 residues 

### ISSUE THREAD

**Issue by HBCH1** [deepmind/alphafold#666]
Hi, I am using AlphaFold 2  (Colab pro +) to predict some proteins with long sequences. While it successfully predicted the structures of shorter sequences, it keeps failing with longer ones even tho I upgraded to colab pro + to have higher memory. 
Here is what I am getting: 

<img width="1234" alt="Alpha fold " src="https://user-images.githubusercontent.com/121411082/209489459-5fcca930-8962-4be4-a175-bea7d17b206c.png">
<img width="904" alt="alpha" src="https://user-images.githubusercontent.com/121411082/209489463-a95d93fa-3a25-48c2-b0b0-bc7f1a743bd9.png">

Is there a way to fix this issue or is AlphaFold 2 not currently able to predict >2000 bp sequences?
Thanks in advance!

**Comment by Htomlinson14** [comment]
Hi @ HBCH1 what GPU were you using in this session?

**Comment by Augustin-Zidek** [comment]
We recently updated AlphaFold Colab notebook (see http://go/gh/deepmind/alphafold/commit/a0b0cd9cc9f6db0f54ed6e4ba454a7e7f9add41f) to handle longer sequences better. Could you try with the updated code?

**Comment by HBCH1** [comment]
> Hi @ HBCH1 what GPU were you using in this session?

I was using Premium GPU with Colab Pro plus

**Comment by HBCH1** [comment]
> 

Hi @Augustin-Zidek , thanks for the link - I was not able to upload the page associated with the link you provided. Where can I find the updated notebook?

**Comment by Augustin-Zidek** [comment]
Sorry, I fixed the link in my previous comment. The notebook was updated in the repository, so the [standard Colab link](https://colab.research.google.com/github/deepmind/alphafold/blob/main/notebooks/AlphaFold.ipynb) points to the updated version

**Comment by Augustin-Zidek** [comment]
Closing this issue now, feel free to re-open if there is anything we could help with.

**Comment by HBCH1** [comment]
@Augustin-Zidek I have tried running my 2750 bp sequences on the new version but I had two issues:
1. msa was taking a very long time to search the data bases (~35 hours)
2. the prediction failed 

Do you mind advising on how to fix those issues?
