### ISSUE TITLE
fatal: unable to access 'https://github.com/soedinglab/hh-suite.git/': gnutls_handshake() failed: The TLS connection was non-properly terminated.

### ISSUE THREAD

**Issue by hezhiqiang8909** [deepmind/alphafold#668]
Making a new docker image shows The TLS connection was non-properly terminated.
![image](https://user-images.githubusercontent.com/49931482/209633902-3e9a55d2-5d01-4089-b1f5-240880953104.png)

**Comment by Augustin-Zidek** [comment]
Is this still an issue? It seems like a (hopefully transient) GitHub/network issue rather than AlphaFold issue.

**Comment by Augustin-Zidek** [comment]
Closing this issue now, feel free to open a new one if you are still hitting this problem.
