### ISSUE TITLE
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

### ISSUE THREAD

**Issue by hezhiqiang8909** [deepmind/alphafold#669]
![image](https://user-images.githubusercontent.com/49931482/209643661-e3176a5c-3c9b-4851-965f-c684f38aa740.png)

**Comment by Augustin-Zidek** [comment]
Sorry, I could not replicate this issue. Is it still happening, or was it transient?

**Comment by Augustin-Zidek** [comment]
Closing this issue now, feel free to open a new one if you are still hitting this problem.
