### ISSUE TITLE
uniref90 can't download

### ISSUE THREAD

**Issue by hezhiqiang8909** [deepmind/alphafold#671]
![image](https://user-images.githubusercontent.com/49931482/209895467-352dc627-eeda-4367-9670-8b19703c7f84.png)

**Comment by hezhiqiang8909** [comment]
Replace ftp://ftp.uniprot.org/pub/databases/uniprot/uniref/uniref90/uniref90.fasta.gz with https://ftp.uniprot.org/pub/databases/uniprot/uniref/uniref90/uniref90. fasta.gz solves the problem of not being able to download

**Comment by Augustin-Zidek** [comment]
Closing this issue, feel free to reopen this issue or open a new issue if this is still a problem.

**Comment by orbsmiv** [comment]
The link posted on 29 Dec 2022 works for me but is very slow. In the UK I am instead using the following:  
<https://ftp.ebi.ac.uk/pub/databases/uniprot/uniref/uniref90/uniref90.fasta.gz>

**Comment by JethroHemmann** [comment]
I just run into the same issue. Should the [download_uniref90.sh](https://github.com/deepmind/alphafold/blob/main/scripts/download_uniref90.sh) script be updated with the new URL?

**Comment by yamule** [comment]
https://www.uniprot.org/help/metalink
ftp://ftp.expasy.org/databases/uniprot/current_release/uniref/uniref90/uniref90.fasta.gz
I use expasy mirror site when there is a download problem with UniProt.

**Comment by th-of** [comment]
I don't think there's anything the AlphaFold team can do about this, but the download of uniref90 is extremely slow. The best I can get is 200-300 KiB/s, ETA of 30-50 hours. I get 56 MiB/s for the other databases.

**Comment by tcoates5** [comment]
Have you tinkered with the aria2c settings on the download, particularly -x and -j?

**Comment by hezhiqiang8909** [comment]
> Have you tinkered with the aria2c settings on the download, particularly -x and -j?

Didn't make any modification, could it be faster on your side

**Comment by tcoates5** [comment]
Yeah, I got some speed increases by increasing the max number of connections in aria2c. I think overall download was still around 10-12 hours, while it had previously taken over 20.

**Comment by Augustin-Zidek** [comment]
Fixed in https://github.com/deepmind/alphafold/commit/4bd3ff76cc51613af617f49e8179b603ee2f1576 -- I changed the UniRef90 mirror to EBI's mirror which should be ~100x faster.
