### ISSUE TITLE
Alphafold-Multimer was run for more than 48h, I still couldn't get the structure of a complex with 4 subunits (total aa length: 2222+689+201+196). 

### ISSUE THREAD

**Issue by echoduan** [deepmind/alphafold#673]
Hi, author

```
python3 docker/run_docker.py \
  --fasta_paths=complex1.fasta \
  --max_template_date=2022-12-30 \
  --model_preset=multimer \
  --data_dir=/data  --gpu_devices=0,1,2,3 > complex1.log &
```

1) The program was always calculating the model until now.

```
I0107 01:49:08.176561 140086208259904 run_docker.py:255] I0107 01:49:08.175831 140502687897408 run_alphafold.py:191] Running model model_1_multimer_v3_pred_0 on complex1
I0107 01:49:08.178550 140086208259904 run_docker.py:255] I0107 01:49:08.178094 140502687897408 model.py:165] Running predict with shape(feat) = {'aatype': (3308,), 'residue_index': (3308,), 'seq_length': (), 'msa': (5799, 3308), 'num_alignments': (), 'template_aatype': (4, 3308), 'template_all_atom_mask': (4, 3308, 37), 'template_all_atom_positions': (4, 3308, 37, 3), 'asym_id': (3308,), 'sym_id': (3308,), 'entity_id': (3308,), 'deletion_matrix': (5799, 3308), 'deletion_mean': (3308,), 'all_atom_mask': (3308, 37), 'all_atom_positions': (3308, 37, 3), 'assembly_num_chains': (), 'entity_mask': (3308,), 'num_templates': (), 'cluster_bias_mask': (5799,), 'bert_mask': (5799, 3308), 'seq_mask': (3308,), 'msa_mask': (5799, 3308)}
```

2) The instance (p3.8xlarge) has four GPUs (4xNVIDIA V100).  All GPUs are available to calculate the model (`--gpu_devices=0,1,2,3`). But I noticed that 'run_alphafold.py' seems to use four GPUs, but why only the first one GPU memory is fulfilled?

![image](https://user-images.githubusercontent.com/22016970/211168401-e7fa4b22-3321-490b-b727-4cf7da0ee94a.png)
How can I use the four GPUs with maximum memory usage at the same time to speed up the prediction?

**Comment by alexanderimanicowenrivers** [comment]
Hi @echoduan, AlphaFold inference cannot be split over multiple devices. Most of the time elapsed for the first prediction will be MSA search. To get a final prediction for your structure, you should leave the script to run until completion, ideally without running additional tasks else on the workstation, as this could dramatically slow things down. Closing this issue, feel free to reopen this issue or open a new issue if this is still a problem.
