### ISSUE TITLE
If it is a wrong comparison in _openmm_minimize function？

### ISSUE THREAD

**Issue by wzabsd** [deepmind/alphafold#674]
Sorry for first time write issue in this project.

It is a part of `_openmm_minimize` function in  amber_minimize.py.

```python
 if stiffness > 0 * ENERGY / (LENGTH**2): 
    _add_restraints(system, pdb, stiffness, restraint_set, exclude_residues)
```
It seems that this if statement always returns **True**, but **stiffness** is a parameter we set.
Is it a hardcoded part to force adding restraints?
Thank you.

**Comment by andyballard** [comment]
Hi,

Thanks for your question. 

The relax procedure is a restrained minimization and so the restraints should be applied by default. You are free to turn off restraints entirely by setting the stiffness to zero (in which case the `if` statement would evaluate to `False`), but this could cause the structure to move far from the model's prediction and so is likely to give less accurate results.

**Comment by andyballard** [comment]
The stiffness also has meaning as a float -- a higher value will keep the protein closer to its prediction during relax, but setting the value too high can result in violations that don't get resolved. In our experience the default value of 10.0 is a good one to go with.
