### ISSUE TITLE
confusing result after running alphafold-multimer 

### ISSUE THREAD

**Issue by lamyankin** [deepmind/alphafold#678]
I have run alphafold-multimer for several heterodimers, but everytime I got the confusing result .
As shown in the picture, the distance between the two subunits are so far. Does this mean they cannot be heterodimer?
![image](https://user-images.githubusercontent.com/86952016/212030889-d1111dae-8451-4e0f-b888-8ec58152319f.png)

**Comment by abhinavb22** [comment]
Looks like they don't interact. However, just because two chains are in contact in the prediction doesnt mean that it is accurate. You need to look at the ranking confidence / iptm scores to say if they interact or not.

**Comment by lamyankin** [comment]
thanks for you reply!
