### ISSUE TITLE
HHBlits database is not found at uniref30_database

### ISSUE THREAD

**Issue by kimdn** [deepmind/alphafold#679]
I downloaded all databases.

![Screen Shot 2023-01-12 at 12 02 05 PM](https://user-images.githubusercontent.com/3903446/212168993-bd7e2c3f-f88c-4e0d-be05-b6bd82169d25.png)

Of course, I think that I downloaded uniref30 db well
![Screen Shot 2023-01-12 at 11 56 14 AM](https://user-images.githubusercontent.com/3903446/212167915-e49ebaf1-2a44-49cb-a210-e780e750eacd.png)

since I ran
`source scripts/download_uniref30.sh /people/kimd999/nanobody_rcfs/alphafold/db`

and AF expects 7 files of uniref30 DB

![Screen Shot 2023-01-12 at 11 57 47 AM](https://user-images.githubusercontent.com/3903446/212168260-43623f9c-9739-4b3e-8d85-ef23755dcb18.png)

However, when I ran
```

cmd="/share/apps/alphafold/2.3.0/alphafold"
data_dir="/rcfs/projects/nanobody/alphafold/db"
fasta_paths="test.fasta"

max_temp="3000-01-01" #https://github.com/deepmind/alphafold/issues/344

output="output"

$cmd --data_dir=$data_dir --fasta_paths=$fasta_paths --output_dir=$output --max_template_date=$max_temp

```
HHBlits database is not found at uniref30_database.

![Screen Shot 2023-01-12 at 12 00 05 PM](https://user-images.githubusercontent.com/3903446/212168612-f796d586-2456-4df5-bb7e-5bd7caba6cdd.png)

If someone can share their working uniref30 path etc. that will be helpful.

**Comment by tomgoddard** [comment]
I recall seeing the same error and the problem in my case was that the file uniref30/uniref30.fasta did not have read permission for group and others.

**Comment by kimdn** [comment]
> I recall seeing the same error and the problem in my case was that the file uniref30/uniref30.fasta did not have read permission for group and others.

Thanks Tom for this Alphafold advice (on top of chimeraX one).

**Comment by kimdn** [comment]
I'm closing this issue.

The solution was to use 
`uniref30_database_path=<FLAGS.data_dir>/uniref30/UniRef30_2021_03`
according to https://github.com/deepmind/alphafold/blob/main/docker/run_docker.py

Unlike uniref90 that uses uniref90.fasta
uniref30 has non-fasta files
<img width="399" alt="Screen Shot 2023-01-12 at 4 56 51 PM" src="https://user-images.githubusercontent.com/3903446/212212576-e64bebb3-20de-4f73-b988-52da4d1fc71f.png">
