### ISSUE TITLE
Downloading issue

### ISSUE THREAD

**Issue by wguan3** [deepmind/alphafold#681]
I used ChimeraX 1.4 AlphaFold function to predict a complex protein structure. After it completed, it shows "Downloading structure predictions to directory Downloads/ChimeraX/AlphaFold", but I couldn't find it on my mac. I'm wondering whether anyone knows how to download the predictions of pdb files. Thanks.

**Comment by longlong1884** [comment]
Hi, I am facing the same issue as you had. The downloading is stopped in the middle and never go ahead. I am wondering if you have fix the problem and may suggest me the solutions. Thanks

Chen
