### ISSUE TITLE
dependencies in readme

### ISSUE THREAD

**Issue by janxkoci** [deepmind/alphafold#688]
In the readme you mention users should install `aria2c` as it is needed for downloading the databases. Searching with most package managers will fail, because the name you mention is just the binary to run the download client - the real package name is `aria2` (without the `c`), which is indeed present in package managers I checked (`conda`, `apt`) as well as a module at a HPC cluster I have access to.

So if you can please change the instructions to show `aria2` as dependency, so users can find it faster.

Thanks

**Comment by Augustin-Zidek** [comment]
Good point, thanks for the suggestion. I submitted a documentation fix internally, I will close this issue once it is pushed to GitHub.

**Comment by Augustin-Zidek** [comment]
Fixed in https://github.com/deepmind/alphafold/commit/41871c0989b2d705c0a3d81bf6e6d2b807b464ea. Thanks again for reporting!
