### ISSUE TITLE
Community Integration: Making AlphaFold cheaper, faster, and more efficient

### ISSUE THREAD

**Issue by binmakeswell** [deepmind/alphafold#690]
Thank you for your outstanding contribution to AlphaFold!

AI for Science, e.g., AlphaFold, has recently risen to be one of the hottest topics in AI. We are happy to share a fantastic solution where the costs of training/inference AlphaFold can be cheaper a lot!

[Colossal-AI](https://github.com/hpcaitech/ColossalAI) provides an optimizing AlphaFold training and inference solution on GPU clusters. We successfully minimize AlphaFold’s training time from 11 days to only 67 hours and accelerate inference time by up to ~11.6 times. Developers can use a laptop to analyze 90% of proteins, with a single-GPU inference sequence exceeding 10,000! It accelerates AlphaFold inference by 5 times and reduces GPU memory by 75%.

Open-source code：https://github.com/hpcaitech/ColossalAI#Biomedicine

More details can be found on the [blog](https://www.hpc-ai.tech/blog/use-a-laptop-to-analyze-90-of-proteins-with-a-single-gpu-inference-sequence-exceeding). We would appreciate it if we could build the integration with you to benefit both of our users, and we are willing to provide help you need in this cooperation.

Thank you very much.

**Comment by zw7u9tru** [comment]
Translation:
Your team used 256 -> then 512 A100s to train AF2 over 2.8 days, and Deepmind used 128 TPUv3s over 11 days to do the same thing.

It appears your team has made some improvements to the algorithm, but if you're going to do this type of advertising directly on the af2 github you could at least try to not be deceptive about it. those numbers are not comparable at all.
