### ISSUE TITLE
Is it possible to cull or replace the alignment data set?

### ISSUE THREAD

**Issue by dahaigui** [deepmind/alphafold#691]
I am working on _Brassica oleracea_ and I want to speed up the AlphaFold, is it possible to replace the mgnify database and the uniref90 database with protein database from some Brassicaceae crops (e.g. _Arabidopsis thaliana_, _Brassica napus_, _Brassica rapa_ etc.)?

**Comment by Augustin-Zidek** [comment]
It is possible, but a bit hacky. What you can do is take the specific protein database in a FASTA format, rename it to match MGnify or UniRef90 and replace the MGnify/UniRef90 FASTA file with the one you want to use instead. AlphaFold will then search that database instead. 

However, I expect this will degrade AlphaFold folding accuracy as AlphaFold accuracy strongly correlates with MSA depth and the MSA contains also similar sequences across multiple species.

Alternatively, you could also use the AlphaFold Database: www.alphafold.com which contains predictions for vast majority of UniProt sequences.
