### ISSUE TITLE
AlphaFold-multimer v3 training data

### ISSUE THREAD

**Issue by gezmi** [deepmind/alphafold#693]
Hi,

Is there a chance that the training data for v2.3 is shared/could be shared somewhere (either just the list of used pdbs and chains)? It would be great for one of our projects.

Thank you!

**Comment by Htomlinson14** [comment]
Hi @gezmi! Thanks for the question. We don't plan on releasing the training data, but this can be reproduced by following the AlphaFold2 paper, and the updated instructions for 2.3 in https://github.com/deepmind/alphafold/blob/main/docs/technical_note_v2.3.0.md
