### ISSUE TITLE
Odd release in conjunction with RoseTTAFold gaining traction

### ISSUE THREAD

**Issue by MentalGear** [deepmind/alphafold#7]
While it's great you finally release your code publicly (after months of criticism for keeping it secret against the ethos of mutual aid in the scientific world) it certainly seems strange to do it just around the time [RoseTTAFold](https://techcrunch.com/2021/07/15/researchers-match-deepminds-alphafold2-protein-folding-power-with-faster-freely-available-model/) , a system that does nearly the same thing for free at a fraction of the computational cost, gains significant traction in news stories.

That sudden release might give the impression of an orchestrated effort of your PR department to bury the RoseTTAFold news story.

I'm certain you will deny any of this, but to be without the shadow of a doubt in the future, DeepMind might want to share their work openly and proactively with the scientific world, instead of releasing what seems in a defensive way.

**Comment by ValZapod** [comment]
> That sudden release might
RoseTTA was released 15 days ago.
https://github.com/RosettaCommons/RoseTTAFold/commit/dcaf58abba412bae5ae82c47b357ed343518f534

Also, who cares about code, the most important part is the model, of course. You know weights for neuronet.

> I'm certain you will deny any of this,

Why?? Nobody denies that. Alphafold is superiour and if they will do decentralised learning like leela chess  did (in C++, not Python using nvidia 20 series and 30 series tensor cores) they will dominate the field immediatelly.

**Comment by MentalGear** [comment]
> > That sudden release might
> 
> RoseTTA was released 15 days ago.
> [RosettaCommons/RoseTTAFold@dcaf58a](https://github.com/RosettaCommons/RoseTTAFold/commit/dcaf58abba412bae5ae82c47b357ed343518f534)
> 

It's about RoseTTAFold just recently gaining traction in the newscycle which is important to make more people aware of it, not the release date of the source code.

> Also, who cares about code, the most important part is the model, of course. You know weights for neuronet.

Seriously? The model alone doesn't allow you to reproduce the underlying approach used or compare it with other methods. Which is the whole point of gaining knowledge to refine approaches, not just using them in a model.
Also, it's far more valuable to have the code to a smaller, far more efficient model that you can modify, train and run yourself than a huge model that can only run on TPU cloud tech you need to rent for huge sums.

> Alphafold is superior and if they will do decentralised learning like leela chess did (in C++, not Python using nvidia 20 series and 30 series tensor cores) they will dominate the field immediatelly.

What exactly is it that you call superior? Alphafold seems to be still a bit more precise, but an open-source system as is RoseTTAFold which can be improved quickly and openly, and which is far more efficient in what it does, will soon become the "superior" solution.

**Comment by Augustin-Zidek** [comment]
We announced our plans to release our full methods in a peer-reviewed paper at CASP14 last December, which we have now done alongside this source code. You'll see that our paper was submitted to Nature in [early May](https://www.nature.com/articles/s41586-021-03819-2#article-info); this release has been in the works for a long time.

**Comment by ValZapod** [comment]
Looks like this is over with https://alphafold.ebi.ac.uk/entry/O14746 it is also now used in Uniprot. Wow, that is fast.
