### ISSUE TITLE
issue on docker build

### ISSUE THREAD

**Issue by ajian-he** [deepmind/alphafold#70]
I set my alphafold in my data drive (60T), download all database and put into the alphafold/library
then I build docker by
$ docker build -f docker/Dockerfile -t alphafold .
Sending build context to Docker daemon  2.735TB
Error response from daemon: Error processing tar file(exit status 1): write /library/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt.tar.gz: no space left on device

Any help? Does this mean I need reinstall docker not in a different path, not in the default path (/), which only have 2T including the system CentOS 7.

Thank you!

**Comment by nzhou26** [comment]
I met the same error. My solution is moving the database folder outside the alphafold folder. Then Modify DOWNLOAD_DIR in docker/run_docker.py

**Comment by ajian-he** [comment]
Works! Thank you, nzhou26!
