### ISSUE TITLE
afdb - retrieving accession_ids.csv and sequences.fasta

### ISSUE THREAD

**Issue by joegeorgeson** [deepmind/alphafold#703]
Dear alphafold,

Is there another location to download `accession_ids.csv` and `sequences.fasta` other than below? The connection drops before the download finishes - I've tried from local and cloud-based servers and the connection dies after a few hours (via `wget` or `curl`). With these download issues in mind, might you consider compressing and providing a checksum?

```
http://ftp.ebi.ac.uk/pub/databases/alphafold/accession_ids.csv
http://ftp.ebi.ac.uk/pub/databases/alphafold/sequences.fasta
```

Thank you very much,
Joe

**Comment by Htomlinson14** [comment]
Hi have you tried using the gcloud CLI? https://cloud.google.com/sdk/gcloud/reference/storage

**Comment by Htomlinson14** [comment]
https://storage.googleapis.com/public-datasets-deepmind-alphafold-v4/accession_ids.csv
https://storage.googleapis.com/public-datasets-deepmind-alphafold-v4/sequences.fasta

Both FTP site and cloud should work but if there are connection issues its worth seeing what works best for your use case.

**Comment by Htomlinson14** [comment]
https://storage.googleapis.com/public-datasets-deepmind-alphafold-v4/accession_ids.csv
https://storage.googleapis.com/public-datasets-deepmind-alphafold-v4/sequences.fasta

These can be downloaded as:
```
gcloud storage cp gs://public-datasets-deepmind-alphafold-v4/accession_ids.csv <DOWNLOAD_DIR>
```
or 
```
gcloud storage cp gs://public-datasets-deepmind-alphafold-v4/sequences.fasta <DOWNLOAD_DIR>
```

**Comment by joegeorgeson** [comment]
Thank you very much for this. Another question - should I be able to download from the public bucket to a local directory or only another bucket? I get some error that doesn't make sense because all the dependencies are installed, however I can transfer to my s3 bucket without problem.

this works fine;
```
gcloud storage cp gs://public-datasets-deepmind-alphafold-v4/accession_ids.csv s3://my-place/
```

This fails;
```
[user@access ~]$ gcloud storage cp gs://public-datasets-deepmind-alphafold-v4/accession_ids.csv .
Copying gs://public-datasets-deepmind-alphafold-v4/accession_ids.csv to file://./accession_ids.csv
Pausing command execution:/7.0GiB

This command requires the `gcloud-crc32c` component to be installed. Would you like to install the `gcloud-crc32c` component to continue command execution? (Y/n)?
⠹ Completed files 0/1 | 0B/7.0GiB
```

**Comment by Htomlinson14** [comment]
You should also be able to download to a local directory. It may be that gcloud requires this dependency to do so -- I haven't come across this error.

Looking at https://cloud.google.com/storage/docs/gsutil/addlhelp/CRC32CandInstallingcrcmod, it seems that this is used to validate integrity (e.g. checksums) so perhaps this is helpful for the use case you described in your original issue comment

**Comment by joegeorgeson** [comment]
So ...it seems that the file size might be prohibitive?

I can easily download a `cif` locally, as below;
```
gcloud storage cp gs://public-datasets-deepmind-alphafold-v4/AF-A0A009EVU0-F1-model_v4.cif .
```

But I noticed that when moving to my bucket I get the below warning about checksums (but it transfers ok);
```
WARNING: S3 support is currently unstable and should not be relied on for production workloads.
Copying gs://public-datasets-deepmind-alphafold-v4/sequences.fasta to s3://my-place/sequences.fasta

WARNING: S3 support is currently unstable and should not be relied on for production workloads.
WARNING: S3 does not support MD5 validation for the entire object if size > 5368709120 bytes. File size: 99265486907
```

I think my comment earlier is just a coincidence...so for my specific case I found a work-around to transfer from your bucket to my bucket, and then from my bucket to my local drive, but I was still unable to copy these from the ftp site or gs to my local storage.

**Comment by Htomlinson14** [comment]
I have been able to download large files locally -- what error were you seeing there? There is also the storage transfer service for cloud-to-cloud: https://cloud.google.com/storage-transfer-service

**Comment by joegeorgeson** [comment]
> I have been able to download large files locally -- what error were you seeing there?

As written above, just the warning `WARNING: S3 does not support MD5 validation for the entire object if size > 5368709120 bytes. File size: 99265486907` but the gs-to-aws bucket transfer is completed ok.

> There is also the storage transfer service for cloud-to-cloud: https://cloud.google.com/storage-transfer-service

I was able to transfer from your gs to my aws bucket - I have paid aws and gcp accounts but maybe it's a configuration issue on my end.

Thanks for you help, because I have the bucket-transfer workaround I won't troubleshoot further. It could be a specific issue to my environemnt.

**Comment by Htomlinson14** [comment]
Thats great that this has worked. Closing this issue. Thanks!

**Comment by joegeorgeson** [comment]
Hi sorry to reopen this, but just want to point out that this worked for gs but failed for the s3 transfer with the below error. A quick search revealed that it's related to file size and internal aws checksums which may be circumvented by compressing.

```
gcloud storage cp gs://public-datasets-deepmind-alphafold-v4/sequences.fasta s3://my-place/

⠏ERROR: InvalidArgument: Part number must be an integer between 1 and 10000, inclusive
```
