### ISSUE TITLE
module 'lib' has no attribute 'OpenSSL_add_all_algorithms'

### ISSUE THREAD

**Issue by bioaurbehno** [deepmind/alphafold#707]
After I run the "Search against genetic databases", I get this error. I don't understand what is wrong

**Comment by MooseyGoosey** [comment]
Getting the same issue, was working fine yesterday.

**Comment by outlierd29** [comment]
you have to upgrade pyopenssl, like:

!pip install --upgrade pyopenssl

**Comment by SolMiele** [comment]
I get this error in the colab notebook, what should I do?

**Comment by MooseyGoosey** [comment]
> I get this error in the colab notebook, what should I do?

@outlierd29's suggestion worked for me in the colab notebook, I just added it as a new line of code and ran it before step 4.
