### ISSUE TITLE
Getting "ValueError: Cannot create a tensor proto whose content is larger than 2GB." for smaller sequences

### ISSUE THREAD

**Issue by DavidB256** [deepmind/alphafold#71]
Hello! I'm getting the error "ValueError: Cannot create a tensor proto whose content is larger than 2GB." when running AlphaFold jobs for proteins longer than ~650 residues. I have tried using `--max_template_data=1900-01-01` in order to limit MSA size, but this has not helped. I using 1 GPU, 8 CPU cores, and 150GB memory on my university's supercomputer. I am not interested in using `--preset=reduced_dbs`. Thanks!!

**Comment by abridgland** [comment]
Hi, would you mind sharing your input sequence and/or the MSA size? We wouldn’t expect to see this error from inputs of that length but there have been a few other reports like this, so we would like to investigate it further.

**Comment by DavidB256** [comment]
> Hi, would you mind sharing your input sequence and/or the MSA size? We wouldn’t expect to see this error from inputs of that length but there have been a few other reports like this, so we would like to investigate it further.

Here is a link to a Google Drive folder containing the .fasta file and .a3m file for my AlphaFold job: https://drive.google.com/drive/folders/1bGS80lNFlo9xUDXQs71K5im_1ZihBPut?usp=sharing

If there are any more files or contextual information that I should provide, please let me know! Thanks so much for taking a look at my issue.

**Comment by ShuminBAL** [comment]
same issue here.

**Comment by biohegedus** [comment]
Hi,

I have the same issue: 
>sp|Q9H222|ABCG5_HUMAN, as a control run for my install; this protein is in the afold db.
approx. 650 a.a., --preset=reduced_dbs 
```
I0803 14:46:22.664624 140420767680320 run_docker.py:193] I0803 12:46:22.663788 139992798213952 run_alphafold.py:142] Running model model_1
...
I0803 14:46:23.571433 140420767680320 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/tensor_util.py", line 528, in make_tensor_proto
I0803 14:46:23.571529 140420767680320 run_docker.py:193] "Cannot create a tensor proto whose content is larger than 2GB.")
I0803 14:46:23.571625 140420767680320 run_docker.py:193] ValueError: Cannot create a tensor proto whose content is larger than 2GB.
```

If I run with a shorter segment, ~280a.a. I have a nice result.

**Comment by biohegedus** [comment]
It seems for me that not the protein length was my problem. I got my shorter segment by removing a domain, which is highly conserved. The alignment and feature files with the highly conserved domain were extremely large (over 5GB). However, I do not understand why this is happening and this did not happen when deepmind generated the structure for this protein.

**Comment by chrisroat** [comment]
Would it be recommended (or not recommended) to tweak either of these parameters to deal with this error?  (I am facing it with 1200 a.a. sequences)

mgnify_max_hits: int = 501
uniref_max_hits: int = 10000

**Comment by arashnh11** [comment]
Following

**Comment by arashnh11** [comment]
@abridgland A similar error, I don't think it's the residue size. I successfully folded a giant protein with 4,800 sequences without an issue. but now getting error on a lower chain of 1,480 acids. 
Maybe related to the graph-proto definition for the tensor? 
https://stackoverflow.com/questions/51470991/create-a-tensor-proto-whose-content-is-larger-than-2gb

**Comment by mbassalbioinformatics** [comment]
same issue here for protein with 1070AA

```
MSRRKQAKPQHINSEEDQGEQQPQQQTPEFADAAPAAPAAGELGAPVNHPGNDEVASEDE
ATVKRLRREETHVCEKCCAEFFSISEFLEHKKNCTKNPPVLIMNDSEGPVPSEDFSGAVL
SHQPTSPGSKDCHRENGGSSEDMKEKPDAESVVYLKTETALPPTPQDISYLAKGKVANTN
VTLQALRGTKVAVNQRSADALPAPVPGANSIPWVLEQILCLQQQQLQQIQLTEQIRIQVN
MWASHALHSSGAGADTLKTLGSHMSQQVSAAVALLSQKAGSQGLSLDALKQAKLPHANIP
SATSSLSPGLAPFTLKPDGTRVLPNVMSRLPSALLPQAPGSVLFQSPFSTVALDTSKKGK
GKPPNISAVDVKPKDEAALYKHKCKYCSKVFGTDSSLQIHLRSHTGERPFVCSVCGHRFT
TKGNLKVHFHRHPQVKANPQLFAEFQDKVAAGNGIPYALSVPDPIDEPSLSLDSKPVLVT
TSVGLPQNLSSGTNPKDLTGGSLPGDLQPGPSPESEGGPTLPGVGPNYNSPRAGGFQGSG
TPEPGSETLKLQQLVENIDKATTDPNECLICHRVLSCQSSLKMHYRTHTGERPFQCKICG
RAFSTKGNLKTHLGVHRTNTSIKTQHSCPICQKKFTNAVMLQQHIRMHMGGQIPNTPLPE
NPCDFTGSEPMTVGENGSTGAICHDDVIESIDVEEVSSQEAPSSSSKVPTPLPSIHSASP
TLGFAMMASLDAPGKVGPAPFNLQRQGSRENGSVESDGLTNDSSSLMGDQEYQSRSPDIL
ETTSFQALSPANSQAESIKSKSPDAGSKAESSENSRTEMEGRSSLPSTFIRAPPTYVKVE
VPGTFVGPSTLSPGMTPLLAAQPRRQAKQHGCTRCGKNFSSASALQIHERTHTGEKPFVC
NICGRAFTTKGNLKVHYMTHGANNNSARRGRKLAIENTMALLGTDGKRVSEIFPKEILAP
SVNVDPVVWNQYTSMLNGGLAVKTNEISVIQSGGVPTLPVSLGATSVVNNATVSKMDGSQ
SGISADVEKPSATDGVPKHQFPHFLEENKIAVS
```

any advise on how to fix this issue would be much appreciated. For now im running alphafold through the run_docker.py script.

**Comment by biohegedus** [comment]
I think that I solved this issue last week.
Based on @chrisroat question, I tried to play with uniref_max_hits. However, it did not have any effect. I realized that this option is not implemented in the pipeline.py script. I suggest that two lines are missing from the script:
+    uniref90_msa = uniref90_msa[:self.uniref_max_hits]  # hege
+    uniref90_deletion_matrix = uniref90_deletion_matrix[:self.uniref_max_hits] # hege

Download the patch: http://alphafold.hegelab.org/pipeline.patch
and apply it as: patch alphafold/data/pipeline.py pipeline.patch

**Comment by mbassalbioinformatics** [comment]
ok for me this patch seems to have fixed the issue and ive been able to generate a prediction for my protein. Thanks @biohegedus for the support!!

**Comment by biohegedus** [comment]
I thought about forking, since I have corrected some other issues.
However, I am new to git. What do you suggest?

I started to use and modify a non-docker fork, since it is easier to test and modify.
So I will create a fork of that, make changes, and make pull request to that?
Or should I create two forks?

Thanks.

**Comment by Augustin-Zidek** [comment]
Addressed in https://github.com/deepmind/alphafold/commit/0be2b30b98f0da7aecb973bde04758fae67eb913.
