### ISSUE TITLE
AlphaFold v2.3.1 Colab Notebook - ImportError: Python version mismatch

### ISSUE THREAD

**Issue by biobrett6** [deepmind/alphafold#714]
Import Error in the 4th Cell of the Colab Notebook

![Screen Shot 2023-03-08 at 4 56 38 PM](https://user-images.githubusercontent.com/126603377/223859769-13ed5cdc-aad5-4e8a-b194-1a8a3ab4546d.png)

Thanks for the help in advance!

**Comment by Augustin-Zidek** [comment]
We are validating a fix, in the meanwhile you can use the fix from https://github.com/deepmind/alphafold/pull/715 as a workaround. I will close this issue once we push a fix.

**Comment by evilegggyy1** [comment]
hi, @biobrett6 .
Actually, it seems that the version of python installed at first is different from the compiled version.
What you need is that **replace the "python 3.8" with the "python 3.9"** in the first block, after that everything seem well.

**Comment by zyc573823770** [comment]
@evilegggyy1 
thanks a lot! address my problem.
