### ISSUE TITLE
CUDA / Tensorflow version mismatch in Dockerfile

### ISSUE THREAD

**Issue by chrisroat** [deepmind/alphafold#72]
The [Dockerfile has the default CUDA of 11.0](https://github.com/deepmind/alphafold/blob/1e216f93f06aa04aa699562f504db1d02c3b704c/docker/Dockerfile#L15), and the [requirements for this package use tensorflow v2.5](https://github.com/deepmind/alphafold/blob/1e216f93f06aa04aa699562f504db1d02c3b704c/requirements.txt#L12).  [Tensorflow's documentation](https://www.tensorflow.org/install/source#gpu) states it should be used with at least CUDA 11.2.

**Comment by chrisroat** [comment]
And simply switching to 11.2 does not work, since the nvidia image needs the full version number (i.e. 11.2.2) and [jaxlib does not get built for 11.2](https://github.com/google/jax/blob/main/CHANGELOG.md#jaxlib-0166-may-11-2021).

**Comment by Aspreadfire** [comment]
Not only the CUDA version，cuDNN is requested be 8.1 for Tensorflow 2.5
details for TF2.5:
https://analyticsindiamag.com/tensorflow-2-5-0-released-all-major-updates-features/
I don't think the Dockerfile is sensible.

**Comment by riquri** [comment]
In my environment (Ubuntu 20.04, RTX 3090), CUDA 11.1 works well.
Try to load a docker image "nvidia/cuda:11.1.1-cudnn8-runtime-ubuntu20.04" instead "nvidia/cuda:${CUDA}-base".
cuDNN 8.1 is installed and jaxlib 0.1.69 for CUDA11.1 is available.

**Comment by Aspreadfire** [comment]
I failed in installing conda module during build container in image "nvidia/cuda:11.3.1-cudnn8-runtime-ubuntu20.04".
So maybe CUDA image 11.1 or 11.2 is suitable for dockerfile.

**Comment by bkotopka** [comment]
As a temporary workaround for others with this issue - I was able to build a working container using "tensorflow/tensorflow:latest-gpu" as the base image.

**Comment by tfgg** [comment]
Hi,

We don't actually need GPU support in Tensorflow, as it is only used in the data pipeline which is pinned to the CPU. To make this clear (and avoid confusion about versions), I've fixed the `requirements.txt` to be `tensorflow-cpu` in b3ed8603e8b5f085342c50259da0ba9fe485ef94.

**Comment by chrisroat** [comment]
Does the [setup.py](https://github.com/deepmind/alphafold/blob/main/setup.py) file need to be sync'd with the requirements.txt file?

Also, as indicated in #88, it seems tensorflow is referenced within the model subdirectory.  Can you confirm the lack of GPU need for the model inference?

**Comment by tfgg** [comment]
The model is created using JAX, not Tensorflow, and so uses the GPU.

**Comment by chrisroat** [comment]
OK.  Does the setup.py file need to be updated to stay in sync with requirements.txt?
