### ISSUE TITLE
AF Colab crashing

### ISSUE THREAD

**Issue by jfbazan** [deepmind/alphafold#734]
When I run the DeepMind AF2.3.1 Colab, it will go through the start up procedure but just before the 'search through genetic databases' step, it will suddenly crash with the following error msg, centering on the fault **AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms**

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-4-af259064ea59>](https://localhost:8080/#) in <module>
     25 import py3Dmol
     26 
---> 27 from alphafold.model import model
     28 from alphafold.model import config
     29 from alphafold.model import data

30 frames
[/opt/conda/lib/python3.9/site-packages/OpenSSL/crypto.py](https://localhost:8080/#) in <module>
   3266 # OpenSSL library (and is linked against the same one that cryptography is
   3267 # using)).
-> 3268 _lib.OpenSSL_add_all_algorithms()
   3269 
   3270 # This is similar but exercised mainly by exception_from_error_queue.  It calls

**AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'**

**Comment by alexwu66666** [comment]
Same issue occurs to me. Please help fix this. Thanks.

**Comment by ycyclop** [comment]
I'm encountering the same issue with ColabPro+. Please fix this ASAP as we paid for Pro+ and can't really use it.

**Comment by Htomlinson14** [comment]
This should be fixed with https://github.com/deepmind/alphafold/commit/3f31725591b0c6b0b6d63214235d3abe6b81742c
