### ISSUE TITLE
Invalid resolution format: ['?']

### ISSUE THREAD

**Issue by HF06** [deepmind/alphafold#738]
when i run the multimer inference, i have encountered "Invalid resolution format: ['?']" error. could anybody help me to deal with the error issues?

                   INFO     colossalai - root - INFO: Reading PDB entry from data/pdb_mmcif/mmcif_files/6xuo.cif. Query:                           
                             MSILFYVIFLAYLRGIQGNNMDQRSLPEDSLNSLIIKLIQADILKNKLSKQMVDVKENYQSTLPKAEAPREPERGGPAKSAFQPVIAMDTELLRQQRRYNSPRVLLSDSTPLEPPPLYL
                             MEDYVGSPVVANRTSRRKRYAEHKSHRGEYSVCDSESLWVTDKSSAIDIRGHQVTVLGEIKTGNSPVKQYFYETRCKEARPVKNGCRGIDDKHWNSQCKTSQTYVRALTSENNKLVGWR
                             WIRIDTSCVCALSRKIGRT, template:                                                                                         
                             TALRRARSAPARAIAARVAGQTRNITVDPKLFKKRRLRSPRVLFSTQPPPVAADTQDLDFEAGGAASFNRTHRSKRSSSHPVFHRGEFSVCDSVSVWVGDKTTATDIKGKEVMVLGEVN
                             INNSVFKQYFFETKCRDPNPVDSGCRGIDSKHWNSYCTTTHTFVKALTMDGKQAAWRFIRIDTACVCVLSRKTGR                                            
                    INFO     colossalai - root - INFO: Found an exact template match 6xuo_A.                                                        
                    INFO     colossalai - root - INFO: Reading PDB entry from data/pdb_mmcif/mmcif_files/3ij2.cif. Query:                           
                             MSILFYVIFLAYLRGIQGNNMDQRSLPEDSLNSLIIKLIQADILKNKLSKQMVDVKENYQSTLPKAEAPREPERGGPAKSAFQPVIAMDTELLRQQRRYNSPRVLLSDSTPLEPPPLYL
                             MEDYVGSPVVANRTSRRKRYAEHKSHRGEYSVCDSESLWVTDKSSAIDIRGHQVTVLGEIKTGNSPVKQYFYETRCKEARPVKNGCRGIDDKHWNSQCKTSQTYVRALTSENNKLVGWR
                             WIRIDTSCVCALSRKIGRT, template:                                                                                         
                             RVTGQTRNITVDPRLFKAARLHSPRVLFSTQPPPTSSDTLDLDFQAHGTIPFNRTHRSAASSTHPVFHMGEFSVCDSVSVWVGDKTTATDIKGKEVTVLAEVNINNSVFRQYFFETKCR
                             ASNPVESGCRGIDSKHWNSYCTTTHTFVKALTTDEKQAAWRFIRIDTACVCVLSRKAT                                                             
                    INFO     colossalai - root - INFO: Found an exact template match 3ij2_A.                                                        
                    INFO     colossalai - root - INFO: Reading PDB entry from data/pdb_mmcif/mmcif_files/3ij2.cif. Query:                           
                             MSILFYVIFLAYLRGIQGNNMDQRSLPEDSLNSLIIKLIQADILKNKLSKQMVDVKENYQSTLPKAEAPREPERGGPAKSAFQPVIAMDTELLRQQRRYNSPRVLLSDSTPLEPPPLYL
                             MEDYVGSPVVANRTSRRKRYAEHKSHRGEYSVCDSESLWVTDKSSAIDIRGHQVTVLGEIKTGNSPVKQYFYETRCKEARPVKNGCRGIDDKHWNSQCKTSQTYVRALTSENNKLVGWR
                             WIRIDTSCVCALSRKIGRT, template:                                                                                         
                             RVTGQTRNITVDPRLFKAARLHSPRVLFSTQPPPTSSDTLDLDFQAHGTIPFNRTHRSAASSTHPVFHMGEFSVCDSVSVWVGDKTTATDIKGKEVTVLAEVNINNSVFRQYFFETKCR
                             ASNPVESGCRGIDSKHWNSYCTTTHTFVKALTTDEKQAAWRFIRIDTACVCVLSRKAT                                                             
                    INFO     colossalai - root - INFO: Found an exact template match 3ij2_B.                                                        
                    INFO     colossalai - root - INFO: Reading PDB entry from data/pdb_mmcif/mmcif_files/1b8k.cif. Query:                           
                             MSILFYVIFLAYLRGIQGNNMDQRSLPEDSLNSLIIKLIQADILKNKLSKQMVDVKENYQSTLPKAEAPREPERGGPAKSAFQPVIAMDTELLRQQRRYNSPRVLLSDSTPLEPPPLYL
                             MEDYVGSPVVANRTSRRKRYAEHKSHRGEYSVCDSESLWVTDKSSAIDIRGHQVTVLGEIKTGNSPVKQYFYETRCKEARPVKNGCRGIDDKHWNSQCKTSQTYVRALTSENNKLVGWR
                             WIRIDTSCVCALSRKIGRT, template:                                                                                         
                             YAEHKSHRGEYSVCDSESLWVTDKSSAIDIRGHQVTVLGEIKTGNSPVKQYFYETRCKEARPVKNGCRGIDDKHWNSQCKTSQTYVRALTSENNKLVGWRWIRIDTSCVCALSRKIGRT
                    INFO     colossalai - root - INFO: Found an exact template match 1b8k_A.                                                        
                    INFO     colossalai - root - INFO: Reading PDB entry from data/pdb_mmcif/mmcif_files/1nt3.cif. Query:                           
                             MSILFYVIFLAYLRGIQGNNMDQRSLPEDSLNSLIIKLIQADILKNKLSKQMVDVKENYQSTLPKAEAPREPERGGPAKSAFQPVIAMDTELLRQQRRYNSPRVLLSDSTPLEPPPLYL
                             MEDYVGSPVVANRTSRRKRYAEHKSHRGEYSVCDSESLWVTDKSSAIDIRGHQVTVLGEIKTGNSPVKQYFYETRCKEARPVKNGCRGIDDKHWNSQCKTSQTYVRALTSENNKLVGWR
                             WIRIDTSCVCALSRKIGRT, template:                                                                                         
                             YAEHKSHRGEYSVCDSESLWVTDKSSAIDIRGHQVTVLGEIKTGNSPVKQYFYETRCKEARPVKNGCRGIDDKHWNSQCKTSQTYVRALTSENNKLVGWRWIRIDTSCVCALSRKIGRT
                    INFO     colossalai - root - INFO: Found an exact template match 1nt3_A.                                                        
                    INFO     colossalai - root - INFO: Reading PDB entry from data/pdb_mmcif/mmcif_files/3buk.cif. Query:                           
                             MSILFYVIFLAYLRGIQGNNMDQRSLPEDSLNSLIIKLIQADILKNKLSKQMVDVKENYQSTLPKAEAPREPERGGPAKSAFQPVIAMDTELLRQQRRYNSPRVLLSDSTPLEPPPLYL
                             MEDYVGSPVVANRTSRRKRYAEHKSHRGEYSVCDSESLWVTDKSSAIDIRGHQVTVLGEIKTGNSPVKQYFYETRCKEARPVKNGCRGIDDKHWNSQCKTSQTYVRALTSENNKLVGWR
                             WIRIDTSCVCALSRKIGRT, template:                                                                                         
                             YAEHKSHRGEYSVCDSESLWVTDKSSAIDIRGHQVTVLGEIKTGNSPVKQYFYETRCKEARPVKNGCRGIDDKHWNSQCKTSQTYVRALTSENNKLVGWRWIRIDTSCVCALSRKIGRT
                    INFO     colossalai - root - INFO: Found an exact template match 3buk_A.                                                        
                    INFO     colossalai - root - INFO: Reading PDB entry from data/pdb_mmcif/mmcif_files/3buk.cif. Query:                           
                             MSILFYVIFLAYLRGIQGNNMDQRSLPEDSLNSLIIKLIQADILKNKLSKQMVDVKENYQSTLPKAEAPREPERGGPAKSAFQPVIAMDTELLRQQRRYNSPRVLLSDSTPLEPPPLYL
                             MEDYVGSPVVANRTSRRKRYAEHKSHRGEYSVCDSESLWVTDKSSAIDIRGHQVTVLGEIKTGNSPVKQYFYETRCKEARPVKNGCRGIDDKHWNSQCKTSQTYVRALTSENNKLVGWR
                             WIRIDTSCVCALSRKIGRT, template:                                                                                         
                             YAEHKSHRGEYSVCDSESLWVTDKSSAIDIRGHQVTVLGEIKTGNSPVKQYFYETRCKEARPVKNGCRGIDDKHWNSQCKTSQTYVRALTSENNKLVGWRWIRIDTSCVCALSRKIGRT
[03/30/23 09:19:58] INFO     colossalai - root - INFO: Found an exact template match 3buk_B.                                                        
                    INFO     colossalai - root - INFO: Reading PDB entry from data/pdb_mmcif/mmcif_files/1bnd.cif. Query:                           
                             MSILFYVIFLAYLRGIQGNNMDQRSLPEDSLNSLIIKLIQADILKNKLSKQMVDVKENYQSTLPKAEAPREPERGGPAKSAFQPVIAMDTELLRQQRRYNSPRVLLSDSTPLEPPPLYL
                             MEDYVGSPVVANRTSRRKRYAEHKSHRGEYSVCDSESLWVTDKSSAIDIRGHQVTVLGEIKTGNSPVKQYFYETRCKEARPVKNGCRGIDDKHWNSQCKTSQTYVRALTSENNKLVGWR
                             WIRIDTSCVCALSRKIGRT, template:                                                                                         
                             YAEHKSHRGEVSVCDSESLWVTDKSSAIDIRGHQVTVLGEIKTQNSPVKQYFYETRCKEARPVKNGCRGIDDKHWNSQCKTSQTYVRALTSENNKLVGWRWIRIDTSCVCALSRKIGRT
                    INFO     colossalai - root - INFO: Invalid resolution format: ['?']                                                             
                    INFO     colossalai - root - INFO: Found an exact template match 1bnd_B.

**Comment by smturzo** [comment]
how can i recreate this error? Can you copy paste your exact inputs?

**Comment by Htomlinson14** [comment]
Hi thanks for raising this. The logs suggest this was run with ColossalAI. Could you please raise this issue with their Github? Thanks!
