### ISSUE TITLE
Python version mismatch: module was compiled for Python 3.9, but the interpreter version is incompatible: 3.10.11 (main, Apr  5 2023, 14:15:10) [GCC 9.4.0].

### ISSUE THREAD

**Issue by natalijensen** [deepmind/alphafold#756]
I am trying to run a protein structure prediction but after inputting my sequence I get errors. 

<img width="1343" alt="alphafold error" src="https://user-images.githubusercontent.com/124371621/235109949-4193d593-1be1-4ac6-9a80-164ef093eea7.png">

**Comment by lucaskbobadilla** [comment]
I am having the same issue.

**Comment by Augustin-Zidek** [comment]
Thanks for reporting, we are working on a fix which involves updating OpenMM to 7.7.0 which is compatible with Python 3.10. We will update this issue once fixed.

**Comment by SergioVerjovski** [comment]
I am also having the same issue.

**Comment by capricorn416** [comment]
I am also having the same issue.

**Comment by tonyhong007** [comment]
I am also having the same issue.

**Comment by aadilmanazir** [comment]
If possible, I would really appreciate it if this issue was resolved soon. I'm expanding another library to support Alphafold for a final course project (CS267, Berkeley) due next week. Whoever resolves this, you're a lifesaver!

**Comment by capricorn416** [comment]
> If possible, I would really appreciate it if this issue was resolved soon. I'm expanding another library to support Alphafold for a final course project (CS267, Berkeley) due next week. Whoever resolves this, you're a lifesaver!

I have found a solution that the colab has noted when connected to a runtime, choosing `Using the fallback runtime version`  from the Command Palette temporarily allows access to the Python 3.9 runtime, and will be available until mid-May. This will address the problem now. As you can read in https://medium.com/google-colab/colab-updated-to-python-3-10-27eb02daa162

**Comment by aadilmanazir** [comment]
capricorn the goat on gon cuh

**Comment by 8marmar8** [comment]
I'm trying to follow your suggestion, but when I open the link "https://colab.research.google.com/github/deepmind/alphafold/blob/main/notebooks/AlphaFold.ipynb", I don't have the option to change the Python version. I only see the option to choose between GPU and TPU. How can I resolve this issue?

**Comment by capricorn416** [comment]
> I'm trying to follow your suggestion, but when I open the link "https://colab.research.google.com/github/deepmind/alphafold/blob/main/notebooks/AlphaFold.ipynb", I don't have the option to change the Python version. I only see the option to choose between GPU and TPU. How can I resolve this issue?

First connecting to a runtime. Then you will find `Using the fallback runtime version` as shown in the below
![image](https://user-images.githubusercontent.com/74668705/235690263-4582a10e-85b6-43c1-914b-05ce46ac28e4.png)
