### ISSUE TITLE
Colab AlphaFold.ipynb  importing 'simtk.openmm' is deprecated error

### ISSUE THREAD

**Issue by uvfulcrum** [deepmind/alphafold#762]
Alphafold is failing during the 5th and final step (Run AlphaFold and download prediction) with an error: 

AMBER relaxation: 83%
5/6 [elapsed: 4:36:46 remaining: 55:17]
WARNING:root:Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.

**Comment by Augustin-Zidek** [comment]
I believe you must be running an old version of the notebook (see e.g. https://github.com/deepmind/alphafold/commit/955737f12cc4b27398fe2369417fc2cc79815eb6).

Could you try reloading the Colab notebook and rerunning from the beginning?
