### ISSUE TITLE
Supplement/source code discrepancy in TriangleMultiplicationIncoming

### ISSUE THREAD

**Issue by gahdritz** [deepmind/alphafold#77]
It seems to me that there's a slight discrepancy between the implementation of the "incoming" triangular matrix multiplicative update and the [official supplement to the writeup](https://static-content.springer.com/esm/art%3A10.1038%2Fs41586-021-03819-2/MediaObjects/41586_2021_3819_MOESM1_ESM.pdf).

**Supplement**

On line 4 of Alg. 12 (TriangleMultiplicationIncoming) on page 18 of the supplement, the left and right projections of the input (_a_ and _b_, respectively) are combined according to the following formula:

![image](https://user-images.githubusercontent.com/26167235/127585015-9c57ad80-15d5-4bb7-bc92-4d38528cefae.png)

**Source code**

In `config.py`, the einsum implementation of said formula is given as:

https://github.com/deepmind/alphafold/blob/1e216f93f06aa04aa699562f504db1d02c3b704c/alphafold/model/config.py#L238

The two differ by an extra transposition in the _i_, _j_ dimensions. There is no compensating additional transposition in the function in which the einsum formula is invoked:

https://github.com/deepmind/alphafold/blob/1e216f93f06aa04aa699562f504db1d02c3b704c/alphafold/model/modules.py#L1262

I'm noting this here because I believe the mistake to be in the source code and not the supplement, but I could be wrong about that.

**Comment by tfgg** [comment]
Hi,

Thanks for the question. The einsum expression is equivalent to the SI, as what's called `a` in the SI is `right_activation` in the code and what's called `b` in the SI is `left_activation` in the code.

**Comment by tfgg** [comment]
We've added a comment to this code to clarify its connection to the SI in b88f8dacef5d94e4d3d49613d08523feb20caec1.

**Comment by gahdritz** [comment]
I see! If you don't mind; do I understand correctly that the outcome would be the same if the incoming formula were `kic,kjc->ijc`, such that `a` and `b` are not flipped in this way?
