### ISSUE TITLE
The official AlphaFold2-multimer package with non-docker.

### ISSUE THREAD

**Issue by xiejuande** [deepmind/alphafold#770]
Hello, 

I would like to install AlphaFold2-multimer with non-docker. 
I found it on the Internet https://github.com/amorehead/alphafold_non_docker;
https://github.com/kalininalab/alphafold_non_docker
https://github.com/shrestha-bikash/Alphafold-Non-Docker
which one is official? 

 Looking forward to your reply, thank you!

 Best wishes!
Juan Xie

**Comment by Htomlinson14** [comment]
None of these are official in the sense that they are not affiliated with DeepMind -- thanks!
