### ISSUE TITLE
ModuleNotFoundError: No module named 'py3Dmol'

### ISSUE THREAD

**Issue by Leon-HXL** [deepmind/alphafold#78]
Hi,

I am running colab module of Alphafold but it keeps giving me the following error(s) although I have followed all the instructions. I ran it last night on one of my protein and it worked but now it's unable to find the module(s). I tried Factory reset runtime, I tried re-download and re-install the Alphafold, neither of them worked. Sometimes it told me ModuleNotFoundError: No module named 'alphafold.model', sometimes it told me ModuleNotFoundError: No module named 'py3Dmol'. I'm a green bird of Phython and Alphafold, and I don't know how to fix it. I really hope that someone can help me fix this issue. Thanks a lot!

Regards,
Leon

------------------------------------------------------------------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-22-1640ae7ce3a3> in <module>()
     24 import py3Dmol
     25 
---> 26 from alphafold.model import model
     27 from alphafold.model import config
     28 from alphafold.model import data

ModuleNotFoundError: No module named 'alphafold.model'

or
------------------------------------------------------------------------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-1640ae7ce3a3> in <module>()
     22 import matplotlib.pyplot as plt
     23 import numpy as np
---> 24 import py3Dmol
     25 
     26 from alphafold.model import **model**

ModuleNotFoundError: No module named 'py3Dmol'

**Comment by Leon-HXL** [comment]
Help needed!!! Don't let my issue sink... My problem is not solved yet... Can someone give me some useful suggestions??? PLS

**Comment by Augustin-Zidek** [comment]
Could you try the following two methods:

**Method 1**
1. Run the "Install third-party software" cell. 
2. Restart Runtime. 
3. Then run your import statement cell.

**Method 2**
If Method 1 doesn't help, then try rerunning the "Install third-party software" but change the line

```
%shell pip install py3dmol
```

to

```
%shell pip install -e py3dmol 
```

See also more tips in https://stackoverflow.com/questions/57838013/modulenotfounderror-after-successful-pip-install-in-google-colaboratory.

**Comment by Leon-HXL** [comment]
Thank you! I re-tried everything from the beginning after a few days and it suddenly worked! However, I don't understand why. Anyway, thanks a lot for helping out!
