### ISSUE TITLE
Error in parsing custom template file

### ISSUE THREAD

**Issue by data2code** [deepmind/alphafold#788]
When I provided my custom PDB file (see attached 3fn0.cif), AF failed to parse it.
The bug can be illustrated with the example code below (cif file can be found by unzipping the attachment):

```
    def _read_file(path):
        with open(path, 'r') as f:
            file_data = f.read()
        return file_data
    
    cif_path="3fn0.cif"
    cif_string = _read_file(cif_path)
    from alphafold.data import mmcif_parsing
    parsing_result = mmcif_parsing.parse(
        file_id="3fn0", mmcif_string=cif_string)
    print(parsing_result)
```

The code outputs:

```
ParsingResult(mmcif_object=None, errors={('3fn0', ''): KeyError('L')})
```
I did a bit of tracing into the code. In 3fn0.cif, the chains are ["L", "H", "P"], mmcif uses its own chain id ["A","B","C"]. Therefore, mmcif_to_author_chain_id dictionary has the value of {"A":"L", "B":"H", "C":"P"}.

However, it is odd to me that the code then tries to extract residue positions using mmcif chain id, i.e., line 221 in mmcif_parsing.py is never executed. Should not the code use author_chain_id instead?

```
      mmcif_to_author_chain_id[atom.mmcif_chain_id] = atom.author_chain_id

      ##### the next if condition is False, b/c mmcif_chain_id is not found in valid_chains. valid_chains contains "L","H", and "P".
      if atom.mmcif_chain_id in valid_chains:
        hetflag = ' '
        if atom.hetatm_atom == 'HETATM':
          # Water atoms are assigned a special
```
Finally, the error is thrown on line 247:
```
   for chain_id, seq_info in valid_chains.items():
      author_chain = mmcif_to_author_chain_id[chain_id]
```
Here the code use chain_id "L" from valid_chains to lookup, but mmcif_to_author_id only has keys ("A","B","C").

The logic seems will fail whenever the author chain id is not A, B, C, ... ?

Really appreciate your helps!

[cif.zip](https://github.com/deepmind/alphafold/files/11890401/cif.zip)

**Comment by data2code** [comment]
It seems the issue is AlphaFold cannot deal with the case when the label_asym_id is different from author_asym_id. Is the issue with the logic inside AF's mmcif_parsing.parse, or the problem needs to be fixed in the input .cif?

**Comment by Augustin-Zidek** [comment]
Hello, the problem is in the input mmCIF file:
* it is missing the `_entity_poly` table, 
* it is missing the `_entity` table,
* the `_struct_asym` table is corrupt as it contains author chain IDs instead of internal chain IDs.

These tables are needed by the mmCIF parser, otherwise it won't function correctly.

I did a test of the parser with the vanilla 3fn0.cif downloaded from the PDB and it parsed fine -- so I recommend using that one instead of your modified version.
