### ISSUE TITLE
Confusing wording/procedure in the Colab notebook

### ISSUE THREAD

**Issue by josephrocca** [deepmind/alphafold#79]
The FAQ for the Colab notebook says:

> Run all cells in the Colab, either by running them individually (with the play button on the left side) or via Runtime > Run all.

Although the meaning of this is clear to regular Colab users, I directed a friend in the bio space (non-programmer) to the notebook and they didn't understand this. In particular it's not clear what "cell" means, especially since the Colab notebook's UI is not very "cell-like". They clicked the third party dependencies play button, and then tried to just paste the protein sequence in the text area, and then click the play button on that cell. Perhaps they looked at the "Download AlphaFold" header and thought "Well, I don't want to download it to my computer. I want to use it on this website" and scrolled down to the next header.

For people who regularly use notebooks it's hard to see the difficulty in using a Colab notebook like this (the dev that created this has certainly done a lot better in terms of explanation than 95% of notebooks out there!), but user interfaces like this are completely foreign to many people outside computer science.

So, in the interests of making the notebook as accessible as possible, would it make more sense to have the very first cell (after the introduction) be the protein sequence text input, and then after that, informing the user to click `Runtime > Run all`? That way it's a simple 2-step process. If they then enter a second sequence and click `Runtime > Run all` again, the installation/setup could of course be skipped.

Or even better, making all execution happen within a single cell so that they can simply enter the sequence and then click the play button. Again, the install/setup would be skipped on subsequent play button clicks.

Or if those two solutions are for some reason not possible, perhaps the text "STEP \<NUMBER\>" could be added to each cell header.  So, for example, the first step would look something like this:

![image](https://user-images.githubusercontent.com/1167575/127608336-b93c79d7-5ca9-473b-a66f-5c4e2b63e7b3.png)

Though personally I like the `Runtime > Run all` or single-cell approach because then there's no need to "babysit" the colab notebook - watching it to see when each step is complete so you can click the next step (informing the user that you can queue play button clicks would just produce extra confusion).

**Comment by Augustin-Zidek** [comment]
Thanks for reporting this, this will be improved in the next bugfix release.
