### ISSUE TITLE
conda and python compatibility

### ISSUE THREAD

**Issue by YuriModeX** [deepmind/alphafold#798]
How to solve the problem below in block 1?

Specifications:

  - conda==4.13.0 -> python[version='>=3.10,<3.11.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']

Your python: python=3.11

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.31=0
  - feature:|@/linux-64::__glibc==2.31=0

Your installed version is: 2.31

**Comment by ikun821** [comment]
Having the same issue when trying to build the docker image. 

Code :docker build -f docker/Dockerfile -t alphafold .
[+] Building 23.3s (9/15)                                  docker:desktop-linux
 => [internal] load .dockerignore                                          0.0s
 => => transferring context: 72B                                           0.0s
 => [internal] load build definition from Dockerfile                       0.0s
 => => transferring dockerfile: 3.34kB                                     0.0s
 => [internal] load metadata for docker.io/nvidia/cuda:11.1.1-cudnn8-runt  0.6s
 => [internal] load build context                                          0.0s
 => => transferring context: 8.69kB                                        0.0s
 => [ 1/11] FROM docker.io/nvidia/cuda:11.1.1-cudnn8-runtime-ubuntu18.04@  0.0s
 => CACHED [ 2/11] RUN apt-get update     && DEBIAN_FRONTEND=noninteracti  0.0s
 => CACHED [ 3/11] RUN git clone --branch v3.3.0 https://github.com/soedi  0.0s
 => CACHED [ 4/11] RUN wget -q -P /tmp   https://repo.anaconda.com/minico  0.0s
 => ERROR [ 5/11] RUN conda install -qy conda==4.13.0     && conda insta  22.6s
------                                                                          
 > [ 5/11] RUN conda install -qy conda==4.13.0     && conda install -y -c conda-forge       openmm=7.7.0       cudatoolkit==11.1.1       pdbfixer       pip       python=3.8       && conda clean --all --force-pkgs-dirs --yes:                
0.346 Collecting package metadata (current_repodata.json): ...working... done   
2.224 Solving environment: ...working... unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
2.224 Collecting package metadata (repodata.json): ...working... done
8.635 Solving environment: ...working... unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
15.56 Solving environment: ...working... 
21.89 Found conflicts! Looking for incompatible packages.
21.89 This can take several minutes.  Press CTRL-C to abort.
Examining @/linux-64::__linux==5.15.49=0:  17%|█▋        | 1/6 [00:00<00:00, 102Examining @/linux-64::__unix==0=0:  33%|███▎      | 2/6 [00:00<00:00, 12157.40itExamining @/linux-64::__archspec==1=x86_64:  50%|█████     | 3/6 [00:00<00:00, 1Examining conda==4.13.0:  67%|██████▋   | 4/6 [00:00<00:00, 13389.64it/s]       Examining conflict for conda python:  17%|█▋        | 1/6 [00:00<00:00, 303.23it                                                                                failed
22.00 
22.00 UnsatisfiableError: The following specifications were found
22.00 to be incompatible with the existing python installation in your environment:
22.00 
22.00 Specifications:
22.00 
22.00   - conda==4.13.0 -> python[version='>=3.10,<3.11.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0']
22.00 
22.00 Your python: python=3.11
22.00 
22.00 If python is on the left-most side of the chain, that's the version you've asked for.
22.00 When python appears to the right, that indicates that the thing on the left is somehow
22.00 not available for the python version you are constrained to. Note that conda will not
22.00 change your python version to a different minor version unless you explicitly specify
22.00 that.
22.00 
22.00 The following specifications were found to be incompatible with your system:
22.00 
22.00   - feature:/linux-64::__glibc==2.27=0
22.00   - python=3.11 -> libgcc-ng[version='>=11.2.0'] -> __glibc[version='>=2.17']
22.00 
22.00 Your installed version is: 2.27
22.00 
22.00 
------
Dockerfile:56
--------------------
  55 |     ENV PATH="/opt/conda/bin:$PATH"
  56 | >>> RUN conda install -qy conda==4.13.0 \
  57 | >>>     && conda install -y -c conda-forge \
  58 | >>>       openmm=7.7.0 \
  59 | >>>       cudatoolkit==${CUDA_VERSION} \
  60 | >>>       pdbfixer \
  61 | >>>       pip \
  62 | >>>       python=3.8 \
  63 | >>>       && conda clean --all --force-pkgs-dirs --yes
  64 |     
--------------------
ERROR: failed to solve: process "/bin/bash -o pipefail -c conda install -qy conda==4.13.0     && conda install -y -c conda-forge       openmm=7.7.0       cudatoolkit==${CUDA_VERSION}       pdbfixer       pip       python=3.8       && conda clean --all --force-pkgs-dirs --yes" did not complete successfully: exit code: 1

**Comment by yiozzo** [comment]
I resolved my issue my reverting to April 2023 version of Anaconda

# Install OpenMM and pdbfixer.
      %shell rm -rf /opt/conda
      %shell wget -q -P /tmp \
        https://repo.anaconda.com/miniconda/Miniconda3-py310_23.5.2-0-Linux-x86_64.sh \
          && bash /tmp/Miniconda3-py310_23.5.2-0-Linux-x86_64.sh -b -p /opt/conda \
          && rm /tmp/Miniconda3-py310_23.5.2-0-Linux-x86_64.sh
      pbar.update(9)

**Comment by kbrunnerLXG** [comment]
im getting the same issue tried again with a fresh install of Ubuntu22.04

**Comment by YuriModeX** [comment]
> im getting the same issue tried again with a fresh install of Ubuntu22.04, could you explain the shell script a but please. I Installed Openmm and pdbfixer but when i run the code i get a /opt/conda permission denied.

in the ipynb notebook in the block one find lines which looks like above (Miniconda version will be different) and change to what you see above

**Comment by kbrunnerLXG** [comment]
found the fix at https://github.com/deepmind/alphafold/issues/321#issuecomment-1475245689, just copy past the updated Dockerfile
