### ISSUE TITLE
Predicted residuewise errors

### ISSUE THREAD

**Issue by huhlim** [deepmind/alphafold#8]
Thank you for the nice work! It worked smoothly and was faster than I expected before :)

I have a question about the predicted residue-wise errors. I guess the information is stored in $output_dir/result_model_{1,2,3,4,5}.pkl, but the information is not recorded in the output PDB files. I found that pkl['plddt'] is for the predicted residue-wise errors. Is it the correct thing that I am looking for?

**Comment by Augustin-Zidek** [comment]
Thank you, I am glad it worked smoothly! 

You are right, we don’t set the b-factors to pLDDT in the output PDB file, you will have to do that manually using the information in the pickle file. The correct field is, as you mention, the `output_pickle['plddt']` which is a NumPy array of shape `num_residues`, so it should be straight forward to fill that in the PDB.

I recommend reading the relevant sections on pLDDT in the paper for how to interpret it. Also note that pLDDT is 0–100 where 100 means most confident and 0 least confident.
