### ISSUE TITLE
how to compile alphafold with multiple CPUs

### ISSUE THREAD

**Issue by zengt28** [deepmind/alphafold#80]
when i run alphafold with a GPU, i found  100% CPU-Util usage after MSA, it seems taht the model compilation is performed by the CPU, so how can i use multi-CPUs when compilation or how can i improve the speed of compilation

**Comment by zengt28** [comment]
i get this in the output file

W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/gemm_algorithm_picker.cc:207] Failed to find best cuBLAS algorithm, GEMM performance might be suboptimal: Internal: All algorithms tried for %custom-call.224 = f32[2260,64]{1,0} custom-call(f32[2260,64]{1,0} %bitcast.399, f32[64,64]{1,0} %bitcast.400), custom_call_target="__cublas$gemm", backend_config="{\"alpha_real\":1,\"alpha_imag\":0,\"beta\":0,\"dot_dimension_numbers\":{\"lhs_contracting_dimensions\":[\"1\"],\"rhs_contracting_dimensions\":[\"0\"],\"lhs_batch_dimensions\":[],\"rhs_batch_dimensions\":[]},\"batch_size\":\"1\"}" failed. Falling back to default algorithm.

i used nvidia K80 and cuda 11.2, What's the meaning of this?

**Comment by uKitago** [comment]
Hi, I'm facing same issue. Have you solved it?

**Comment by zengt28** [comment]
> Hi, I'm facing same issue. Have you solved it?

I guess this problem can be with my K80 GPU, since I find this in the code of tensorflow:
https://github.com/tensorflow/tensorflow/blob/51ee4155408c29a94345dd38595331b189b829fc/tensorflow/compiler/xla/service/gpu/gemm_algorithm_picker.cc#L57

While K80 doesn't support sm_50

**Comment by uKitago** [comment]
I'm also using K80 whose compute capability of K80 is sm_37. I have to update it.
Thx!!

**Comment by ShannonTown** [comment]
Hi, I'm having the same issue but a little confused here, does that mean that K80 can not be used for alphafold?

**Comment by ShannonTown** [comment]
Thank you. We have K80, and alphafold can work to the end if I set it to only use one GPU core, even though it runs in to this error "Failed to find best cuBLAS algorithm, GEMM performance might be suboptimal". Does this make the final prediction not optimal or does it not matter?
