### ISSUE TITLE
Installing third-party software on alphafold colab not working

### ISSUE THREAD

**Issue by songkim97** [deepmind/alphafold#800]
This error pops up when I try to install third-party software on colab: 
<img width="2084" alt="Screen Shot 2023-07-19 at 2 37 28 PM" src="https://github.com/deepmind/alphafold/assets/82833018/b6f6e334-9e37-4f7d-b101-e9eaa1ccb66b">

How can I fix this issue?

Thank you so much for your time in advance.

**Comment by Augustin-Zidek** [comment]
Sorry about that! Fixed in https://github.com/deepmind/alphafold/commit/6cb85e96845ef32a888b1af0f0d3caf8e2501bc2 and https://github.com/deepmind/alphafold/commit/69afc4df91d6174d1d09f8c736c0b6d9854434ab.
