### ISSUE TITLE
/usr/local/nvidia not found

### ISSUE THREAD

**Issue by cyclicdiamp** [deepmind/alphafold#81]
Hi,
hopefully this question is not too stupid - i'm not a docker expert:

I have installed alphafold as described  in the README (on ubuntu 20.04, cuda 11.4, docker etc ) - everything works (inclduing nvidia-smi) and I end up with nice models, but after JackHMMER and the template steps (i.e. probably starting with TF) - the output says it cannot load libcusolver.so  - so it does not use the GPU(s)

---snip ---
I0730 15:15:46.802867 140093149157184 run_docker.py:193] 2021-07-30 13:15:46.801667: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
I0730 15:15:46.805760 140093149157184 run_docker.py:193] 2021-07-30 13:15:46.805361: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1766] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
I0730 15:15:46.805899 140093149157184 run_docker.py:193] Skipping registering GPU devices...
---snap---

and of course that is true:
 in the running docker there is no /usr/local/nvidia but cuda libraries are in /usr/local/cuda/lib64

i have created a symlinks in the host - does not work
i have created a respective symlink in the running container (while alphafold is running, using docker exec -it dockerID /bin/bash ) does not work....

Is there any way to set the LD_LIBRARY_PATH prior running alpha fold via
$> python3 docker/run_docker.py -fasta_paths=/input_data/protein.fasta --max_template_date=2020-05-14 --preset=reduced_dbs

it would be nice to have some GPU support..... (I have 2x Nvidia 2070super in the system)

As said.. first time docker user......

thanks for any help!

**Comment by tfgg** [comment]
Hi,

This is a non-fatal warning coming from Tensorflow, which we only use for feature preprocessing. The model itself uses JAX - can you confirm that `nvidia-smi` shows that the GPU is occupied while the model is making the prediction?

In b3ed8603e8b5f085342c50259da0ba9fe485ef94 I have change the Tensorflow dependency to be explicitly CPU-only, which should eliminate this confusing warning.
