### ISSUE TITLE
Titin sequences causing alphafold warning and exit without result

### ISSUE THREAD

**Issue by dhan1004** [deepmind/alphafold#810]
Hi, as mentioned in #135 , even when I am trying to run sequences of length 300-350 residues, an HHBlits error continuously causes AlphaFold to exit without results and print warnings:

```
I0803 09:23:06.891149 140328755347456 run_docker.py:258] - 13:17:57.670 WARNING: maximum number of residues 32763 exceeded in sequence UniRef100_UPI0018F7DC1F titin isoform X2 n=1 Tax=Canis lupus familiaris TaxID=9615 RepID=UPI0018F7DC1F
I0803 09:23:06.891169 140328755347456 run_docker.py:258] 
I0803 09:23:06.891188 140328755347456 run_docker.py:258] - 13:17:57.671 WARNING: Number of match columns too large. Only first 19999 match columns will be kept!
```

All of the warnings mention titin sequences in uniref. The issue should not be the length of the sequences in my fasta files; this issue has occurred with multimers that have sequences of only 250 residues or less. The only work-around I have found so far is to use the reduced database, which I am assuming does not include the error-causing titin sequences. Does anyone have a better solution with the full database? Thanks.

**Comment by linuxfold** [comment]
I think I solved this error by downloading the latest version of Uniclust30 (2023-02) from here: https://gwdu111.gwdg.de/~compbiol/uniclust/2023_02/

I also downloaded the latest versions of other databases if available but I'm pretty sure Uniclust30 is the problem. There seems to be something wrong with 2021-03.

Then you have to change the run_docker.py file to point to the new database name:
```
  # Path to the MGnify database for use by JackHMMER.
  mgnify_database_path = os.path.join(
      FLAGS.data_dir, 'mgnify', 'mgy_clusters_2022_05.fa')
```

**Comment by dhan1004** [comment]
@linuxfold It worked! Thanks for your help.

**Comment by yummy-hat** [comment]
any updates on this? updating the database version doesn't work for me. i get a ton of titin hits still.

**Comment by realsagarbatra** [comment]
Hi @linuxfold @dhan1004 
I am getting the same titin error and hhblits keeps failing. Is there any other way around this issue? or the only way is updating the Uniref30 database to the latest?
Also if you could please share the info on how to update the database would be highly appreciated.

**Comment by Lili-irtyd** [comment]
Hi, I also met the same question, I update the database but it doesn't work.. Hope any one know other methods could help me.
