### ISSUE TITLE
high RAM usage w reduced_dbs

### ISSUE THREAD

**Issue by biohegedus** [deepmind/alphafold#82]
Hi,

I have only 32GB sys RAM, so I tried to use --preset=reduced_dbs, which needs only 8GB according to "running alphafold": 
`python3 docker/run_docker.py --fasta_paths=mytarget.fasta --max_template_date=2021-07-30 --preset=reduced_dbs --gpu_devices=0
`

However, jackhmmer used my total RAM and ~4GB swap, but it could be completed (monitoring using htop)
In the next step af2 used all my RAM and swap space (48GB).

Is this expected? 8GB should not be sufficient?

(I have downloaded not only the small_bfd, but also bfd, since I am planning RAM upgrade; however its presence is not expected to override the preset=reduced_dbs option, isn't it?)

(BTW: the results/mytarget/msas dir is emtpy - this is also strange, since earlier runs failed during jackhmmer run becuase of approx: alignment files could not been written because no space on the device; after setting the output_dir to other then /tmp, I have no problem at this stage, but I do not have any file in msas dir - is this unexpected or not?)

Thanks for your feedback and suggestions,
Tamas

**Comment by biohegedus** [comment]
The 8GB, mentioned in the README.md, is likely for the GPU RAM.
jackhmmer uses a large amount of RAM (I saw up to 75GB)

**Comment by Augustin-Zidek** [comment]
Hopefully this was fixed in https://github.com/deepmind/alphafold/commit/57a2455e5fab752d8df430ae1d0334e1a21b548c, feel free to reopen if not.

**Comment by hegelab** [comment]
I think that it is or will be fixed by the RAM-fix of hegelab
