### ISSUE TITLE
AttributeError: module 'jax' has no attribute 'xla'

### ISSUE THREAD

**Issue by cmartinez88** [deepmind/alphafold#827]
I am using AlphaFold2_advanced (on Google Chrome) to predict the structure of a 1152aa protein that is not in the database. I have followed all the steps: login, paste protein sequence, jobname, sampling options (by default), Runtime menu> Run all. After 2-4 sec, the error message below comes up in the "Run AlphaFold" cell: 

**AttributeError: module 'jax' has no attribute 'xla'**

Can anyone help to fix this please?

Thank you,

Cristina

**Comment by Htomlinson14** [comment]
Hi -- AlphaFold2_advanced is part of colabfold. Please raise this issue here: https://github.com/sokrypton/ColabFold/tree/main
