### ISSUE TITLE
Timeout while submitting to MSA server. Retrying...

### ISSUE THREAD

**Issue by shhashem** [deepmind/alphafold#828]
Hello,

I am experiencing a problem with the generation of MSA. When running ColabFold, I get "Timeout while submitting to MSA server. Retrying..." in the logfile. 

Could you please assist in that?

Thanks,

**Comment by Htomlinson14** [comment]
Hi. Please raise this issue on the colabfold github directly. https://github.com/sokrypton/ColabFold
