### ISSUE TITLE
tensorflow issue

### ISSUE THREAD

**Issue by ajian-he** [deepmind/alphafold#83]
hi, I met error like this:

I0730 11:48:09.232837 139818409686848 run_docker.py:193] 2021-07-30 03:48:09.231795: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
I0730 11:48:09.241934 139818409686848 run_docker.py:193] 2021-07-30 03:48:09.241074: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1766] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
I0730 23:23:54.957218 140285687289664 run_docker.py:193] Skipping registering GPU devices...
I0730 23:24:00.114461 140285687289664 run_docker.py:193] I0730 15:24:00.113234 139925785536256 model.py:132] Running predict with shape(feat) = {'aatype': (4, 643), 'residue_index': (4, 643), 'seq_length': (4,), 'template_aatype': (4, 4, 643), 'template_all_atom_masks': (4, 4, 643, 37), 'template_all_atom_positions': (4, 4, 643, 37, 3), 'template_sum_probs': (4, 4, 1), 'is_distillation': (4,), 'seq_mask': (4, 643), 'msa_mask': (4, 508, 643), 'msa_row_mask': (4, 508), 'random_crop_to_size_seed': (4, 2), 'template_mask': (4, 4), 'template_pseudo_beta': (4, 4, 643, 3), 'template_pseudo_beta_mask': (4, 4, 643), 'atom14_atom_exists': (4, 643, 14), 'residx_atom14_to_atom37': (4, 643, 14), 'residx_atom37_to_atom14': (4, 643, 37), 'atom37_atom_exists': (4, 643, 37), 'extra_msa': (4, 5120, 643), 'extra_msa_mask': (4, 5120, 643), 'extra_msa_row_mask': (4, 5120), 'bert_mask': (4, 508, 643), 'true_msa': (4, 508, 643), 'extra_has_deletion': (4, 5120, 643), 'extra_deletion_value': (4, 5120, 643), 'msa_feat': (4, 508, 643, 49), 'target_feat': (4, 643, 22)}
I0730 23:24:00.715444 140285687289664 run_docker.py:193] 2021-07-30 15:24:00.714358: W external/org_tensorflow/tensorflow/stream_executor/gpu/asm_compiler.cc:235] Falling back to the CUDA driver for PTX compilation; ptxas does not support CC 8.6
I0730 23:24:00.715841 140285687289664 run_docker.py:193] 2021-07-30 15:24:00.714454: W external/org_tensorflow/tensorflow/stream_executor/gpu/asm_compiler.cc:238] Used ptxas at ptxas
I0730 23:24:00.720550 140285687289664 run_docker.py:193] 2021-07-30 15:24:00.719690: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:625] failed to get PTX kernel "shift_right_logical_3" from module: CUDA_ERROR_NOT_FOUND: named symbol not found
I0730 23:24:00.720843 140285687289664 run_docker.py:193] 2021-07-30 15:24:00.719853: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:2040] Execution of replica 0 failed: Internal: Could not find the corresponding function
I0730 23:24:00.729022 140285687289664 run_docker.py:193] Traceback (most recent call last):
I0730 23:24:00.729309 140285687289664 run_docker.py:193] File "/app/alphafold/run_alphafold.py", line 302, in <module>
I0730 23:24:00.729531 140285687289664 run_docker.py:193] app.run(main)
I0730 23:24:00.729702 140285687289664 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 312, in run
I0730 23:24:00.729867 140285687289664 run_docker.py:193] _run_main(main, args)
I0730 23:24:00.730043 140285687289664 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
I0730 23:24:00.730206 140285687289664 run_docker.py:193] sys.exit(main(argv))
I0730 23:24:00.730366 140285687289664 run_docker.py:193] File "/app/alphafold/run_alphafold.py", line 284, in main
I0730 23:24:00.730528 140285687289664 run_docker.py:193] random_seed=random_seed)
I0730 23:24:00.730703 140285687289664 run_docker.py:193] File "/app/alphafold/run_alphafold.py", line 148, in predict_structure
I0730 23:24:00.730861 140285687289664 run_docker.py:193] prediction_result = model_runner.predict(processed_feature_dict)
I0730 23:24:00.731029 140285687289664 run_docker.py:193] File "/app/alphafold/alphafold/model/model.py", line 133, in predict
I0730 23:24:00.731185 140285687289664 run_docker.py:193] result = self.apply(self.params, jax.random.PRNGKey(0), feat)
I0730 23:24:00.731376 140285687289664 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/jax/_src/random.py", line 75, in PRNGKey
I0730 23:24:00.731535 140285687289664 run_docker.py:193] k1 = convert(lax.shift_right_logical(seed_arr, lax._const(seed_arr, 32)))
I0730 23:24:00.731691 140285687289664 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/jax/_src/lax/lax.py", line 382, in shift_right_logical
I0730 23:24:00.731846 140285687289664 run_docker.py:193] return shift_right_logical_p.bind(x, y)
I0730 23:24:00.732010 140285687289664 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/jax/core.py", line 264, in bind
I0730 23:24:00.732167 140285687289664 run_docker.py:193] out = top_trace.process_primitive(self, tracers, params)
I0730 23:24:00.732321 140285687289664 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/jax/core.py", line 604, in process_primitive
I0730 23:24:00.732475 140285687289664 run_docker.py:193] return primitive.impl(*tracers, **params)
I0730 23:24:00.732630 140285687289664 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/jax/interpreters/xla.py", line 262, in apply_primitive
I0730 23:24:00.732787 140285687289664 run_docker.py:193] return compiled_fun(*args)
I0730 23:24:00.732952 140285687289664 run_docker.py:193] File "/opt/conda/lib/python3.7/site-packages/jax/interpreters/xla.py", line 378, in _execute_compiled_primitive
I0730 23:24:00.733112 140285687289664 run_docker.py:193] out_bufs = compiled.execute(input_bufs)
I0730 23:24:00.733345 140285687289664 run_docker.py:193] RuntimeError: Internal: Could not find the corresponding function

I did install tensorflow and set the library path, but still have this issue.
anyone has similar issue?

Thank you.

**Comment by tfgg** [comment]
Hi,

This appears to be the same issue as #55 - you have a GPU with compute capacity 8.6, which CUDA 11.0 doesn't support. Can you try following the instructions in issue #55 to modify `docker/Dockerfile` to use a more recent version of CUDA?

**Comment by akhoroshev** [comment]
```W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64```

I have the same issue on V100.

@tfgg 
This error is all about dynamic libraries not GPU compute compatibility.

**Comment by tfgg** [comment]
Hi,

That's a warning message, and shouldn't be relevant. Does the process fail with the same error as reported in this issue? If not, please open a new issue.
