### ISSUE TITLE
out of memory w/ colab notebook

### ISSUE THREAD

**Issue by ttianchen** [deepmind/alphafold#85]
Hi, I'm running a 1.7k sequence with the colab notebook version, I'm using a colab pro account. Alphafold crashes every time after the genetic database search is done. I've also tried several truncated sequences (~1.4k aa), same thing happened. 
What is the maximal sequence length that Colab notebook version can handle?

![image](https://user-images.githubusercontent.com/23733541/127745033-7fe7d118-6a8e-4896-be15-de2a5593f098.png)

---------------------------------------------------------------------------
UnfilteredStackTrace                      Traceback (most recent call last)
<ipython-input-5-ae0b49d61c11> in <module>()
     41                                                            random_seed=0)
---> 42     prediction_result = model_runner.predict(processed_feature_dict)
     43 

11 frames
UnfilteredStackTrace: RuntimeError: Resource exhausted: Out of memory while trying to allocate 13816236064 bytes.

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/jax/interpreters/xla.py in _execute_compiled(compiled, avals, handlers, kept_var_idx, *args)
    891           for i, x in enumerate(args)
    892           if x is not token and i in kept_var_idx))
--> 893   out_bufs = compiled.execute(input_bufs)
    894   check_special(xla_call_p.name, out_bufs)
    895   return [handler(*bs) for handler, bs in zip(handlers, _partition_outputs(avals, out_bufs))]

RuntimeError: Resource exhausted: Out of memory while trying to allocate 13816236064 bytes.

**Comment by emehinovic72** [comment]
Hi I ran into some of these issues too, 

They do have a max length of 2500, however I would try factory resetting the runtime and see if that helps.  Also it does seem like colabnotebook has a time-out limit if file does not start running with a certain period of time.  In addition, try not to have any other collabnotebooks run at the same time. Hopefully this helps!
 

![Screen Shot 2021-08-02 at 12 14 14 PM](https://user-images.githubusercontent.com/77067493/127899268-3b39d659-e41b-481f-980b-334ba6e586aa.png)

**Comment by Dann0012** [comment]
Hi, having the same issue. Colab seems to have a hard limit of ~14gb GPU vram. It needed 16gb, truncation reduce to 15gb. Seems like every 100aa is about 1gb, at least for my protein. 

Is there some way to decrease the size required when working with large input sequences? Maybe some compromise on the number of MSA used? 

Or maybe shift it to work completely on CPU in colab, since pro users can get 25gb of ram?

**Comment by ttianchen** [comment]
Now there's Colab Pro+ available, assuming I can get more computational power, I upgraded of course. When I tried the 1.7k sequence, it even didn't pass MSA step this time. Anyone came across this error?
![image](https://user-images.githubusercontent.com/23733541/130546428-80f3ac21-c2f6-4c2b-8cfd-5ee52f8fedb0.png)

**Comment by Augustin-Zidek** [comment]
Colab has multiple different GPU types, so you might get a different GPU type each time and that will impact the maximum length of the sequence you would be able to fold. Colab Pro should give access to GPUs with more RAM but this still might not be sufficient for long proteins (1500+). I recommend either running a local version of AlphaFold for long proteins or checking if that particular protein is in the AlphaFold Protein Structure Database (www.alphafold.com).
