### ISSUE TITLE
tensorflow-cpu

### ISSUE THREAD

**Issue by akhoroshev** [deepmind/alphafold#88]
Hello! Can you explain this commit 

https://github.com/deepmind/alphafold/commit/b3ed8603e8b5f085342c50259da0ba9fe485ef94

The commit message is talking about the data pipeline. But as we see

https://github.com/deepmind/alphafold/search?p=1&q=tensorflow&type=code

tf is used by a `model` submodule. Does this mean that the inference now only works on CPU (GPU is not used)?

**Comment by tfgg** [comment]
If you look, model.py is only importing Tensorflow in order to use tf.train.Example (as output by the data pipeline) for pytyping.

[JAX](https://github.com/google/jax), which is used to actually run the model, will run on GPU regardless of whether Tensorflow is built with GPU support or not.
