### ISSUE TITLE
AlphaFold Prediction Server

### ISSUE THREAD

**Issue by AndrewOkie** [deepmind/alphafold#9]
An online service for predicting the structure of a protein (similar to I-TASSER server) would be useful for academic users.

**Comment by xinwei-sher** [comment]
AlphaFold would run hours or even days to get a prediction, according to news articles, so it may not to be feasible for an online server. RosettaFold, however, is much light weighted and makes predictions very close to alphafold, has a online server for fast prediction: https://robetta.bakerlab.org/

**Comment by mziel** [comment]
Hi,

For a server use-case you can now use a Colab notebook to predict your sequence of choice with an online interface:
https://colab.research.google.com/github/deepmind/alphafold/blob/main/notebooks/AlphaFold.ipynb

Note that the current version of the Colab doesn't use templates (see the section `Differences to AlphaFold v2.0` for more details).
