### ISSUE TITLE
How to visualize the result?

### ISSUE THREAD

**Issue by RodenLuo** [deepmind/alphafold#92]
Hi, How can I have the same visualization as that in the simplified online collab version as shown below? Thanks.

![](https://i.gyazo.com/0e694da66803eb361c194d395b605b16.gif)

**Comment by Augustin-Zidek** [comment]
You can check out the Python code to show this visualisation in the Colab notebook by clicking the "Show code" button in the [Run AlphaFold and download prediction](https://colab.research.google.com/github/deepmind/alphafold/blob/main/notebooks/AlphaFold.ipynb#scrollTo=XUo6foMQxwS2) cell.

**Comment by ValZapod** [comment]
That is using https://github.com/molstar/molstar/issues/236

**Comment by RodenLuo** [comment]
Hi, Thanks for the hint. 

I still did not get the results from the command line results visualized. I did get the following variables from the `result_model_*.pkl` file. 

```
dict_keys(['distogram', 'experimentally_resolved', 'masked_msa', 'predicted_aligned_error', 'predicted_lddt', 'structure_module', 'plddt', 'aligned_confidence_probs', 'max_predicted_aligned_error', 'ptm', 'iptm', 'ranking_confidence'])
```

It would be much more user-friendly if there is a separate notebook that people can upload the below folder structure (or only the necessary files) to Colab and then click run to visualize the same plots as the online pipeline provided. Or if a more detailed guide can be provided, it would be much more appreciated. E.g., which variables from which file should be plugged to which line. 

Thanks

```
$ tree -L 3
.
├── features.pkl
├── msas
│   ├── A
│   │   ├── bfd_uniclust_hits.a3m
│   │   ├── mgnify_hits.sto
│   │   ├── pdb_hits.sto
│   │   ├── uniprot_hits.sto
│   │   └── uniref90_hits.sto
│   ├── B
│   │   ├── bfd_uniclust_hits.a3m
│   │   ├── mgnify_hits.sto
│   │   ├── pdb_hits.sto
│   │   ├── uniprot_hits.sto
│   │   └── uniref90_hits.sto
│   └── chain_id_map.json
├── ranked_0.pdb
├── ranked_1.pdb
├── ranked_2.pdb
├── ranked_3.pdb
├── ranked_4.pdb
├── ranking_debug.json
├── relaxed_model_1_multimer.pdb
├── relaxed_model_2_multimer.pdb
├── relaxed_model_3_multimer.pdb
├── relaxed_model_4_multimer.pdb
├── relaxed_model_5_multimer.pdb
├── result_model_1_multimer.pkl
├── result_model_2_multimer.pkl
├── result_model_3_multimer.pkl
├── result_model_4_multimer.pkl
├── result_model_5_multimer.pkl
├── timings.json
├── unrelaxed_model_1_multimer.pdb
├── unrelaxed_model_2_multimer.pdb
├── unrelaxed_model_3_multimer.pdb
├── unrelaxed_model_4_multimer.pdb
└── unrelaxed_model_5_multimer.pdb
```

**Comment by RodenLuo** [comment]
With a new conda evnironment and a few packages installed as: 

```
conda create -n AF2_vis -c conda-forge jupyterlab
conda activate AF2_vis
pip install py3Dmol
conda install numpy
conda install matplotlib
```

Then launch the notebook as: 

```
jupyter-lab
```

With this self-created [notebook](https://colab.research.google.com/drive/1CizC7zmYvFkav5qfBbWxhgUHrOxwym2w), I can achieve visualizations very close to the ones shown in the AlphaFold Colab notebook. 

[![Image from Gyazo](https://i.gyazo.com/91116b68994a1f1c4702f097aed93a4a.jpg)](https://gyazo.com/91116b68994a1f1c4702f097aed93a4a)

:warning: `result_model_1_multimer.pkl` may not corresponds to `ranked_1.pdb`. The relation between `ranked_*.pdb` and `result_model_*_multimer.pkl` can be found at `ranking_debug.json` if I am not mistaken.

However, I have not got the `# Color the structure by per-residue pLDDT` and `# Display lines at chain boundaries.` in "the Run AlphaFold and download prediction [cell](https://colab.research.google.com/github/deepmind/alphafold/blob/main/notebooks/AlphaFold.ipynb#scrollTo=XUo6foMQxwS2)" working. More specifically, I have not figured out what is `PLDDT_BANDS` and `best_unrelaxed_prot.chain_index` and how I can construct them with minimum input rather than relying on the AlphaFold package and data structures. Would very much appreciate it if any help can come in. 

I have also asked `afdbhelp@ebi.ac.uk` to see if they have their interactive "3D viewer" as shown on each of the result pages ([example page](https://alphafold.ebi.ac.uk/entry/P02549)) open-sourced somewhere or not, and if they can have an empty "3D viewer" where we can drag and drop the result from the command line AF2_multimer output and visualize it. 

Not sure how the majority of users of AF2 are interpreting the results or what is the best practice here. If there are other ways of visualizing the score matrics (not in a notebook), would be more than happy to know. IMHO, the visualization of the result is almost of the same importance as the result itself. Also, this has been raised in another [thread](https://github.com/deepmind/alphafold/issues/248). Very grateful if this thread can be kindly reopened and some more help can come in.

**Comment by kiwi2kiwi** [comment]
Is there a way to open just the result_model_*.pkl files locally?
Opening them with pickle throws an error about truncated pickle data. 
Afaik this means the result_model is not a complete file right?

**Comment by RodenLuo** [comment]
If the below lines in python gives you an error, then it probably means there is something wrong with the alphafold run. 

```python
import pickle

with open('result_model_3_multimer.pkl', 'rb') as f:
    data = pickle.load(f)

data.keys()
plddt = data["plddt"]
```

The code is in the notebook mentioned above.

**Comment by RodenLuo** [comment]
@ttianchen In this case, it might be good to search in the issues pool to see if anyone else asked or open another ticket I guess. Or if we can get the attention from the authors here it would also be great. 

I have not run the monomer prediction with the multimer version yet (I have also not been running multimer prediction, waiting for #236 to be solved).

**Comment by WielandF** [comment]
@RodenLuo 
> I have not figured out what is PLDDT_BANDS and best_unrelaxed_prot.chain_index and how I can construct them with minimum input rather than relying on the AlphaFold package and data structures. Would very much appreciate it if any help can come in.

The PLDDT_BANDS are implemented as following:
PLDDT_BANDS = [(0, 50, '#FF7D45'),
               (50, 70, '#FFDB13'),
               (70, 90, '#65CBF3'),
               (90, 100, '#0053D6')]

I adjusted your notebook to get it running on a machine and it is plotting after we fixed a few import issues ;) 
The problem now is, that the color mapping is not really working because the `# Construct multiclass b-factors to indicate confidence bands
# 0=very low, 1=low, 2=confident, 3=very high` is currently missing. I am trying to figure out how to fix it and will post an update then.

**Comment by mattarnoldbio** [comment]
Hi all. I have written a fairly basic and hopefully quite user-friendly command line python 3 script which can be used to visualise metadata, I think in the way you are asking. It is on my GitHub here: https://github.com/mattarnoldbio/alphapickle . 

It takes an input of pickle files (please see instructions on the repo for precise details of accepted arguments etc) and returns plots of PAE (if the correct models generating this statistic were used) and pLDDT, as well as both metrics in csv files for manual plotting by the user.

Please let me know if you find this helpful, struggle to use it, or would like to see any additional features!

**Comment by mattarnoldbio** [comment]
@ttianchen In response to your comment about PAE plots for monomers: this is possible, but only PTM-enabled models output PAE values. If you want to get this metric for predicted monomers, run:
 - If you want to run in Alphafold 2.1.0 for monomers: use the script you have but substitute in the flag: --model_preset=monomer_ptm  (instead of multimer) and then your monomer fast file.
 - If you prefer to reproduce using 2.0.1, add the additional flag to your script: --model_names=model_1_ptm,model_2_ptm,model_3_ptm,model_4_ptm,model_5_ptm
For the difference between PTM models and original models, consult: https://doi.org/10.1038/s41586-021-03819-2 Supplement 1

**Comment by Intron7** [comment]
I created a small python package called alpha-viewer (https://github.com/Intron7/alpha_viewer). It's a class that handles the visualisation. You can for example view the pLDDT in the py3Dmol viewer and other custom annotations. It works on monomer and multimer models.
