### ISSUE TITLE
Download speed of database pdb_mmcif is very slow, about 80 KB/s

### ISSUE THREAD

**Issue by liuboeo** [deepmind/alphafold#94]

**Comment by liuboeo** [comment]
Is there any solution

**Comment by Augustin-Zidek** [comment]
You could try using a different mirror, see https://www.wwpdb.org/ftp/pdb-ftp-sites for a list of mirrors available.

Change the mirror in `scripts/download_pdb_mmcif.sh`. Here is an example that uses EBI's mirror:

```
rsync --recursive --links --perms --times --compress --info=progress2 --delete --port=33444 \
  rsync.ebi.ac.uk::pub/databases/pdb/data/structures/divided/mmCIF/ \
  "${RAW_DIR}"
```

Try to use a mirror that is close to your geographic location (PDBj for Asia, EBI for Europe, RCSB for America).
